### ISSUE TITLE
TrackException sample call in readme.md uses deprecated syntax

### ISSUE THREAD

**Issue by aguerot** [microsoft/ApplicationInsights-JS#1004]
In [readme.md](https://github.com/microsoft/ApplicationInsights-JS/tree/329d77b15250ae8dfa25b86eae0146a65422a62b#sending-telemetry-to-the-azure-portal), sample syntax to call `trackException` is `appInsights.trackException({exception: new Error('some error')});`

this syntax seems to be [deprecated ](https://github.com/microsoft/ApplicationInsights-JS/blob/c13ea685c5ee5b7fd26214459d3ba6701dae3ea0/vNext/AISKU/src/ApplicationInsightsDeprecated.ts#L88) in favor of this [one](https://github.com/microsoft/ApplicationInsights-JS/blob/329d77b15250ae8dfa25b86eae0146a65422a62b/JavaScript/JavaScriptSDK.Tests/DefinitionTypes/applicationinsights-js-tests.ts#L79): `appInsights.trackException(new Error("sample error"));`

**Comment by markwolff** [comment]
Deprecated API uses `appInsights.trackException(new Error("sample error"));`. Latest SDK should use `appInsights.trackException({exception: new Error('some error')});`
