### ISSUE TITLE
Enable GZIP for V2

### ISSUE THREAD

**Issue by rzontar** [microsoft/ApplicationInsights-JS#1007]
The script from https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js is served without gzip compression.
![image](https://user-images.githubusercontent.com/912829/63243810-f03f3f00-c25b-11e9-8bb4-e4b78ee08000.png)

I believe this to be a misconfiguration, since https://az416426.vo.msecnd.net/scripts/a/ai.0.js is served with the correct Content-Encoding.

See related issue #42

**Comment by markwolff** [comment]
Looks like compression was not enabled for `text/javascript`. I've enabled and verified that it is now being served properly.
