### ISSUE TITLE
Consider logging of unhandled promises

### ISSUE THREAD

**Issue by nphmuller** [microsoft/ApplicationInsights-JS#1013]
Currently ApplicationInsights-JS doesn't log uncaught errors of promises. To make sure all errors are caught and logged, something like the following snippet could be implemented:
``` js
window.addEventListener("unhandledrejection", function(promiseRejectionEvent) { 
    // handle error here, for example log   
});
```

It looks a lot like implementing `window.onerror`, which is already subscribed upon.

**Comment by MSNev** [comment]
This is also referenced in Issue
Unhandled rejected promise tracking #168
I'm linking and going to close #168 and being fixed by this issue

**Comment by MSNev** [comment]
Will be closing this issue once v 2.4.3 (which includes the option to enbale this) is published the the CDN

**Comment by MSNev** [comment]
Version 2.4.3 is now published to CDN and NPM and addresses this enhancement
