### ISSUE TITLE
Correlation information is not being sent

### ISSUE THREAD

**Issue by freerangeeggs** [microsoft/ApplicationInsights-JS#1019]
I have an angular app calling a backend API, both log telemetry to their own instances of AI. I am attempting to have distributed tracing work across both. I am using AI-web 2.2.0 and [AI-dotnet 2.10.0](https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.10.0)

This is what I see on the Front-end AI:
![image](https://user-images.githubusercontent.com/16587477/63898445-62720980-ca3c-11e9-92b6-da9f37aac6ee.png)

This is what I see when looking at AI for the API:
![image](https://user-images.githubusercontent.com/16587477/63899043-baaa0b00-ca3e-11e9-8a50-09f702dd9822.png)

I expect to have the latter result in both AI instances.

As they are on different domains, I have `enableCorsCorrelation` set to `true`.

I can see the `Request-Id` and `Request-Context` are correctly being sent to my API, and my API returning `Request-Context` with an AppId and the API has exposed the `Request-Context` so the header can be read by [`xhr.getAllResponseHeaders()`](https://github.com/microsoft/ApplicationInsights-JS/blob/62265146e4df28a825035ce37119b4319488ef1d/JavaScript/JavaScriptSDK/ajax/ajax.ts#L267)

When stepping through the code, I can see [`dependency.correlationContext` is being set to the appId](https://github.com/microsoft/ApplicationInsights-JS/blob/62265146e4df28a825035ce37119b4319488ef1d/vNext/extensions/applicationinsights-dependencies-js/src/ajax.ts#L290) rather than [`dependency.target` being appended with the appId](https://github.com/microsoft/ApplicationInsights-JS/blob/62265146e4df28a825035ce37119b4319488ef1d/JavaScript/JavaScriptSDK/ajax/ajax.ts#L256).

When looking at the network traffic, `correlationContext` is not being sent to AI. I can see that the [`correlationContext` is not being serialized on creation of the dependency envelope](https://github.com/microsoft/ApplicationInsights-JS/blob/62265146e4df28a825035ce37119b4319488ef1d/vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts#L260).

If I use fiddler to manually adjust the traffic:
- Adding `correlationContext` to `baseData` has no effect.
- Adjusting `target` to append ` | cid-v1:{APP_ID}` DOES have the desired effect, and I can see the same telemetry in the front-end AI as I do in the AI of the API.

I have attempted to use a Telemetry Initializer to adjust the `target` so it includes the AppId, but it is overwritten before it is posted.

Where I notice that `dependency.correlationContext` is being set in favor of appending `dependency.target`, I see that this is a change as part of the `vNext` folder, should this be part of the current deployment?

**Comment by markwolff** [comment]
Thanks for the report. It seems this bit was commented out for some reason or another. I'll enable it for the next release

**Comment by freerangeeggs** [comment]
Awesome, thank you!
