### ISSUE TITLE
Use CDN with single paged app

### ISSUE THREAD

**Issue by RobPethick** [microsoft/ApplicationInsights-JS#1024]
App insights is bloating my bundle with almost 500kB of pre-gzipped code.

I was hoping to work out a way that I could reference the CDN and then use an external to include it in my project but I cannot work this out. I would need a CDN that exported the '@microsoft/applicationinsights-web' package as a global object.

**Comment by markwolff** [comment]
Can I see your package.json? Also have you tried using the [snippet setup](https://github.com/microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup) instead? Although if you are using the react plugin or have a lot of manual tracks or need typings its not ideal.

**Comment by RobPethick** [comment]
```
    "@microsoft/applicationinsights-react-js": "^2.0.2",
    "@microsoft/applicationinsights-web": "^2.0.1",
```

Then the code that I use is below

```
import { ApplicationInsights, ITraceTelemetry, IEventTelemetry } from '@microsoft/applicationinsights-web';
import { ReactPlugin, withAITracking } from '@microsoft/applicationinsights-react-js';

const reactPlugin = new ReactPlugin();

let ai = (window as any).appInsights as ApplicationInsights;

export const initAppInsights = (reactPluginConfig: any) => {
{                    
  ai = new ApplicationInsights({
      config: {
          instrumentationKey: (window.config as any).appInsights.instrumentationKey,
          maxBatchInterval: 0,
          disableFetchTracking: false,
          disableAjaxTracking: false,
          loggingLevelConsole: 2,
          extensions: [reactPlugin],
          extensionConfig: {
              [reactPlugin.identifier]: reactPluginConfig
          },
          appId: (window.config as any).teams.appId        
      },          
      });        
      
  ai.loadAppInsights(false); 
}};
```


I can declare app insights as an external and load the package from a CDN if that CDN is the '@microsoft/applicationinsights-web' package as a UMD
