### ISSUE TITLE
Thoughts on recording Request Body and Response Body?

### ISSUE THREAD

**Issue by gustavobini** [microsoft/ApplicationInsights-JS#1025]
Hello.

Application Insights could be a lot more helpful if we could log the requests content. Say, for instance, that a request fails. With the request and response body, you'd know it failed because you forgot to send some data in the request.

I feel like there is a reason why this feature is not added as it's a very simple one to implement. Just so I do not waste time on it, I wonder what the reason is. Do anyone know?

**Comment by Ro3A** [comment]
Sensitive data is likely the primary concern. I've build support for including request body and response body on request telemetry via .net core middleware. That said, I also build in configurable ignore routes to exclude collecting request and response bodies for our token / login endpoints to avoid leaking credentials into the logs. 

There are other threads on this discussion and from what I've read, Microsoft is exploring this feature.
