### ISSUE TITLE
w3c traceparent should set the `sampled` flag

### ISSUE THREAD

**Issue by vishwam** [microsoft/ApplicationInsights-JS#1036]
Version: 2.2.1

With the W3C Distributed Tracing Mode, the library currently emits a traceparent with trace-flag=`00` (i.e., sampled=false), even if we're logging the request. Shouldn't this be set to `01` according to [the W3C spec](https://w3c.github.io/trace-context/#trace-flags)? 

> If a component made definitive recording decision - this decision SHOULD be reflected in the sampled flag.

**Comment by markwolff** [comment]
Yes you are right. I've adjusted this in 3ba5281 and https://github.com/microsoft/ApplicationInsights-node.js/pull/545. It will land in the next release (2.2.3)
