### ISSUE TITLE
ReactPlugin becomes undefined after certain amount of time

### ISSUE THREAD

**Issue by Jack-Ramboll** [microsoft/ApplicationInsights-JS#1053]
We've been trying to integrate the react SDK of this into our project that uses redux with persistent states but it seems to be after a certain amount of time the React plugin object becomes undefined resulting in an exception which stops the page from loading

"TypeError: reactPlugin.trackMetric is not a function"

**Comment by patburke234** [comment]
Yes, this happens to me as well. Using the code from the react demo and on component unmount of the withAITracking it is undefined. 

TypeError: Cannot read property 'trackMetric' of undefined
class_1.componentWillUnmount

**Comment by Soffylicious** [comment]
Same here :(

**Comment by AravindTReddy** [comment]
Facing the same issue, Any solution for this ?? Thanks

**Comment by heberacostalipera** [comment]
Same here, did anyone find a workaroud to avoid this?

**Comment by heberacostalipera** [comment]
People: I've just found out a possible outcome:

in the `TelemetryService.js` file theres this code
```
let reactPlugin = null;
```

and then this inside the `initialize` function:

```
reactPlugin = new ReactPlugin();
```
I've replaced the first one with: 
```
const reactPlugin = new ReactPlugin();
```
and commented the second one and it somehow fixed the issue, but I cant tell yet if this breaks something else.

**Comment by DeepakPKumar** [comment]
Same here - Do we have any updates / solutions for this please ?

**Comment by eric-gonzalez-tfs** [comment]
This issue is still happening - does anyone have a resolution for this?
![Screen Shot 2022-10-19 at 2 57 19 PM](https://user-images.githubusercontent.com/82120345/196812619-29a689da-bd21-41f4-958c-c9e97bb78d2e.png)
