### ISSUE TITLE
sampleRate should be child of envelope instead of being added as tag

### ISSUE THREAD

**Issue by scbeek** [microsoft/ApplicationInsights-JS#1056]
**Description/Screenshot**
When using sampling, the sampleRate currently is being added as tag to the telemetry-item. Although it is available in AppInsights this way, it is not correct. AppInsights expects this sampleRate to be in the telemetry-envelope, as sibling of time/name and tags. 
In our situation we have enabled ingestion sampling (as fallback for non sampling applications in our landscape), and this bug is causing our telemetry to be sampled twice.  Also we are unable to extrapolate the actual statistics from the telemetry that is available.

**Steps to Reproduce**
Enable sampling and check the telemetry which is being tracked. It will look like this:
```json
   { 
      "time":"2019-09-24T12:09:48.240Z",
      "iKey":"x",
      "name":"y",
      "tags":{ 
         "sampleRate":"25"
      },
      "data":{ }
   }
```
while it should be something like:
```json
   { 
      "time":"2019-09-24T12:09:48.240Z",
      "iKey":"x",
      "name":"y",
      "sampleRate": 25,
      "tags":{ },
      "data":{ }
   }
```

 - OS/Browser: N/A
 - SDK Version [e.g. 22]: 22
 - How you initialized the SDK: NPM Setup 

**Expected behavior**
sampleRate should get its own property on IEnvelope / Envelope.

**Comment by xiao-lix** [comment]
Fixed in this PR #1061
