### ISSUE TITLE
Numeric attributes are not logged with trackTrace and trackMetric

### ISSUE THREAD

**Issue by riteshbhoi** [microsoft/ApplicationInsights-JS#1057]
**Description/Screenshot**
Numeric attributes (or custom properties) are not logged with trackTrace and trackMetric

**Steps to Reproduce**

 - OS/Browser: Windows 10
 - SDK Version [e.g. 22]: 2.2.0
 - How you initialized the SDK: 
```
appInsights = new ApplicationInsights({
            config: {
                instrumentationKey: cfg.AIKey,
                disableFetchTracking: false,
                extensions: [customPlugin]
            }
        });
        appInsights.loadAppInsights();
```

**Expected behavior**
Numeric custom attributes should get logged.

**Additional context**

**Comment by xiao-lix** [comment]
Fixed in this PR: #1065
