### ISSUE TITLE
applicationinsights-react-native - jest failing

### ISSUE THREAD

**Issue by MakhouT** [microsoft/ApplicationInsights-JS#1058]
**Description/Screenshot**
I've updated my packages to
```
"react-native-device-info": "3.1.4",
"@microsoft/applicationinsights-react-native": "1.0.3",
"@microsoft/applicationinsights-web": "2.2.4",
"react-native": "0.60.5",
"react": "16.8.6",
```
However the API of `react-native-device-info` has changed since version `3.0.0`. I think this hasn't been reflected in `applicationinsights-react-native`. All the calls are now async and return a Promise.

Now when running my tests I am getting this error:
```
  ● Test suite failed to run

    @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
      • Run `react-native link react-native-device-info` in the project root.
      • Rebuild and re-run the app.
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
      If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

      at Object.<anonymous> (node_modules/@microsoft/applicationinsights-react-native/node_modules/react-native-device-info/deviceinfo.js:19:11)
      at Object.<anonymous> (node_modules/@microsoft/applicationinsights-react-native/src/ReactNativePlugin.ts:14:1)
```

I wanted to verify it, but I can't seem to find the source code of `applicationinsights-react-native` on github, I can only find it on npmjs. 

@markwolff Could you please confirm this?

If more details are needed I am happy to help

EDIT:
I looked in the my local `node_modules` to check the source code of `applicationinsights-react-native` and I am right. The package is using `"react-native-device-info": "^2.0.2",`.
But the README also states 

```
This plugin relies on react-native-device-info. You must install and link this package. Keep react-native-device-info up-to-date to collect the latest device names using your app.
```

**Comment by markwolff** [comment]
This is probably because of a version conflict between 2 and 3 of react-native-device-info. I've published  2.0.0 of `@microsoft/applicationinsights-react-native` which is updated to support 3.x of react-native-device-info.

**Comment by MakhouT** [comment]
@markwolff Thanks for the update.

Well because we're using the sync API, we can't really have our debugger open - this is currently a bug in `react-native-device-info`. To work around this we'll have to do something like `await DeviceInfo.getVersion()`
Check this discussion: https://github.com/react-native-community/react-native-device-info/issues/776
Because of this there is an other API breaking change coming for `react-native-device-info`.
I'm keeping an eye out for that, when that happens, I'll let create a new ticket to remind you of this. 
That's also going to be a change of 3.x probably.

For now would it be possible to be using the async methods? Any other ideas/suggestions?

**Comment by markwolff** [comment]
I moved it to use the sync ones since where the plugin hooks into the rest of the SDK is not set up to handle promises. Does having the sync stuff at all block you? Or is just when it is run? Since the async stuff is only used during initialization and if it only affects you when it is run, I can expose some way for you to init the plugin async, and then pass the initilized plugin in to the SDK and it won't need to reinitialize. Basically you will be handling the promise yourself. Would this work for you?

**Comment by MakhouT** [comment]
Well it only blocks when having the chrome debugger on.
I think our best option is to wait for the next update of `react-native-device-info` and then we can bump `react-native-device-info` in this package. The iOS PR is already out for review.

**Comment by MakhouT** [comment]
@markwolff `react-nativce-device-info` has been [updated](https://github.com/react-native-community/react-native-device-info/releases/tag/v4.0.1) to V4.0.1
Could you please update and use the new constants instead of the `xxxSync` API.

**Comment by MakhouT** [comment]
@markwolff Good news, `RNDI` got updated to `5.0.1` where you can use `getDeviceType` as a constants instead of `getDeviceTypeSync`
https://github.com/react-native-community/react-native-device-info/releases

When you upgrade, then everything should be good again! 
Thanks for the support!

**Comment by MakhouT** [comment]
Hi @markwolff, any update on this by any chance? Or do you rather have me create a new ticket for this?
