### ISSUE TITLE
How does the batching works in react plugin?

### ISSUE THREAD

**Issue by maple10001** [microsoft/ApplicationInsights-JS#1060]
I have a react app + AI react plugin setup.
The page I am looking at have one fetch API call.

After page rendered, I saw 3 post request send to AI:
1. "PageViewData": `duration: "00:00:00.000"`.
2. "PageViewData": ` duration: "00:00:01.279"`.
3.  "RemoteDependencyData". 

Is this the correct behavior with `maxBatchInterval` of 15 seconds? 

PS:
I added a test to send custom message to AI in `componentDidmount` 100 times, they do got batched before send to AI.

**Comment by markwolff** [comment]
The first PageView item from the `onload` event is sent right away. Afterwards, we batch items and flush either every 15 seconds or when the maximum batch size is reached. We also flush when the tab is closed.

**Comment by maple10001** [comment]
Does the `Network Dependency Requests` been sent seperately?
