### ISSUE TITLE
front-end telemetry partially sent with NPM setup 

### ISSUE THREAD

**Issue by tejkosie2** [microsoft/ApplicationInsights-JS#1062]
**Description/Screenshot**
In my application the telemetry is only partially sent when I use the NPM setup and it seems to be working when I use the  Snippet javascript code. 
I cant see any events being logged in the Performance -> Browser window when I log in Azure when using the NPM setup.
The error i am getting in the Developer tools is: 
24 message:"Missing required field specification. The field is required but not present on source" props:"{field:exceptions,name:baseData}"

**Steps to Reproduce**
This is what I use in npm 
```
import { ApplicationInsights } from '@microsoft/applicationinsights-web';

const appInsights = new ApplicationInsights({
  config: {
    instrumentationKey: 'key',  
  },
});

appInsights.loadAppInsights();
```

**Comment by markwolff** [comment]
Which version of the SDK are you using?

**Comment by tejkosie2** [comment]
SDK of NPM ? or sdk of application insights ?

**Comment by tejkosie2** [comment]
in my ConnectedService.json file I can see  "Version": "9.1.611.1"

**Comment by tejkosie2** [comment]
it turned out that adding 
```
appInsights.loadAppInsights();
appInsights.trackPageView({}); <--- adding this line solves it 
```

**Comment by engineersamuel** [comment]
One place this can happen is when calling trackException with an exception variable that isn't an instanceof an Error, see: https://github.com/microsoft/ApplicationInsights-JS/blob/d3abfe4138d0cfd624f72288c14e73b0b4849f3b/shared/AppInsightsCommon/src/Telemetry/Exception.ts#L39

The documentation infers to do exception: new Error(...) and doing that fixes this issue.

One way you can reproduce this is if you do:

```
    trackException({
      exception: error
    })
```

where error could be something like:

```
    {
      message: 'some error',
      stack: 'some stack'
    }
```

Which is an object and not an instanceof an Error.
