### ISSUE TITLE
Refactor code to provide better tree shaking and minification of generated code

### ISSUE THREAD

**Issue by MSNev** [microsoft/ApplicationInsights-JS#1076]
**Is your feature request related to a problem? Please describe.**
Currently the generated code is not optimal and is larger than required. There are several techniques that can be used to assist with the minification of the generated code.

**Describe the solution you'd like**
By default the generated code uses multiple instances of global scope names and keywords that can be replaced with local scoped variables that can be minified to a smaller net usage.
e.g.
Instead of multiple usages of ClassName.prototype.XXXX (which can't be minified) you can assign this to a local variable such as var proto = ClassName.prototype; proto.XXXX.
This technique works only when un-minifable references are used more than once so that the nett effect is a smaller codebase.

**Additional context**
As a general SDK, every byte counts especially on slower connections or mobile devices.

**Comment by mohamedfasil** [comment]
@MSNev any update to this ?

**Comment by MSNev** [comment]
Nothing yet! We have only applied some simple basic improvements, but not the full/big changes.
But it is getting close.

To support this I recently created and published a helper utility to the community DynamicProto-JS
https://github.com/microsoft/DynamicProto-JS

This will be used to remove the usages of the typescript ClassName.prototype.XXXX and hide the internal properties (those starting with "_") so they are not exposed on the instance and therefore will be correctly minified.

One known outstanding item that I don't currently have a solution for is that as part of using DynamicProto-JS the DTS needs to change the methods to optional (for compile errors only) even though they will always be defined.

**Comment by ericp96** [comment]
Plus one on this one!

It's my second largest dependency in my node_modules.  My only dependency larger than app insights is core-js and I can still trim those down.  Shipping with 303kb is very large for what the library is doing.

![image](https://user-images.githubusercontent.com/11936796/74484068-21987080-4e75-11ea-8fc8-fd1c73c803e3.png)

**Comment by danieljaguiar** [comment]
Any updates here?

**Comment by MSNev** [comment]
@danieljaguiar rather than taking a big bang approach we are doing this in smaller chunks, in the next few months we will be spending some time refactoring some of the bigger items, but you will already see some changes (even though the total size is still a lot larger than I'd like) where we have introduced the DynamicProto() module and refactored some of the modules we have recently made changes on (like the dependencies module).

My next major target will be the sender channel.

**Comment by dimaqq** [comment]
> @danieljaguiar rather than taking a big bang approach we are doing this in smaller chunks...

Can't wait!

Today (`applicationinsights-web 2.5.8`) is **the largest** package in my build. Given that I don't strictly need it for the application to be functional, I'm considering to drop it (and azure insights) every so often...

**Comment by MSNev** [comment]
Hi All,

I'm looking for feedback on the results of the 2.6.0 changes around the added tree-shaking support
https://github.com/microsoft/ApplicationInsights-JS#tree-shaking-support-and-enhancements

Has anyone managed to successfully follow the guidance with the new bits and did it provide a significant improvement?

Looking over the code I'm not currently finding big chunks (like the work done in the 2.6.0 release) that will have quite the same impact -- so it will be back to small incremental improvements (I think)

**Comment by MSNev** [comment]
The final part of the planned work for the 2.x code base is now in PR, this has been a long road and depending on which SKU you use the new PR will provide a different level of savings.
However, because we have continued to add features and provide backward compatibility overall this package is still larger than I'd like.

As part of the 3.x code (which will be in beta in a month or so) and now planned for release in early 2023, we will be removing some of the legacy code (that most people don't use) to try and bring the package size back down. This will include
- Removal ES3 support and the associated internal Polyfills
- Removal of the namespaced "helper" classes (like CoreUtils) and will only provide the unnamespaced helpers (if you have good tree shaking already your packaging "should" already be doing this), this is primarily to help the CDN payload as internally we no longer use these namespaced helpers this way.
- As we get further into the `beta` I'm sure we will find more code that can be removed or refactored, will it be significantly smaller? Don't know are this point as we are also adding support for dynamic config updates (part 2 of the full SDK unload / reinitialize that is in the current release). Once we get going I'll update the size tracking [here](https://github.com/microsoft/ApplicationInsights-JS/tree/master/AISKU) to include the `beta` as well as the items that are currently there.
