### ISSUE TITLE
[BUG] Multiple App Insights instances auto collect not working?

### ISSUE THREAD

**Issue by mirajp** [microsoft/ApplicationInsights-JS#1078]
**Description/Screenshot**
I instantiated 2 instances of App Insights and expected to see the auto collection in both App Insights. However, I only see track telemetry going out with the key of the 2nd (last) instantiated -- nothing goes out to the 1st app insight instance. Also check in Azure Portal and notice the same items are not in both instances (in fact nothing new is recorded in the instance that is initialized first).

**Steps to Reproduce**

 - OS/Browser: Chrome on windows 10.
 - SDK Version: 2.2.4
 - How you initialized the SDK:
```
import { ReactPlugin } from '@microsoft/applicationinsights-react-js';
import { ApplicationInsights, ITelemetryItem, IEventTelemetry } from '@microsoft/applicationinsights-web';

import Environment from '../environments';
import history from '../history';

const reactPlugin = new ReactPlugin();
const defaultAppInsightsConfig = {
    disableAjaxTracking: false,
    disableFetchTracking: false,
    enableAutoRouteTracking: true,
    enableCorsCorrelation: true,
    enableDebugExceptions: true,
    endpointUrl: Environment.telemetryUrl,
    extensionConfig: {
        [reactPlugin.identifier]: { history },
    },
    extensions: [reactPlugin],
    instrumentationKey: Environment.telemetryKey,
    maxBatchInterval: 0,
};


const appInsights = new ApplicationInsights({config: defaultAppInsightsConfig});
appInsights.loadAppInsights();

const secondAppInsights = new ApplicationInsights({
    config: {
        ...defaultAppInsightsConfig,
        instrumentationKey: Environment.secondTelemetryKey,
    });
secondAppInsights.loadAppInsights();
```

**Expected behavior**
Expected it to log into both App Insights instances.

**Comment by markwolff** [comment]
Hi, can you try setting a `namePrefix` for one of your instances?

**Comment by mirajp** [comment]
Yes I did, I also set it on both but no matter what I did, only the 2nd one has outbound 'track' network traffic. Btw, I'm trying to get all the auto-collection to be duplicated (dependency data, page views, etc.).

**Comment by mirajp** [comment]
I ended up getting this to work:

```
if (Environment.secondTelemetryKey) {
    // @ts-ignore
    XMLHttpRequest.prototype.realSend = XMLHttpRequest.prototype.send;
    XMLHttpRequest.prototype.send = function(value: any) {
        let parsedValue = value;
        try {
            parsedValue = JSON.parse(value);
        } catch {}
        
        let valueToSend = value;
        if (Array.isArray(parsedValue)) {
            valueToSend = [];
            parsedValue.forEach((telemetryItem: any) => {
                if (telemetryItem && telemetryItem.iKey === Environment.telemetryKey) {
                    const clonedItem = cloneDeep(telemetryItem);
                    clonedItem.iKey = Environment.secondTelemetryKey;
                    valueToSend.push(clonedItem);
                }
                valueToSend.push(telemetryItem);
            });
            parsedValue = JSON.stringify(valueToSend);
        }
        // @ts-ignore
        this.realSend(parsedValue);
    };
}
```

Using lodash's cloneDeep, I can clone the outgoing telemetry and modify the instrumentation key with the 2nd AI instance's key when I want to selectively send telemetry into that 2nd App Insights.

**Comment by markwolff** [comment]
Forking your data seems fine to me. Also be aware that the instrumentation key is in 2 different places in your telemetryItem var. It is both in `telemetryItem.iKey`, as you've already set, and in the middle of `telemetryItem.name` with the dashes removed!

**Comment by mirajp** [comment]
Do you mean the top-level `name` key-value which is dot-delimited?
> Microsoft.ApplicationInsights.{iKey}.Pageview
> Microsoft.ApplicationInsights.{iKey}.RemoteDependency

The only key-value with hyphens I saw was the sessionId (`tags['ai.session.id']`)

Note for future readers, I'll end up doing this:
```
clonedItem.iKey = Environment.secondTelemetryKey;
clonedItem.name = clonedItem.name.replace(Environment.telemetryKey, Environment.secondTelemetryKey);
```

**Comment by markwolff** [comment]
Yes the top-level `name` key. The iKey there is without dashes, e.g.
```
Microsoft.ApplicationInsights.{iKeyWithoutDashes}.Pageview
```

**Comment by mirajp** [comment]
Oh oops, thanks! Updated my snippets.
