### ISSUE TITLE
custom event name is getting recorded as "not_specified"

### ISSUE THREAD

**Issue by amitphule** [microsoft/ApplicationInsights-JS#1079]
**Description/Screenshot**
Name of the custom event is showing "not_specified" even after providing value.

![image](https://user-images.githubusercontent.com/6881833/66305213-77d03280-e91c-11e9-97bc-06173328ccc9.png)

**Code snippet:**
Init sdkInstance :
`var sdkInstance = "appInsightsSDK"; window[sdkInstance] = "appInsights"; var aiName = window[sdkInstance], aisdk = window[aiName] || function (e) { function n(e) { t[e] = function () { var n = arguments; t.queue.push(function () { t[e].apply(t, n) }) } } var t = { config: e }; t.initialize = !0; var i = document, a = window; setTimeout(function () { var n = i.createElement("script"); n.src = e.url || "https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js", i.getElementsByTagName("script")[0].parentNode.appendChild(n) }); try { t.cookie = i.cookie } catch (e) { } t.queue = [], t.version = 2; for (var r = ["Event", "PageView", "Exception", "Trace", "DependencyData", "Metric", "PageViewPerformance"]; r.length;)n("track" + r.pop()); n("startTrackPage"), n("stopTrackPage"); var s = "Track" + r[0]; if (n("start" + s), n("stop" + s), n("setAuthenticatedUserContext"), n("clearAuthenticatedUserContext"), n("flush"), !(!0 === e.disableExceptionTracking || e.extensionConfig && e.extensionConfig.ApplicationInsightsAnalytics && !0 === e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)) { n("_" + (r = "onerror")); var o = a[r]; a[r] = function (e, n, i, a, s) { var c = o && o(e, n, i, a, s); return !0 !== c && t["_" + r]({ message: e, url: n, lineNumber: i, columnNumber: a, error: s }), c }, e.autoExceptionInstrumented = !0 } return t }(
            {
                instrumentationKey: "<AppInsightsInstrumentationKey>"
            }
        ); window[aiName] = aisdk, aisdk.queue && 0 === aisdk.queue.length && aisdk.trackPageView({});`

Track event:
`appInsights.trackEvent("DocumentLink", {
                    eventCategory: "DocumentLink", eventAction: "click", documentUrl: "/Documents/AZ0002.docx"
                });`

**Steps to Reproduce**
1. Setup appInsightsSDK
2. Call following method:
appInsights.trackEvent("DocumentLink", {
                    eventCategory: "DocumentLink", eventAction: "click", documentUrl: "/Documents/AZ0002.docx"
                });
3. Go to Azure Portal and open App insights service.
4. From Logs (Analytics), view custom events.

**Expected behavior**
Custom event name should show "DocumentLink" instead of "not_specified"
**Additional context**
Website is hosted on Azure App service

**Comment by markwolff** [comment]
Hi, latest snippet of the SDK uses named arguments.
```js
appInsights.trackEvent({
  name: "DocumentLink",
  properties: { eventCategory: "DocumentLink", eventAction: "click", documentUrl: "/Documents/AZ0002.docx" }
});
```
https://github.com/microsoft/ApplicationInsights-JS#sending-telemetry-to-the-azure-portal
