### ISSUE TITLE
[Enhancement] AI is not catching all "Unload" dom events

### ISSUE THREAD

**Issue by MSNev** [microsoft/ApplicationInsights-JS#1080]
**Description/Screenshot**
The Beforeunload is not the only navigation away event that should be caught the list of events should include
- beforeunload
- unload
- pagehide

It should also be attached to the document as not all browsers (mostly older ones) support the events on window.

**Comment by egrendonDev** [comment]
Hi MSVen,

Have you made any progress on this issue? We are also experiencing similar issues on Desktop Chrome 78. Users appears to randomly have missing application insight events. The options have been set to 100% sampling. And we are are calling "appInsightsFlush()"  on every browser "beforeunload" event.


`	public initAppInsightsAnalytics(): void {
		if (!this.isAppInsightsInitialized) {
			AppInsights.downloadAndSetup({
				instrumentationKey: this.appInsightsKey,
				samplingPercentage: 100  // 100% of all telemetry will be sent to Application Insights
			});

			this.isAppInsightsInitialized = true;
		}
	}`


`	/**
	 * Method will initialize the session expired subscription monitoring
	 */
	private initBrowserWindowClosedSubscribe() {
		this.windowProvider.browserWindowClosed$
			.pipe(takeUntil(this.subscriptionKiller))
			.subscribe((event: any) => {
					//console.log('Attempt to flush before we close browser window');
					//Attempt to flush AppInsights before we close browser window
					this.appInsights.appInsightsFlush();
				}
			);
	}`


Thanks,
Ernesto

**Comment by MSNev** [comment]
Not yet, as I've been working on the IE8 compatability item, I suspect I should get to this by the end of november (not withstanding the holidays).
The change itself is not that large, I just have a few other high priority items on my work list before I get to this one. The main one that we are missing is the pagehide event (https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event) which is when the user hits the browser back button.

**Comment by MSNev** [comment]
Hi Ernesto,

PR created to address this enhancement

Cheers
Nev

**Comment by egrendonDev** [comment]
@MSNev - This is great news! ETA on a new possible release?

**Comment by MSNev** [comment]
The change should get checked in this week, but I don't have a timeline for when we would push a new release yet. That's probably still the end of Nov unless we end up with some sort of High Priority issue that needs addressing/publishing.

**Comment by MSNev** [comment]
PR checked in and fixed should be included in v2.3.2 or later
