### ISSUE TITLE
[BUG] Can not send telemetry from React app in Chrome

### ISSUE THREAD

**Issue by austinrutledge0** [microsoft/ApplicationInsights-JS#1084]
I configured application insights inside of my react app using the NPM Setup. I can send telemetry from Edge, but not from Chrome. The error I get in my console is as follows.

VM292:1 OPTIONS https://dc.services.visualstudio.com/v2/track net::ERR_BLOCKED_BY_CLIENT

Here is the error I get when I open the failed network call
Request URL: https://dc.services.visualstudio.com/v2/track
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Access-Control-Request-Headers: content-type,sdk-context
Access-Control-Request-Method: POST
Origin: http://localhost:3000
Referer: http://localhost:3000/login
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by markwolff** [comment]
Probably because of [adblock](https://stackoverflow.com/questions/23341765/getting-neterr-blocked-by-client-error-on-some-ajax-calls)
