### ISSUE TITLE
Enhancement: update location.country property name

### ISSUE THREAD

**Issue by 3xj** [microsoft/ApplicationInsights-JS#1085]
**Is your feature request related to a problem? Please describe.**
We discovered during our security review that the `location.country` property name is flagged as an issue in the PoliCheck tool. Here is the guidance we received from MSFT CELA:
> The “location.country” code should be updated to location.countryRegion.  Even though this is in code, if it is open source then likely it will be seen by people.  Our recommendation is to change this if at all possible, or contact the MS team that owns this OSS component.  While not urgent, it definitely is a “good to fix”.

**Describe the solution you'd like**
Update `location.country` to `location.countryRegion`

**Describe alternatives you've considered**

**Additional context**

**Comment by markwolff** [comment]
The `location.country` tag is used by all SDKs and is something that is specifically parsed by the ingestion server, so I would re-open  this issue over at [https://github.com/microsoft/applicationinsights-home](ApplicationInsights-Home) (I'm unable to transfer it there)
