### ISSUE TITLE
getUniqueIdSync is not a function

### ISSUE THREAD

**Issue by Highspeed7** [microsoft/ApplicationInsights-JS#1086]
Your ReactNativePlugin calls getUniqueIdSync(); and getModelSync()... both of which no longer exist in the react-native-device-info package.

![image](https://user-images.githubusercontent.com/9501337/66720529-a6ce2480-edb2-11e9-8043-334a4ae3d39e.png)

**Comment by Highspeed7** [comment]
Downgrading react-native-device-info-package to v4.0.1-beta.4 circumvents this issue. For anyone else who comes across this.

**Comment by WolfyUK** [comment]
I downgraded to `3.1.4` to resolve this. 

At the very least the [README.md](https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-react-native/README.md) should modify the *Keep `react-native-device-info` up-to-date* clause as this tripped me up.

**Comment by markwolff** [comment]
Sorry for the delay on this. I've republished the react-native plugin (2.0.1) to use the latest breaking change version of rndi. It should use constants where available, else it will use the sync APIs. Please let me know how it goes!
