### ISSUE TITLE
[BUG] If a user hibernates his computer when a request is performing, AppInsights sends duration of the request equals the duration of the computer's sleep

### ISSUE THREAD

**Issue by Mental-NV** [microsoft/ApplicationInsights-JS#1090]
**Description/Screenshot**
AppInsights' portal shows us that the duration of some requests equal to a few days. It cannot be true, the maximum timeout for requests we have is 5 minutes.
![image](https://user-images.githubusercontent.com/7886867/66915652-33324e80-f022-11e9-9d3d-01a5a16cd4c2.png)

We investigated the issue and found that it happens when a user ends his web session by hibernating the computer. If the hibernation happens in the middle of performing a request, AppInsights sends a request duration equals the duration of the sleep. For example, here are a few sessions when a user worked with a particular page and finished the sessions by hibernating his computer:
![image](https://user-images.githubusercontent.com/7886867/66917227-ad180700-f025-11e9-86b4-1b47039f7546.png)

**Steps to Reproduce**
Needs to run a request which will last at least 30 seconds (to catch the issue easier) and hibernate the computer in the middle of performing the requests. Wake up the computer after 10 minutes and AppInsights will send telemetry that the request lasted 10 minutes. 

 - OS/Browser: Windows 10/Edge 18.18362 (actually it happens in any browser including mobile browsers on iOS and Android)
 - SDK Version [e.g. 22]: 2.2.2 (latest)
 - How you initialized the SDK: by using a snippet from the documentation https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#snippet-based-setup

**Expected behavior**
Exclude telemetry which measures the longevity of a computer sleep

**Comment by markwolff** [comment]
For this, I'd recommend implementing a [telemetry initializer](https://github.com/microsoft/ApplicationInsights-JS#telemetry-initializers) which you can use to preprocess your telemetry before it is sent over the wire. For example, you can set it to drop any telemetry item (`return false`) which is of type `DependencyData`  and has a duration that exceeds some limit
