### ISSUE TITLE
"Pause" sending of messages

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/ApplicationInsights-JS#1093]
Hi,
I have the usecase that some informations (eg. UserName) are not directly available after startup, but getting fetched after bodyloaded. However, appInsights should start asap on the page to be able to record every action/requests done already during pageload.

Problem is, that currently the first messages are sent to appInsights without the informations (eg. Username) as they were not available at that point.

What I want to ask is, if there is the possibility to somehow let the appInsights engine run, so that it can record everything, but hold back the sending of the messages to the server, until a specific event occurs (in my case all of the informations are available), eg. through a promise. 

Something like the opposite of the "flush" command, if you know what I mean

**Comment by MSNev** [comment]
Just to clarify, it sounds like your looking not just to "pause" sending of messages but also to wait until some specific point in time to "post process" all recorded/reported events so you can update them with in this case user details... Am I following the request correctly?

We have a feature planning to allow pausing / resuming the sending of event, however, this is really caching and batching previously reported events -- there is (currently) no option to re-decorate the events as this can and could lead to reporting incorrect data (from a timeline perspective at least)
