### ISSUE TITLE
[BUG]client_IP value always 0.0.0.0

### ISSUE THREAD

**Issue by zhangKunUserGit** [microsoft/ApplicationInsights-JS#1098]
I look for documents
![image](https://user-images.githubusercontent.com/13297317/67729152-f5262900-fa2a-11e9-89b7-eded50f1997f.png)

Example：
![image](https://user-images.githubusercontent.com/13297317/67729075-abd5d980-fa2a-11e9-9efd-42f8c6d74f40.png)

Can I have a look, please！

**Comment by xiao-lix** [comment]
Hi @zhangKunUserGit , please check the first answer in this [post](https://social.msdn.microsoft.com/Forums/en-US/d7587623-25d0-4982-bb5e-2cb167ea59a0/client-ip-logged-as-0000-but-geolocation-is-logged-correctly?forum=ApplicationInsights). 
But you can send IP by using `addTelemetryInitializer`, something like this: 
```
var telemetryInitializer = (envelope) => {
  envelope.tags["ai.location.ip"] = "your ip";
}
appInsights.addTelemetryInitializer(telemetryInitializer);
```
The link of the doc is here: https://github.com/microsoft/ApplicationInsights-JS#telemetry-initializers

**Comment by xiao-lix** [comment]
Hi @zhangKunUserGit , double checked on our end, the approach above will show you the custom added tags through Network ( if you open chrome dev tools ) but will stripped off by the endpoint but not scrubbed by our SDK. Instead, you can add it as a custom property: 
```
var telemetryInitializer = (envelope) => {
  envelope.baseData.properties = {};
    envelope.baseData.properties['ip'] = "1.2.3.4";
}
appInsights.addTelemetryInitializer(telemetryInitializer);
```
Then this will show in the portal under `Custom Properties` field: 
![image](https://user-images.githubusercontent.com/20292261/67995235-ac2acc00-fc06-11e9-8dcf-5684990ba3f5.png)
