### ISSUE TITLE
trackEvent API Reference Wrong?

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/ApplicationInsights-JS#1101]
**Description/Screenshot**
When I call: `appInsights.trackEvent({ name: 'mike d event name test' });` it produces _'[object Object]'_ for an `Event name`:

![image](https://user-images.githubusercontent.com/14079228/67698243-6230b480-f980-11e9-9755-daa76bda14a6.png)

---

But according to [Sending Telemetry to the Azure Portal](https://github.com/microsoft/ApplicationInsights-JS#sending-telemetry-to-the-azure-portal) in the readme I should be using: `appInsights.trackEvent({name: 'some event'});`

Also, the [API reference for trackEvent](https://github.com/microsoft/ApplicationInsights-JS/blob/master/API-reference.md#trackevent) says it takes in an [`ITelemetryEvent`](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Interfaces/IEventTelemetry.ts) which is defined as:

```
export interface IEventTelemetry extends IPartC {
    /**
     * @description An event name string
     * @type {string}
     * @memberof IEventTelemetry
     */
    name: string;
}
```

---
When I search through the code I see tests that are passing strings not objects:

![image](https://user-images.githubusercontent.com/14079228/67952001-f25e3c00-fbc2-11e9-8c20-6ae1657daf2a.png)

**Steps to Reproduce**

 - OS/Browser:
 - SDK Version: Microsoft.ApplicationInsights.AspNetCore (2.8.1) via NuGet 
 - How you initialized the SDK: I didn't directly, I just add app insights to my ASP.NET Core project via Visual Studio and it wired up the magic.  Looks like it added `@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet` to my _'_Layout.cshtml'_ file.

**Expected behavior**

**Additional context**

**Comment by spottedmahn** [comment]
I just noticed _Legacy_ in the path for [my search results](https://github.com/microsoft/ApplicationInsights-JS/search?p=2&q=trackEvent&unscoped_q=trackEvent).

I'm guessing the old way it was just a string, i.e. `appInsights.trackEvent('mike d event name test');`

---

How do I determine the SDK version for App Insights JS when using the [NuGet package](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/)? 🤔

When will the [NuGet package](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/) have the new pattern? 🤔

**Comment by markwolff** [comment]
You are probably using the legacy version of the SDK as you've determined. We are in the process of updating all dotnet integrations after we ensure the SDK works properly on <IE8. I think you can do `window.appInsights.version` in your console, but I could be wrong... Else the sdk version will show up in the "tags" section of your telemetry

**Comment by spottedmahn** [comment]
>the sdk version will show up in the "tags" section of your telemetry
_v1.0.20_ apparently

![image](https://user-images.githubusercontent.com/14079228/67967155-758b8c00-fbdb-11e9-84f7-2971412a7e79.png)

**Comment by markwolff** [comment]
Actually that nuget package may be updated with the latest JS SDK soon. This PR was just merged to move it to the latest https://github.com/microsoft/ApplicationInsights-dotnet/pull/1276#event-2758134114

/cc @timothyMothra can provide a rough ETA

**Comment by TimothyMothra** [comment]
Hi @spottedmahn. 
We're going to be releasing an update to AspNetCore probably next week (2.12-Beta2) with the stable release coming in December.
