### ISSUE TITLE
withAITracking reports Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by ayayalar** [microsoft/ApplicationInsights-JS#1106]
**Description/Screenshot**

![image](https://user-images.githubusercontent.com/130195/68049570-7cc89d80-fca0-11e9-93b4-9ef5d69fe879.png)

**Steps to Reproduce**
Here is the codesandbox to repro the problem
[codesandbox](https://codesandbox.io/s/app-insights-demo-mpg39?fontsize=14)

**Expected behavior**
withAITracking should not report this error

**Comment by markwolff** [comment]
Hi, I was able to get this working by exporting out the react plugin after it had been initialized by the SDK. It didn't work when I made this change in the codesandbox, but it was working if I cloned it instead...

**Comment by ayayalar** [comment]
Hi Mark, thank you for quick response. Do you mind sharing the link to your sandbox?

**Comment by markwolff** [comment]
Sure, [here](https://codesandbox.io/s/app-insights-demo-fnum2?fontsize=14) it is. When running it locally, it makes a bunch of changes to the tsconfig for me (I think the export style I used is esnext compat only), but pushing those over to the sandbox doesn't seem to fix it there either.

**Comment by ayayalar** [comment]
So I still see the same issue in your cloned sandbox. Did I misunderstand what you said? I thought you said when you cloned it, it worked correctly?

**Comment by markwolff** [comment]
I mean cloning as in downloading the sandbox and running it locally on my machine :)

**Comment by ayayalar** [comment]
Yes, you are right. It works locally, just fine. I did not expect that :). Okay, I will close the issue, and perhaps the codesandbox account! Thanks Mark!

**Comment by dabarne** [comment]
Did you figure out what was different about the local environment that got rid of this error? I find that I am having it when running jest tests, but cannot figure out how to fix it.

**Comment by ayayalar** [comment]
Initially, I was testing it in the code sandbox and ran into this problem. Locally, I never experienced it. I figured it is the sandbox environment that might have an issue. I didn’t further research.

**Comment by dabarne** [comment]
Ah, ok, thanks.

**Comment by millicentachieng** [comment]
@dabarne Did you find a solution for your tests problem? I'm having the same issue.

**Comment by dabarne** [comment]
@millicentachieng It's been a while, but I remember re-implementing the code setting up the app insights service out of the index to its own component, like here: https://www.aaron-powell.com/posts/2019-10-04-implementing-monitoring-in-react-using-appinsights/, and this helped!

**Comment by millicentachieng** [comment]
That helped. Thanks @dabarne .
