### ISSUE TITLE
track requests failing with 400. Field 'ai.operation.name' on type 'ContextTagKeys' is too long. Expected: 1024 characters, Actual: 1169"

### ISSUE THREAD

**Issue by studioab** [microsoft/ApplicationInsights-JS#1107]
JS SDK used in React web app. We are sending basic telemetry to Appinsight, same code was working for 4 months without any problems.

Few days ago we noticed that 90% our telemetry isn't coming through and track requests are failing with error 

`Field 'ai.operation.name' on type 'ContextTagKeys' is too long. Expected: 1024 characters, Actual: `

Is this a known bug? Any help is appreciated.

**Comment by Dmitry-Matveev** [comment]
@markwolff, I moved this issue from AI-Home repo, can you please take a look?

**Comment by markwolff** [comment]
Hi, are you using NPM to consume the SDK, or the snippet? If you are using NPM, could you look at your package-lock file and let me know which version of the SDK you are using? Do you have any telemetry initializers or telemetry processors which are writing to this tag member?
