### ISSUE TITLE
[BUG] [Legacy] Sender does not retry sending telemetry during browser offline

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/ApplicationInsights-JS#1108]
**Description/Screenshot**
In `Sender._xhrReadyStateChange`, if browser goes offline, `xhr.status` will be 0. In this case, the code path goes directly to L525, meaning the telemetry is marked as "sent successfully". This will cause all the telemetry lost during browser offline. I'm not sure, but is this by design (for legacy)? If not, is it possible to provide a fix on it, as we are currently still on `ai.0.js`?

https://github.com/microsoft/ApplicationInsights-JS/blob/17ef50442f73fd02a758fbd74134933d92607ecf/legacy/JavaScript/JavaScriptSDK/Sender.ts#L502-L528

**Steps to Reproduce**

 - OS/Browser: Edge 80.0.320.3 dev
 - SDK Version [e.g. 22]: **1.0**.20
 - How you initialized the SDK: snippet

**Expected behavior**
I suppose the retry behavior should be applied for the case where browser goes offline.
Here is the [v2 counterpart](https://github.com/microsoft/ApplicationInsights-JS/blob/0b12b6163ea1d6acc6ad590d0e8fb633feb283c1/channels/applicationinsights-channel-js/src/Sender.ts#L360).

**Additional context**

**Comment by markwolff** [comment]
We probably won't be moving those over to the legacy version without a major reason since no significant updates are planned for the legacy version. Are you unable to update to the latest version?

**Comment by chenxinyanc** [comment]
Thanks for your confirmation! I think we will eventually upgrade the SDK but the work is still being prioritized, and we need to ensure nothing is broken by the upgrade.

Will update this issue (or in other way) if we meet anything really tough to solve.
