### ISSUE TITLE
Project has an unmet peer dependency: "tslib"

### ISSUE THREAD

**Issue by rafaelalmeidatk** [microsoft/ApplicationInsights-JS#1114]
**Description/Screenshot**

There is a warning about a missing peerDependency. This is not expected to happen because my project doesn't even use TS.

**Steps to Reproduce**

Run `yarn add @microsoft/applicationinsights-web` in a JS project and you will receive the following warning:

    warning " > @microsoft/applicationinsights-web@2.3.1" has unmet peer dependency "tslib@^1.9.3".

**Expected behavior**

You should be able to install the lib without warnings. In my opinion, `tslib` shouldn't be a peer dependency.

**Comment by markwolff** [comment]
`tslib` isn't directly a "typescript" dependency, but rather a helper. It makes bundle sizes smaller by making the assumption that most libs being consumed are reusing the same helpers via tslib. It is a direct dependency of all of the "extensions" of this project, and so the peer dependency should be met anyways after installing. Your app would be throwing errors if tslib were not installed via the full dep tree, although yarn might not be checking the full dependency tree before checking peer dependencies.

It might make sense to just add tslib as a pure dep to the `-web` package to suppress this error

**Comment by rafaelalmeidatk** [comment]
Thanks for the explanation. In this case, it is indeed best suited as a dependency (like Formik does, for example, https://github.com/jaredpalmer/formik/blob/master/package.json#L53)

If you add a dependency as a peerDepedency it is expected that the consumer have it in their own `package.json`, which is not necessary in this case.

**Comment by markwolff** [comment]
Thanks for the feedback! I'll move it over as a pure dep

**Comment by wbeeftink** [comment]
Ran into the same. Cheers for looking into this 👌🏻

**Comment by markwolff** [comment]
This was fixed by #1116, but will be released in Jan release
