### ISSUE TITLE
[BUG] enableCorsCorrelation doesn't work on ionic/cordova app

### ISSUE THREAD

**Issue by eelitlauree** [microsoft/ApplicationInsights-JS#1115]
**Description/Screenshot**

I want to correlate my ionc app to my api server on Application Map of Application Insights. So I set "enableCorsCorrelation" to true in the config object and construct ApplicationInsights with the object. 

However, the configuration doesn't take effect when I build and run the android app on devices/emulator. I suspected the issue is caused by this line of code.

https://github.com/microsoft/ApplicationInsights-JS/blob/8d7fd1e43c41ee2e94c4cde3ddbcbed8ef9fc258/extensions/applicationinsights-dependencies-js/src/ajax.ts#L154-L155

```this.currentWindowHost ``` will be an empty string in runtime, since it is assigned to be window.location.host, [here](https://github.com/microsoft/ApplicationInsights-JS/blob/8d7fd1e43c41ee2e94c4cde3ddbcbed8ef9fc258/extensions/applicationinsights-dependencies-js/src/ajax.ts#L98), which is an empty string when running with cordova runtime (cordova-android@7.1.1).

**Steps to Reproduce**

 - OS/Browser: Android 4.4+
 - SDK Version [e.g. 22]: @microsoft/applicationinsights-web 2.3.1
 - How you initialized the SDK: 

```
new ApplicationInsights({ config: {
      instrumentationKey: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
      correlationHeaderDomains: [domain], 
      enableCorsCorrelation: true
    }});
```

**Expected behavior**

"Request-Id" should be sent along with all requests to API server. 

**Additional context**

**Comment by markwolff** [comment]
It seems like the `this.currentWindowHost &&` part of the conditional could be removed and an update to `canIncludeCorrelationHeader` to add some falsey sanitization would resolve this
