### ISSUE TITLE
App insights APPINSIGHTS_JAVASCRIPT_ENABLED preventing slider.js

### ISSUE THREAD

**Issue by siddheshGit** [microsoft/ApplicationInsights-JS#1123]
**Description/Screenshot**
I have enabled clientsite event tracking using APPINSIGHTS_JAVASCRIPT_ENABLED after this 
my internal image slider javascript for home page i not working
**Steps to Reproduce**

 - OS/Browser:
All
 

**Expected behavior**
Image slide should work properly
**Additional context**
Please let me know any solution for this.

**Comment by markwolff** [comment]
If APPINSIGHTS_JAVASCRIPT_ENABLED does not work as intended, you should try manually adding the SDK via the snippet instead

**Comment by siddheshGit** [comment]
@markwolff you please help me to find best guide for doing so..

**Comment by markwolff** [comment]
You can use these docs
https://github.com/microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup
