### ISSUE TITLE
[BUG] @microsoft/applicationinsights-angular-js is not published

### ISSUE THREAD

**Issue by biltongza** [microsoft/ApplicationInsights-JS#1124]
As title says, the package is present in the source repo but it does not appear to be on the public npm registry.

Also, it is not mentioned in the docs, I found it by accident when I wanted to check the source of the react plugin.

**Comment by MSNev** [comment]
This is because it's has not yet been officially published / complete.

**Comment by hhermas** [comment]
Any update on this?
