### ISSUE TITLE
Disable Cookies

### ISSUE THREAD

**Issue by PartisanEntity** [microsoft/ApplicationInsights-JS#1125]
We want to disable the Application Insights cookies for our EPiServer project.

I was told that we need to set isCookieUseDisabled to true in ApplicationInsights.config. But I think this is incorrect?

From what I have managed to gather so far this settings needs to go in https://az416426.vo.msecnd.net/scripts/a/ai.0.js - is my assumption correct?

If yes, then I would need to download this JS file, modify it and then point to my modified version?

Thankful for any help.

**Comment by MSNev** [comment]
Setting the config entry "isCookieUseDisabled" to a value of true is the correct way to tell the SDK not to use cookies (set, get, delete).

There is also a global switch we are are considering moving Util.disableCookies() or CoreUtils.disableCookies() which disable the cookies functions for ALL AppInsights usages (this means that if you are using another component on your page and it also uses AppInsights then it will also be disabled.

Discussion on this is on the following issue
https://github.com/microsoft/ApplicationInsights-JS/issues/1091

Cheers
Nev

**Comment by PartisanEntity** [comment]
Thanks very much, where do I need to set this? In which file?

**Comment by MSNev** [comment]
You canb just set this as part of the configuration (same location as the instrumentationKey).
const appInsights = new ApplicationInsights({ config: {
  instrumentationKey: 'YOUR_INSTRUMENTATION_KEY_GOES_HERE'
  /* ...Other Configuration Options... */
  isCookieUseDisabled: true
} });

However, as per the other thread, there is currently no non-hacky way to re-enable for the session.

**Comment by markwolff** [comment]
I am not sure if ApplicationInsights.config propagates the setting over to the JS snippet, but if you can tweak the snippet, what Nev mentioned is all you would need to do. You do not need to modify `ai.0.js`.

See here https://github.com/microsoft/applicationinsights-js#basic-usage

**Comment by MSNev** [comment]
Closing as seems to be resolved @PartisanEntity please feel free to reopen if not.
