### ISSUE TITLE
Manage SameSite Cookie Settings

### ISSUE THREAD

**Issue by audacity76** [microsoft/ApplicationInsights-JS#1126]
I was wondering how I can set the SameSite option for the Application Insights cookies. Chrome will change the behavior of SameSite cookies in Feb 2020 (https://www.chromestatus.com/feature/5088147346030592). Is there any documentation how the cookie options are set depending on the browser agent?

**Comment by markwolff** [comment]
If you are on the latest version of the SDK, we are already [setting SameSite to `None`](https://github.com/microsoft/ApplicationInsights-JS/pull/1088/commits/12c6799f25d637425d81fbd3b80031b7fe54cd74). This only applies to new cookies, and existing cookies will not have the policy applied to them. From what I can tell the new policy only blocks the "creation" of non-policy'd cookies.

**Comment by audacity76** [comment]
Thank you for your information. As far as I know the cookie setting depends on the browser agent as there are incompatible clients: https://www.chromium.org/updates/same-site/incompatible-clients

**Comment by neolefty** [comment]
It looks like the fix for legacy cookies (issue #1112) is not in the latest NPM release 2.3.1:

* Fix: https://github.com/microsoft/ApplicationInsights-JS/pull/1112 was published 2019-11-08
* NPM package v2.3.1 was published on 2019-11-07: https://www.npmjs.com/package/@microsoft/applicationinsights-react-js/v/2.3.1

**Comment by markwolff** [comment]
@neolefty The legacy cookie fix PR is (unreleased) patch for 1.0.20 iteration of the (legacy) SDK. For the 2.* version, the cookie change for this SDK is already released

**Comment by hiraldesai** [comment]
I have an angular app using version 2.4.2 of the @microsoft/application-insights-web package and the SameSite issue doesn't happen in Chrome80 but I noticed that Edge Chromium Version 79.0.309.71 (Official build) (64-bit) is still writing no SameSite attribute that results in a warning (screenshot).

![image](https://user-images.githubusercontent.com/1005174/73583535-a16f1580-4447-11ea-9491-570fe544729c.png)

**Comment by markwolff** [comment]
@hiraldesai Could you delete the cookie and see if it writes it with the correct property?

**Comment by hiraldesai** [comment]
I had tried that before, tried it one more time. Same issue. 

![image](https://user-images.githubusercontent.com/1005174/73584008-3ffc7600-444a-11ea-9ba8-559e40e3cbd0.png)

**Comment by markwolff** [comment]
Was it also an issue on 2.3.1?

**Comment by MSNev** [comment]
The issue is that the URL must be https, otherwise we don't write the Secure; or SameSite=None settings. As SameSite requires Secure :-). and looking at the URL in the screenshot its http://localhost

**Comment by hiraldesai** [comment]
Ohhh, my bad! Sorry I should have figured it out on my own. Thank you for checking!

**Comment by MSNev** [comment]
Version 2.4.3 is now published to CDN and NPM and addresses this the SameSite issues, it also includes checks for incompatible clients.
