### ISSUE TITLE
page view > name returning incorrectly on android and iOS mobile browser

### ISSUE THREAD

**Issue by matthiasploetz** [microsoft/ApplicationInsights-JS#1127]
I would appreciate some help to figure out why the name of the page view is not returning correctly for mobile safari on iOS and android mobile browser.

page title is "Tracing lost payments"
name in page view is "Open sidebar"

The name property in the page view is populated correctly on other browsers.

![doc title in source](https://user-images.githubusercontent.com/10324309/70081043-99683600-15bc-11ea-9664-3e779798a60c.png)
![name property](https://user-images.githubusercontent.com/10324309/70081046-99683600-15bc-11ea-8b48-bfea89f6bb7b.png)
![device info](https://user-images.githubusercontent.com/10324309/70081047-99683600-15bc-11ea-8059-a11acc32254e.png)

**Comment by markwolff** [comment]
We fill in the pageview name to be `window.document.title` by default. Does this var show up differently on mobile?

**Comment by matthiasploetz** [comment]
Thank you!! yes, indeed. Turned out to be a bug on our end. Thank you for your help. Sometimes short questions trigger the right thinking.
