### ISSUE TITLE
Id format changes in W3C mode

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-JS#1136]
In W3C mode we report parentId and Id in the format of `|traceId.parentSpanId.` and `|traceId.spanId.` respectively.

This is not needed anymore even for backward compatibility reasons. Compatibility with old versions of Application Insights SDK is handled by ingestion.

**Describe the solution you would like**

I believe JS SDK does not have incoming request scenario.
**For dependencies**
-  dependency.Context.Operation.Id = traceId, // no changes
-  dependency.Context.Operation.ParentId = parent span id, // new, was |trace.parent.
-  dependency.Id = new span id, // new, was |trace.span.

**When sending Request-Id in outgoing requests it still MUST be formatted in the |TraceId.SpanId. format!**

**Comment by MSNev** [comment]
@lmolkova Does Marks linked change address this request?
