### ISSUE TITLE
In SPA app insight reporting same time duration for all the pages/routes

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [microsoft/ApplicationInsights-JS#1139]
**Description/Screenshot**

**Steps to Reproduce**

 - OS/Browser: Chrome 79
 - SDK Version [e.g. 22]: 2.3.1
 - How you initialized the SDK:
I had created the HOC component as follows.
TelimetryService.js
`import {ApplicationInsights} from '@microsoft/applicationinsights-web';
import {ReactPlugin} from '@microsoft/applicationinsights-react-js';
let reactPlugin = null;
let appInsights = null;
/**
 * Create the App Insights Telemetry Service
 * @return {{reactPlugin: ReactPlugin, appInsights: Object, initialize: Function}} - Object
 */
const createTelemetryService = () => {
    /**
     * Initialize the Application Insights class
     * @param {string} instrumentationKey - Application Insights Instrumentation Key
     * @param {Object} browserHistory - client's browser history, supplied by the withRouter HOC
     * @return {void}
     */
    const initialize = (instrumentationKey, browserHistory) => {
        if (!browserHistory) {
            throw new Error('Could not initialize Telemetry Service');
        }
        if (!instrumentationKey) {
            throw new Error('Instrumentation key not provided in ./src/telemetryProvider.js')
        }
        reactPlugin = new ReactPlugin();
        appInsights = new ApplicationInsights({
            config: {
                instrumentationKey: instrumentationKey,
                maxBatchInterval: 0,
                disableFetchTracking: false,
                extensions: [reactPlugin],
                extensionConfig: {
                    [reactPlugin.identifier]: {
                        history: browserHistory
                    }
                },
                disableCorrelationHeaders: false,
                enableCorsCorrelation: true,
            }
        });
        appInsights.loadAppInsights();
        //setting to windows object
        window.appInsights = appInsights;
    };
    return {reactPlugin, appInsights, initialize};
};
export const ai = createTelemetryService();
export const getAppInsights = () => appInsights;`

TelemetryProvider.js
`import React, {Component, Fragment} from 'react';
import {withAITracking} from '@microsoft/applicationinsights-react-js';
import {ai} from './service/TelemetryService';
import {withRouter} from 'react-router-dom';
/**
 * This Component provides telemetry with Azure App Insights
 *
 * NOTE: the package '@microsoft/applicationinsights-react-js' has a HOC withAITracking that requires this to be a Class Component rather than a Functional Component
 */
class TelemetryProvider extends Component {
    state = {
        initialized: false
    };
    componentDidMount() {
        const {history} = this.props;
        const {initialized} = this.state;
        const AppInsightsInstrumentationKey = this.props.instrumentationKey; // PUT YOUR KEY HERE
        if (!Boolean(initialized) && Boolean(AppInsightsInstrumentationKey) && Boolean(history)) {
            ai.initialize(AppInsightsInstrumentationKey, history);
            this.setState({initialized: true});
        }
        this.props.after();
    }
    render() {
        const {children} = this.props;
        return (
            <Fragment>
                {children}
            </Fragment>
        );
    }
}
export default withRouter(withAITracking(ai.reactPlugin, TelemetryProvider));`

App.js
`
Class App extend React.Component{
...
...
render() {
      return (
        <HashRouter>
          <TelemetryProvider instrumentationKey={process.env.REACT_APP_TelemetryKey} after={() => { appInsights = getAppInsights() }}>
            <Switch>
              <Route path="/" name="Home" render={
                (props)=>(<Home />)
              }/> 
            </Switch>
          </TelemetryProvider>
        </HashRouter>
      );
  }
}`
**Expected behavior**
each route change should log correct page view time

**Additional context**
In azure portal i can see same duration for all the pages, which should be different as per the page load time

**Comment by markwolff** [comment]
This is expected behavior because the pageload time of a SPA route change is undefined so we reuse the initial pageload event's duration. The route changes immediately and the components can render whenever. If you would like to provide your own duration, you should disable the feature and use the existing pageview APIs to report your own duration once your components have painted.

```js
appInsights.context.telemetryTrace.traceID = Util.generateW3CId();
appInsights.trackPageView({ name: "/some_route", properties: { duration: 123 }});
```

**Comment by AbhaysinghBhosale** [comment]
Can u explain little bit about the solution u suggested. How i can disable the feature and add my own duration for the page load time.

**Comment by markwolff** [comment]
In config, set `enableAutoRouteTracking: false`. Then you can use the 2 lines above whenever you have a route change and supply a custom duration.

**Comment by AbhaysinghBhosale** [comment]
appInsights.context.telemetryTrace.traceID = Util.generateW3CId();
This line indicates that it will create new Operation Id each time it called. But what i want is to show entire page view in same operation id until use refresh the page.

**Comment by markwolff** [comment]
You can omit that part then. Everything will be correlated across the original pageview then. You may also want to adjust `maxAjaxCallsPerView`. By default we only track the first 500 ajax calls per pageview call, but since you aren't resetting the pageview counter anymore, it could impact you here

**Comment by bwcgn** [comment]
@markwolff this was working with the applicationinsights-js 1.x. Why did it change?

My current "old" setup
```EnerlyticsAzureAppInsights.downloadAndSetup({
    instrumentationKey: 'xxx,
    disableTelemetry: disableTelemetry,
    autoTrackPageVisitTime: true
  })
```

My new setup:
```
const AppInsights = new ApplicationInsights({
  config: {
    connectionString: 'InstrumentationKey=xxx',
    enableUnhandledPromiseRejectionTracking: true,
    enableAutoRouteTracking: true,
    disableFetchTracking: false,
    autoTrackPageVisitTime: true,
    overridePageViewDuration: false,
    enableAjaxPerfTracking: true,
    enableAjaxErrorStatusText: true,
    enableRequestHeaderTracking: true,
  },
});```

Is there any other possibility instead of measuring it manually? I find this pretty odd, because from my POV measuring the actual page load time is the most important metric. Due to our decoupled microfrontend approach its pretty impossible to get valid numbers in app insights. Any other tracking vendords provide this functionality out of the box.
