### ISSUE TITLE
[BUG]AI: TelemetryInitializerFailed message

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-JS#1141]
Hi All,
One of our application uses Application Insights and we observed following error being reported in the Application Insights,  can someone help me understand how we can fix it:

AI: TelemetryInitializerFailed message:"One of telemetry initializers failed, telemetry item will not be sent: TypeError" props:"{exception:[object Error]{ stack: 'TypeError: Cannot read property 'correlationKey' of undefined\n    at https://xyzzzzzzzz.com/quote/generating:47:42\n    at n._track (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:71156)\n    at n.track (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:69930)\n    at n.trackDependencyData (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:85929)\n    at n.onAjaxComplete (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:46357)\n    at XMLHttpRequest.<anonymous> (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:45057)', message: 'Cannot read property 'correlationKey' of undefined', name: 'TypeError'}"

Is this because of the AI Version used? seems like it is ai.0.js .. not sure what it means any help please?

Thanks,

**Comment by markwolff** [comment]
This error means that one of your telemetry initializers is crashing and so it is dropping the telemetry as a result. correlationKey is not something the Application Insights JS SDK knows about, so it makes me think this is a telemetry initializer added by your application itself. Do you have any custom telemetry initializers? Adding one looks like this.

`appInsights.context.addTelemetryInitializer(/* some function */)`

**Comment by ketaanhshah** [comment]
@markwolff Thank you for your response so this means the issue is in custom Initilializer where we simply setting the CLOUD ROLENAME and that even if we are using old library it is ok or you suggest we upgrade to the new AI library. Cause I think my team is using old library atleast from the error it seems its ai.0.js.1  and following is our Custom Initializer (nothing complex):


`import { Injectable } from '@angular/core';
import { AppInsights } from 'applicationinsights-js';

@Injectable()
export class AppInsightService {

    private appInsightConfig = (<any>window).environment && (<any>window).environment.appInsights || {};
    private config: Microsoft.ApplicationInsights.IConfig = {
        instrumentationKey: this.appInsightConfig.instrumentationKey,
    };;
    
    constructor() {       
        if (!AppInsights.config && this.appInsightConfig.instrumentationKey) {            
            AppInsights.downloadAndSetup(this.config);
            AppInsights.queue.push(() => {
                AppInsights.context.addTelemetryInitializer(this.getCustomTelemetryInitializer());
            });
        }
    }

    logPageView(name?: string, url?: string, properties?: any, measurements?: any, duration?: number) {
        AppInsights.trackPageView(name, url, properties, measurements, duration);
    }

    logEvent(name: string, properties?: any, measurements?: any) {
        AppInsights.trackEvent(name, properties, measurements);
    }

    logError(error: Error, properties?: any, measurements?: any) {
        AppInsights.trackException(error, null, properties, measurements);
    }

    private shouldSkipMetric(envelope :Microsoft.ApplicationInsights.IEnvelope) {
        return this.appInsightConfig.trimKeepAlive && envelope.name === Microsoft.ApplicationInsights.Telemetry.RemoteDependencyData.envelopeType && /session\/keepalive/.test(envelope.data.baseData.name);
    }

    private getCustomTelemetryInitializer() {
        return (envelope: Microsoft.ApplicationInsights.IEnvelope) => {
            if (this.shouldSkipMetric(envelope)) {
                return false;
            }
            envelope.tags['ai.device.roleName'] = this.appInsightConfig.roleName;
        };
    }
}`

**Comment by markwolff** [comment]
The error is indicating that it is occurring in your app at `quote/generating.js` on line 47

**Comment by ketaanhshah** [comment]
ty @markwolff I will try and check with my team what code we have in the Model/View as this is MVC node.js app and will report back the finding soon.

Thank you again for your help.
