### ISSUE TITLE
AI: TelemetryInitializerFailed message One of telemetry initializers failed

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-JS#1143]
Hi All,
One of our application uses Application Insights and we observed following error being reported in the Application Insights, can someone help me understand how we can fix it:

AI: TelemetryInitializerFailed message:"One of telemetry initializers failed, telemetry item will not be sent: TypeError" props:"{exception:[object Error]{ stack: 'TypeError: Cannot read property 'correlationKey' of undefined\n at https://xyzzzzzzzz.com/quote/generating:47:42\n at n._track (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:71156)\n at n.track (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:69930)\n at n.trackDependencyData (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:85929)\n at n.onAjaxComplete (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:46357)\n at XMLHttpRequest. (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:45057)', message: 'Cannot read property 'correlationKey' of undefined', name: 'TypeError'}"

Is this because of the AI Version used? seems like it is ai.0.js .. not sure what it means any help please?

Thanks,

**Comment by markwolff** [comment]
Duplicate of #1141
