### ISSUE TITLE
Bing Ads.js injected with AI scripts

### ISSUE THREAD

**Issue by stemixreal** [microsoft/ApplicationInsights-JS#1147]
Hi, I recently enabled application insights on an app service app from the Azure Portal. As expected scripts are added to enable AI to do its thing.

When testing the website, I found pages have the bing_ad.js script injected, not the home page but the next level. I've read some documentation (https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript) where I can't find any reference to bing ads and I've looked at the source here where I've found some references to bing.com in tests but no luck finding out how/where this script is injected.

This script is what I'm trying to find information on.

![image](https://user-images.githubusercontent.com/57687696/71311761-8f4a9200-241a-11ea-9a56-9761f7f6419b.png)

Specifically, am I able to exclude it? 

thanks in advance
Merry Christmas!

**Comment by stemixreal** [comment]
Well it appears that the name Bing Ads is the name given to the resource by the test tool I am using, google pagespeed insights. I don't know enough about the inner working of AI at the moment to be sure but it looks like it is actually this script "ai.0.js" that the page speed tool is identifying as bing ad.

The reason I'm interested is that I don;t have tracking of any kind on our sites, there's no marketing analytics or ads. I'd like to use AI but would like confirm there is no interaction with ad services, it doesn't look like there is

![image](https://user-images.githubusercontent.com/57687696/71325157-b10e4c80-24e0-11ea-8ade-3dfa715c909e.png)

Just to check, am I asking this in the right place? Any help appreciated, 
Many thanks

**Comment by MSNev** [comment]
You are correct, ai.0.js is the (version 1 - now called legacy) of the Application Insights and it has NO marketing or ads.

**Comment by stemixreal** [comment]
Thanks Nev.
