### ISSUE TITLE
Set a long `max-age` for `immutable` resources

### ISSUE THREAD

**Issue by Malvoz** [microsoft/ApplicationInsights-JS#1148]
(I'm personally not a user of the Application Insights SDK, but as I stumbled on this I thought I'd file an issue, I'm hopefully in the right place.)

Considering not all browsers [support](https://caniuse.com/#feat=mdn-http_headers_cache-control_immutable) the [`immutable`](https://tools.ietf.org/html/rfc8246) directive, these resources should typically include a long `max-age`, conventionally: `max-age=31536000`.

https://az416426.vo.msecnd.net/scripts/a/ai.0.js returns:

```http
Cache-Control: public, max-age=86400, immutable
```
and: 

https://github.com/microsoft/ApplicationInsights-JS/blob/d0184962d439fcd448f18cfa8400e70a4cf57f5e/AISKU/scripts/uploadFilesToAzureStorage.ps1#L2

**Comment by MSNev** [comment]
Hi Malvoz,

These short times are actually required as ai.0.js will return the current version of the script. With these set to a day (86400), this means that *if* we happen to publish a breaking change then browsers will only keep this cached for a max of 24 hours. If we set this to 1 year (365 days) as suggested that we would break ever user for an entire year AND we could also never publish any update within the same sliding window (as it's relative to when it's uploaded and/or (depending on browsers / proxies that are caching it) first fetched by an end user.

While i agree that 1 day is not ideal (as we don't publish that often) it is a trade off and to correctly handle this we would need another trade off, by including an additional fetch.

Something like
-> Request to ai.0.js => causes a 302 or client side redirect script to fetch the true versioned (with a hash)
-> This hashed file can then have the 1 year (or more policy) as it should never change (based on the hashed content).

The real downside of this is for first time users / uncached requests, there would now be 2 requests.
This requires some infrastructure changes which will need to be addressed as part of a future work item and some analysis on the impacts.

For now I'm going to close this issue as I don't believe that it will be addressed in the near term -- but I will be working to have this addressed in the longer term -- just not for the legacy version (ai.0.js).
