### ISSUE TITLE
[BUG] Auto AJAX Dependency tracking not working if XHR request made on Web Worker 

### ISSUE THREAD

**Issue by aniket7824** [microsoft/ApplicationInsights-JS#1149]
**Description/Screenshot**
In my **angular** app whenever a XHR call is made using **web worker** (not in main thread), **AppInsights is not capturing it a AJAX dependency**.
**Steps to Reproduce**

 - OS/Browser: Windows 10/Chrome 79
 - SDK Version [e.g. 22]: @microsoft/applicationinsights-web (v2.3.1) 
 - How you initialized the SDK: npm

**Expected behavior**
It should send telemetry about the AJAX call happening in web worker (not in main thread)

**Comment by markwolff** [comment]
I believe the SDK would need to also be initialized within the web worker so that we can patch the webworker's instance of XHR. Is this the case?

**Comment by aniket7824** [comment]
I have tried to do that also. But when I am calling loadAppInsights()
method after providing proper config , I am getting the following error.

_TelemetryContext.js:29 Uncaught TypeError: Cannot read property
'automaticSession' of undefined_ TelemetryContext.js:29 Uncaught TypeError:
Cannot read property 'automaticSession' of undefined

I think this is due to unavailability of the window object in the worker
thread.

**Comment by markwolff** [comment]
@aniket7824 I think that error would be a bug here, since it is currently relying on a window being present to initialize.
https://github.com/Microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-properties-js/src/TelemetryContext.ts#L46

 As a workaround, before you call loadAppInsights, you could try providing your own session?
```js
appInsights.context.session = { id: "foo" };
```

**Comment by aniket7824** [comment]
> @aniket7824 I think that error would be a bug here, since it is currently relying on a window being present to initialize.
> https://github.com/Microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-properties-js/src/TelemetryContext.ts#L46
> 
> As a workaround, before you call loadAppInsights, you could try providing your own session?
> 
> ```js
> appInsights.context.session = { id: "foo" };
> ```

I have tried to do that. But that also doesn't work. After going via the error stack I found that a new TelemetryContext has initialized before from this code [https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts#L51](https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts#L51)
Hence providing session.id for appInsight doesn't help.

Attaching the error trace for more your understanding.

`TelemetryContext.js:29 Uncaught TypeError: Cannot read property 'automaticSession' of undefined
    at TelemetryContext../node_modules/@microsoft/applicationinsights-properties-js/dist-esm/TelemetryContext.js.TelemetryContext.applySessionContext (TelemetryContext.js:29)
    at PropertiesPlugin../node_modules/@microsoft/applicationinsights-properties-js/dist-esm/PropertiesPlugin.js.PropertiesPlugin._processTelemetryInternal (PropertiesPlugin.js:95)
    at PropertiesPlugin../node_modules/@microsoft/applicationinsights-properties-js/dist-esm/PropertiesPlugin.js.PropertiesPlugin.processTelemetry (PropertiesPlugin.js:63)
    at AppInsightsCore../node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/BaseCore.js.BaseCore.track (BaseCore.js:149)
    at AppInsightsCore../node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/AppInsightsCore.js.AppInsightsCore.track (AppInsightsCore.js:30)
    at Array.<anonymous> (AppInsightsCore.js:71)
    at Function../node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/CoreUtils.js.CoreUtils.arrForEach (CoreUtils.js:65)
    at AppInsightsCore.js:63`

**Comment by xiao-lix** [comment]
@aniket7824 I reproduced the error you met and added the null check in #1164 . And I think @markwolff is correct that SDK needs to be initialized also in web worker then xhr got patched. Workaround before next release is to add `appInsights.context.session = { id: "foo" };`, make sure you add it after `loadAppInsights()` where context is created. 

The code here: 
https://github.com/microsoft/ApplicationInsights-JS/blob/7a800f19805716b137670299183cd4adbb8348ac/extensions/applicationinsights-properties-js/src/TelemetryContext.ts#L32

won't create a session because of the window null check.

**Comment by aniket7824** [comment]
> @aniket7824 I reproduced the error you met and added the null check in #1164 . And I think @markwolff is correct that SDK needs to be initialized also in web worker then xhr got patched. Workaround before next release is to add `appInsights.context.session = { id: "foo" };`, make sure you add it after `loadAppInsights()` where context is created.
> 
> The code here:
> https://github.com/microsoft/ApplicationInsights-JS/blob/7a800f19805716b137670299183cd4adbb8348ac/extensions/applicationinsights-properties-js/src/TelemetryContext.ts#L32
> 
> won't create a session because of the window null check.

@xiao-lix That check was needed but will it solve the issue? 
Whenever it will try to execute applySessionContext() method, it will break at        
` const sessionContext = this.session || this.sessionManager.automaticSession;`
this.session and this.sessionManager both will be undefined i think. 

Another observation here.  You have mentioned that 
> won't create a session because of the window null check.
But as a user my expectation will be to pass same session information which is available in main thread to the worker so that there are not 2 parallel session for the same user and same application. I think there should be some mechanism to get the session info from main thread appInsights and to pass on the same info during initialization of the appInsights in worker.

**Comment by MSNev** [comment]
The main issue is that web workers run in a different context to that of the main window and don't have access to the main window or document. And the session manager uses a cookie to handle the current session id (which can change if expired).

I'm investigating the possibility on who we can share / pass this type of information between the an instrumented worker and an instrumented page so we could possibly use postMessage / onmessage event handling to try and share this data... However, this may get problematic (we don't want to affect other user message handling) so I don't expect that we will have a complete solution (if possible) for a few months.

**Comment by MSNev** [comment]
But we should have PR's out to fix/stop the exceptions from occurring, i.e. handle the not-initialized cases.
