### ISSUE TITLE
TrackEvent on onClick does not send the telemetry

### ISSUE THREAD

**Issue by MrDesjardins** [Microsoft/ApplicationInsights-JS#115]
Hello,

I have a tracking event on click of a simple link (<a>) that is added by JQuery on onClick event.
$('#xyz').click(function () {
        appInsights.trackEvent("NameHere",
            { LinkDestination: "Go/Here", TypeButton: "GreenButton" }
        );
    });

This does not write the event in AppInsight. However, if I copy-paste it in Chrome's console. I can see the event in Azure portal. I suspect that the click of the link is so fast to go to the target page that the trackEvent does not have the time to send the event to AppInsight server. Is that a bug or a misuse of trackEvent and link?

**Comment by MaxShehovtsov** [comment]
If you navigate away too soon after calling track() then AI endeed might not have enough time to send event. We subscribe to window.onbeforeunload ([see code](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/Initialization.ts#L112)) to still try sending all outstanding events, but it's not guaranteed to always work.

Try calling appInsights.flush() right after the trackEvent in the onclick handler.
Alternatively you can set maxBatchSizeInBytes to 0 (in the snippet configuration) which will force flush for all your telemetry:

`<script>`
`appInsights=...})`
`({`
`    instrumentationKey: "000...000",`
`    maxBatchSizeInBytes: 0`
` });`
`</script>`

**Comment by MrDesjardins** [comment]
It works. The documentation should give more information about Javascript capabilities of the API. Didn't know we could Flush, thought it was just for C#. Nice tips. Thank you.
