### ISSUE TITLE
Support telemetry filtering

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/ApplicationInsights-JS#116]
I think it would be useful to have filtering/masking capability (like the .NET TelemetryProcessor).  I would use this to filter out specific AJAX dependency calls (by hostname) with the built-in AJAX dependency tracking.

**Comment by MaxShehovtsov** [comment]
You can do it already! Just return false from your telemetry initializer [see short description in api reference](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#addtelemetryinitializer)

**Comment by gregjhogan** [comment]
Thanks, that is exactly what I was looking for. Standardizing on telemetry initializer features across languages would have helped me.
