### ISSUE TITLE
Automatically collect logs for OPTIONS calls

### ISSUE THREAD

**Issue by thoo1** [microsoft/ApplicationInsights-JS#1160]
**Is your feature request related to a problem? Please describe.**
Say I do a cross origin call A, as part of CORS, the browser will do some OPTIONS call B as a pre-flight

Say that call B fails, I get a resultCode == 0 in AppInsights for call A (as call A is not performed)

I also do not see call B in AppInsights logs

**Describe the solution you'd like**
I don't need a solution for resultCode to not equal 0 (this part might be application specific)

But what I'm really looking for is if there's an option to automatically log these OPTIONS calls? If not, that feature would be great.

**Describe alternatives you've considered**
I might use this method: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests to manually add logs for OPTIONS calls

**Comment by thoo1** [comment]
I just realized this is probably impossible since CORS is intentionally made opaque by the browser to the client code, feel free to close if y'all think the same

**Comment by xiao-lix** [comment]
@thoo1 hi you are right, we can't intercept OPTIONS preflight request. There're ways to work around this, please check this post: https://stackoverflow.com/questions/21557423/is-it-possible-to-intercept-the-response-to-an-http-options-preflight-in-angular
