### ISSUE TITLE
setContext not been implemented

### ISSUE THREAD

**Issue by chattersley** [microsoft/ApplicationInsights-JS#1165]
In the old version of the library you could set additional context that would augment each insight telemetry. This appears to have not been implemented in the new version of the library.

[https://github.com/Azure/react-appinsights/blob/master/README.md#set-application-context](https://github.com/Azure/react-appinsights/blob/master/README.md#set-application-context)

Is there any plans to bring this back please? We have built a multi-tenancy system so losing the context, and not being able to add to the withAITracking context is a setback.

**Comment by xiao-lix** [comment]
@chattersley Hi, I think what you need is to add Telemetry initializers` that are used to modify the contents of collected telemetry before being sent from the user's browser. Instructions here: https://github.com/microsoft/ApplicationInsights-JS#telemetry-initializers Can you try this?

**Comment by chattersley** [comment]
Brill, thank you! Works a treat. Appreciate you getting back so quickly.

Example for others.
`
    const telemetryInitializer: (item: ITelemetryItem) => boolean | void = envelope => {
      if (envelope !== undefined) {
        (envelope.data as any).userId = state.user ? state.user.userId : undefined;
        (envelope.data as any).organisationId = state.user.organisations[0].organisationId;
      } else {
        throw new Error("App insights not initialised properly");
      }
    };`

Working in typescript so had to cast envelope.data to any, the interface ICustomProperties is an empty declaration. Perhaps the interface needs to be `[key: string]: any;` in the types declaration?
