### ISSUE TITLE
Syntax error tools/rollup-es3/src/es3/Es3Tokens.ts

### ISSUE THREAD

**Issue by jimnet2005** [microsoft/ApplicationInsights-JS#1179]
This line is generating a syntax error. Note this is only a misspelling of "hasOwnProperty" (missing letter t) 

"if (obj.hasOwnPropery(attr)) { cpy[attr] = obj[attr]; } " +

**Comment by MSNev** [comment]
This also means version 2.4.2 AISKU is broken and I'll fix and bump to version 2.4.3

**Comment by MSNev** [comment]
Fixed published to NPM as v 2.4.3

**Comment by MSNev** [comment]
Closing as this issue was introduced in 2.4.2 which was only published as an NPM packages and we now have published the updates that contain the fixes.
