### ISSUE TITLE
[BUG] Snippet overwrites existing Microsoft JS namespace. 

### ISSUE THREAD

**Issue by martinlingstuyl** [microsoft/ApplicationInsights-JS#1184]
**Description/Screenshot**
When using the Application Insights snippet on SharePoint (for example), things on SharePoint start breaking. This is due to the Application Insights JavaScript file overwriting the Global Microsoft namespace.

**Steps to Reproduce**
1) Create a Classic SharePoint site with a Content Search Webpart
2) Add the Snippet from https://github.com/microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup using a JavaScript block or JavaScript Link Custom Action
3) Refresh the page. You'll get the following kind of errors in the Console:
`Uncaught TypeError: Cannot read property 'Client' of undefined`

 - OS/Browser: Chrome, Edge
 - SDK Version [e.g. 22]: Web, 2.4.3
 - How you initialized the SDK: Using the Snippet

**Expected behavior**
SharePoint keeps working, pageviews are logged

**Workaround**
if we add the following two lines above the snippet, it starts working again:
`window.Microsoft = window.Microsoft || {};`
`window.Microsoft.ApplicationInsights = {};`

**Comment by stephenegriffin** [comment]
This bug is causing massive outages in Office add-ins that use AI for telemetry. I had to patch MHA to use 2.3.1 to end a two day outage:
https://github.com/stephenegriffin/MHA/commit/04a03fbf725ce6b07090d235ec174a97f02fe8d4
