### ISSUE TITLE
Device Info not getting captured in UWP App

### ISSUE THREAD

**Issue by rahulseth01** [Microsoft/ApplicationInsights-JS#119]
In our UWP App, AppInsight does not auto captures "Device Information". Below are parameters that should get auto populated:
1. ContextDeviceOemName (e.g Hewlett-Packard, Dell Inc.)
2. ContextDeviceDeviceModel (e.g HP Z230 SFF Workstation, XPS 12 9Q23)
3. ContextDeviceScreenResolutionValue
4. ContextDeviceType

I know, we will be able to set this manually using below code, but getting these values in UWP seems challenging.
-------------
            appInsights.context.device.oemName = "YOUR OEM NAME";
            appInsights.context.device.model = "YOUR MODEL";
            appInsights.context.device.resolution= "YOUR MODEL";
            appInsights.context.device.type = "YOUR TYPE";
-----------

**Comment by SergeyKanzhelev** [comment]
@JoshuaWeber - what would be your recommendations here?

**Comment by MaxShehovtsov** [comment]
JSSDK can't auto-populate it in generic case as primary scenario is browser monitoring where this data is collected differently. Closing this issue.
