### ISSUE TITLE
[BUG] ICustomProperties does not support setting values

### ISSUE THREAD

**Issue by onionhammer** [microsoft/ApplicationInsights-JS#1191]
According to the [docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#adding-the-javascript-sdk) we should be able to assign custom values like this:

```js
var telemetryInitializer = (envelope) => {
  envelope.data.someField = 'This item passed through my telemetry initializer';
};
```

However in the typescript definition, 'envelope.data' is an empty interface, which does not allow any extension.

![image](https://user-images.githubusercontent.com/969938/74751033-48b6bf80-5232-11ea-9355-99f4501e487f.png)

**Comment by MSNev** [comment]
Hi,
It looks from the error, that you don't have an IEnvelope which defines the "data" element as any...

A TelemetryInitializer is passed an object that conforms to the IEnvelope interface...
Can you provide more of the code as the following works for me

var telemetryInitializer = (envelope) => {
                    envelope.data.someField = 'This item passed through my telemetry initializer';
                  };
                  appInsights.addTelemetryInitializer(telemetryInitializer);
                  appInsights.trackTrace({message: 'This message will use a telemetry initializer'});

Cheers

Nev

**Comment by MSNev** [comment]
I think I have a possible solution for this, but as the issue is really just with the type safety (and perhaps strict) a workaround you could apply is to create a local variable for data and "cast" (in typescript terms) to any or some other type you want to enforce.

**Comment by MSNev** [comment]
Fixed deployed as NPM and next CDN channels
