### ISSUE TITLE
[Feature | Request] Angular Plugin

### ISSUE THREAD

**Issue by iameduardod** [microsoft/ApplicationInsights-JS#1196]
What's the roadmap in providing an Angular plugin similar to the one for React?

**Comment by StefanSchoof** [comment]
I today where searching on this topic and was surprised that there is no official documentation/example on this topic. The [third party plugin](https://github.com/TrilonIO/angular-application-insights) is still be still on v1.

**Comment by hhermas** [comment]
I'm wondering about this as well. There is an Angular Plugin under this project, but it is not available on NPM yet.
https://github.com/microsoft/ApplicationInsights-JS/tree/5f725827f1117db4234fec2bfe71c175bb425bb9/extensions/applicationinsights-angular-js

**Comment by MSNev** [comment]
We have renamed the applicationinsights-angular-js plugin to applicationinsights-angularplugin-js and published the initial version as v2.5.8 as https://www.npmjs.com/package/@microsoft/applicationinsights-angularplugin-js

**Comment by MSNev** [comment]
Will close this issue tomorrow once we have fully deployed v2.5.8 (to the CDN -- doesn't affect this plugin as it's only released via NPM)

**Comment by MSNev** [comment]
v2.5.8 is now fully deployed
