### ISSUE TITLE
[BUG] - AI.js 1.0.21 (legacy) *.map files are not on CDN

### ISSUE THREAD

**Issue by jkernMINITAB** [microsoft/ApplicationInsights-JS#1197]
**Description/Screenshot**
The bottom of ai.0.js specifies the URL of the source-mapping file to help assist with debugging: ai.0.js.map. This source-mapping file contains the relative file paths and locations of all uncompiled TypeScript sources, and Edge is trying to load them all.

Since these TypeScript files are not actually stored on the CDN, Edge is reporting 404s.

![image](https://user-images.githubusercontent.com/61419659/75159034-5a421080-56e5-11ea-8ce4-434534736f46.png)

**Steps to Reproduce**

 - OS/Browser: Windows 10 + Microsoft Edge, pre-Chronium
 - SDK Version [e.g. 22]: 1.0.21

**Expected behavior**
The 404 errors would disappear once the missing files are uploaded onto the CDN.

**Additional context**
See also: https://stackoverflow.com/questions/35142485/why-is-bootstrap-trying-to-load-less-files-in-edge

CDN JS file:
https://az416426.vo.msecnd.net/scripts/a/ai.0.js

CDN MAP file:
https://az416426.vo.msecnd.net/scripts/a/ai.0.js.map

**Comment by MSNev** [comment]
I investigated if there was any simple work around which would scale and resolve this issue, however, there isn't. And as the legacy version ai.0.js is no longer receiving active development, this is unlikely to be fixed.
