### ISSUE TITLE
Can withAITracking be used on react-native app?

### ISSUE THREAD

**Issue by ranierimazili** [microsoft/ApplicationInsights-JS#1198]
I have an application with web and mobile version (react and react-native).
Using the demo (https://github.com/Azure-Samples/application-insights-react-demo) I could send all the events without code each one by hand using the TelemetryProvider and it uses this withAITracking.
With it I can see the pageViews and events (api calls) on Azure Application Insights.

Is there something similar for react-native? Is there any example available? Or do I need to code each pageView and events one by one on react-native app?

P.S: I've tried to use the same example on react-native app but I receive the message TypeError: Prototype value can only be object or null
The print screen is attached.

I really appreciate any help.
![Simulator Screen Shot - iPhone 11 - 2020-02-24 at 14 59 33](https://user-images.githubusercontent.com/15436207/75249589-49f96680-57b5-11ea-8e67-c96946c1a7b4.png)

**Comment by xiao-lix** [comment]
@ranierimazili WithAITracking does not work on React Native for now, but all APIs are available to use. And yes you'll need to manually call the APIs you need. Currently, ReactNative plugin only collects device info, and it relies on `react-native-device-info`. Please find the doc [here](https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-react-native#microsoft-application-insights-javascript-sdk---react-native-plugin).
