### ISSUE TITLE
how to import ai.0.21.5-build00175.js file

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/ApplicationInsights-JS#120]
I have download the package from nuget. It creates a file called ai.0.21.5-build00175.js.  I couldnt find any sample html code about how to include this on my html code. All of them show examples for using the cdn. How do I use my local version?

**Comment by MaxShehovtsov** [comment]
we expose 'URL' config parameter, so it should look like this in your js snippet:

`
<script>
...
})({
    instrumentationKey: <your key>,
    url: 'path to your local .js'
})
...
</script>

**Comment by ahmettaha** [comment]
Thank you.

One more question. I would like to set the user id. However, since the javascript is loaded async, the browser executes the user setting function early, and causing a not defined error. How can I set the user id, after the javascript it loaded

**Comment by MaxShehovtsov** [comment]
You can set user id by calling [setAuthenticatedUserContext](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#setauthenticatedusercontext). This is available in snippet before AI is fully loaded.
 Note that it's different from our internal user id which is not supposed to be set - one disadvantage of using it is that it's not updated in cookies and therefore not sent to server SDK (if you use it on server side) - unless you update cookies manually. With setAuthenticatedUserContext there's no such problem.

**Comment by ahmettaha** [comment]
Hello,

I'm getting the following error.

   setAuthenticatedUserContext is not defined

Code is like below:


    <script type="text/javascript">
        var appInsights = window.appInsights || function (config) {
            function s(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, r = document, f = window, e = "script", o = r.createElement(e), i, u; for (o.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", r.getElementsByTagName(e)[0].parentNode.appendChild(o), t.cookie = r.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) s("track" + i.pop()); return config.disableExceptionTracking || (i = "onerror", s("_" + i), u = f[i], f[i] = function (config, r, f, e, o) { var s = u && u(config, r, f, e, o); return s !== !0 && t["_" + i](config, r, f, e, o), s }), t
        }({
            instrumentationKey: "XXXXX",
            url: '/scripts/ai.0.21.5-build00175.min.js'
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>

        <script>
            setAuthenticatedUserContext('45c072bd-eef3-46bb-8c14-5b362f04098a');
        </script>

**Comment by MaxShehovtsov** [comment]
You have an old snippet, you have to take a new one from AI portal.

**Comment by ahmettaha** [comment]
thank you
