### ISSUE TITLE
Add ability to set the session cookie's domain

### ISSUE THREAD

**Issue by greg84** [Microsoft/ApplicationInsights-JS#121]
We have a site that spans two sub-domains. We can't join user session specific telemetry from the two domains unless the `ai_session` cookie can be set for the root domain.

It would be great if we could set something like `config.sessionCookieDomain` to solve the problem.

**Comment by SergeyKanzhelev** [comment]
Dup for this: https://github.com/Microsoft/ApplicationInsights-JS/issues/64
