### ISSUE TITLE
[BUG] Typescript error when using @microsoft/applicationinsights-web 2.5.0 and "noImplicitAny"/"strict" option

### ISSUE THREAD

**Issue by nicolashenry** [microsoft/ApplicationInsights-JS#1210]
**Description/Screenshot**
There is a Typescript  error when using `@microsoft/applicationinsights-web` version `2.5.0` of  and "noImplicitAny"/"strict" option configured in tsconfig.json.
![image](https://user-images.githubusercontent.com/139160/75984979-b712a780-5eeb-11ea-884a-534dac633f71.png)

**Steps to Reproduce**
Use `@microsoft/applicationinsights-web` with version `2.5.0` and add "noImplicitAny"/"strict" option to "true" in tsconfig.json.

 - OS/Browser: Windows 7
 - SDK Version: 2.5.0
 - How you initialized the SDK: npm install @microsoft/applicationinsights-web

**Expected behavior**
No error

**Comment by MSNev** [comment]
Investigating to see if we can enable this...

**Comment by MSNev** [comment]
I'm adding noImplicitAny to the standard build config and fixing the breaks, however, adding strict is a very large issue, so not doing that now. Based on the error you are getting, I believe that this will unblock you once we republish with the fix

**Comment by MSNev** [comment]
We published version 2.5.1 to npm last night, which should address this issue. Once we complete the rollout to the CDN, I'll close this issue (unless we here that it's still an issue)

**Comment by nicolashenry** [comment]
It seems to be fixed :+1:

**Comment by MSNev** [comment]
Version 2.5.2 is now fully deployed to the CDN, closing as this should address this issue.
