### ISSUE TITLE
How to customize request's name while tracking ajax calls to include query params?

### ISSUE THREAD

**Issue by 200sOnly** [microsoft/ApplicationInsights-JS#1220]
**Is your feature request related to a problem? Please describe.**
applicationinsights-js automatically tracks ajax calls which we can view on requests table. But I couldn't find any documentation to be able to customize the network call's name to add query params. Currently, the URL, operation_name, and name consist of url data in it and it's difficult to categorize.

**Describe the solution you'd like**
Current State:
name: GET /Api/v1/customer/C-01075934

I want to customize the name as
name: GET /Api/v1/customer/{customer-id}

**Describe alternatives you've considered**
Right now I am doing it using kusto queries and it's becoming complex and complex

**Additional context**

![image](https://user-images.githubusercontent.com/53316702/76533336-453be000-644e-11ea-9850-1869cde329b0.png)

**Comment by MSNev** [comment]
Sorry for the delay response.

As part of ensuring that we don't include PII data in the request (not to mention the noise it can created during correlation) we only include the path on the name.

If I'm following your ask correctly, have you considered or tried adding a telemetry initializer? You should then be able to process the request (path etc) and set custom properties for the request that you should then be able to use within the Kusto query.

**Comment by MSNev** [comment]
Alternate though after re-reading this issue
My previous comment was around you wanting to "add" querystring paramters as part of the ajax request (your URL) and having those stored and sent to the server -- which is not possible.

However, based on the URL "GET /Api/v1/customer/C-01075934", if all you want to do is change this to "GET /Api/v1/customer/{customer-id}" you should be able to achieve this via adding your own telemetry initializer to change the values

See: https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#javascript-telemetry-initializers
Where you can check the value of the "envelope.name" should be "Microsoft.ApplicationInsights.{0}.RemoteDependency" with the {0} replaced with your iKey.
