### ISSUE TITLE
npm @microsoft/applicationinsights-web: license information missing in package.json

### ISSUE THREAD

**Issue by schlemmge** [microsoft/ApplicationInsights-JS#1221]
Just a minor issue leading to a warning in our context, but nagging for us. It would be great if you took a look at it!

We are using license-webpack-plugin to aggregate and check licenses of the npm packages.
Because of missing license information (thus also unspecified on the npm web site https://www.npmjs.com/package/@microsoft/applicationinsights-web, reading "None") we receive a build warning:

`license-webpack-plugin: could not find any license type for @microsoft/applicationinsights-web in its package.json
`

We know that there are some (non-working) workarounds for this in license-webpack-plugin, but it would be wise to specify the license correctly in the right place (presumably).

Thanks!

**Comment by MSNev** [comment]
Fixed deployed as NPM and next CDN channels

**Comment by MSNev** [comment]
Closing as this was an NPM issue only
