### ISSUE TITLE
[BUG]Disable remote dependencies (AJAX calls ) in applicationinsights-web

### ISSUE THREAD

**Issue by pk091990** [microsoft/ApplicationInsights-JS#1223]
I have spfx library component( v 1.9.1) with spfx 1.9.1 using AppInsights (applicationinsights-web  v ^2.5.2). I need to disable remote dependencies i.e.AJAX calls in AppInsights logging as its consuming lot of data and my client wants to disable it.
As given in the [link](https://github.com/microsoft/applicationinsights-js), configure below 2 properties (disableAjaxTracking and maxAjaxCallsPerView)to disable it. It seems that the no of calls has been decreased but its still coming up.
Config:
![image](https://user-images.githubusercontent.com/46436213/77149979-d1867c80-6ab8-11ea-8ea2-ee5e6136c485.png)

Dependency logs:

![image](https://user-images.githubusercontent.com/46436213/77150358-b700d300-6ab9-11ea-858c-e3dbe2d77eef.png)
Please let me know if is there any other property which I need to add to disable it?

**Comment by markwolff** [comment]
`disableAjaxTracking` should be the only setting you need to set. How are you setting up the SDK with this config object?

**Comment by MSNev** [comment]
@pk091990 Do you have an answer for the above question?

The disableAjaxTracking config setting MUST be past into the initialize() call, as changing the value after calling initialize() is not supported.

And based on your screenshot, you seem to be referencing the config after initialization().

If we don't get a response by the end of the week  (April, 4th), I'll close this issue.

**Comment by pk091990** [comment]
Yes there was some issue with the initialization part only. Its working for me now.
You can close the issue now, Thanks!
