### ISSUE TITLE
[BUG] Custom exception type

### ISSUE THREAD

**Issue by leaderhun** [microsoft/ApplicationInsights-JS#1228]
I'm trying to send some custom exceptions from client side, but somehow on the azure portal, the exception type and the message of the exception are always the same.

 - OS/Browser: Windows 10 / Chrome
 - SDK Version [e.g. 22]: "@microsoft/applicationinsights-web": "2.5.1",

![code](https://user-images.githubusercontent.com/32794194/77826007-1fc8fa80-710d-11ea-98f2-8bef5d105221.PNG)

As you can see, i'm just initializing the SDK, than right after that i'm trying to send a custom exception.
The data sent by the SDK:
![network](https://user-images.githubusercontent.com/32794194/77826131-ec3aa000-710d-11ea-91c2-bb978409189c.PNG)

As you can see the typeName is set correctly, however the result i see on the azure portal is incorrect:
![result](https://user-images.githubusercontent.com/32794194/77826177-2146f280-710e-11ea-830c-39b9de757890.PNG)

Could you please help me what am I doing wrong, or let me know if this is a bug. Thank you in advance.

**Comment by markwolff** [comment]
Does `typeName` also appear in the telemetry when you view it in Analytics view? (e.g. run a query)

**Comment by leaderhun** [comment]
`  
"2020-03-26T15:59:14.998Z",
  "some message at loadAppInsights",
  "",
  "some message",
  "",
  "webpack-internal:///./src/index.js",
  "loadAppInsights",
  "some message",
  "some message",
  "webpack-internal:///./src/index.js",
  "loadAppInsights",
  "",
  "",
  "",
  "",
  null,
  "[{"parsedStack":[{"method":"loadAppInsights","level":0,"fileName":"webpack-internal:///./src/index.js","assembly":"at loadAppInsights (webpack-internal:///./src/index.js:266:15)","line":266},{"method":"eval","level":1,"fileName":"webpack-internal:///./src/index.js","assembly":"at eval (webpa....}]",
  "exception",
  null,
  null,
  "location",
  "uid",
  "sid",
  "",
  "50t+j",
  "BxbiQ",
  "",
  "",
  "",
  "Browser",
  "Other",
  "Windows 10",
  "0.0.0.0",
  "Budapest",
  "Budapest",
  "Hungary",
  "Chrome 80.0",
  "",
  "",
  "appId",
  "appName",
  "ikey",
  "javascript:2.5.1",
  "bf7f5db0-6f7a-11ea-971b-b75606529012",
  1
`

This is the result from the query. The exception type is already missing here.

**Comment by MSNev** [comment]
FYI - We are checking with the backend team as this looks like a mapping issue from the request the SDK sends to where it lands in the portal.

**Comment by leaderhun** [comment]
Hi @MSNev, is there any progress?

**Comment by MSNev** [comment]
We are still trying to track down which backend service is dropping, replacing or using a different name for this value. So no eta yet.

**Comment by MSNev** [comment]
This does appear to be a backend ingestion issue, further investigation and scheduling is required. I don't have any possible timeframe on a fix for this yet. Will keep this issue open and will update as further details are known.

**Comment by MSNev** [comment]
This is a backend ingestion issue which is overwriting the passed in typeName. Work to fix this is being scheduled -- no specific timeframe for the fix or backend deployment of the fix at this time.

**Comment by leaderhun** [comment]
Hi @MSNev, is there any progress with this issue?

**Comment by MSNev** [comment]
@leaderhun No not yet the work is still getting scheduled around other items

**Comment by MSNev** [comment]
FYI, the backend is going throw a modernization process so the timeline for this is still a little way out 👎

**Comment by MSNev** [comment]
As this is taken a lot longer than expected, as part of adding additional support to handle more error types, including throwing strings and some older browsers. I'm going to add the ExceptionType to the beginning of the message (if it is not already present).

So in this case the "message" will become ```MyError: some message```.

The exceptions to this will be that it won't prepend the Type if
- It's ready present (anywhere - not just the beginning) within the message
- The Error type is either "String"; "Object" or "Error"
-

**Comment by MSNev** [comment]
I've also added the typeName as a CustomProperty -- which is getting populated in the portal.

**Comment by MSNev** [comment]
FYI - Backend change is almost ready to be committed, we will then just need to wait for deployment.

**Comment by leaderhun** [comment]
Hello, actually we ended up accepting that this is working differently, so we started using some custom properties for our types, and aggregate the data on azure portal by these types if required.
Thank you for keeping this thread up to date though!
