### ISSUE TITLE
[Question] How to get `operation_Id` and `operation_ParentId` from an Angular front-end?

### ISSUE THREAD

**Issue by ZhimaoLin** [microsoft/ApplicationInsights-JS#1231]
Hi, 

I want to get the `operation_Id` and `operation_ParentId` when a request fails so that I can search for the failed operation in Application Insights.

Ideally, I would like to get those IDs after a request is sent by [Angular HttpClient](https://angular.io/guide/http). I know the `traceparent` in the request header contains those IDs, but there seems no way to get the request from Angular HttpClient. I am wondering if `@microsoft/applicationinsights-web` provides any functions to get those IDs.

Thanks.

**Comment by markwolff** [comment]
You can grab them from the outgoing telemetry through telemetry initializers. You can grab them from  HTTP requests through `traceparent` or `request-id` header

**Comment by ZhimaoLin** [comment]
Hi @markwolff. Thank you for your reply.

Currently, we are having problems with getting the request object from [Angular HttpClient](https://angular.io/guide/http). However, we managed to get `operation_Id` from `applicationInsights.context.telemetryTrace.traceID`, but the `operation_ParentId` in `applicationInsights.context.telemetryTrace.parentID` is empty. Can you tell me
- Why `applicationInsights.context.telemetryTrace.parentID` is empty?
- Where can I get `operation_ParentId`?
- Is this the best practice to get `operation_Id` and `operation_ParentId` through `applicationInsights.context.telemetryTrace` object?

Also, I would really appreciate it if you could tell me how to get the request object after sending a request using [Angular HttpClient](https://angular.io/guide/http).

Thank you.

**Comment by markwolff** [comment]
You should get the current operation id from the `context.telemetryTrace` object. It should be the same for each telemetry item on a pageview. Parent id is probably included when the telemetry is sent instead of including it on http requests. In most cases it will be the same value as the operation id.

In general (not just JS SDK), there isn't a nice way to get parent id, since it is different for each request. For the JS SDK, it is, by default, the operation id.

**Comment by IGx89** [comment]
> Why `applicationInsights.context.telemetryTrace.parentID` is empty?

I ran into this as well. It appears that they refactored their API last year and you now need to do `appInsights.properties.context.telemetryTrace.parentID` -- see https://github.com/microsoft/ApplicationInsights-JS/pull/910/files. Unfortunately if you're using TypeScript you'll then run into another hurdle: appInsights.properties is private!

**Comment by jean-moldovan** [comment]
Have more or less the same question. Interesting to know how to spit out current ai session information into the browser console, so it can be used for debugging on azure portal?

Not sure what is best to use in this case: ai session id, operation id, userid perhaps?

https://github.com/microsoft/ApplicationInsights-JS/issues/1256

**Comment by IGx89** [comment]
The bug I mentioned above is fixed now in the latest release, so I'm finding it very easy to use now. Here's my code that adds the trace ID to a user-facing error message when an HTTP request fails (it runs inside an Axios response interceptor):

```typescript
// Pull the W3C trace context ID from AI and add it to the error message.
if (window.appInsights) {
	const w3cTraceId = window.appInsights.context.telemetryTrace.traceID;
	if (w3cTraceId) {
		errorMessage += ' Error ID: ' + w3cTraceId;
	}
}
```
The ID, even just the first few characters of it, can then be entered into the Application Insights resource in the portal to find the operation details. Very slick!
