### ISSUE TITLE
[BUG] Duplicate React dependency

### ISSUE THREAD

**Issue by remijean** [microsoft/ApplicationInsights-JS#1233]
**Description/Screenshot**

React is duplicated in my dependencies list, I get errors in my browser:

![Capture d’écran de 2020-04-01 13-33-18](https://user-images.githubusercontent.com/4329231/78133063-1ba72080-741e-11ea-9231-8fe144924671.png)

I run "npm ls react" and see that the duplication comes from this library:

![Capture d’écran de 2020-04-01 13-32-48](https://user-images.githubusercontent.com/4329231/78132594-4e9ce480-741d-11ea-96f7-f0f309bf08a3.png)

**Steps to Reproduce**

 - OS/Browser: Chrome 80.0.3987.149 / Ubuntu 18.04
 - SDK Version [e.g. 22]: applicationinsights-react-js 2.5.3
 - How you initialized the SDK: 

In my App file : 

```
if (process.env.REACT_APP_MICROSOFT_APPLICATION_INSIGHTS_KEY) {
  var reactPlugin = new ReactPlugin()
  const browserHistory = createBrowserHistory({ basename: '' })
  var appInsights = new ApplicationInsights({
    config: {
      instrumentationKey:
        process.env.REACT_APP_MICROSOFT_APPLICATION_INSIGHTS_KEY,
      extensions: [reactPlugin],
      extensionConfig: {
        [reactPlugin.identifier]: { history: browserHistory },
      },
    },
  })
  appInsights.loadAppInsights()
}
```

**Expected behavior**

My project should not contain multiple copies of react. This is a problem according to the React documentation:

https://reactjs.org/warnings/invalid-hook-call-warning.html

> If you see more than one React, you’ll need to figure out why this happens and fix your dependency tree. For example, maybe a library you’re using incorrectly specifies react as a dependency (rather than a peer dependency). Until that library is fixed, Yarn resolutions is one possible workaround.

**Additional context**
N/A

**Comment by MSNev** [comment]
Reopening to tag for release -- make it easier to see whats deployed and whats not

**Comment by MSNev** [comment]
Fixed deployed as NPM and next CDN channels

**Comment by MSNev** [comment]
Closing as this is an NPM issue only
