### ISSUE TITLE
[BUG] Dependency tracking data not as expected

### ISSUE THREAD

**Issue by henry-chris** [microsoft/ApplicationInsights-JS#1239]
**Description/Screenshot**
I am attempting to set up AppInsights to work with Axios interceptors.  So that when we receive a bad response/error from a dependent web service it is logged through App Insights directly.

Example of telemetry object used in `trackDependencyData()` - 
```
{
  "name": "Browser.DependencyFailure",
  "id": "1",
  "responseCode": 400,
  "duration": 238,
  "success": false,
  "type": "get",
  "target": "https://<actualUrl>!poly?$select=*,&$filter=$id+in+'dc7c26d6-d97f-4ef0-be15-7d549b5a5e44']",
  "correlationContext": "appId=cid-v1:a5aa0fa1-9dab-4c2d-92fb-c798aad3f142",
  "data": "{\"errorId\":null,\"errorMessage\":\"Unexpected character at index 0 in the specified literal. Expected: [ But was: '\",\"errorDescription\":null}"
}
```
Example of what actually gets sent in network tab - 
```
{
  "baseType": "RemoteDependencyData",
  "baseData": {
    "id": "1",
    "ver": 2,
    "name": "Browser.DependencyFailure",
    "resultCode": "400",
    "duration": "00:00:00.102",
    "success": false,
    "data": "Browser.DependencyFailure",
    "target": "<base-url> | appId=cid-v1:a5aa0fa1-9dab-4c2d-92fb-c798aad3f142",
    "type": "get",
    "properties": {},
    "measurements": {}
  }
}
```
**Steps to Reproduce**
Instantiate app insights.
Create `IDependencyTelemetry `object
send telemetry object to `appInsights.trackDependencyData(...)`
In my case, dependency is a non MS URL.  It's just a dependent web service we use.

 - OS/Browser:  Windows 10 / Chrome 80
 - SDK Version [e.g. 22]: 2.5.3
 - How you initialized the SDK:
From inside an app insights wrapper class like so - 
```
public constructor(
    appInsightsKey: string, 
    private readonly _routeService: RouteService, 
    private readonly _authnService: AuthenticationService, 
  ) {
    this._appInsights = new ApplicationInsights({
      config: {
        instrumentationKey: appInsightsKey,
        disableAjaxTracking: true,
        disableDataLossAnalysis: true,
        disableFetchTracking: true,
        disableExceptionTracking: false,
        disableTelemetry: false,
        isBeaconApiDisabled: !navigator.sendBeacon,
      }
    });
    this._appInsights.loadAppInsights();
}
```
**Expected behavior**
`trackDependencyData()` sends exactly what I give it through the `IDependencyTelemetry` interface.

**Additional context**

I'm not sure if I'm using this incorrectly or if I should just use the `TrackEvent` api or if I have to add in the Dependency Plugin (which I can't find much documentation about) or what.  Any guidance would be helpful.

In addition.  Your ReadMe API file doesn't match the types in the package.  Which confuses me a bit more. -
```
import { IPartC } from './IPartC';
/**
 * DependencyTelemetry telemetry interface
 */
export interface IDependencyTelemetry extends IPartC {
    id: string;
    name?: string;
    duration?: number;
    success?: boolean;
    responseCode: number;
    correlationContext?: string;
    type?: string;
    data?: string;
    target?: string;
}
```
Vs. ReadMe - 
![image](https://user-images.githubusercontent.com/4165721/78294643-524d6b80-74f0-11ea-9ccf-7a3ba00fc13d.png)

**Comment by MSNev** [comment]
All requests are formatted into what we call the envelope and as part of this conversion to ensure that the field / data is correctly formatted and assigned not all of the data is blindly included.

You can however, include any key value pair data as part of the "properties" value that is defined on the IDependencyTelemetry.

I'll work to clarify the documentation around the field definitions.

In terms of the using trackEvent() vs trackDependency().
trackDependency() is used internally for ajax requests, (and I believe - may not be 100% correct) that it uses the type and name to assist with the dependency mapping in the portal.

So if you don't necessarily want it track in the portal as a dependency then you could use trackEvent(), otherwise you would need to put most (not all) of your data in the properties map.

**Comment by BuZZ-T** [comment]
According to https://docs.microsoft.com/en-us/azure/azure-monitor/app/data-model-dependency-telemetry the "name" field should contain an identifier, e.g. the URL without query params and variable names without assigned values. "data" should contain the complete URL including query parameters which was initiated.

We observed the same behavior as described by the issue creator. No matter what is set as "data", it's overwritten by the value set by "name". So we are not able to fulfill the data model for dependencies.

Plus, we observed a similar behavior when setting "disableAjaxTracking" to false and let the appInsights client automatically track dependencies. "name" is always the same as "data" and both contain the full path including path variable values and query params, so it violates the data model for "name".

So imho the label "documentation" should be replaced by bug in this case.

P.S.: We are using the currently latest version @microsoft/applicationinsights-web@2.5.11

**Comment by xiao-lix** [comment]
@BuZZ-T thanks for the comment. After investigation, we confirmed that the change to have the "data" field being the sanitized version of the "name" is a requirement of downstream systems. Updated the outdated doc, and as Nev suggested above, please  include any key value pair data as part of the "properties" value that is defined on the IDependencyTelemetry.
