### ISSUE TITLE
React Native - AI (Internal): 19 message: "Could not add handler for beforeunload and pagehide"

### ISSUE THREAD

**Issue by aajahid** [microsoft/ApplicationInsights-JS#1245]
I'm using Application Insight JS on my React Native app with the react native extension.
Everything works fine. Except It sends an AI Internal message each time the app initialize. 

```
AI (Internal): 19 message:"Could not add handler for beforeunload and pagehide"
```
I understand `beforeunload` and `onpagehide` are part of browser window, which is not available on ReactNative. So those events are failing to add handler.

Shouldn't these event binding ignored in react native app? And not to send this as AI message to the tracking?

**Comment by MSNev** [comment]
We already have a config that you can pass to stop this message from being sent.

Just add `disableFlushOnBeforeUnload: true` to your config

**Comment by aajahid** [comment]
Thanks for the solution. I'll try that.

Wondering - as we have a `react-native` specific extension, shouldn't we apply this configuration on the react-native extension by default?

**Comment by MSNev** [comment]
On the "extension", yes that is basically what I was going to look at with my comment above about "automatic suppression", Part of the issue is that the event/message is currently captured/reported before the complete initialization occurs (i.e. the react-native extension is activated).

**Comment by MSNev** [comment]
Release is now fully deployed
