### ISSUE TITLE
Send custom complex properties to Telemetry to Azure Portal with App Insights TrackEvent in Javascript?

### ISSUE THREAD

**Issue by florinvirdol** [microsoft/ApplicationInsights-JS#1246]
**Description/Screenshot**
How can I send custom complex non-string properties to Telemetry to Azure Portal with App Insights TrackEvent in basic Javascript (not NodeJS)?

I initialized the Application Insights JavaScript SDK through the following setup snippet:
```
<script type='text/javascript'>
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey: "@Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.InstrumentationKey"
        });
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
```

**Steps to Reproduce**
I tried the example from here https://github.com/microsoft/ApplicationInsights-JS and here https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#properties but without success:
```
appInsights.trackEvent({
  name: 'EventName',
  properties: { // accepts any type
    prop1: 'string',
    prop2: 123.45,
    prop3: { 
        nested: 'objects are okay too'
    }
  }
});
```

In the Ajax track request sent to Azure the sent payload has this form:
````
ver: 2
name:
   name: 'EventName'
      properties:
         prop1: 'string'
         prop2: 123.45
         prop3:
            nested: 'objects are okay too'
````

And in the Azure Portal App Insights, I get this:
```
CUSTOM EVENT
Event name	[object Object]
```

I also get an Javascript Warning in the Console:
```
Logging.ts:206 AI: CannotSerializeObjectNonSerializable 
message:"Attempting to serialize an object which does not implement ISerializable" 
props:"{name:name}"
```

 - OS/Browser: Chrome v. 80
 - SDK Version [e.g. 22]: **Not sure. In tags it shows: javascript:1.0.21**
 - How you initialized the SDK: The above Snippet setup

**Expected behavior**
For the above test, i wanted to see in Azure portal the Event with the corresponding complex and nested properties.

**Additional context**
I was able to send only by specifying ``name`` property separately and only string typed properties and only one-level nested properties.

Successful tests:
```
appInsights.trackEvent("EventName1", { properties: 'something' });
appInsights.trackEvent("EventName2", { prop1: 'something', prop2: 'prop2' });
```
Unsuccessful tests:
```
appInsights.trackEvent("EventName3", { prop1: 'prop1', nestedProp2: {prop2: 'prop2'} });
appInsights.trackEvent('EventName4', { properties: { dataToSend: 'something' }, measurements: {prop1: 'prop1', prop2: 'prop2'}});
```
**Possible fix?**
I suppose it's something with the SDK version? 

Should I upgrade to the latest SDK version by replacing my snippet setup url ``az416426.vo.msecnd.net/scripts/a/ai.0.js`` with this one ``az416426.vo.msecnd.net/scripts/b/ai.2.min.js`` ?

**Comment by MSNev** [comment]
Yes, you should update to the latest version as 1.0.21 is no longer actively maintained.

The readme has provides details on the new snippet and link (ai.2.min.js), there may also be some additional property changes for your events. Please ensure that you test locally before deploying as depending on your usage there may be breaking changes in relation to the details sent and where / how they appear in the portal.

**Comment by MSNev** [comment]
Closing based on 1.0.21 being no longer actively maintained and version 2 should correctly handle this situation. Feel free to reopen if you have the same issue with v2.

**Comment by florinvirdol** [comment]
Ok, @MSNev. 
Thank you!
