### ISSUE TITLE
[DOCS] Missing docs on setAuthenticatedUserContext

### ISSUE THREAD

**Issue by jean-moldovan** [microsoft/ApplicationInsights-JS#1252]
Hello!

In the previous version (v1) of appinsights js sdk we had `appInsights.setAuthenticatedUserContext` method. I think it was used to override user id with a custom value from the application.

This method seem to exist in the latest version of appinsights js sdk (2.5.4):
```
    Initialization.prototype.setAuthenticatedUserContext = function (authenticatedUserId, accountId, storeInCookie) {
        if (storeInCookie === void 0) { storeInCookie = false; }
        this.properties.context.user.setAuthenticatedUserContext(authenticatedUserId, accountId, storeInCookie);
    };
```

However, I don't see any docs related to that. Is this officially supported in v2.5.*?

Thanks.

**Comment by MSNev** [comment]
Yes it is supported, will update the docs

**Comment by xiao-lix** [comment]
@MSNev @jean-moldovan The doc is here: https://github.com/microsoft/ApplicationInsights-JS/blob/master/API-reference.md#setauthenticatedusercontext

**Comment by xiao-lix** [comment]
Close this issue as requested document is existing.
