### ISSUE TITLE
[BUG] Argument order for stopTrackPage method

### ISSUE THREAD

**Issue by jean-moldovan** [microsoft/ApplicationInsights-JS#1253]
According to the docs you can pass in custom options as a second argument into the `stopTrackPage` function:
```
appInsights.stopTrackPage("pageName", {customProp1: "some value"});
```
However, what I'm seeing is that when you pass custom props as a second argument, those are not sent to the app insights. In order to make it work you have to pass custom props as a third argument:
```
appInsights.stopTrackPage("pageName", undefined, {customProp1: "some value"});
```

Version: v2.5.4

Thanks!

**Comment by MSNev** [comment]
This is a docs issue, the 2nd argument is an optional override for the url, when the url is not passed it defaults to the current location.

Will update the docs.

**Comment by MSNev** [comment]
Updated the readme documentation to include null as the 2nd argument, it appears that this issue occurred because the stopTrackEvent() doesn't have the url override argument while the stopTrackPage() does.
