### ISSUE TITLE
[BUG] Deprecation of applicationinsights-js v1.0.20

### ISSUE THREAD

**Issue by jean-moldovan** [microsoft/ApplicationInsights-JS#1254]
Hello!

It is not entirely clear on what is the status of `applicationinsights-js v1.0.20`. It seems to be deprecated, however still works fine and I do not get any deprecation warnings in the console.

Because of the fact that new v2 appinsights is moved to another npm package, v1.0.21 is displayed as the latest version of the `applicationinsights-js` package and there is no good indicator (unless you go the github page) of the fact that users may want to switch to v2 package.

I'm worried that the old version would stop working one day without the users noticing it.

Thanks!

**Comment by markwolff** [comment]
Updated the deprecation. When we pushed out the Chrome SameSite changes, it seems to have undeprecated itself.
