### ISSUE TITLE
[BUG] Exception not_specified

### ISSUE THREAD

**Issue by jean-moldovan** [microsoft/ApplicationInsights-JS#1255]
Hello!

In a Vue js application I catch the exception and call the trackException method manually:
```
  Vue.config.errorHandler = (err, vm) => {
    appInsights.trackException(err)
    console.error(err)
  }
```

However, error details do not seem to be logged correctly.

This is an exception how it appears in the console:
![Screen Shot 2020-04-16 at 16 18 50](https://user-images.githubusercontent.com/3635352/79461027-48525f00-7ffe-11ea-9961-f02234f0bb3d.png)

This is how I trigger the exception in my js code:
      `this.window2.getSOmethins()`

This is what a see in the app insights:
![Screen Shot 2020-04-16 at 16 19 54](https://user-images.githubusercontent.com/3635352/79460904-21942880-7ffe-11ea-912e-b37d08bda594.png)

I think this was logging exceptions correctly with the old v1 of app insights. Any help would be appreciated.

**Comment by markwolff** [comment]
Please use the latest [APIs](https://github.com/microsoft/ApplicationInsights-JS#sending-telemetry-to-the-azure-portal)
```ts
appInsights.trackException({ exception: err });
```
