### ISSUE TITLE
Telemetry Tracking Plug-in

### ISSUE THREAD

**Issue by gdkerr** [microsoft/ApplicationInsights-JS#1257]
With this feature, a user would be able to wrap certain components in a withTelemetryTracking component to track button clicks of that component when the application is running.

On top of this, there could be extensibility in this feature for tracking more telemetry data type metrics.

**Comment by gdkerr** [comment]
I am working on this for my university senior design project with sponsorship from Microsoft for quality control and following implementation standards.

**Comment by MSNev** [comment]
Hi, who are your contacts at Microsoft in relation to this as we also have several (currently) internal streams of work already going or about to start that sound awfully similar to this.

**Comment by gdkerr** [comment]
@MSNev Hi! My current contact within Microsoft is Chris Dietsch <chris.dietsch@microsoft.com>. After today, I am handing off my work to him so please be in contact about where to proceed with this. Thank you!

**Comment by MSNev** [comment]
Thanks, I've reached out to Chris to get more context and to understand how this might fit into the overall plans.
Cheers

**Comment by MSNev** [comment]
I reached out to Chris and he is going to send me the info you created and we will see how we can incorporate that into the project.
