### ISSUE TITLE
[BUG] How to set the minimum log level

### ISSUE THREAD

**Issue by Shyam268** [microsoft/ApplicationInsights-JS#1259]
How to set the minimum log level

Project is configured using app insights vreston 2.5.4
  this.appInsights = new ApplicationInsights({
      config: {
        instrumentationKey: xxx-xxxxx-xxxxx-xxxx,
      }
    });
    this.appInsights.loadAppInsights();
   so far i can log all SeverityLevel (Information,Error,Warning,Critcal). 
  How to configure the minimum log level(Example- Error) ?

**Comment by markwolff** [comment]
You would use a telemetry initializer and `return false` on any log you want to filter out
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#javascript-web-applications
