### ISSUE TITLE
[BUG]Web Forms page view not correlating to server request

### ISSUE THREAD

**Issue by t525** [microsoft/ApplicationInsights-JS#1261]
Describe any aspect of your environment relevant to the problem:

SDK version: 2.12
.NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): .net 4.6.2
Hosting Info (IIS/Azure WebApps/etc): IIS
Platform and OS version: Windows 10
If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

Steps to reproduce.
I noticed that when a ASP.NET web forms page does a full postback, a new page view in app insight is generated but it is not being correlated with the server request. All I see in the end to end transaction is a list of dependency calls and then at the end is the page view. For partial post back (AJAX), only one page view is generated and all dependency calls appear under the server request.

What is the expected behavior?
I am thinking that for full post back, the dependency calls should be still linked to the server request.

What is the actual behavior?
Dependency calls associated with full post back are not linked to server request.

Additional context.

**Comment by MSNev** [comment]
Hi Tim, 
This issue list is only for the JS SDK -- not the .Net SDK, I think this is the correct repo is
https://github.com/Microsoft/ApplicationInsights-dotnet/issues

Can you report there -- as there doesn't seem to be a "move" issue capability :-( 

Cheers

Nev

**Comment by t525** [comment]
Hi Nev, I have entered the ticket in .net sdk forum.  I had entered in both because I wasn't sure if there problem is on the client or server.

**Comment by MSNev** [comment]
Linking of page Form based Post back operations are not the domain of the JS SDK, only the ajax request via XMLHttpRequest, XDomainRequest and fetch.

**Comment by t525** [comment]
You can go ahead and close this one then.
