### ISSUE TITLE
[BUG] Custom properties added with addTelemetryInitializer are ignored for exceptions

### ISSUE THREAD

**Issue by Trenrod** [microsoft/ApplicationInsights-JS#1262]
**Description/Screenshot**
Custom properties added with addTelemetryInitializer are ignored for exceptions

Custom property session_id is only send for custom events. It is not send with any exception
![image](https://user-images.githubusercontent.com/5102094/81099448-38e27980-8f0b-11ea-8dcc-bed53ef680b3.png)

**Steps to Reproduce**
init telemetry with custom properties
```typescript
        const telemetryInitializer = (item: ITelemetryItem) => {
            if (item.data !== undefined) {
                item.data.session_id = theConferenceController.getClientSessionIdentifier();
            }
        };
        appInsights.loadAppInsights();
        appInsights.addTelemetryInitializer(telemetryInitializer);
```

Calling examples
```typescript
      getAppInsights()?.trackEvent({name: "TEST"});
      throw Error("This is just a test, calm down");
    } catch (error) {
      getAppInsights()?.trackException(error);
```

 - OS/Browser:
Chrome: Version 81.0.4044.129 (Offizieller Build) (64-Bit)
 - SDK Version [e.g. 22]:
"@microsoft/applicationinsights-react-js": "^2.5.4",
"@microsoft/applicationinsights-web": "^2.5.4",
 - How you initialized the SDK: 
https://github.com/Azure-Samples/application-insights-react-demo/blob/master/src/TelemetryService.js

**Expected behavior**
session_id should also be send on exception like it is send when custom events are triggered.

**Additional context**
No

**Comment by MSNev** [comment]
This is an issue with the way that the exception envelope is created.
I have a work item around enhancing the way the exceptions are serialized (part of a fix for #363), I'll see if I can address this at the same time.

**Comment by MSNev** [comment]
I'm also tagging as an enhancement as it appears to have been like this for a while -- it assumes that custom properties are passed to the trackException() which they aren't for automatically caught exceptions

**Comment by riteshbhoi** [comment]
i had raised this issue almost a year back and it was closed stating this was fixed. 
reference: https://github.com/microsoft/ApplicationInsights-JS/issues/954

**Comment by MSNev** [comment]
Release is now fully deployed
