### ISSUE TITLE
[BUG] Not working with function components

### ISSUE THREAD

**Issue by psytonik** [microsoft/ApplicationInsights-JS#1263]
**Description/Screenshot**
NOT WORK WITH FUNCTIONAL COMPONENTS
**Steps to Reproduce**

 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**

**Additional context**
HOW I CAN FIX THIS  ?

**Comment by MSNev** [comment]
Hi,
Can you please provide some additional information, as what framework you are using.

What are you calling Functional components... What are you current doing or have you tried?

**Comment by MSNev** [comment]
Closing due to lack of response on what the issue is, feel free to reopen and add the requested details.
