### ISSUE TITLE
[BUG] Error is not logged

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/ApplicationInsights-JS#1267]
**Description/Screenshot**

**Steps to Reproduce**

just throw error in console eg with command:
throw Error("test")

 - OS/Browser: Chrome
 - SDK Version [e.g. 2.5.4]:
 - How you initialized the SDK:

    config: {
        instrumentationKey: "<DAP.AIInstrumentationKey>",
        appId: "OSKAR",
        disableFetchTracking: false,
        enableCorsCorrelation: true,
        disableCorrelationHeaders: false,
        // correlationHeaderExcludedDomains: [
        //     "*.com",
        // ],
        correlationHeaderDomains: ["*oskarsvc*", "*localhost*"],
    },

**Expected behavior**
Exception should be tracked and appear in AI

**Additional context**
I came across this as I observed that eg resolving of a fetch-response using (res) => res.json() was not logged, when it throw an error due to an invalid json-string. (altough that was thrown correctly into console)

**Comment by MSNev** [comment]
Hi, I just created a couple of local html files using both the current and previous snippet using your basic config above and I'm seeing the exception being thrown and reported in the portal

If an error is thrown as part of the snippet initialization then the SDK will not initialize and therefore you wont get anything in the portal -- as nothing is sent...

What is the response that is returned (look in the F12 dev console).

This is the entire content of the test html files, I've also attached the sample I used with the current snippet -- just replace the Instrumentation key with yours.
[Sample.zip](https://github.com/microsoft/ApplicationInsights-JS/files/4623593/Sample.zip)
  <script type="text/javascript">
... <remove the snippet code> ...
src: "https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js", // The SDK URL Source
cfg: { // Application Insights Configuration
    instrumentationKey: "MyInstrumentationKey",
    appId: "OSKAR",
    disableFetchTracking: false,
    enableCorsCorrelation: true,
    disableCorrelationHeaders: false,
    // correlationHeaderExcludedDomains: [
    // "*.com",
    // ],
    correlationHeaderDomains: ["oskarsvc", "localhost"],    
}});

setTimeout(function() {
  throw Error("test");
}, 500);
        </script>

**Comment by LeopoldLerch** [comment]
weird.
But remotedependencys are tracked, so it is not the case that it is not initialized at all.

**Comment by LeopoldLerch** [comment]
I also look at the network-request going out and wait, until the page is fully loaded, so that all track-requests are out. Then I do the error and look at the track-requests going out (if any). But (besides remotedependencies, nothing goes out)

**Comment by LeopoldLerch** [comment]
> Hi, I just created a couple of local html files using both the current and previous snippet using your basic config above and I'm seeing the exception being thrown and reported in the portal
> 
> If an error is thrown as part of the snippet initialization then the SDK will not initialize and therefore you wont get anything in the portal -- as nothing is sent...
> 
> What is the response that is returned (look in the F12 dev console).
> 
> This is the entire content of the test html files, I've also attached the sample I used with the current snippet -- just replace the Instrumentation key with yours.
> [Sample.zip](https://github.com/microsoft/ApplicationInsights-JS/files/4623593/Sample.zip)
> 
> <script type="text/javascript"> ... ... src: "https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js", // The SDK URL Source cfg: { // Application Insights Configuration instrumentationKey: "MyInstrumentationKey", appId: "OSKAR", disableFetchTracking: false, enableCorsCorrelation: true, disableCorrelationHeaders: false, // correlationHeaderExcludedDomains: [ // "*.com", // ], correlationHeaderDomains: ["oskarsvc", "localhost"], }}); setTimeout(function() { throw Error("test"); }, 500); </script>

well, your timeout works

but if you open the console and throw an error by executing 
`throw Error("Test")`
the error is thrown, but it does not track anything

**Comment by MSNev** [comment]
Thats because the console is consuming the error and not calling window.onerror (the way we hook the errors). As long as the console is open any exception thrown from the console will be swallowed by it.

eg. in the console do the following
setTimeout(function() { throw new Error("console test"); }, 5000);

If you leave the dev console open for 5 seconds then the exception is caught by the dev console and nothing is logged, but if you close the console, wait five seconds and then open it again (after the exception was thrown) navigate to the network tab you will see the exception was caught and is sent out the door.

**Comment by biltongza** [comment]
We've seen similar behaviour. The telemetry is logged, but it never shows up in the "Failures" panel on the portal. It does show up if we use the search panel.

**Comment by MSNev** [comment]
I've been working on enhancing the collection of exceptions from the JS side as there are a couple of corner cases that either don't get logged or there is no stack trace available...

Can you provide an idea on the sorts of environment that you are seeing where no failures are being reported? i.e. browser (and version) / OS, in the case of  it showing in the search there should be the useragent and identified browser that would possible help narrow down this issue.

**Comment by biltongza** [comment]
It appears to affect all environments. We have _zero_ exceptions from web showing up in Failures across all of our test environments as well as production. I think it may be a problem on the Azure portal. Like I said, the exception telemetry is all sent and shows up if we explicitly search for it, it's just the Failures screen seems to exclude it all. We haven't updated the library in a while either (we are on 2.3.1 in prod) and it used to work fine, which is why I think it is an Azure portal problem.
