### ISSUE TITLE
WireDep Issues

### ISSUE THREAD

**Issue by jasteph** [Microsoft/ApplicationInsights-JS#127]
I'm using WireDep to automatically grab all of my bower packages and inject them into my application. https://github.com/taptapship/wiredep

It is not finding this library. They require that an application define its dependencies and have a main property in it's bower.json file. I tried hardcoding these, but have been unsuccessfuly in getting it to recognize.

Has anyone else came across this issue before?

**Comment by laughin1** [comment]
Was able to get it working with overriding it in Wiredep's config.

**Comment by jasteph** [comment]
Was able to get it working with overriding it in Wiredep's config.

**Comment by MaxShehovtsov** [comment]
I'm glad you figured this out! Would you mind sharing the fix?

**Comment by jasteph** [comment]
In my own bower.json I added an 'overrides' object:

```
  "overrides": {
    "applicationinsights-js": {
      "main": "dist/ai.js"
    }
  }
```

**Comment by MaxShehovtsov** [comment]
Thank you!
