### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by moraiMicrosoft** [microsoft/ApplicationInsights-JS#1272]
Hi!

Description:
We are using Application insights into our web application by adding the script to our HTML file.
When deleting the cookies and local storage from the browser data, only the cookies are set with the ai values. It used to also update the local storage with an equivalent value. Now, it set an empty value or doesn't set anything at all.
Looking into the docs didn't result in any function or param that can init local storage with ai values.
Can you please advise with this issue?

 - OS/Browser: Windows, chrome
- How you initialized the SDK:
 - SDK Version [e.g. 22]: Using manually script from this link:
az416426.vo.msecnd.net/scripts/a/ai.0.js

Thanks!

**Comment by ramthi** [comment]
You are using an older version of the SDK.  Are you able to upgrade to our current version (released about a year ago) following these directions? https://github.com/microsoft/ApplicationInsights-JS#upgrading-from-the-old-version-of-application-insight and report back if you continue to see the issues?

**Comment by moraiMicrosoft** [comment]
At the moment it is upgraded on our test environments and it didn't solve the issues I mentioned. I will check it on production once we will push the updates.
Any other ideas?
