### ISSUE TITLE
[BUG] WithAITracking cannot wrap around functional components

### ISSUE THREAD

**Issue by Ishraque99** [microsoft/ApplicationInsights-JS#1274]
**Description/Screenshot**
![image](https://user-images.githubusercontent.com/30386992/83147091-8fbe2600-a13a-11ea-9437-7bc0375cdedf.png)
Functional components (ala ES6) have undefined prototype and no constructor name. While we can provide a name parameter to WithAITracking I don't think it makes sense as these components are meant to be anonymous/nameless.

**Steps to Reproduce**
- create a functional component as such and wrap it `withAITracking()`
```TS
const Test = (props: Props) => {
    return (<div>
        <p>This is a test component</p>
    </div>);
}
...
export default withAITracking(reactPlugin, Test)
```

 - OS/Browser: Ubuntu 20.04/Firefox
 - applicationinsights-react-js version: ^2.5.4
 - How you initialized the SDK: following the basic usage guideline in the README for applicationinsights-react-js

**Expected behavior**
Component should load as normal

**Possible fix**
**Edit:** Added PR #1275 :)
I think it's a simple fix. Update WithAITracking as such.
```TS
  if (componentName === undefined || componentName === null || typeof componentName !== 'string') {
    componentName = Component.prototype && 
          Component.prototype.constructor && 
          Component.prototype.constructor.name ||
          'Anonymous component';
  }
```
instead of "Anonymous component" it could also be an empty string, just like the default for className.

**Comment by MSNev** [comment]
Included in v 2.5.5 which is now fully deployed
