### ISSUE TITLE
[BUG] AppInsights stub methods captured incorrect method names in the closure

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/ApplicationInsights-JS#1283]
**Description/Screenshot**
https://github.com/microsoft/ApplicationInsights-JS/blob/5cb9e44cfd8eef63099c5ecd5b11d8cb9fb81697/AISKU/snippet/snippet.js#L225-L240

Note the statement on L227:
```js
var name = methods.pop();
```

Since `var` spans the variable scope to the containing function (i.e. `_createMethods`), the value of this variable gets replaced among each iteration of the while loops.

This causes all the `appInsights.[method]` calls before `ai.2.js` has loaded incorrectly forwarded as `appInsights.trackEvent` calls.

**Steps to Reproduce**
Copy-paste all the code in `snippet.js`, or its minimized version on README.md. Then follows the code. Ensure the following code is executed before `ai.2.js` has been downloaded.
```js
appInsights.addTelemetryInitializer(function (e) { /* dummy */ } );
```
When running the code, you will find there are 2 `trackEvent` calls to the actual appInsights object, making 2 extra (invalid) event traces.

![image](https://user-images.githubusercontent.com/50703224/83847148-53905400-a73e-11ea-9d50-2aad5171ff6d.png)

 - OS/Browser:
 - SDK Version [e.g. 22]: v2
 - How you initialized the SDK: with snippet (snippet.js)

**Expected behavior**
I should have telemetry initializer set up. And there should be `trackPageView` called so I should have its telemetry.

**Additional context**

**Comment by MSNev** [comment]
NICE CATCH! - the issue is on line 234 as you identified where it's using effectively the last popped name!

**Comment by MSNev** [comment]
Reopening for release tracking

**Comment by MSNev** [comment]
Release is now fully deployed
