### ISSUE TITLE
[BUG] Can't access dead object error in Firefox

### ISSUE THREAD

**Issue by serkan-inci** [microsoft/ApplicationInsights-JS#1290]
**Description/Screenshot**
We are seeing some client errors in our product, which all seems to be happening in applicationinsights-channel-js/src/Sender based on the stacktrace we have in our telemetry.

**b**@https://ml.azure.com/static/js/main.f6ce6a49.chunk.js:1:249257 AUji/Ue</e.prototype.**isOnline**@https://ml.azure.com/static/js/main.f6ce6a49.chunk.js:1:355295 AUji/Ue</e.prototype.**isOffline**@https://ml.azure.com/static/js/main.f6ce6a49.chunk.js:1:355436 AUji/Ke</t.prototype.**_xhrReadyStateChange**@https://ml.azure.com/static/js/main.f6ce6a49.chunk.js:1:363064 AUji/Ke</t.prototype.**_xhrSender**/n.onreadystatechange@https://ml.azure.com/static/js/main.f6ce6a49.chunk.js:1:366151

We think that this is not a user impacting error and only occurs on Firefox but it may be good to check there is no memory leak when subscribing/unsubscribing events based on this link:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object
**Steps to Reproduce**

 - OS/Browser: Firefox 66.0
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**
No uncaught exceptions fired

**Comment by MSNev** [comment]
@serkan-inci Is it possible for you to identify the exact object that is being referenced for this line
b@https://ml.azure.com/static/js/main.f6ce6a49.chunk.js:1:249257

Looking at the code the current instance looks fine (as it's a static Offline object), but it is referencing the navigator object, and based on the Dead_object error it's sounding like the page is unloading... 

So the exception dead_object seems to be somewhere in this method, we could probably resolve by simply wrapping in a try / catch, but I'd like to try and understand exactly which scenario this is.

    public isOnline(): boolean {
        var _navigator = getNavigator();
        if (this.isListening) {
            return this._onlineStatus
        } else if (_navigator && !CoreUtils.isNullOrUndefined(_navigator.onLine)) { // navigator.onLine is undefined in react-native
            return _navigator.onLine;
        } else {
            // Cannot determine online status - report as online
            return true;
        }
    }

**Comment by MSNev** [comment]
@serkan-inci any updates, I assume this still occurring?

**Comment by serkan-inci** [comment]
That code doesn't exist anymore and we haven't seen any occurrence since then. If it doesn't occur someone else then we might be doing something wrong but unfortunately there is no way for us right now to figure that out.

I think you can close this bug and if it occurs again, I can reactivate and try to understand exactly what we are doing.

**Comment by MSNev** [comment]
Closing as we have not been able to narrow down the issue.
