### ISSUE TITLE
[BUG] Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by lukos** [microsoft/ApplicationInsights-JS#1292]
**Description/Screenshot**
Caused by JS App Insights snippet copied directly from [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#snippet-based-setup)

![image](https://user-images.githubusercontent.com/581018/84370268-f11cd500-abcf-11ea-8266-84b88e03d8d7.png)

**Steps to Reproduce**
 - Windows 10, Chrome : 83.0.4103.97
 - SDK Version: Not sure, isn't just "latest"?
 - How you initialized the SDK: Not sure what that means. I have just pasted the snippet into an aspx page.

Interestingly, it consistently errors on some pages and not others even though they all have the same snippet.

**Expected behavior**
No errors logged to console

**Additional context**
It looks like the track POST is still successful according to the network tab. We have only recently updated the snippet to support addTelemetryInitializer

**Comment by lukos** [comment]
We think the problem might be pages that have ajax calls on them.

**Comment by markwolff** [comment]
Which snippet did you use for your pages?

**Comment by MSNev** [comment]
There was a bug in snippet v3 z(#1283), which is now fixed and we have updated the snippets.
Can you please check the version of the snippet you are using? Search for the value of the ,sv: field, if it's ,sv:"4", then it's the latest, but if it's sv:"3" then please update to the latest version.

**Comment by MSNev** [comment]
@lukos did this resolve your issue?

**Comment by MSNev** [comment]
Closing from no response -- please reopen if this is still occurring
