### ISSUE TITLE
Is it possible to send 'client app version' with each event sent with js sdk?

### ISSUE THREAD

**Issue by quarryman** [microsoft/ApplicationInsights-JS#1295]
**Is your feature request related to a problem? Please describe.**
How can I add my 'application version'  to every event that is sent to Azure Monitor?

**Describe the solution you'd like**
I would like to mark each event/expection with application version to know which version event belongs to, just like it can be done in any error tracking software like Sentry or Bugsnag

**Describe alternatives you've considered**
Looked through appInsights initialization options and couldn't see option for app version.
appId is smth similar, yet it description make me think its for different purpose

**Additional context**

**Comment by markwolff** [comment]
Hey @quarryman, try this telemetry initializer out

```js
appInsights.addTelemetryInitializer((envelope) => {
  envelope.tags["ai.application.ver"] = "<your application version>";
});
```
