### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by giriv1985** [microsoft/ApplicationInsights-JS#1296]
**Description/Screenshot**

We are seeing client-side dependencies request with duration > 0 but resultCode=0 for google analytics very rarely. What does it mean ?.

**Steps to Reproduce**

 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**

**Additional context**

**Comment by markwolff** [comment]
A result code 0 can mean user was offline or the request was blocked by adblock, tracking blockers, etc.

https://stackoverflow.com/questions/872206/what-does-it-mean-when-an-http-request-returns-status-code-0/14507670#:~:text=An%20HTTP%20response%20code%20of,execute%20within%20a%20specified%20time.

**Comment by giriv1985** [comment]
Above situation i mentioned happening most of time in safari browser. Please tell and suggest there is any issue with mac ios safari browser.

**Comment by SrinivasaKrishnamurthy** [comment]
Any update?

**Comment by MSNev** [comment]
As per Marks response, this is the status value returned by the XmlHttpRequest object, which means.
4


An HTTP response code of 0 indicates that the AJAX request was cancelled.

This can happen either from a timeout, XHR abortion or a firewall stomping on the request. A timeout is common, it means the request failed to execute within a specified time.

And as per https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status
Before the request completes, the value of status is 0. Browsers also report a status of 0 in case of XMLHttpRequest errors.

And the duration reported is based on the amount of milliseconds between the xhr.send() and when the browser calls the ready state change event with a status of 4 (complete).

Additionally, there is a corner case that if you are using local files Firefox sets the status to 0 upon success.
