### ISSUE TITLE
Tag telemetry with cookies

### ISSUE THREAD

**Issue by JasonFreeberg** [microsoft/ApplicationInsights-JS#1298]
**Is your feature request related to a problem? Please describe.**

Azure App Service allows users to deploy their code into environments (slots) and split traffic between them for A/B testing. Using separate Instrumentation Keys per slot is prohibitive because the deployed code can "swap" between these environments (ex: from test to staging to prod). 

App Service exposes the cookie, `x-ms-routing-name`, with the current slot. I am looking for a way to tag the AI telemetry with this cookie value. I tried to *roll my own* using TelemetryInitializers, but I couldn't get it to work.

**Describe the solution you'd like**

I am able to use a Telemetry Initializer to create a tag with a constant string, but when I use the snippet below to use a method to grab the current cookie, the initializer doesn't seem to register the tag.

```js
var telemetryInitializer = (envelope) => {
      envelope.tags["ai.cloud.role"] = "app-service-slot";
      envelope.tags['environment'] = getCookieValue('x-ms-routing-name');
    }
    this.$appInsights.addTelemetryInitializer(telemetryInitializer);
}
```

Here is the implementation for `getCookieValue()`. It seems to work fine.

```js
/**
 * Returns the value of the specified cookie. If the cookie cannot be found, returns null;
 * @param {string} key The key of the cookie
 */
export function getCookieValue(key) {
  const cookie = document.cookie
    .split('; ')
    .find(cookie => cookie.startsWith(key));
  
  return cookie ? cookie.split('=')[1] : null;
}
```

**Describe alternatives you've considered**

I tried adding the `async` decorator to `getCookieValue()` and awaiting the method in the TelemetryInitializer, but this didn't seem to have an effect. Any ideas?

**Comment by JasonFreeberg** [comment]
For added context, I am using Vue.js and the [vue-app-insights plugin](https://www.npmjs.com/package/vue-application-insights).

**Comment by markwolff** [comment]
I think the only issue here is that you need to store your environment as a custom property and not as a tag. This SDK serializes any unknown tags away (and I also think they might be serialized away elsewhere in ingestion or on the Portal if we didn't do this). Try something like this

```js
var telemetryInitializer = (envelope) => {
      envelope.tags["ai.cloud.role"] = "app-service-slot";
      envelope.data['environment'] = getCookieValue('x-ms-routing-name');
    }
    this.$appInsights.addTelemetryInitializer(telemetryInitializer);
```

https://github.com/microsoft/ApplicationInsights-JS#example-filtering

**Comment by MSNev** [comment]
Closing -- assuming the above resolved the issue -- please reopen if it's still occurring.
