### ISSUE TITLE
Manually setting session ID

### ISSUE THREAD

**Issue by chuanqisun** [microsoft/ApplicationInsights-JS#1302]
Is there a way to manually set the session ID during or after the client sdk gets initialized?

In our app, the session id is generated on the server side and passed into the client via a javascript variable e.g. `window.myAiSessionId`. We have multiple isolated client apps that share the same session so being able to share the same session id will allow us to track user flow across the apps. Thanks!

**Comment by markwolff** [comment]
Try `appInsights.context.session.id = "<some random id>"`

**Comment by chuanqisun** [comment]
Thanks! A manually set `context.session.id` works for me!
