### ISSUE TITLE
[BUG] Nodejs - Live metrics - Request per second doesn't seem to work

### ISSUE THREAD

**Issue by harisubramaniam1** [microsoft/ApplicationInsights-JS#1304]
**Description/Screenshot**
Live metrics request telemetry doesn't seem to produce the metrics for requests in flight
**Steps to Reproduce**
![image](https://user-images.githubusercontent.com/63234380/86120964-1add6380-bacd-11ea-9e6b-405e5cc355cd.png)

 - OS/Browser: Windows ASP Azure function v2
 - SDK Version [e.g. 22]: Node js - https://registry.npmjs.org/applicationinsights/-/applicationinsights-1.5.0.tgz - ^1.5.0
 - How you initialized the SDK:
`const` setupAppInsights =
`async` () => {
    `const` environment = getEnvironment();
    `if` (environment.appInsightsKey) {
        `appInsights.setup()`
            `.setAutoDependencyCorrelation(true)`
            `.setAutoCollectRequests(true)`  // set to false if we do our own tracking trackDependency
            `.setAutoCollectPerformance(true,` true)
            `.setAutoCollectExceptions(true)`
            `.setAutoCollectDependencies(true)`  // set to false if we do our own tracking trackRequests
            `.setAutoCollectConsole(true,` true)
            `.setUseDiskRetryCaching(true)`
            `.setSendLiveMetrics(true)`
            `.setDistributedTracingMode(appInsights.DistributedTracingModes.AI_AND_W3C);`

        `appInsights.start();`
    `}`

    return appInsights.defaultClient;
};

export default setupAppInsights;
**Expected behavior**

Live metrics has request telemetry populated

**Additional context**

**Comment by markwolff** [comment]
Azure functions configured with HTTP triggers are not seen as http from node.js perspective, they are just arbitrary function calls. You would need to manually call trackRequest for FaaS request telemetry to appear in Live Metrics or in the Portal.
