### ISSUE TITLE
"Unminify" feature does not work if a "version" query string parameter is appended to the file path.

### ISSUE THREAD

**Issue by mirkolugano** [microsoft/ApplicationInsights-JS#1313]
I am embedding scripts into my page like this `<script type="text/javascript" src="~/Scripts/bundled/register.min.js" asp-append-version="true"></script>` which results in the final HTML in having a "version" appended to the file url like this: `https://mysite.com/Scripts/bundled/register.min.js?v=HgCD8hP3kcnJPwImmu8nky2zGX3hPNKSoyT6rTyEfuc`. This is to avoid caching issues on the client. It seems to me, that the "unminify" feature does not recognize the query string (which should be stripped out), thus looking for a .map file named exactly like the full path (including query string) plus .map. (see image below). 

![Unbenannt](https://user-images.githubusercontent.com/11976472/86561935-0f24ed80-bf62-11ea-871e-a1bf628bd181.PNG)

#178 for reference.

**Comment by markwolff** [comment]
Hey, I've released a fix for this on the Portal. It should roll out completely in the next few days. Let me know if this is still an issue after a week or so.

**Comment by mirkolugano** [comment]
it looks good, thank you!
