### ISSUE TITLE
"Unminify" feature does not work if some source map files are missing

### ISSUE THREAD

**Issue by mirkolugano** [microsoft/ApplicationInsights-JS#1314]
Sometimes when analysing a javascript error, in the Stack trace are referred some scripts which come from external libraries, which I do not need to unminify and debug. A source map is therefore not available. It would be best, if the corresponding line would be ignored, and directly pass on to the following lines, for which sourcemaps are available. Instead, it gives an error and no unminification takes place. (see image below - 1st line: no source map; 2nd and 3rd line: source maps are there, but not applied)

![Unbenannt1](https://user-images.githubusercontent.com/11976472/86562369-e2bda100-bf62-11ea-8910-6505185d6511.PNG)

#178 for reference.

**Comment by markwolff** [comment]
The way the error reporting works now is to only report on the 1st line, since many call stacks could have several lines of external dependencies. I'm not sure how to adapt nicely for your scenario in addition to the typical 1st line only scenario. Perhaps the error could still show, but the rest of unminificaion could proceed?

**Comment by mirkolugano** [comment]
> Perhaps the error could still show, but the rest of unminificaion could proceed?

@markwolff for instance, yes that would do. The way I see it, I was thinking of AI going over all lines of the stack trace and search for corresponding sourcemap files, and if not present, move on to the next line without unminifying the "not found" entry. The user can still be notified that some files are missing and have not been unminified.
