### ISSUE TITLE
Can Unminify button search all folders within Blob Storage Account ?

### ISSUE THREAD

**Issue by puneetg1983** [microsoft/ApplicationInsights-JS#1318]
**Is your feature request related to a problem? Please describe.**
We are using the UnMinify feature of Application Insights for our Angular Frontend project. We have configured Azure Devops to Copy Source Maps to our Blob Storage account by following this article. https://docs.microsoft.com/en-us/azure/azure-monitor/app/source-map-support. To keep things organized, we are storing the SourceMaps with the version information (20200707.2) like this.

https://<**STORAGEACCOUNT**>.blob.core.windows.net/sourcemaps/**20200707.2**/1.f10f936dc57eed434bd0.js.map

The problem is that when we click Unminify button, Application Insights is searching only the ROOT of the folder to look for source maps. 

**Describe the solution you'd like**
Is there some magic we can do to ensure that Application Insights searches **either all the folders** or **a specific folder for the correct version** to find the source maps?

**Describe alternatives you've considered**
We are currently copying source maps from all releases directly in to the root of the BLOB Container which is a bit tough to organize.

**Additional context**
none

**Comment by markwolff** [comment]
The current behavior is for it to search for the mapfile based on the folder structure of the originating JS file. The exact behavior is described here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/source-map-support#push-your-source-maps-to-your-blob-container

To self-debug, you can view the network tab of your browser's F12 menu and see where we are looking for mapfiles when you click unminify.

You do not need to host all of your mapfiles at the root of the storage container anymore.
