### ISSUE TITLE
Start root operation on every http request - Angular

### ISSUE THREAD

**Issue by AlissonRS** [microsoft/ApplicationInsights-JS#1320]
Following issue #976 I understand that in SPA, one can use `enableAutoRouteTracking` so every time users navigate to a new route, it will automatically create a new top level (root) operation. This is a good feature as operations in different routes won't be correlated by a common parent operation.

However, in my application there are cases a user may still do too many requests/operations in the same route, and all them will be correlated (up to thousands of operations). I wanted to begin a new top level (root) operation on each http request made inside Angular.

Is this possible?

**Comment by AlissonRS** [comment]
I just checked other people want to be able to manually begin a new root operation, but they are having issues, refer to #727 

![image](https://user-images.githubusercontent.com/4753901/86969959-f7598f00-c144-11ea-9574-927c42e1d6e2.png)

**Comment by MSNev** [comment]
As I mentioned in #727 the 'enableAutoRouteTracking' config is a feature of v2 of the SDK, and searching through the code the Operation object no longer exists in v2.

With v2 and the config this causes a new pageview event for each url route change (url#xyz...) which in response to the location change event will create a new telemetry traceId.

https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts#L648

You can reset these values directly on the appInsights object via the public "context" object
appInsights.context.telemetryTrace.traceId = ...
or
by adding a telemetry initializer and overwriting the values that are set from the context.
