### ISSUE TITLE
[BUG] Type 'ReactNativePlugin' is not assignable to type 'ITelemetryPlugin'

### ISSUE THREAD

**Issue by nairmanu** [microsoft/ApplicationInsights-JS#1324]
**Description/Screenshot**

Type 'ReactNativePlugin' is not assignable to type 'ITelemetryPlugin'.
  Types of property 'setNextPlugin' are incompatible.
    Type '(next: ITelemetryPlugin) => void' is not assignable to type '(next: ITelemetryPlugin | ITelemetryPluginChain) => void'.
      Types of parameters 'next' and 'next' are incompatible.
        Type 'ITelemetryPlugin | ITelemetryPluginChain' is not assignable to type 'ITelemetryPlugin'.
          Type 'ITelemetryPluginChain' is missing the following properties from type 'ITelemetryPlugin': priority, initialize, identifier

**Steps to Reproduce**
When I add the latest versions of applicationinsights-react-native and applicationinsights-web, I get the above error while trying to create a new instance of ApplicationInsights(). 
ReactNativePlugin is not accepted as a valid value for extensions array.

yarn add @microsoft/applicationinsights-react-native
yarn add @microsoft/applicationinsights-web

Versions installed are,
"@microsoft/applicationinsights-react-native": "^2.2.5",
"@microsoft/applicationinsights-web": "^2.5.6",

 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**

**Additional context**

**Comment by MSNev** [comment]
This issue is a method signature issue only, as a workaround you *should be able* and can safely cast the plugin to an ITelemetryPlugin when assigning the react-native to the extensions.

The ITelemetryPluginChain property is only used *if* you are creating a shared instance and reusing across multiple AI instances.

**Comment by nairmanu** [comment]
thanks! the workaround seems to do the trick. Is there a plan to fix this in the future releases?

**Comment by MSNev** [comment]
Yep, about to start working on it now -- should be in next release

**Comment by nairmanu** [comment]
thank you!

**Comment by MSNev** [comment]
PR is out -- please have a look as I've applied a couple of changes, specifically
- fixed this issue, by extending from the new base class
- refactored to use dynamicProto() -- for better minification
- as part of the refactoring ALL of the private properties are now closure based instance variables (part of the minification changes), but the big change is that they will no longer be available on the instance.

**Comment by MSNev** [comment]
Fully Deployed to CDN and NPM as version 2.5.7
