### ISSUE TITLE
[BUG] SamplingScoreGenerators folder missing in dist-esm/TelemetryProcessors in 2.5.6

### ISSUE THREAD

**Issue by AndrewKindleysides** [microsoft/ApplicationInsights-JS#1326]
```
./node_modules/@microsoft/applicationinsights-channel-js/dist-esm/TelemetryProcessors/Sample.js
Module not found: Can't resolve './SamplingScoreGenerators/SamplingScoreGenerator'
```

SamplingScoreGenerators folder has dissappeared from the dist of 2.5.6

**Comment by MSNev** [comment]
Can you please explain a bit more?

Building locally, I am seeing the file present in the "dist-esm" folder (I don't believe it's ever been included in the "dist" folder and extracting the latest npm package the same is true -- present in the dist-esm folder

npm i @microsoft/applicationinsights-channel-js

**Comment by AndrewKindleysides** [comment]
interesting, i'm using yarn. I've deleted my node_modules folder to perform a clean install of packages.
```yarn add @microsoft/applicationinsights-web``` has installed v2.5.6, when i start my app (that has worked before using application insights) i get the above error, when i look into the folder ```./node_modules/@microsoft/applicationinsights-channel-js/dist-esm/TelemetryProcessors``` there is no SamplingScoreGenerators folder.

I'll investigate further on my end and try again, but seems odd that it's downloading the rest of the dist but not that folder.

**Comment by AndrewKindleysides** [comment]
could be something locally on my end like cached packages, colleague has tried it and he's not having the above issue.

sorry for the false alarm
