### ISSUE TITLE
Will this work with AngularJS?

### ISSUE THREAD

**Issue by vaibhavahuja** [microsoft/ApplicationInsights-JS#1330]
I am unable to find a demo which shows the use of this library in angularJS.
Can someone please point or just confirm if it will work?
Thanks

**Comment by kryalama** [comment]
Here is a link to AI Angular Demo
https://github.com/dmnk/application-insights-angular-demo

**Comment by vaibhavahuja** [comment]
> Here is a link to AI Angular Demo
> https://github.com/dmnk/application-insights-angular-demo

Angular and AngularJs are different, that is why I asked 
Do you have an idea about angularjs?

**Comment by MSNev** [comment]
AngularJS is basically Angular v1, which is primarily a JS framework. 
Yes, Application Insights will work with Angular V1 (JS).
Things to not if you are building a SPA application then by default it won't (necessarily) automatically wire up to the router, however. if you are updating the browser URL using '#' based changes to support the browser back support functionality AND the browser your app is running in supports the history / location API then it will listen and handle that.
And I suspect error handling won't automatically work either -- you will need to call the trackException() from you angular error handler.

**Comment by vaibhavahuja** [comment]
okay thanks

**Comment by vaibhavahuja** [comment]
@MSNev error handling is not working automatcally, and I am unable to call trackException() from my angular error handler since the way I am initializing Application Insghts is by using a snippet.
In the index.html file, I have initialized the snippet, since I cannot use `import` or `require` in Angular JS
When I throw a new error in any of the .html files it gets logged, `throw new Error("message")
but if I do the same thing using some js file (any controller or module) it does not get logged.

What should I do?

**Comment by markwolff** [comment]
AngularJS, or your app might have its own global error handler which is swallowing the errors before they reach `window.onerror`. You can call `trackException` from anywhere in your app via `window.appnsights.trackException(...)`

**Comment by MSNev** [comment]
As mark says, you will need to add your own exception handler as by default AngularJS captures exceptions and as appInsights is registered as a global variable reference as above.
Example exception handler
https://www.tutorialsteacher.com/angularjs/angularjs-exception-handling

**Comment by vaibhavahuja** [comment]
I did that and now I can access the appInsights object
Thanks @markwolff @MSNev
