### ISSUE TITLE
SpeedIndex vs browserTimings totalDuration

### ISSUE THREAD

**Issue by Romiko** [microsoft/ApplicationInsights-JS#1341]
Hi,

I am currently generating Service Level Objectives off browserTimings, however I am finding that browserTimings totalDuration is longer than when the visible portion of the page loads. 

For a service level objective where 99% of users can use the visible portion of the page in under 5s, I think we require a new metric.
Speed Index is the ideal solution.

The Speed Index is the average time at which visible parts of the page are displayed.  It is expressed in milliseconds and dependent on size of the view port.

The Speed Index metric was added to WebPagetest in April, 2012 and measures how quickly the page contents are visually populated (where lower numbers are better).  It is particularly useful for comparing experiences of pages against each other (before/after optimizing, my site vs competitor, etc) and should be used in combination with the other metrics (load time, start render, etc) to better understand a site's performance.

[Google Speed-Index](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index)

Is this a metric that can be added. How is browserTimings totalDuration different to speed-index?

We currently instrument to appinsights, but I am finding browserTimings to not truly portray the user experience.

**Comment by MSNev** [comment]
No, SpeedIndex is a calcuated metric based on an instrumented browser (running inside of WebPageTest) and this information is not available to the JavaScript runtime. 

While I would like to be able to include this information, it's not currently possible.

**Comment by Romiko** [comment]
Hi, Thank you for this information. We would love a solution in the metric that allows to know when the visible part of the page loaded. This is a more accurate representation to define an SLO.

for example
If browsertimings says the total time to load the webpage is 10 seconds but users can interact with it in under 4 seconds, this is acceptable performance for us.

We could use the current load time as a baseline, but in the future the load time could increase e.g. thirdparty banners etc below the fold and yet user experience (RUM) is fine. So we could get false alerts

What would you recommend?

**Comment by Romiko** [comment]
Also, what about implementing something similar to this in the appinsights js library?
[RUM SpeedIndex](https://github.com/WPO-Foundation/RUM-SpeedIndex)
