### ISSUE TITLE
[BUG] - Event Type - Dependency and Page View Not Showing All Properties 

### ISSUE THREAD

**Issue by wesley-trantham** [microsoft/ApplicationInsights-JS#1347]
**Description/Screenshot**
![image](https://user-images.githubusercontent.com/34066897/90827643-2fd2b800-e302-11ea-995d-84747359ff64.png)

**Steps to Reproduce**
Add telemetry initializer to track information for PageView and Dependencies since these are tracked automatically.

 - OS/Browser: Chome 83.0.4103.97
 - SDK Version [e.g. 22]: 2.5.7
 - How you initialized the SDK:
```
this.appInsights = new ApplicationInsights({
   config: {
     instrumentationKey,
     enableAutoRouteTracking: true, // enables SPA application tracking
},
```

```
const telemetryInitializer = (envelope) => {
  if (this.authenticatedUserName) {
    envelope.tags['ai.user.id'] = this.authenticatedUserName;
  }
  if (this.machineName) {
    envelope.tags['ai.device.machineName'] = this.machineName;
    // ajax dependencies don't track machineName
    // adding authUserId so that we can do a search on machineName for dependencies
    // hopefully authUserId isn't a property we need in the future
    envelope.tags['ai.user.authUserId'] = this.machineName;
  }
};
this.appInsights.addTelemetryInitializer(telemetryInitializer);
```

**Expected behavior**
I would like to see the machineName show up, even if it gets considered as a custom property. Also expect any property listed in [the list of context tag keys](https://github.com/microsoft/ApplicationInsights-JS/blob/88cf8edccfefd7d4bcd1657f15715076b83bf325/shared/AppInsightsCommon/src/Interfaces/Contracts/Generated/ContextTagKeys.ts) to show up. I've tested many but they don't seem to show up.

If I manually call trackPageEvent with my custom properties, they show up just fine.
I know it is at least partially working as it shows the `ai.user.authUserId` field that I'm setting.

**Additional context**
Running this code in Angular 8

**Comment by markwolff** [comment]
@wesley-trantham If you view this telemetry item in the "Analytics" view (from running a Kusto query), are you able to see these tags here? My assumption here is that we only show certain `envelope.tags` in the Details pane, and the rest are visible in the query view only.
