### ISSUE TITLE
disableAjaxTracking flag is not working

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-JS#136]
As reported [here](http://stackoverflow.com/questions/34638507/dependency-ajax-in-application-insights/35068928) `disableAjaxTracking: true` is not working as expected. Right now the only mitigation I could suggest is to use` maxAjaxCallsPerView:0`

**Comment by MaxShehovtsov** [comment]
Can't repro it for some reason

**Comment by kamilszostak** [comment]
I can't repro either. The `disableAjaxTracking` seems to be working fine. Configuration is stored in the global var: `window["appInsights"].config.disableAjaxTracking `, and if it's false than the AjaxMonitor is not initialized. 

@AlexBulankou, you said that you can repro it. Could you provide more details?

**Comment by AlexBulankou** [comment]
I definitely had a repro, but now I no longer do :( Will ask on the forum if they can help with a repro and reactivate if needed.
