### ISSUE TITLE
[BUG] Manually defined ai.location.city and ai.location.province are overriden by real geolocation data

### ISSUE THREAD

**Issue by ahelmel** [microsoft/ApplicationInsights-JS#1360]
**Description/Screenshot**

When using ApplicationINsights the tags "ai.location.city" and "ai.location.province" are overridden by real geolocation. According to the documentation the behaviour should be as follows:
```
The city of the client device. If any of Country, Province, or City is specified, those values will be preferred over geolocation of the IP address field...
```

TypesScript code:
```
    const snippet: Snippet = {
      config: {
        instrumentationKey,
      },
    };
    this.applicationInsights = this.applicationInsightsFactoryService.create(snippet);
    this.applicationInsights.loadAppInsights();
    this.applicationInsights.addTelemetryInitializer((envelope: ITelemetryItem) => {
      envelope.tags[CtxTagKeys.locationCountry] = 'Unknown';
      envelope.tags[CtxTagKeys.locationProvince] = 'Unknown';
      envelope.tags[CtxTagKeys.locationCity] = 'Unknown';
    });
```

Tracking event sent to Application Insights server:
```
{
      ...
      tags: {
        ...
        ai.device.id: "browser",
        ai.device.type: "Browser",
        ai.internal.sdkVersion: "javascript:2.5.7",
        ai.location.city: "Unknown",
        ai.location.country: "Unknown",
        ai.location.province: "Unknown",
        ...
      }
    }
```

In Azure Portal - Web UI => Application Insights => Exception, I see following:
```
- City: "The city of my real geolocation" => wrong
- State or province: "The state of my real geolocation" => wrong
- Country or region: Unknown => correct
```

 - OS/Browser: Windows 10, Chrome 85.0
 - SDK Version [e.g. 22]: 2.5.7
 - How you initialized the SDK: Via npm

**Expected behavior**

Should use given/manually defined values for "ai.location.city", "ai.location.province" and "ai.location.country" fields, in this case "Unknown": In Azure Portal - Web UI => Application Insights => Exception:
```
- City: Unknown
- State or province: Unknown
- Country or region: Unknown
```

**Comment by kryalama** [comment]
Please try the following configuration to modify the contents of telemetry
`this.applicationInsights.addTelemetryInitializer((envelope: ITelemetryItem) => {
      envelope.tags[ai.location.country] = 'Unknown';
      envelope.tags[ai.location.city] = 'Unknown';
      envelope.tags[ai.location.province] = 'Unknown';
    });`

**Comment by ahelmel** [comment]
Azure Portal 
=> Application Insights 
=> Investigate 
=> Browser activated (Server/Browser switch on the right side)
=> Exceptions
=> End-to-end transaction details (Show All) 
=> Exception Properties section
Marked green on the screenshot (right side):

![azure-portal-exception-details](https://user-images.githubusercontent.com/756820/92098289-56502300-edd9-11ea-92ea-a6898ce5cbfc.png)

**Comment by kryalama** [comment]
PFB the config I have been using in my tests:
`import { CtxTagKeys } from '@microsoft/applicationinsights-common';
import {ApplicationInsights} from '@microsoft/applicationinsights-web';
let telemetryInitializer = (envelope) => {
            envelope.tags[CtxTagKeys.locationCountry] = 'Unknown';
            envelope.tags[CtxTagKeys.locationProvince] = 'Unknown';
            envelope.tags[CtxTagKeys.locationCity] = 'Unknown';
          }
let appInsights = new ApplicationInsights({
            config: {
                instrumentationKey: instrumentationKey,
            }
        });
appInsights.loadAppInsights();
appInsights.addTelemetryInitializer(telemetryInitializer);
`
![AIExceptionSnip2](https://user-images.githubusercontent.com/66494519/92151533-27847d80-edd6-11ea-8cbf-d183cfac6c8c.png)
