### ISSUE TITLE
Question: What are the conditions necessary to get the details of xhr perf? 

### ISSUE THREAD

**Issue by thoo1** [microsoft/ApplicationInsights-JS#1362]
I'm trying out the new feature where application insights will add the window.performance timings for xhr and fetch by passing this config,
`enableAjaxPerfTracking: true`

It works, in app insights, I can see customDimensions.ajaxPerf with some properties
for example:
`{"response":"00:00:00.002","sentRequest":"00:00:00.654","duration":666.7100000195205,"perfTotal":666.7100000195205,"serverTiming":{},"transferSize":3344,"encodedBodySize":2980,"decodedBodySize":24469}`

However I was wondering where the timings for the redirect, dns lookup, connect, request, response are, as detailed here: https://github.com/microsoft/ApplicationInsights-JS/blob/d3a08d08f5d9988d79e30c0bb3e9277cb048199f/extensions/applicationinsights-dependencies-js/src/ajaxRecord.ts#L58

I'm wondering what are the conditions necessary to get this data?
The request is same origin so there shouldn't be any cross origin limitations here

I noticed there's configs for `maxAjaxPerfLookupAttempts` and `ajaxPerfLookupDelay`, do these play a role and if so how do I config them properly?

**Comment by MSNev** [comment]
Not all values will be present, if the value is undefined or zero then they are not populated

redirect - will only be set if the server responds to a XHR request with a redirect and you request is configured to follow redirects then the browser will populate these
dns lookup - Will only be set if the system needs to resolve the domain to an IP address, this depends on the domain you are connecting to, the DNS TTL and when the system last resolved the domain

The values are set as individual properties when set, and should be available in the logs.

It also depends on whether the users browser supports this API and the number of requests that have already been traced in the performance API (browsers have a max limit -- which really only affects long running SPA's or it the users stays on the page for a long period of time)

The defaults for maxAjaxPerfLookupAttempts and ajaxPerfLookupDelay should be fine, these are exposed via config to allow tweaking if your users' browsers are running on older hardware or older versions. As the performance API values are generally not available immediately after getting the response via the fetch/xhr request (so it needs to wait and retry the lookup).

**Comment by MSNev** [comment]
Closing based on no additional follow up, feel free to reopen with additional questions -- if required
