### ISSUE TITLE
[BUG] correlationHeaderExcludePatterns missing from types

### ISSUE THREAD

**Issue by southpolesteve** [microsoft/ApplicationInsights-JS#1363]
I see correlationHeaderExludePatterns was recently introduced, but it does not appear to be showing up in the types. In vscode, I get red squiggly lines when trying to use it:

![image](https://user-images.githubusercontent.com/471400/92194806-259bd800-ee31-11ea-8819-9587055f1c31.png)

 - OS/Browser: Chrome
 - SDK Version [e.g. 22]: 2.5.8
 - How you initialized the SDK:

```
const appInsights = new ApplicationInsights({
  config: {
    instrumentationKey: "foo",
    disableFetchTracking: false,
    enableCorsCorrelation: true,
    correlationHeaderExludePatterns : [/foo/]
  }
});
appInsights.loadAppInsights();
```

**Comment by kryalama** [comment]
Typo? it should be "correlationHeaderEx**c**ludePatterns"

**Comment by MSNev** [comment]
This is a type 
correlationHeaderExludePatterns should be correlationHeaderEx**c**ludePatterns

Where did you get the "correlationHeaderExludePatterns" from -- searching the current repo the correct name "correlationHeaderExcludePatterns" is used

**Comment by southpolesteve** [comment]
Doh 🤦 That is a typo. But I still see the same problem after correcting:

![image](https://user-images.githubusercontent.com/471400/92272205-bc5aaa00-eeae-11ea-9f51-e05ea62025b8.png)

**Comment by MSNev** [comment]
Yep, we only defined it on the extension config *doh!* * 2, @kryalama is going to add it to the main IConfig as well which will resolve the issue --  will be included in the next release (scheduled for end of the month).

**Comment by MSNev** [comment]
Closing as 2.5.9 is now completely deployed to NPM and all CDN ednpoints
