### ISSUE TITLE
[BUG] PerfManager and NotificationManager are not exported in AISKU

### ISSUE THREAD

**Issue by kryalama** [microsoft/ApplicationInsights-JS#1364]
PerfManager and NotificationManager are not exported in AISKU
 - OS/Browser:
 - SDK Version [e.g. 22]: 2.5.8

**Comment by MSNev** [comment]
Removed fixed label as it's not fixed yet waiting on #1366

**Comment by Saibamen** [comment]
What is AISKU?

**Comment by MSNev** [comment]
To answer your question
AISKU = Application Insights Stock Keeping Unit (SKU)

Where we have the SKU's as a default collection of components, which is what is also uploaded to the CDN as ai.2.min.js etc.

**Comment by MSNev** [comment]
Closing as 2.5.9 is now completely deployed to NPM and all CDN ednpoints
