### ISSUE TITLE
Page Load is getting tracked for other pages as same as the login page load time in AppInsights 

### ISSUE THREAD

**Issue by VasanthRavi91** [microsoft/ApplicationInsights-JS#1367]
**Description/Screenshot**

Our Application is developed using React SPA.

**Issue i am facing**
After the login , time taken to load the page has been tracked correctly in AppInsights but when I navigate to some other pages , same time has been tracked which has been traced during login. It should be depending upon the time taken to load the particular page

![image](https://user-images.githubusercontent.com/63836033/92731397-a0fe0c00-f392-11ea-93e7-66c22293be74.png)

From the screenshot you can that same page load time it's getting displayed in AppInsights

**Configuration of AppInsights:**

import { ApplicationInsights } from '@microsoft/applicationinsights-web'
import { ReactPlugin, withAITracking } from '@microsoft/applicationinsights-react-js'
import { globalHistory } from "@reach/router"

const reactPlugin = new ReactPlugin();
const ai = new ApplicationInsights({
    config: {
        instrumentationKey: dummy,
        enableAutoRouteTracking: false,
        autoTrackPageVisitTime: false,
        enableAjaxPerfTracking: true,
        isCookieUseDisabled: true,
        isStorageUseDisabled: true,
        enableRequestHeaderTracking: true,
        enableResponseHeaderTracking: true,
        extensions: [reactPlugin],
        extensionConfig: {
            [reactPlugin.identifier]: { history: globalHistory }
        }
    }
})
ai.loadAppInsights();
ai.trackPageView();
ai.trackPageViewPerformance();

export default (Component) => withAITracking(reactPlugin, Component);
export const appInsights = ai.appInsights;

**Usage in React App:**

const App = (props) => {

  return (
    <MainContainer>
      {
        props.accountInfo &&
        <ThemeContext.Provider value={themes.dark}>
        <Suspense fallback={<LoadingIndicator />}>
          <Router>
            <Route path="/" component={Home}/>
            {/* <LanguageHandler handleClick={props.handleClick} />  */}
          </Router>
        </Suspense>
      </ThemeContext.Provider>
      }
      
    </MainContainer>
  );
};
export default withAppInsights(AuthContext(App));

**Comment by kryalama** [comment]
Looks like there are  few problems with react plugin. Created a new bug #1369 for the same. As a work around please enable enableAutoRouteTracking flag to get the correct page view load times.

**Comment by VasanthRavi91** [comment]
Hi @kryalama when i enabled enableAutoRouteTracking as true, I faced similar issue displaying initial load time as 0 and then in next call it displays actual track time of the page and even when i navigate to other pages first call it show as 0 ms and then it will show the same track time as login. In order to avoid 0 ms for every page navigation i disabled enableAutoRouteTracking but the actually issue when i mentioned above it's not resolved
