### ISSUE TITLE
I am looking for telemetry related to mobile applications developed using angular/angular JS/ HTML & jquery

### ISSUE THREAD

**Issue by rajatshetty** [microsoft/ApplicationInsights-JS#1368]
I know that there is a extension in application insights for react-native which emits telemetry of the mobile environment, like os version, handset model etc.

But i did not find anything for angular or angular js or html & js kind of application.

Do you have any option how we can emit these information for mobile applications

**Comment by MSNev** [comment]
We have just published the angular js plugin to NPM as part of the last release, the sources is also located in this repo.
https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-angularplugin-js

**Comment by fknjerkz** [comment]
@MSNev the Angular package doesn't seem to have been generated with "ng generate library", which causes a bit of an issue. 
The README on the extention page doesn't reflect the one contained within the package either.

**Comment by MSNev** [comment]
@xiao-lix, @kryalama to reply and investigate

**Comment by rajatshetty** [comment]
I am looking for something more generic which can be used by any SPA

**Comment by rajatshetty** [comment]
Device information for mobile application developed in ReactJs or AngularJs or Angular usually come from the SPA framework libraries like angular/core in case of angular or react/native in case of ReactJS.

Developing a generic solution means taking a dependencies on all the SPA frameworks core libraries which is practically not a right approach of solving some problem.

On the other hand some people suggest to use window.navigator.userAgent which is not available if you are looking in mobile application, this can be used if you are using a web application in mobile browser.

One of the best solution at this point of time is to develop a extension or Plugin using application insights specifically for each of the frameworks, which is would similar to the one available here.

https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-react-native

Closing this issue for now!

Thanks for all the inputs and help
