### ISSUE TITLE
Reconfiguration of JS snippet via module import ignores settings

### ISSUE THREAD

**Issue by coonmoo** [microsoft/ApplicationInsights-JS#1370]
Previously we just used the applicationinsights-web module in our Angular application, but that didn't track any exceptions occurring before loading the Angular ApplicationInsights service.

So now we load the ApplicationInsights CDN JS snippet in the head part of our page and after bootstrapping the Angular application we re-configure ApplicationInsights with values provided from our API.

  ```
      const instance = (window as any).appInsights;
      instance.config.correlationHeaderDomains = configuration.correlationHeaderDomains;
      instance.config.enableCorsCorrelation = configuration.enableCorrelation;
      instance.addTelemetryInitializer(configuration.initializers);
```

In the head script we have `enableCorsCorrelation:false` it seems having the Angular service setting `enableCorsCorrelation=true `on the global appInsights instance seems to have no effect.
Correlation headers are missing.

Is there a proper way to provide new configuration values?

**Comment by MSNev** [comment]
Changing the configuration after initialization is not a (generally) supported scenario -- 

While it *may* (currently) work as a side effect of some plugin implementations, unless it's specifically documentation as "supported" ALL configuration should be set prior to calling initialize() on the appInsights instance.

**Comment by coonmoo** [comment]
Thanks for the fast feedback.

Is there any way to support the scenario I'm describing? We want to be able to catch client exceptions occurring prior to having application insights configuration settings available (these are tenant specific and we first need to fetch them from the API).

I also tried replacing the ApplicationInsights instance created in the head section with a new one:
`(window as any).appInsights = new ApplicationInsights({....})`

but that resulted in having e.g. ajax dependencies being tracked twice.

Can we somehow flush and dispose / unload the first instance before creating a new one?

**Comment by MSNev** [comment]
The Snippet should be handling catching all errors that occur from the point of running snippet script (i.e. any exceptions prior to snippet script won't be caught).

You should be able to set you configuration on the snippet chunk (in the cfg section) and you can add the telemetry initializer to the queue mechanism that is available by (currently) adding some code to the end of the snippet script (in the same script tag)

I have some ideas on making this a bit cleaner, but for now it's something like 
<script... the snippet block
...
cfg: { // Application Insights Configuration
    instrumentationKey: "INSTRUMENTATION_KEY"
}});
if (appInsights && appInsights.queue) {
    // Add telemetry initializer
    appInsights.queue.push(function () {
        appInsights.addTelemetryInitializer(function (envelope) {
            //Add a custom property
            envelope.data.name = 'This item passed through my telemetry initializer';
        });
    });
}
</script>

If you put the addTelemetryInitializer in a trailing script block, it very likely that the queue has already been processed and therefore the above code (the added queue function) will actually never get called.

**Comment by MSNev** [comment]
Linked to future enhancement #1427 and closing this issue
