### ISSUE TITLE
indexof is wrongly cased

### ISSUE THREAD

**Issue by ncoder** [microsoft/ApplicationInsights-JS#1374]
It should be "indexOf"

I get a "TypeError: r.indexof is not a function" on execution.

https://github.com/microsoft/ApplicationInsights-JS/blob/0af75e93f2e4e59b8bcceb7ecfb72e1efc135a7f/AISKU/src/Initialization.ts#L475

**Comment by Saibamen** [comment]
Can be closed - already released: https://github.com/microsoft/ApplicationInsights-JS/releases/tag/2.5.9

BTW @ncoder: You can easily edit single file in GitHub without even downloading source code :)

Just go to file you mendtioned https://github.com/microsoft/ApplicationInsights-JS/blob/0af75e93f2e4e59b8bcceb7ecfb72e1efc135a7f/AISKU/src/Initialization.ts#L475 and click Edit icon. If edit icon is disables, make sure, you have selected `master` branch. Then you make your changes, creates a commit and then a Pull Request from your browser.

![image](https://user-images.githubusercontent.com/905878/95424770-78dadc00-0943-11eb-929a-5fc9c7afbd95.png)

**Comment by Saibamen** [comment]
Oh, there is already documentation for this ;) 

https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/editing-files-in-your-repository

**Comment by MSNev** [comment]
Closing as 2.5.9 is now completely deployed to NPM and all CDN ednpoints
