### ISSUE TITLE
[BUG] - Fetch requests & Errors not recorded

### ISSUE THREAD

**Issue by hloughrey** [microsoft/ApplicationInsights-JS#1376]
**Description/Screenshot**
Dependencies & errors thrown during Fetch requests are not being captured within AppInsights. We use the Fetch API to make our network requests, therefore we have set `disableFetchTracking: false`, but still our fetch requests are not being recorded. To try and identify the issue a bit more we replicated the fetch request with jQuery's ajax method - these network requests were recorded. Therefore we believe there is an error with the `disableFetchTracking` flag.

**Steps to Reproduce**
Attached is a sample app which demonstrates the issue:
[Sample.html.zip](https://github.com/microsoft/ApplicationInsights-JS/files/5230797/Sample.html.zip)

***OS/Browser:***
- Firefox: 80.0.1
- Chrome: 85.0.4183.102
- Safari: 13.1.2 

**Expected behaviour**
Fetch requests should be recorded in the same way as ajax requests, with any thrown Errors being captured within AppInsights.

**Comment by georgewilde** [comment]
I am also having this issue.

**Comment by MSNev** [comment]
Are you talking about exceptions during the "then" processing or "catch" events?

If you want to track error thrown via catch events then enabling "enableUnhandledPromiseRejectionTracking" *should* handle these as exceptions (if the browser runtime supports the hook).

**Comment by MSNev** [comment]
@hloughrey, @georgewilde did the above help?

**Comment by hloughrey** [comment]
@MSNev - apologies, we were just finishing off some testing around this. Yes adding this config option seems to have done the trick. Appreciate it. I'll close this ticket.
