### ISSUE TITLE
[BUG] Session storage buffers being initialized though configured not to use

### ISSUE THREAD

**Issue by johansuperstar** [microsoft/ApplicationInsights-JS#1377]
**Description/Screenshot**
The session storage entries AI_sentBuffer and AI_buffer are being initialized even though isStorageUseDisabled is set to true and enableSessionStorageBuffer is set to false. It doesn't have any negative effects for us but the ePrivacy team are wishing that they would not be created.

**Steps to Reproduce**

 - OS/Browser: Tested in Chrome 85.0.4183.102 and Firefox 80.0.1 on Windows 10
 - SDK Version [e.g. 22]: @microsoft/applicationinsights-web 2.3.1
 - How you initialized the SDK:
```
import { ApplicationInsights } from '@microsoft/applicationinsights-web';

const appInsights = new ApplicationInsights({ 
       config: {
		instrumentationKey: instrumentationKey,
		isCookieUseDisabled: true,
		isStorageUseDisabled: true,
		enableSessionStorageBuffer: false
	} 
});
appInsights.loadAppInsights();
```

**Expected behavior**
Session storage entries would not be created.

**Comment by johansuperstar** [comment]
Great! Is there any coming release planned?

**Comment by MSNev** [comment]
Yep, we are normally establishing a monthly cadence for issues. So the next version should be available early (1st or beginning of  2nd week) next month (Oct, 2020)

**Comment by MSNev** [comment]
Closing as 2.5.9 is now completely deployed to NPM and all CDN ednpoints
