### ISSUE TITLE
Log verb (GET/POST) as part of AJAX name

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/ApplicationInsights-JS#138]
The new ajax dependency tracking is awesome, but the dependency naming convention could be improved.  Right now it looks like it is always the hostname of the AJAX request.

![image](https://cloud.githubusercontent.com/assets/4112046/13485845/482f6f70-e0d1-11e5-9ecf-7b26bc0e370d.png)

I feel like SQL dependencies, for example, have a much better naming convention, which is:
SQL: ServerName | DatabaseName | StoredProcedureName

The reporting on things like dependencies with performance problems is much more useful when the name has more context.  It also helps a lot when browsing search results.  Perhaps you could add the HTTP method and the relative URL to the dependency name?

**Comment by madeleinefletcher** [comment]
Thanks for the feedback! We don't currently collect the HTTP verb, but we do have the relative URL available. I will open a bug on our UI to add the relative path to the search results view so the difference between the calls is clearer.

**Comment by SergeyKanzhelev** [comment]
We need to do the same in full framework when using Profiler API to collect dependencies. This will make naming of dependency aligned with the naming of corresponding request. @abaranch can you please track it?

**Comment by abaranch** [comment]
Sergey, if you are talking about path than I expect UI will work both for JS SDK dependencies and for Web SDK dependencies. If you are talking about adding the verb than yes: we need a separate issues for JS and Web SDKs. For Web: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/54

**Comment by SergeyKanzhelev** [comment]
I was talking about VERB in a name. I'm sure `POST` dependencies typically longer than `GET` dependencies

**Comment by AlexBulankou** [comment]
I'm renaming this issue to "Add verb to dependency name". To address the other part of @gregjhogan's question we opened an Ibiza UI bug to add full url (CommandName) to search results for dependencies.

**Comment by kamilszostak** [comment]
Fixed in #192 . 

The verb isn't exposed in the Azure Portal UI yet, but it is accessible through Application Analytic.
