### ISSUE TITLE
[BUG] NPM package for @microsoft/applicationinsights-angularplugin-js does not have a dist folder

### ISSUE THREAD

**Issue by OumarLM** [microsoft/ApplicationInsights-JS#1381]
**Description/Screenshot**
The @microsoft/applicationinsights-angularplugin-js folder in `node-modules` does not have a `dist`
 folder
**Steps to Reproduce**
run npm install @microsoft/applicationinsights-angularplugin-js
and check node_modules. 

 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**
not get : `Cannot find module '@microsoft/applicationinsights-angularplugin-js' or its corresponding type declarations.`
**Additional context**

**Comment by MSNev** [comment]
Looks like the official build / publish pipeline is not building the angular plugin before packaging -- sorry

**Comment by OumarLM** [comment]
Awesome!!!

**Comment by MSNev** [comment]
Closing as 2.5.9 is now completely deployed to NPM and all CDN ednpoints
