### ISSUE TITLE
No way to suppress cross-domain script errors from logging?

### ISSUE THREAD

**Issue by jasmcc** [microsoft/ApplicationInsights-JS#1383]
We run advertising on our site, and there is a large number of badly behaved ads in some browsers.  As a result, we are drowning in a large volume of these errors:

"Script error: The browser's same-origin policy prevents us from getting the details of this exception. Consider using the 'crossorigin' attribute."

This is great in general, but unfortunately it's not helping us anymore as we've caught all the obvious problems causing it, and now it's just unhelpfully logging a zillion errors a day.  We know, we know, people are bad at writing ad javascript.

I've tried suppressing this exception like we do our other exceptions, as seen here:
https://zone.msn.com/gameplayer/gameplayerHTML.aspx?game=msmahjong&instance=default

Unfortunately, it doesn't seem to work.  Looking at the AI unminified source, this seems to be because there's a special case where it's send with a different message:
https://az416426.vo.msecnd.net/scripts/b/ai.2.js

Am I misinterpreting this, and we actually suppress from being sent in some way?

**Comment by MSNev** [comment]
So exactly how are suppressing exceptions (without decoding all of your source on the link provided).

At the end of the day both exceptions and cors exceptions eventually call and following the track path.
Send Cors: https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts#L729
sendExceptionInternal: https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts#L399

And in both cases they are tagged as exceptions...
So depending on how you are suppressing will depend on any guidance we can provide.

In the short term the simplest way would be to add you own window.onerror handler (before the snippet / initialization of app insights) detect the Cors situation and just return true (telling us that you have handled the exception and we wont process it).
One trick I've done on a previous team was to detect the "source" of the exception (the url) and if it's not in a list of "supported" domains (main page and cdn's) then just throttle reporting of the exception (to only 1) and for consistent bad actors add code to the page to complete drop the details.

**Comment by jasmcc** [comment]
On page ready we call this:
        if(appInsights && appInsights.queue){
            appInsights.queue.push(function() {
                appInsights.addTelemetryInitializer(zoneSuppressExceptions);
            });
        } else if (appInsights && appInsights.addTelemetryInitializer) {
            appInsights.addTelemetryInitializer(zoneSuppressExceptions);
        }

In this based on event type & consent we return false to not log it:
        var zoneSuppressExceptions = function(envelope) {
            if (envelope.baseType === 'ExceptionData' && envelope.baseData.exceptions) {

I'll take a look at your suggestions, thanks.

**Comment by MSNev** [comment]
Just a minor point, you should also check the length of the queue as if it's empty it's already been processed and adding anything to it won't actually get processed.
So changing the following will probably help and I'd also do this well before page ready

if(appInsights && appInsights.queue && appInsights.queue.length > 0) {

Also all exceptions are tagged with the data type, so just changing your if check to following would catch both normal exceptions and CORS.
if (envelope.baseType === 'ExceptionData') {

**Comment by jasmcc** [comment]
Following up here, thanks for the advice, it worked like a charm.  For anyone else's reference:
* CORS exceptions show up as baseType 'ExceptionData', with no exceptions property.  Here's how we're catching them:
            if (envelope.baseType === 'ExceptionData') {
                if (typeof (envelope.baseData.exceptions) === 'undefined' &&
                    envelope.baseData.message &&
                    envelope.baseData.message.indexOf('same-origin policy prevents us from getting the details of this exception') >= 0)
                {
                        // Log at 1%.
                        var samplingPercentage = 0.01;
                        var samplingRandom = Math.random();

                        return samplingRandom < samplingPercentage;
                }
