### ISSUE TITLE
[BUG] Angular Plugin: Unwanted dialog. The code creates unwanted confirmation dialog

### ISSUE THREAD

**Issue by OumarLM** [microsoft/ApplicationInsights-JS#1387]
**Description/Screenshot**
Unwanted dialog. The code below creates unwanted confirmation dialog. Using `ngOnDestroy` alone doesn't work, neither does using a custom method with the event listener (The `_mountTimestamp` would have been destroy by then. )
``` 
@HostListener('window:beforeunload')
  ngOnDestroy() {
    this.angularPluginService.trackMetric();
  } 
```
**Steps to Reproduce**
Using the aforementioned code in any component. 
 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**
Being able to Use `trackMetric` without the confirmation dialog popping up. 
**Additional context**

**Comment by xiao-lix** [comment]
@OumarLM can you please explain more what do you mean by "unwanted dialog"? Do you see similar payload on your network tab? 
![image](https://user-images.githubusercontent.com/20292261/94216342-ff97af80-fe93-11ea-9507-67b8faa273c7.png)

**Comment by OumarLM** [comment]
@xiao-lix, yes i see a similar payload. I meant using `@HostListener('window:beforeunload')` causes a confirm dialog whenever refreshing or navigating away from the page. and the metric seems not to be consistent without `@HostListener('window:beforeunload')`.

**Comment by xiao-lix** [comment]
Due to inappropriate implementation, the track metrics feature is taken off from the new released version of [angular plugin](https://github.com/microsoft/applicationinsights-angularplugin-js), hence close this issue.
