### ISSUE TITLE
IConfig.appUserId appears to be unused?

### ISSUE THREAD

**Issue by AtOMiCNebula** [Microsoft/ApplicationInsights-JS#139]
Not sure if I'm missing something subtle here, but while looking at some of the API docs and the code itself, ```IConfig.appUserId``` appears to be set in a few places, but never actually read.  I had assumed, due to its proximity to ```IConfig.accountId```, that it was related to ```AppInsights.setAuthenticatedUserContext```, but it appears to not be the case.

If this is indeed dead code, I'd be happy to submit a PR to clean it up.  If it's not dead code, I'm prepared to be enlightened.  Thanks either way! :)

**Comment by kamilszostak** [comment]
It looks like you can set "appUserId" in the snippet header but this field is not included in a telemetry. 

@MaxShehovtsov do you know why we have 'appUserId" field? Is it safe to remove it? 

```
    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){ ....  }({
            instrumentationKey: "<your-key>",
            appUserId: "customUserId"
        });
        (....)
    </script>
```

**Comment by abaranch** [comment]
Per my understanding we had old API where userId and accountId could be set in the snippet. setAuthenticatedUserContext was added later. Account id still can be used and was preserved for backward compatibility but user id is not used now from anywhere. So it should be safe to remove.

**Comment by kamilszostak** [comment]
PR: https://github.com/Microsoft/ApplicationInsights-JS/pull/142
