### ISSUE TITLE
[BUG] enableAutoRouteTracking should also update the Operation Name with the hashroute

### ISSUE THREAD

**Issue by markwolff** [microsoft/ApplicationInsights-JS#1393]
**Description/Screenshot**
`enableAutoRouteTracking: true` should update `ai.operation.name` to include the hashroute in the pathname

https://github.com/microsoft/ApplicationInsights-JS/blob/ae71ebf806da82e149b0af60f00d70b2c1d3e3f0/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts#L650-L653

**Comment by xiao-lix** [comment]
Fixed with #1510

**Comment by MSNev** [comment]
v2.6.2 is now fully deployed
