### ISSUE TITLE
[BUG] React Native using appinsights.trackException causes cycle issues for reactnative

### ISSUE THREAD

**Issue by keilwastaken** [microsoft/ApplicationInsights-JS#1394]
**Description/Screenshot**
![image](https://user-images.githubusercontent.com/68410905/94964585-dcca5400-04ae-11eb-8606-8dd2a952dcb2.png)
![image](https://user-images.githubusercontent.com/68410905/94964610-e3f16200-04ae-11eb-8a86-64d77437e27f.png)

**Steps to Reproduce**
 add appInsights.trackException anywhere in your application and you will see this cycle issue
 - How you initialized the SDK:
![image](https://user-images.githubusercontent.com/68410905/94964843-421e4500-04af-11eb-8efd-cbdd81e8d445.png)

**Expected behavior**
no cycle issues and the ability to use appInsights without any unnecessary cycle issues 
**Additional context**
I have tested this this out on application start up and various other places and have received this error. I have also removed the AppInsights code to verify that it is the root source of this problem

**Comment by MSNev** [comment]
What version of the SDK are you using?
We added some detection for the whatwg fetch polyfill used by reactnative in version v2.5.2 (March, 2020), so from this version onwards it *should* not be attempting to instrument the fetch API which will cause a never ending sending of fetch dependency requests.
