### ISSUE TITLE
[BUG] autoTrackPageVisitTime causing tracking to be sent too often

### ISSUE THREAD

**Issue by danielbecroft** [microsoft/ApplicationInsights-JS#1406]
**Description/Screenshot**
Enabling the `autoTrackPageVisitTime` or `enableAutoRouteTracking` options causes a `/track` call to be made each time an event is raised. For example, if `autoTrackPageVisitTime = true`, then every time the page changes, a `/track` call is getting sent to record the time on that page. 

**Steps to Reproduce**

 - OS/Browser: Windows/Chrome
 - SDK Version [e.g. 22]: 2.5.5
 - How you initialized the SDK:
``` javascript
private appInsights: ApplicationInsights = new ApplicationInsights({
    config: {
      instrumentationKey: environment.appInsights.instrumentationKey,
      distributedTracingMode: DistributedTracingModes.W3C,
      autoTrackPageVisitTime: true,
      disableFetchTracking: false,
      enableAutoRouteTracking: true,
      enableAjaxErrorStatusText: true,
      enableCorsCorrelation: true
    }
  });
```

**Expected behavior**
The data tracked using the `enableAutoRouteTracking` or `autoTrackPageVisitTime` should be batched and sent along with the remaining telemetry.

**Additional context**

**Comment by MSNev** [comment]
Looking over the code, what you are asking for is exactly what happens.

That is, the code internally calls track() which then adds this event to the internal batch and based on the maxBatchInterval (defaults to 15 seconds) and/or maxBatchSizeInBytes (defaults to 100kb) the batched events would eventually get sent.

The "timer" is based on when the "first" event is batched and not the last.

Can you provide more details and perhaps a fiddler trace showing when and events are sent etc. You may need to manual edit the trace to remove and private stuff that you don't want shared publicly.

**Comment by danielbecroft** [comment]
Thanks @MSNev . I'll try and get a redacted example to show. What we're seeing in Chrome Network tab, at least is:

```
/track
<click menu1>
/track
<click menu2>
/track
<click menu3>
/track
```

These are happening immediately, appearing to not have any batching.

**Comment by danielbecroft** [comment]
Hey @MSNev . Between clicking of two components, I am getting two `/track` messages getting posted:

```json
[
  {
    "time": "2020-10-16T00:18:35.140Z",
    "iKey": "<instrumentationKey>",
    "name": "Microsoft.ApplicationInsights.<instrumentationKey>.Pageview",
    "tags": {
      "ai.user.id": "GHCf/WnS5bu8NVc2B2Ot5o",
      "ai.session.id": "4XiDl4e0a4e3+GIda7j5GM",
      "ai.device.id": "browser",
      "ai.device.type": "Browser",
      "ai.operation.name": "/second-component",
      "ai.operation.id": "d6f73d7b94d44d4abfc53691e5b40d99",
      "ai.internal.sdkVersion": "javascript:2.5.9",
      "ai.internal.snippet": "-"
    },
    "data": {
      "baseType": "PageviewData",
      "baseData": {
        "ver": 2,
        "name": "/second-component",
        "url": "http://localhost:4200/second-component",
        "duration": "00:00:00.009",
        "properties": {
          "refUri": "",
          "duration": "9"
        },
        "measurements": {},
        "id": "d6f73d7b94d44d4abfc53691e5b40d99"
      }
    }
  },
  {
    "time": "2020-10-16T00:18:35.143Z",
    "iKey": "<instrumentationKey>",
    "name": "Microsoft.ApplicationInsights.<instrumentationKey>.Metric",
    "tags": {
      "ai.user.id": "GHCf/WnS5bu8NVc2B2Ot5o",
      "ai.session.id": "4XiDl4e0a4e3+GIda7j5GM",
      "ai.device.id": "browser",
      "ai.device.type": "Browser",
      "ai.operation.name": "/second-component",
      "ai.operation.id": "d6f73d7b94d44d4abfc53691e5b40d99",
      "ai.internal.sdkVersion": "javascript:2.5.9"
    },
    "data": {
      "baseType": "MetricData",
      "baseData": {
        "ver": 2,
        "metrics": [
          {
            "name": "PageVisitTime",
            "kind": 0,
            "value": 626,
            "count": 1,
            "min": 626,
            "max": 626
          }
        ],
        "properties": {
          "PageName": "ApplicationInsightTest",
          "PageUrl": "http://localhost:4200/first-component"
        }
      }
    }
  },
  {
    "time": "2020-10-16T00:18:35.637Z",
    "iKey": "<instrumentationKey>",
    "name": "Microsoft.ApplicationInsights.<instrumentationKey>.Pageview",
    "tags": {
      "ai.user.id": "GHCf/WnS5bu8NVc2B2Ot5o",
      "ai.session.id": "4XiDl4e0a4e3+GIda7j5GM",
      "ai.device.id": "browser",
      "ai.device.type": "Browser",
      "ai.operation.name": "/second-component",
      "ai.operation.id": "d6f73d7b94d44d4abfc53691e5b40d99",
      "ai.internal.sdkVersion": "javascript:2.5.9",
      "ai.internal.snippet": "-"
    },
    "data": {
      "baseType": "PageviewData",
      "baseData": {
        "ver": 2,
        "name": "ApplicationInsightTest",
        "url": "http://localhost:4200/second-component",
        "duration": "00:00:00.000",
        "properties": {
          "refUri": "http://localhost:4200/first-component"
        },
        "measurements": {
          "duration": 0
        },
        "id": "d6f73d7b94d44d4abfc53691e5b40d99"
      }
    }
  }
]
```

and the second request is:

```json
[
  {
    "time": "2020-10-16T00:18:35.140Z",
    "iKey": "<instrumentationKey>",
    "name": "Microsoft.ApplicationInsights.<instrumentationKey>.Pageview",
    "tags": {
      "ai.user.id": "GHCf/WnS5bu8NVc2B2Ot5o",
      "ai.session.id": "4XiDl4e0a4e3+GIda7j5GM",
      "ai.device.id": "browser",
      "ai.device.type": "Browser",
      "ai.operation.name": "/second-component",
      "ai.operation.id": "d6f73d7b94d44d4abfc53691e5b40d99",
      "ai.internal.sdkVersion": "javascript:2.5.9",
      "ai.internal.snippet": "-"
    },
    "data": {
      "baseType": "PageviewData",
      "baseData": {
        "ver": 2,
        "name": "/second-component",
        "url": "http://localhost:4200/second-component",
        "duration": "00:00:00.009",
        "properties": {
          "refUri": "",
          "duration": "9"
        },
        "measurements": {},
        "id": "d6f73d7b94d44d4abfc53691e5b40d99"
      }
    }
  },
  {
    "time": "2020-10-16T00:18:35.143Z",
    "iKey": "<instrumentationKey>",
    "name": "Microsoft.ApplicationInsights.<instrumentationKey>.Metric",
    "tags": {
      "ai.user.id": "GHCf/WnS5bu8NVc2B2Ot5o",
      "ai.session.id": "4XiDl4e0a4e3+GIda7j5GM",
      "ai.device.id": "browser",
      "ai.device.type": "Browser",
      "ai.operation.name": "/second-component",
      "ai.operation.id": "d6f73d7b94d44d4abfc53691e5b40d99",
      "ai.internal.sdkVersion": "javascript:2.5.9"
    },
    "data": {
      "baseType": "MetricData",
      "baseData": {
        "ver": 2,
        "metrics": [
          {
            "name": "PageVisitTime",
            "kind": 0,
            "value": 626,
            "count": 1,
            "min": 626,
            "max": 626
          }
        ],
        "properties": {
          "PageName": "ApplicationInsightTest",
          "PageUrl": "http://localhost:4200/first-component"
        }
      }
    }
  },
  {
    "time": "2020-10-16T00:18:35.637Z",
    "iKey": "<instrumentationKey>",
    "name": "Microsoft.ApplicationInsights.<instrumentationKey>.Pageview",
    "tags": {
      "ai.user.id": "GHCf/WnS5bu8NVc2B2Ot5o",
      "ai.session.id": "4XiDl4e0a4e3+GIda7j5GM",
      "ai.device.id": "browser",
      "ai.device.type": "Browser",
      "ai.operation.name": "/second-component",
      "ai.operation.id": "d6f73d7b94d44d4abfc53691e5b40d99",
      "ai.internal.sdkVersion": "javascript:2.5.9",
      "ai.internal.snippet": "-"
    },
    "data": {
      "baseType": "PageviewData",
      "baseData": {
        "ver": 2,
        "name": "ApplicationInsightTest",
        "url": "http://localhost:4200/second-component",
        "duration": "00:00:00.000",
        "properties": {
          "refUri": "http://localhost:4200/first-component"
        },
        "measurements": {
          "duration": 0
        },
        "id": "d6f73d7b94d44d4abfc53691e5b40d99"
      }
    }
  }
]
```

**Comment by danielbecroft** [comment]
An example site illustrating the problem is available here:

https://danielbecroft.github.io/application-insights-example/second-component

**Comment by MSNev** [comment]
@danielbecroft the link for the sample site appears to be locked down -- I'm getting a 404.

Looking at the url / refUri (at least for the second one) it looks like a full page navigation is occurring which will cause the unload event to cause any events to be flushed asap (so the event doesn't get lost) for a SPA it's expected to have hash based navigation (which doesn't cause the browser to trigger the unload event etc)

**Comment by danielbecroft** [comment]
Sorry @MSNev , I accidentally linked to the component route, not the application root. I've fixed the URL.

We'll try using the hashed-route navigiation model, and report back with our testing results.

**Comment by danielbecroft** [comment]
We've tried to move to hash-based navigation / routing, and the problem still persists. I've updated the [example application](https://danielbecroft.github.io/application-insights-example/) (above) to use the hash-based routing. The code for the app is [here](https://github.com/danielbecroft/application-insights-example).

We've also tried disabling the "flush" (via the `disableFlushOnBeforeLoad` configuration item), but the problem still persists.

Not sure if there's anything else we can try.

**Comment by MSNev** [comment]
@danielbecroft Thanks for the sample, after debugging through this I eventually found the "why" the data is being sent.

Basically, this is currently by design, deep down in the PageViewManager it has this comment and in your case the situation is #4 and it's this if block that is being called (resulting in the call to _flushChannels) https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewManager.ts#L134

     * Currently supported cases:
     * 1) (default case) track page view called with default parameters, overridePageViewDuration = false. Page view is sent with page view performance when navigation timing data is available.
     *    a. If navigation timing is not supported then page view is sent right away with undefined duration. Page view performance is not sent.
     * 2) overridePageViewDuration = true, custom duration provided. Custom duration is used, page view sends right away.
     * 3) overridePageViewDuration = true, custom duration NOT provided. Page view is sent right away, duration is time spent from page load till now (or undefined if navigation timing is not supported). 
     * 4) overridePageViewDuration = false, custom duration is provided. Page view is sent right away with custom duration. 

Can this call be delay -- probably, I'll need to chat with some of the other members on the team. But my initial thought is that we should be able to expose a config setting (of some kind) to disable the auto flushing -- unless I'm missing some other subtle issue that caused this to be added initially.

**Comment by danielbecroft** [comment]
Hi @MSNev Is there anything else I need to provide for this? Is there a known workaround or similar that we could apply?

**Comment by MSNev** [comment]
Hi @danielbecroft, sorry for going dark on this, unfortunately this dropped off my radar because of workload and some shuffling around within the team. Specifically the person I was going to ask about the above history.

I've assign this to myself so that it doesn't drop off again (as I scan my allocated items regularly), I'll try and contact some other members on the options. I may end up allocating to someone else after we determine whether adding a config setting is a path forward.

Cheers

**Comment by red-man** [comment]
I have the same issue as @danielbecroft.  I have an existing angular 11 app and am not able to switch to hash based routing since that would break deep linking from other applications.  But just to test things locally I turned on useHash and still see multiple posts to /track on every route change, with no delay.  A configurable delay would help side step the issue for me and help prioritize bandwith for my app data when there is a route change.  But getting it to work with the buffer setting would be ideal.

**Comment by MSNev** [comment]
Still reviewing

**Comment by Karlie-777** [comment]
Hi @danielbecroft @red-man, sorry for late reply. @MSNev and I had a discussion with the team and we think current design still has its advantage. when `autoTrackPageVisitTime` or `enableAutoRouteTracking` is enabled with Single-Page App, a `pageView` will be triggered when a new component is rendered. And for `pageView` data (one of the most important data), it has to be sent right away since there are chances that batch-send may fail due to factors we can not control. Therefore, the frequent `/track` requests is by design.
