### ISSUE TITLE
[BUG] - License file link is invalid

### ISSUE THREAD

**Issue by jeffadavidson** [microsoft/ApplicationInsights-JS#1411]
The link in the license file(http://go.microsoft.com/fwlink/?LinkID=510709) is invalid. Where ever that link use to lead no longer exists. 

Happened sometime between March and now. Suggest just putting the standard MIT license text in there

**Comment by MSNev** [comment]
Thank you for reporting, the owners of this link appear to be no longer valid, we have started the process of claiming ownership so that we can fix this issue.

**Comment by ramthi** [comment]
This has been fixed now.
