### ISSUE TITLE
[BUG] Exceptions logged as console errors aren't appearing in AppInsights

### ISSUE THREAD

**Issue by bernardoflynn** [microsoft/ApplicationInsights-JS#1412]
**Description/Screenshot**

**Steps to Reproduce**
Open a site and page that has an exception and error appears in console
Go to App Insights. Neither the exception nor the console log appears

 - OS/Browser: Chrome
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:
HTML snippet

**Expected behavior**
All exceptions and console errors are automatically pushed to App Insights.

**Additional context**

**Comment by MSNev** [comment]
@bernardoflynn Can you please supply some more information, as per requested in the template.

App Insights hooks the windows.onerror to capture and report exceptions, so depending on how you are using the SDK and when it gets initialized etc any exceptions that occur before the snippet (if you are using that) is run (<script/> on the page) or when the SDK is initialized will not be captured.

**Comment by bernardoflynn** [comment]
Hi @MSNev thanks for replying. The snippet is literally the first thing that loads. However we never see any errors in AppInsights that are definitely showing up in the console as errors. In fact all we see are user counts and page visits, etc. No errors.
e.g. in the console in the browser we see these:
TypeError: Cannot read property '0' of undefined
    at I (_app-80d35823368a6bf2ad4d.js:1)
    at qi (framework.53cfa66f9846f4090096.js:1)
    at yo (framework.53cfa66f9846f4090096.js:1)
    at su (framework.53cfa66f9846f4090096.js:1)
    at uu (framework.53cfa66f9846f4090096.js:1)
    at eu (framework.53cfa66f9846f4090096.js:1)
    at framework.53cfa66f9846f4090096.js:1
    at t.unstable_runWithPriority (framework.53cfa66f9846f4090096.js:1)
    at jl (framework.53cfa66f9846f4090096.js:1)
    at Kl (framework.53cfa66f9846f4090096.js:1)

However there are no errors reported in App Insights.

**Comment by MSNev** [comment]
This error sounds familiar.

Can you check which version of the snippet that you are using, we had to recently update it for a issue around exception handling for catching errors during pre-initialization. Current version is 5.

Look for the "sv" variable in the snippet content.

This is a sample of where to find the snippet version
m={initialize:!0,queue:[],**sv:"5"**,version:2,config:d};

**Comment by MSNev** [comment]
Closing, assuming this issue was because of a bug in prior versions of the snippet.
Please comment again if this assumption is incorrect.
