### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by fab7jj** [microsoft/ApplicationInsights-JS#1413]
I am using the reactjs plugin with react hooks, first of all the documentation on making use of such plugin with functional components (react hooks) is very poor, secondly when I try to use any of the hooks that this package provides, like for example: `useAppInsightsContext()` by using it as follows:

```
import { useAppInsightsContext } from '@microsoft/applicationinsights-react-js';

function BaseLayout(props) {

    const reactPlugin = useAppInsightsContext();

    return (
    );
}

export default BaseLayout;
```

I get the following error: `Invalid hook call. Hooks can only be called inside of the body of a function component.` If I copy the code of such hooks in my project then I can use them just fine. 

Anyone has encountered such issue please?

Maybe @aaronpowell can you help please?

**Steps to Reproduce**

 - Install the reactjs plugin
 - Import a hook
 - Make use of it

**Expected behavior**

I should be able to make use of the imported hook

**Comment by aaronpowell** [comment]
Are you able to provide a sample repo with the error you're experiencing, I haven't been able to reproduce it.

Have you set up the AppInsights connection as per https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin#basic-usage first?

Here's a basic implementation using React context: https://codesandbox.io/s/intelligent-drake-r1cvz?file=/src/AppInsights.js

**Comment by aaronpowell** [comment]
Can you compare your approach with the documented approach - https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin#using-react-hooks
