### ISSUE TITLE
Typo in 'disableInstrumentaionKeyValidation' config property.

### ISSUE THREAD

**Issue by rarmenia** [microsoft/ApplicationInsights-JS#1433]
In the current release the config property 'disableInstrumentaionKeyValidation' in the IConfiguration file is containing a typeo.

As stated in title and this section it is currently 

`disableInstrumentaionKeyValidation`

Where I believe it should be

`disableInstrumentationKeyValidation`

**Comment by MSNev** [comment]
This was fixed and included in 2.5.11
