### ISSUE TITLE
Ability to specify cookie Path so that AI works behind App Gateway

### ISSUE THREAD

**Issue by 01binary** [microsoft/ApplicationInsights-JS#1434]
Currently when creating cookies, the cookie path is hard-coded to `/`. This breaks cookies when an application using AI Client SDK is placed behind a reverse proxy such as App Gateway product in Azure. Applications behind the reverse proxy are available on sub-paths like /app1, /app2, and so on. Because AI cookies have path as /, they are shared between all apps. This results in the app that was refreshed last overwriting the session cookie for all other apps. That means AI session for the app that gets requested from server the most ends up with all the AI logs, and all other apps have their sessions deleted.

Possible solutions:
1. Do not set cookie path at all, browser will choose the current path to be the default. If AI SDK is initialized by /app1, cookie path will be set to /app1 by the browser, then app1 will track all of its AI cookies without other apps seeing and overwriting them.
2. Set cookie path to "", the behavior is identical to #1
3. Let cookie path be configurable for all cookies. You already have a setting for cookie domain, so you would just need to add one more setting for cookie path

Alternatives I considered:
1. Create our own fork of AI Client SDK and maintain it separately. We can choose to make #1, #2, or #3 change there and push it to our package server, then have everyone in the company use that. Obviously there are some maintenance effort issues with that
2. Implement #3 for this repo and submit it as a pull request. It could add a setting for cookie path and have it be '/' by default for backward compatibility. If set to null, cookie path will not be set (#1). That way the solution is both backward compatible and simple.
3. Write additional code and package it for our applications, that will initialize AI SDK with cookies disabled, and then create our own cookies. That has maintenance effort issues just like alternative #1 even though we avoid modifying AI Client SDK.

**Comment by MSNev** [comment]
I'm currently working #1091 which is refactoring the cookie handling, I'll add your suggestions to the changes as it deprecates the global cookie functions in preference for Application Instance versions. So merging your changes now would cause issues -- the cookiePath config though is (I think at this point) spot on.

**Comment by 01binary** [comment]
Wow, thanks @MSNev that's really nice! I will close my PR.

Do you have a +/- 1 month ETA on when your changes are released?

**Comment by MSNev** [comment]
I'm *hoping* to finalize the changes in the next 2 weeks (before holidays) and to have the PR's checked in for the release @ the end of Jan 21, so it will *hopefully* be available early Feb '21 (first or second week) -- all going well.

**Comment by 01binary** [comment]
Thank you for including this @MSNev, I am monitoring this release.

**Comment by MSNev** [comment]
I missed the Jan timeframe, and I'm actively working on bringing over the portions in the next few weeks. So currently targeting to start releasing as part of the end of Feb. i.e. the v2.6.0 milestone is the release.

**Comment by MSNev** [comment]
Note: The due date I put on the milestone is the date when it's fully deployed to the public CDN, the NPM packages are usually available at least 3ish days before the due date.

**Comment by 01binary** [comment]
I know this stuff takes a really long time, I didn't mean that I'm trying to rush anything, just that I didn't forget & appreciate the effort

**Comment by MSNev** [comment]
v2.6.0 is now fully deployed to all CDN endpoints
