### ISSUE TITLE
Is there a way to pass a session id to application insights without using this library?

### ISSUE THREAD

**Issue by iensu** [microsoft/ApplicationInsights-JS#1438]
**Is your feature request related to a problem? Please describe.**
We use app insights for our microservices and that works great, and we would love to be able to pass a session ID with our client requests without pulling in this library. The reason why we want to avoid using this library is that the size clocks in at 463kB which increases our final bundle size with over a a third. We've also tried @microsoft/applicationinsights-web-basic pointed to in the documentation, but its is almost 300kB, so we can't use that either. 

The one thing we want is to be able to assign session ids to requests coming from our client to the backend. Is there a way to do this by just using adding headers? If so, can you please describe how? The only information I can find is about setting `Request-Id` and `Request-Context`. When setting the `Request-Context` header it seems that app insights only care about the `appId` value. 

**Describe the solution you'd like**
A session id is generated by us on the client and passed as a header on requests to our backend, propogated through the system and becomes visible in app insights.

**Describe alternatives you've considered**
We are considering creating this functionality ourselves by making our services check for a specific header and add that information to the log custom dimensions. However, it feels like app insights should already be able to handle this use case.

**Comment by MSNev** [comment]
Hi @iensu, I understand about the size issue, but if your using packaging and minification the total size will (or at least should) be a lot less than 400+ and 300+ kb, we are actively working on improving tree shaking and minification support and I've updated the main readme for the AISKU to show the current sizes (https://github.com/microsoft/ApplicationInsights-JS/tree/master/AISKU).

Now onto your request, I'm not sure I'm following exactly what the ask is?
It seems like you don't want to track anything on the browser except for "The one thing we want is to be able to assign session ids to requests coming from our client to the backend", would this be for Ajax (XMLHttpRequest / fetch) requests only or also for Postback requests (also known as SSPR / Form submit requests) which would result in a new HTML page and re-initialization of App Insights.

For XHR/fetch requests, for the server side correlation with the client requests is done via headers (code to add the headers is located here (https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-dependencies-js/src/ajax.ts#L277), however, if you not also using the trackDependency (client side reporting of the XHR/fetch request) then the linking shown on the Azure Monitor site will (probably) still be one sided as it would only be showing the server side requests.

Additional
While we "ship" and define the AISKU and AISKU basic, as your using NPM packages (based on the sizes you list), *technically* you could re-construct a smaller version (which is what AISKU basic is about) to only include the packages that you are interested in (eg. You might just include the Core, Common and Extension/Dependencies) -- Note however, that this approach may not be as smooth (for initialization etc) as the main SKU paths.

**Comment by MSNev** [comment]
Update, So we are about to release v2.6.0 (plan this week) to NPM and we will start the CDN deployment as well.

As part of this release we have done a lot of additional work for #1076 (we have been slowly addressing this for the last year), and based on local builds the next version has the AISKU Light build shrinking down to just on 200kb and the minified version *just* under 65k (65,526 bytes). 

Additionally, if you you also follow a couple of additional rules, then your tree-shaking / minification packaging should remove a bunch of code that is now only retained for backward compatibility.
- some of which are outlined here https://github.com/microsoft/ApplicationInsights-JS/blob/master/TreeShakingRecommendations.md
- AND you DONT use the global cookie functions (setCookie, getCookie, deleteCookie and CoreUtils._canUseCookies) or any of the tagged deprecated functions (these will cause the CoreUtils and all references to be retained)

**Comment by iensu** [comment]
This sounds amazing, awesome work! Looking forward to trying it out!
