### ISSUE TITLE
Custom Event data sent but it is not stored in Azure at all

### ISSUE THREAD

**Issue by seekingtheoptimal** [microsoft/ApplicationInsights-JS#1443]
**Description/Screenshot**
Data seems like being sent by SDK, yet it is not stored at all in Azure, not visible in transaction search, not anywhere else.
These simple two lines are from my vuejs app:

this.appInsights.trackTrace({message: "whatever trace"});
this.appInsights.trackEvent({name: "whatever event"});

![image](https://user-images.githubusercontent.com/17144089/101953640-fb5d7180-3bfa-11eb-887e-543fe16d9771.png)

![image](https://user-images.githubusercontent.com/17144089/101953603-e680de00-3bfa-11eb-922e-faaafe975575.png)

**Steps to Reproduce**
Try to send any event data, none of it is stored. Trace data and auto collected page views are visible however.

 - OS/Browser: Win 10, Chrome
 - SDK Version [e.g. 22]: @microsoft/applicationinsights-web": "^2.5.10"
 - How you initialized the SDK: npm

**Expected behavior**
Custom events should also be stored and searchable in portal.

**Additional context**
Not sure if it is the SDK's fault and the data payload is incorrect in any way, or app insights is broken at ingestion side in Azure.

**Comment by MSNev** [comment]
I'm not sure either at the moment (been struggling to get some time to try and repro), in the meantime can you try using the debugplugin (https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-debugplugin-js) to see if it helps identify the issue.

Also, as part of the response is the server reporting that it "accepted" all of the sent events (it's a count that we don't currently validate)? 
And is the sent event log appearing as a log entry elsewhere? 

I know for metrics the server does some magic "name" matching, I don't currently know if this is also the case for events.

**Comment by seekingtheoptimal** [comment]
Meanwhile the events did appear, with a huge delay, and they were also present in Kusto logs. The server response was reported as "accepted" btw for all events, so I think this one can be closed as it seems it was a glitch at ingestion side / portal.
Thanks for the debug plugin, didn't know it exists actually, so if I ever come across such thing again, I'll double check everything with it.
