### ISSUE TITLE
[FEATURE REQUEST] Ability to stop requests being tracked for array of domains

### ISSUE THREAD

**Issue by elliotleelewis** [microsoft/ApplicationInsights-JS#1446]
**Is your feature request related to a problem? Please describe.**
We use feature flags in our SPA and the feature flag's service that we use polls for changes to these feature flags every 30 seconds. This is cluttering up our dependency logs because they're all filled with these polling requests. 

**Describe the solution you'd like**
It would be nice to be able to stop these from being sent by filtering out their domain, so that our dependency logs are only filled with our internal application calls. Something like this in the config:

```javascript
config: {
  ...
  dependencyTrackingExcludedDomains: [
    'a.example.com',
    'b.example.com',
    '*.c.example.com',
  ],
}
```

**Describe alternatives you've considered**
Our feature flag platform also supports SSEs, but falls back to polling if the SSE initialization fails, which happens fairly often.

**Additional context**
N/A

**Comment by MSNev** [comment]
I've tagged this as an enhancement to effectively pre-configure a set of URL's as excluded from reporting dependencies.
In the short term (until this enhancement can be included) there is already a option that you can use to disable URL's for requests by tagging the XHR instance or passed URL with the AjaxMonitor.DisabledPropertyName or for fetch the request or init parameter.

The code that performs this check is here https://github.com/microsoft/ApplicationInsights-JS/blob/05a1f410589514a35e70d425b037888bb3d17d9f/extensions/applicationinsights-dependencies-js/src/ajax.ts#L545

Once a URL is added (excluding the querystring) it will always be excluded even when follow up requests are not tagged, what this means is that during any initialization / first request to the URL that you want to exclude you can tag the request as such and then everywhere else in your code will automatically exclude the url.

Feel free to review the code and potentially provide a PR to add the capability to auto populate the internal _disabledUrls map with the configured values (I would expect this to be added to the ICorrelationConfig config etc)

**Comment by xiao-lix** [comment]
Same issue with #1472 Is there a way to disableAjaxTracking for specific ajax requests
Add correct milestone and update release notes. Closing this issue.
