### ISSUE TITLE
[BUG] angular project is not building due to missing types error

### ISSUE THREAD

**Issue by ziqbalbh** [microsoft/ApplicationInsights-JS#1447]
We have an old Angular 4.4.7 application, in which we want to use Application Insights. When we test things out in development mode all looks ok and telemetry is logged. However when we package our application for production it gives us following error.

We are using webpack with aot enabled angular build.

ERROR in ~/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK/CoreUtils.d.ts (121,29): Cannot find name 'object'.
ERROR in ~/node_modules/@microsoft/applicationinsights-dependencies-js/types/ajax.d.ts (15,63): Cannot find name 'Request'.
ERROR in ~/node_modules/@microsoft/applicationinsights-dependencies-js/types/ajax.d.ts (15,88): Cannot find name 'RequestInit'.
ERROR in ~/node_modules/@microsoft/applicationinsights-dependencies-js/types/ajax.d.ts (34,61): Cannot find name 'Request'.
ERROR in ~/node_modules/@microsoft/applicationinsights-dependencies-js/types/ajax.d.ts (34,86): Cannot find name 'RequestInit'.

**Comment by MSNev** [comment]
This seems like a build environment issue as "object", "Request" and "RequestInit" are all objects that should be provided by the TS environment (i.e. they are not part of the SDK), the "Request" and "RequestInit" are part of the fetch() API...

If your environment is not running in a browser based environment then for the later 2 you may need to include a fetch() API polyfill, for "object" this just seems like a build issue.

**Comment by MSNev** [comment]
@ziqbalbh Did the above help identify your issue? Are you still having issues? If not we will close the issue

**Comment by MSNev** [comment]
Closing as this doesn't seem like an SDK issue
