### ISSUE TITLE
More docs for web-basic

### ISSUE THREAD

**Issue by pelikhan** [microsoft/ApplicationInsights-JS#1449]
The current "basic" sku docs are rather sparse. It's unclear how the messages passed to the ``track`` function have to be called to function properly. 

Is there a fully functioning sample out there that uses this SKU?

## Why?

The non-basic AI sku is too big and keeps on getting bigger.

**Comment by MSNev** [comment]
Which documentation are you referencing and which version of the SDK are you using? (v1 - legacy ai.0.min.js or v2 - current ai.2.min.js).

Based on you comment it seems that you may be referencing via NPM packages, if so which package(s) / extension(s) are you using.

Simplistically, though the event sent to track() should not be any different between different SKU's as fundamentally everything routes to the same internal code.

If your using a browser based client for development you could also add the debugplugin (https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-debugplugin-js) which provides easier visualization to the internal errors that are thrown for invalid event and how / what is being sent.

**Comment by MSNev** [comment]
On the Size basis, we are actively working to reduce the total size has become an issue.
