### ISSUE TITLE
[BUG] nativescript/angular support

### ISSUE THREAD

**Issue by Nosfit** [microsoft/ApplicationInsights-JS#1459]
**Description**
appInsights does nothing after initialization in NativeScript app. does not send any requests or log smth to the console
**Steps to Reproduce**
Create new nativeScript/angular project with NativeScript CLI command `ns create MyApp --template angular`
add AI js sdk to app component 
```
export class AppComponent implements OnInit {
    ngOnInit() {
        const appInsights = new ApplicationInsights({
            config: {
                instrumentationKey: "YOUR_INSTRUMENTATION_KEY_GOES_HERE",
                /* ...Other Configuration Options... */
            },
        });
        appInsights.loadAppInsights();
        appInsights.trackPageView();
    }
}
```

**Comment by jitendraP-ashutec** [comment]
@xiao-lix  do you have any suggestion how I can run this package in nativescript/angular ?

**Comment by xiao-lix** [comment]
@Nosfit @jitendraP-ashutec Sorry for the late reply, unfortunately, the application insights package does not support nativescript/angular yet.

**Comment by dmytro-gokun** [comment]
@xiao-lix no problem for the late reply. the most important thing it was helpful

**Comment by jitendraP-ashutec** [comment]
@Nosfit  @dmytro-gokun  @xiao-lix 

I have made small changes in package ApplicationInsights-JS and created local package then it is working on Nativescript.
You can download this package from here: https://github.com/jitendraP-ashutec/ApplicationInsights-JS-package

and add this package into root folder of your project and run below command to install it.

``` 
npm install  microsoft-applicationinsights-channel-js-2.5.12.tgz
npm install microsoft-applicationinsights-common-2.5.12.tgz

```

and in config you have to pass one new config variable Like:
``` private appInsights = new ApplicationInsights({
        config: {
            instrumentationKey: XXXXX
            // I have created new config variable  isHybridApp. If you pass it true then it will work on nativescript
            isHybridApp: true,
        }
    }); ```

Please check and let me know so if its work then I can create PR so any one can use this feature.

**Comment by kriefsacha** [comment]
@jitendraP-ashutec if the app crashes, we are suppose to see it with this new package ?
