### ISSUE TITLE
Difference in browser timings between Chrome and ApplicationInsights for AJAX requests.

### ISSUE THREAD

**Issue by bsumter** [microsoft/ApplicationInsights-JS#1461]
**Browser:** Google Chrome Version 87.0.4280.141
**ApplicationInsights-JS:** Application Insights JavaScript SDK - Web, 2.5.9

While investigating the browser timings, I'm noticing significant differences between Application Insights and Chrome. Below are 2 screenshots of the exact same requests in both App Insights and Google Chrome.

**ApplicationInsights:**
![image](https://user-images.githubusercontent.com/22917990/105204676-bc4d0500-5b44-11eb-9f89-23bb75043d63.png)

**Chrome using `performance.getEntries()`:**
![image](https://user-images.githubusercontent.com/22917990/105205247-52812b00-5b45-11eb-8446-a20411409a6a.png)

**Comment by MSNev** [comment]
The difference is based on how the data is calculated.
For App Insights the time is the Javascript execution time based on timing from the XHR ```send``` to when the XHR requests calls it's ```onComplete```  as we can always calculate this value, it also represents the elapsed time experienced by your users.

While the performance timing API is purely based on the underlying network request time and does not represent the time it takes for your application to process the request (which is required as you are doing this via an XHR / fetch request).

You can however, enable a config  option to cause the SDK to *attempt* to collect and report these performance marks (if available -- there is a limit on the number browsers will store and not available on all browsers in a timely manner)

See, ```enableAjaxPerfTracking``` (it defaults to false) https://github.com/Microsoft/ApplicationInsights-JS#configuration 

The performance information collected when enabled and available is stored as an additional ```ajaxPerf``` property, which I believe will be available in the details logs.

Also when enabled this will also attempt to collect and include any ```serverTiming``` values returned by the server for the Ajax request.

**Comment by MSNev** [comment]
Closing as I assume my comments above answered the question (based on the thumbs up)
