### ISSUE TITLE
[BUG] Response compression not enabled on new CDN endpoint

### ISSUE THREAD

**Issue by harvey-k** [microsoft/ApplicationInsights-JS#1464]
**Steps to Reproduce**

Requesting the application insights bundle from the legacy endpoint returns a compressed response:
https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js
content-encoding  gzip
content-length    37648

Requesting the bundle from the new endpoint does not return a compressed response:
https://js.monitor.azure.com/scripts/b/ai.2.min.js
content-length   126996

**Expected behavior**
The js.monitor.azure.com endpoint should support response compression.

**Comment by MSNev** [comment]
Hi @harvey-k, I've tracked down the issue to a problem with one of our CDN endpoints (which was the primary), I've just switched the provider used for this endpoint (as manual testing should that it was working). It may take up to 5 minutes (depending on your DNS cache and provider) before the change is reflected.

**Comment by MSNev** [comment]
So js.monitor.azure.com should be serving the compressed version shortly, additionally we also just release v2.5.11 to the CDN (not related to this issue -- just timing)

**Comment by harvey-k** [comment]
@MSNev Wonderful, thank you for your help!
