### ISSUE TITLE
[BUG] all tracking XHR requests result in 206 "Telemetry Sampled out." (no tracking data in App Insights)

### ISSUE THREAD

**Issue by jar240** [microsoft/ApplicationInsights-JS#1466]
I see XHR track requests, but they return 206 "Telemetry Sampled out.". Azure Application Insights sees no telemetry data from the browsing sessions. It appears the calls are making it through the proxy but being rejected by App Insights (speculation based on observation).

**Config (one of many attempts)**
![image](https://user-images.githubusercontent.com/6794643/106818301-1a4e1200-6646-11eb-8dd4-327cde7729ad.png)

**Redacted Request Payload**
```
[
    {
        "time": "2021-02-03T22:26:00.672Z",
        "iKey": "xxxxxxxx",
        "name": "Microsoft.ApplicationInsights.xxxxxxxx.Pageview",
        "tags": {
            "ai.user.id": "xxxxxxx",
            "ai.session.id": "xxxxxxx",
            "ai.device.id": "browser",
            "ai.device.type": "Browser",
            "ai.operation.name": "/",
            "ai.operation.id": "<some guid>",
            "ai.internal.sdkVersion": "javascript:2.5.11",
            "ai.internal.snippet": "-"
        },
        "data": {
            "baseType": "PageviewData",
            "baseData": {
                "ver": 2,
                "name": "Angular11test1",
                "url": "http://theurlofmyproject/",
                "duration": "00:00:00.000",
                "properties": {
                    "refUri": "http://theurlofmyproject/"
                },
                "measurements": {
                    "duration": 0
                },
                "id": "some guid"
            }
        }
    }
]
```

**Sample response**
![image](https://user-images.githubusercontent.com/6794643/106817568-05bd4a00-6645-11eb-94df-e8dd913172ef.png)

**Steps to Reproduce**
 - Angular 11.1;  tried using my solution plus a new Angular project via "ng new", both snippet and npm initialization
 - Chrome v88, Windows 10 & Chrome v86, Windows Server 2012 R2:
 - behind a corporate proxy (all http verbs are allowed for the target URLs
 - SDK Version: 2.5.11
 - How you initialized the SDK: both via snippet and npm (yarn)

**Expected behavior**
Telemetry should be accepted

**Additional context**
- I've tried using connectionString instead of instrumentationKey, same results
- I've tried removing all config options except for connectionString (or instrumentationKey), sme results
- I know the Application Insights itself is working because we have a C# Web API project that reports telemetry successfully.
- I've Googled and found nothing except some "scraper" sites I'm not willing to risk visiting

Any help would be appreciated, thanks.

**Comment by kryalama** [comment]
@jar240 from SDKs point of view we dont try to resend the telemetry data if there is a 206 "Telemetry sampled out" from Breeze. I am guessing on the Application Insights portal the sampling percentage is set very low. Could you please confirm it is set to 100% or may be some higher number.
![image](https://user-images.githubusercontent.com/66494519/106832060-d65b0d00-6645-11eb-88be-06611556ea5e.png)

**Comment by jar240** [comment]
> I am guessing on the Application Insights portal the sampling percentage is set very low. Could you please confirm it is set to 100% or may be some higher number.

Thank you! Data Sampling was set to 0%, and changing that to 100% (for now) solved the problem.
