### ISSUE TITLE
Convert undefined to blank in customDimensions?

### ISSUE THREAD

**Issue by coreyroth** [microsoft/ApplicationInsights-JS#1471]
**Is your feature request related to a problem? Please describe.**
I have a number of customDimensions in trackPageView, trackEvent, etc.  Given this SDK is JavaScript based, dealing with undefined is a common thing.  When we send a value of undefined, it shows up in our data model as undefined as well.  I'm then reading the data through the API or Power BI and undefined.  That doesn't look good on reports and we have to do comparisons to both '' and undefined.

I can work around this easily enough, but it's a bit of a mess when I am sending 50+ properties in an event.  Does it make sense for the SDK to strip undefined and send '' instead of undefined?

**Describe the solution you'd like**
I would like the SDK or the API to convert undefined to a blank ('') value so it doesn't show up in the data model.  This could be an option on the SDK perhaps in case people don't want this behavior.  

**Describe alternatives you've considered**
I can work around this of course by wrapping the values I am sending with a function to detect undefined.  I could also use a telemetryInitializer to work around it as well.

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints

**Comment by coreyroth** [comment]
Thanks for including this!

**Comment by MSNev** [comment]
It may take up to around 30 minutes for all CDN endpoints to pick up the new bits (depending where you are located)

**Comment by coreyroth** [comment]
I finally have had a chance to test this with 2.7.2 and I'm still seeing values listed as "undefined" in customDimensions.  Is there a trick to making this work?

**Comment by MSNev** [comment]
Reopened so we can investigate further @Karlie-777 do you have some cycles to investigate this see the PR #1630 to see what was changed

**Comment by Karlie-777** [comment]
Hi @coreyroth 
The current npm version only works with undefined value but not value equal to string "undefined".
so for example, 
```appInsights.trackEvent({ name: "Custom event" , properties:{"prop1": undefined, "prop2": "undefined"}});```

`prop1` will be replaced but not `prop2`.

**Comment by coreyroth** [comment]
Hi @Karlie-777, perfect.  That's my understanding as well.  Using v2.7.2.

I initialize my instance with something like:

`      this.appInsights = new ApplicationInsights({
        config: {
          instrumentationKey: instrumentationKey,
          autoTrackPageVisitTime: true,
          disableAjaxTracking: true,
          convertUndefined: ''
        }
      });`

Then I am writing undefined versus 'undefined' into my objects.  Here's the browser output of some of my object before I call trackPageView().

`          this.appInsights.trackPageView({
            properties: this.trackedProperties
          });`

![Screen Shot 2022-01-17 at 2 09 37 PM](https://user-images.githubusercontent.com/11725265/149831968-bdbefd45-7682-456d-83ad-3ce9dbbbfeaf.png)

Here's what I am seeing in Application Insights:

![Screen Shot 2022-01-17 at 2 13 47 PM](https://user-images.githubusercontent.com/11725265/149832235-530c811f-9341-4b31-bb6a-96d58ea36bb1.png)

**Comment by Karlie-777** [comment]
Hi @coreyroth 
Do you mind trying ``convertUndefined: 'test'`` and ``convertUndefined: ' '`` (Note: use a space instead of empty string)
Do the two configs replace ``undefined``?

**Comment by coreyroth** [comment]
Hi @Karlie-777.  I just validated and neither of those are working for me.  Does it work for all of the various methods in the SDK?  In this case, I was testing trackPageView().

**Comment by Karlie-777** [comment]
Hi @coreyroth 
I tried both npm and snippet 2.7.2 multiple times and both work for my local apps. Do you mind checking network "track" payloads? is the ``undefined`` in ``trackPageViewData`` replaced?

**Comment by coreyroth** [comment]
Hi @Karlie-777, 

Interesting.  So the track network requests are showing as "undefined" in the Payload using quotes.  

![Screen Shot 2022-01-18 at 2 43 51 PM](https://user-images.githubusercontent.com/11725265/150016024-dbe039ee-d5b4-46b9-aa63-5f1593957ec9.png)

That's definitely not how I am writing the values in though as I showed in the screenshot earlier.  I definitely could be doing something wrong but I'm not sure what.

**Comment by Karlie-777** [comment]
Hi @coreyroth,
here is my test code.

<img width="646" alt="code" src="https://user-images.githubusercontent.com/79606506/150019641-d0f65d36-511c-4af4-acea-16331d7f6811.png">
<img width="532" alt="payload" src="https://user-images.githubusercontent.com/79606506/150019646-8b8897d3-47e4-4aee-a030-21c679b2487f.png">
