### ISSUE TITLE
Missing Arguments for `useTrackEvent` in AppInsights Micorsoft Docs for React Plugin 

### ISSUE THREAD

**Issue by ahmadatallah** [microsoft/ApplicationInsights-JS#1476]
**Is your feature request related to a problem? Please describe.**

`useTrackEvent` hook is missing the arguments `eventData`, and `skipFirstRun` in Microsoft docs for AppInsights React plugin [docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin
).

> The `useTrackEvent` Hook is used to track any custom event that an application may need to track, such as a button click or other API call. It takes two arguments, the first is the Application Insights instance (which can be obtained from the useAppInsightsContext Hook), and a name for the event.

so it actually takes four arguments, three are required, and one optional. 
I was able to predict what those extra two arguments do as they are intuitive from the types but still not sure how the code will act with/out providing them.

**Describe the solution you'd like**

Update docs for `useTrackEvent` hook to include  `eventData`, and `skipFirstRun` arguments.

Thanks,

**Comment by kryalama** [comment]
@rmarskell my bad, I have updated the wordings in the doc, but didnot update the snippet. Now its updated in this [pull request](https://github.com/MicrosoftDocs/azure-docs-pr/pull/153341)
