### ISSUE TITLE
Expose Serializer class outside (PublicApi)

### ISSUE THREAD

**Issue by Vijay-Nirmal** [microsoft/ApplicationInsights-JS#1484]
Is it possible to expose `Serializer` outside?

https://github.com/microsoft/ApplicationInsights-JS/blob/05a1f410589514a35e70d425b037888bb3d17d9f/channels/applicationinsights-channel-js/src/Serializer.ts#L5

**Justification** 

In ApplicationInsights-dotnet nuget package they have exposed there Serializer class outside ([JsonSerializer.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/96d5d92715e77113db9a03f7acaa9bb441ab3476/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/JsonSerializer.cs#L20)). So making public for UI gives consistency.

**Use Case**

In will be very helpful to get raw json structure that is passed by app to app insights when we implemented external service to analyze the data that is being send to app insights or even plainly store the raw data for archiving purpose or other debugging purpose

**Comment by MSNev** [comment]
It's not quite as simple as just exposing the Serializer as this would change the options we have to both optimize, refactor and reduce the size of the internal implementations.

Also there are changes coming that may affect the way events will need to be serialized and handled along with the way the Channel handles failures and resiliency, which would not be reflected in the Serializer alone. For example, currently, events are serializer to Json and kept in this form when sent out, this doesn't support any form of retry capability where we could easily tag a follow up sent event as a retried event. While this is also not currently supported on the ingestion endpoint it's internal protocol based things like this that restrict the options.

So while I understand the request and I think I have an idea of the rationale behind it, at this point in time, I'm going to have to say this is a won't fix. I would expect a realistic time frame on when we could consider this would be measured in years not months (so say towards the end of 2022 before I think we might be in a situation where this could become a consideration).
