### ISSUE TITLE
[BUG] ai_user cookie has an expiry of almost 1 year!

### ISSUE THREAD

**Issue by ShayanZafar** [microsoft/ApplicationInsights-JS#1497]
I am not sure if this is a bug but the ai_user cookie in particular has an expiry of almost 1 year

![image](https://user-images.githubusercontent.com/1667047/110558462-8eca1400-8110-11eb-96ea-a6adb7bd3820.png)

how can i set the cookie attribute 'httpOnly' and 'Expiry/ Max-Age' for the ai_user and ai_sesson cookies? or can you guys fix this on your end and expose settings for modifying the cookie attribute values?

I am using the latest version of the javascript sdk from npm: 2.5.11

**Comment by MSNev** [comment]
It's not a bug, but by design

These cookies can't have httpOnly as we need to be able to read them from JavaScript.

And as the expiry is set by the SDK with ai_user being 1yr by design so that you can get a better accurate unique user count.

**Comment by ShayanZafar** [comment]
Thanks for the explanation! perhaps this should be in the SDK documentation as it is being flagged by our security penetration tests.
