### ISSUE TITLE
AppInsights browser cookies trigger OWAS CSR 3.1 false positives

### ISSUE THREAD

**Issue by murdockcrc** [microsoft/ApplicationInsights-JS#1499]
**Is your feature request related to a problem? Please describe.**
AppInsights sets two cookies on the browser:
* ai_user
* ai_session

These cookies may have values which include double dashes "--". When the value of any of these cookies has a double dash, firewalls that enforce OWASP CSR 3.1 block a request from the browser as malicious. The exact rule which is triggered is 942440 (Detect MySQL in-line comments). The exact specification for the rule can be found [HERE](https://github.com/coreruleset/coreruleset/blob/896b220e149ecd074ec8d189cc280171376c63f7/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L483).

**Describe the solution you'd like**
The value-generation logic for these cookies should avoid creating values with double-dashes.

**Describe alternatives you've considered**
None

**Additional context**
You can easily repro this behaviour in the following way:
* Integrate the AppInsights SDK to any SPA app.
* Publish this application using the Azure Web Application Firewall, in protection mode (so rules are enforced, not only detected). Configure the WAF listener to enforce the CSR 3.1 ruleset.
* Set the value of the `ai_user` or `ai_session` cookies to something that includes a double dash. Example: `RZI5CL3Uk8cJjmX3B8S-q0ou--OO--bctU5sx8FhazvyvfAH7wH`

**Comment by MSNev** [comment]
What version of the SDK are you using? the example values look nothing like what the JS SDK uses.

Internally we are using "|" as the encoded field separator and when we create a 22 character random value we only use these values
    const base64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

The only time a single '-' is added is for the date which is stored (in the clear as part of the cookie) which will contain a single '-' between the year-month-day.

**Comment by murdockcrc** [comment]
We are using "@microsoft/applicationinsights-web": "^2.5.11"

So if I read your reply correctly, the way you construct the values for those 2 cookies makes it impossible for a double-dash (--) to be in the value of the cookies? Am I right?

**Comment by MSNev** [comment]
Correct, I don't see anything in the code using the automatic id generation that would cause "--" to be added.
If you have a repro site that I can hit, I'll take a look to see if I can find the source of the issue, if you like.

**Comment by murdockcrc** [comment]
The issue is not easy to repro, as the value of these cookies changes and the issue happened at random. Anyway, if we can repro reliably or collect some evidence, we'll share again in a GH issue. Thanks for clarifying.
