### ISSUE TITLE
Network time in browser doesn't match that logged in Azure portal

### ISSUE THREAD

**Issue by lukos** [microsoft/ApplicationInsights-JS#1505]
We have launched a new site and am trying to see how it performs vs the old site. We were surprised to see in the Azure portal that the performance of most pages were a number of seconds for what is basically a static site.

![image](https://user-images.githubusercontent.com/581018/111767086-31fff380-889e-11eb-9b7a-d0f287a8733b.png)

We went to the site to find out what was wrong but in the browser, everything seems fine. If you load any of the pages, you get timings like these:

![image](https://user-images.githubusercontent.com/581018/111767140-4b08a480-889e-11eb-9a1a-b73b79a90a1f.png)

However, if you look at the network timings tab, you can see that we load a script after pageload has fired and then after a considerable amount of time, another track call is made to AI.

![image](https://user-images.githubusercontent.com/581018/111767394-9458f400-889e-11eb-8b46-62fb35232786.png)

I don't understand. If the browser thinks it has loaded, why is this new dependency part of the page load time in app insights and why is it so long between the end of the dependency before track is called, making the entire page load time seem very excessive?

![image](https://user-images.githubusercontent.com/581018/111767792-0cbfb500-889f-11eb-8194-939e4c0a8e12.png)

- Firefox (latest) on Windows 10. App Insights is v5 JS snippet embedded into page via a script file.

**Expected behavior**

I would expect the page load time as reported by the portal to match what the browser says against "load" and not against "finished"

Maybe there is a way to exclude a certain script from being included in the page performance? That would be an acceptable workaround even though I would expect async/deferred loads not to be included otherwise you don't get any useful measure of page performance from the user's point of view.

**Comment by lukos** [comment]
Note the screenshots are not all from the same request, it's just to give ballpark data.

**Comment by MSNev** [comment]
I don't think I'm completely following, but there is a but #1478 which is fixed but not yet released, which *might* be affecting this, if your talking about the total time based on the dependency calls.

On the call for the track event, these are batched and are only sent after manner seconds (to avoid interfering with the PLT of the page).

> If the browser thinks it has loaded, why is this new dependency part of the page load time

The JS SDK reports (except for the above bug) the times provided by the window.performance and depending on the browser support uses the page on load event to capture when the page has finished loading. This *might* be the portal providing the interactive time for the requests... I'll get someone to investigate further

**Comment by lukos** [comment]
OK thanks. It looks like the bug might be related.

Just to be clear, are you saying that App Insights should be recording the "finish" time and not the "load" time from this screenshot?

![image](https://user-images.githubusercontent.com/581018/112020760-874f3580-8b28-11eb-856b-da3ee13f4645.png)

**Comment by MSNev** [comment]
Sorry for the delay response, I'm not sure I'm following the question...
For Page Load events it should be reporting the page start and load time, the linked error is that it was reporting the "start" time as the time the event was being sent (effectively the page load finish time), but the duration (load time / time taken) was correct.

**Comment by MSNev** [comment]
Closing as I believe the 2.6.0 release fixed this issue, please comment if not.
