### ISSUE TITLE
Provide an out of the box solution to enable cookie tracking only after user accepted cookie policy

### ISSUE THREAD

**Issue by KamilSzostak** [microsoft/ApplicationInsights-JS#151]
This will be useful in European countries wher websites need to obey the "cookie law" (more: https://www.cookielaw.org/the-cookie-law/). 

Sample scenario: 
1) User navigates to a website
2) User accepts cookie policy
3) User navigates to a subpage

In such case we should track 1) and 3) as separate sessions. I'm also not sure if we can set a cookie during the 1) request when user has not accepted the policy yet.

**Comment by SergeyKanzhelev** [comment]
This can be used as workaround: http://apmtips.com/blog/2015/08/15/disable-browser-telemetry-from-the-page/ However out of the box solution would be really nice.

Maybe allow to override setCookie function?

**Comment by AlexBulankou** [comment]
To support this we need API to start new session and new anonymous user id. Let's keep it around to see how many users inquire about it and revisit this in a couple of months

**Comment by n01d** [comment]
I this something that is still being worked on? I currently have a discussion around AI in the context of EU legislation and GDPR going on.

**Comment by MSNev** [comment]
Closing as this is unlikely to be created as part of the main AI SDK directly as to do this properly would require some level of Localization (Language translation) and we don't have any current method for providing / generating translations.

We have provided better support (in current v2) to enable / disable cookies after initialization, so a separate UI component (probably several -- based on UI framework) could be passed the AI instance and then use ```appInsights.getCookieMgr().setEnabled(true/false)```

**Comment by Piedone** [comment]
BTW in our AI module for Orchard Core CMS we've simply solved this by only injecting the tracking script if the ASP.NET Core `ITrackingConsentFeature` says the user allowed it (or `ITrackingConsentFeature` is not used), see: https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/90700de3c559315489704a1b489f1662a83ac2c6/Services/TrackingScriptInjectingFilter.cs#L40
