### ISSUE TITLE
[BUG] `correlationHeaderExcludePatterns` is not honored in Ajax calls

### ISSUE THREAD

**Issue by jpfifer** [microsoft/ApplicationInsights-JS#1528]
**Description/Screenshot**

The value of `correlationHeaderExcludePatterns` in `Snippet` is not honored by the SDK.

It appears that the [`getDefaultConfig()` in `AjaxMonitor`](https://github.com/microsoft/ApplicationInsights-JS/blob/22d3787cb9b328bbf3cab0ee38a686d4779f8031/extensions/applicationinsights-dependencies-js/src/ajax.ts#L154) doesn't include an empty value for `correlationHeaderExcludePatterns`. This causes the [configuration loading](https://github.com/microsoft/ApplicationInsights-JS/blob/22d3787cb9b328bbf3cab0ee38a686d4779f8031/extensions/applicationinsights-dependencies-js/src/ajax.ts#L217) to never see the configuration.

**Steps to Reproduce**
1. Set `correlationHeaderExcludePatterns` to `[/.*/]`
  This should cause no correlation headers to be sent at all
2. Run the application and verify that the correlation headers are being sent.

 - OS/Browser: macOS Chrome and Firefox
 - SDK Version [e.g. 22]: 2.5.10 and 2.6.1
 - How you initialized the SDK:
```
config: {
        instrumentationKey,
        extensions: [reactPlugin],
        extensionConfig: {
          [reactPlugin.identifier]: { history }
        },
        disableFetchTracking: false,
        enableCorsCorrelation: true,
        disableAjaxTracking: false,
        enableRequestHeaderTracking: true,
        enableResponseHeaderTracking: true,
        correlationHeaderExcludedDomains: [`...`],
        correlationHeaderExcludePatterns: [new RegExp('...')],
        distributedTracingMode: DistributedTracingModes.AI
      }
```

**Expected behavior**
Correlation headers should not be sent when the URI matches the exclude pattern

**Comment by MSNev** [comment]
I think this is related to #1524

**Comment by jpfifer** [comment]
I just upgraded to the current version and it `correlationHeaderExcludePatterns` appears to be working correctly.

**Comment by MSNev** [comment]
v2.6.2 is now fully deployed
