### ISSUE TITLE
[BUG] Application Insight dependency setting wrong `parentId` for storage-blob and storage-queue

### ISSUE THREAD

**Issue by oskgro** [microsoft/ApplicationInsights-JS#1529]
**Description/Screenshot**
I have one Azure Function that puts a new Storage Blob in a Storage Account and another function that is set up to be triggered when a new Blob is created. The trigger works and all seems fine, but when I looked at the traces made with Application Insights the two functions are not correlated, and the `parentId` of the second function is not the same as the `dependencyId` of the dependency. As far as I understand from others with similar problems, they should be. When doing a similar setup but using HTTP triggers instead, everything is correlated and works fine. That is, the first function has a requestId that becomes the parentId of the dependency, the dependency generates another id (dependencyId) that becomes the parentId of the second function (trigger-function). Thus, the parent-child correlation works. 

For some reason this does not seem to work with storage-blob and storage-queue as the dependencyId is not carried forward to the parentId of the second function.

The problem seemed somewhat related to this issue for the .NET version: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1915 

**Steps to Reproduce**
Set up a function to be triggered upon a new blob being created in a storage account, create a new blob in another function. Set up Application Insights to trace and correlate: Function -> Dependency -> Function. 

 - OS: MacOS: Big Sur
 - SDK Version: ApplicationInsights@2.6.1, Storage-Blob@12.4.1

**Expected behavior**
A parent-child correlation should be created as the requestId or dependencyId should be carried over to the next step in the correlation as its parentId.

**Actual behavior**
The chain is broken after the dependency: Function -> Dependency -//> Function

**Comment by MSNev** [comment]
Have you raised this issue with StorageBlob, as I don't think it's technically an issue with the AI SDK?
