### ISSUE TITLE
[BUG] React 3.1.1 does is not reusing the shims v2 module correctly -- causing __extends errors

### ISSUE THREAD

**Issue by MSNev** [microsoft/ApplicationInsights-JS#1553]
**Description/Screenshot**

**Steps to Reproduce**

 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**

**Additional context**

**Comment by MSNev** [comment]
I've deprecated v3.1.1 package until I can publish an updated version

**Comment by MSNev** [comment]
PR to fix this is #1555

**Comment by MSNev** [comment]
Reopening for tracking

**Comment by MSNev** [comment]
FYI - Internal prod build servers are timing out -- I need a good clean run to be able to release, will release as soon as I get a good run.

**Comment by MSNev** [comment]
Still having issues with the new tests on the internal servers -- still working on it

**Comment by MSNev** [comment]
Finally got a good build, however, the publish step is broken and will require an update -- unlike to get this fixed today now 😞 😭

**Comment by MSNev** [comment]
Publish step is broken

**Comment by sujitykulkarni** [comment]
Got socket timeout issue with fresh `npm install` attempt just now (28th APr 2021 21:20 IST).

`
npm ERR! request to https://registry.npmjs.org/@microsoft/applicationinsights-shims/-/applicationinsights-shims-2.0.0.tgz failed, reason: Socket timeout
`
Is it due to broken publish?

**Comment by MSNev** [comment]
@sujitykulkarni, no that is not due to the broken publish, that sounds like a network issue or a problem on the npmjs servers.

The publish issue is an issue in the way the production build servers prepare the tarball, and turns out that even though we have a pre-package step the publish was re-creating it without have full access to all of the packages (on the publish servers) the fix for this is in PR #1557

**Comment by MSNev** [comment]
PR is merged, back on the waiting for official internal build generation before publishing -- __hopefully__ this will complete within the next few hours (yes can take this long 😢 )

**Comment by MSNev** [comment]
Ok, finally published!!!

If there are still issues related to this please comment here and I'll jump on it.
For now closing this issue.
