### ISSUE TITLE
How to track desktop app version?

### ISSUE THREAD

**Issue by cawa-93** [microsoft/ApplicationInsights-JS#1563]
Good day :)

This is my first time studying Application Insights. Before that I used Google Analytics.

I'm working on a desktop electron application and want to set up simple telemetry. I've already set up tracking of app screens (I used npm installation), but I can't figure out how to track my app versions.

As I understand it, metrics such as Country, operating system and browser (in my case it's "electron 12.0") are automatically collected and I see these metrics in the insight "Users" report. But how do I track a version not of an electron, but of my application?

I found some [information](https://stackoverflow.com/questions/45942958/how-can-i-set-the-application-version-number-in-azure-application-insights-for-u) on the internet, but it's mostly for java (or something) and not for the JS package.

Thanks 😁

**Comment by MSNev** [comment]
Looking at the code we have a (legacy) setting that might work for you (ie. I've not directly tried this myself).
On the context object there is a public "application" which contains a "ver" and "build" that you can populate, and if the values are present they will be applied to the outbound event.

So it would be something like the following, you should only need to set this once (after the SDK is initialized)

```
appInsights.context.application.ver = "1.x.x";
appInsights.context.application.build = "xxxx.xxxx.xxx.xxx";
```

If this doesn't flow through for all event types, then the other solution would be to add a TelemetryInitializer (You currently need to be using the ```applicationinsights-analytics-js``` extension or the main ```AISKU``` (which includes the extension) to get the ```addTelemetryInitializer``` function. (https://github.com/Microsoft/ApplicationInsights-JS#telemetry-initializers)

**Comment by cawa-93** [comment]
@MSNev It seems `appInsights.context.application.ver = "1.x.x";` working. But if this is legacy setting maybe I should create TelemetryInitializer. TelemetryInitializer  API looks simple, but I don't understand how use it for my use case. I mean what tags I Should set?
```js
var telemetryInitializer = (envelope) => {
  envelope.tags["?????"] = "1.x.x"; // App version
  envelope.tags["?????"] = "xxxx.xxxx.xxx.xxx"; // Build version
}
appInsights.addTelemetryInitializer(telemetryInitializer);
```

**Comment by MSNev** [comment]
You can set any tags you like that would make sense for your queries.

As the application is working, I'd go with that as (if) this ever gets removed (there are no current plans) it won't occur until a major version bump as it would be considered to be a breaking change. I believe that the legacy comment in the code came from providing support for upgrading from v1.

**Comment by cawa-93** [comment]
> You can set any tags you like that would make sense for your queries.

And tags will be some how parsed and available in reports? I feel like a lost child trying to figure out how to work with Application Insights. 

> As the application is working, I'd go with that as (if) this ever gets removed (there are no current plans) it won't occur until a major version bump as it would be considered to be a breaking change. I believe that the legacy comment in the code came from providing support for upgrading from v1.

It make sense. thanks
