### ISSUE TITLE
[BUG] ApplicationRef isStable never return true on browser side on production mode

### ISSUE THREAD

**Issue by marzc** [microsoft/ApplicationInsights-JS#1564]
**Description/Screenshot**
When I run the application based on Angular Universal (SSR) with **production** mode, on the browser side application ApplicationRef.isStable always return false. When I turn off Insight, ApplicationRef.isStable return true (as expected).

logs from console browser and server:
![image](https://user-images.githubusercontent.com/72394619/118664477-cb417c80-b7f1-11eb-99d4-35f1d26ea885.png)

When I run the application without Angular Universal but also production mode, the result was the same.

Application insight I implemented based on this instruction https://devblogs.microsoft.com/premier-developer/angular-how-to-add-application-insights-to-an-angular-spa/
**Steps to Reproduce**
- build application with Angular Universal on production mode

 - OS/Browser: Chrome 90.0.4430.212 , Firefox 88.0.1

**Expected behavior**
ApplicationRef.isStable should return true

**Comment by MSNev** [comment]
As the ApplicationRef.isStable is not part of the ApplicationMonitor SDK, I'm not sure that we have the context to be able to answer this question.

@xiao-lix did you come across this issue as part of the angularplugin creation?

**Comment by marzc** [comment]
Hi @MSNev 
You are right, this is not part of the ApplicationMonitor SDK, but I suppose base on my verification that the ApplicationMonitor SDK may have an effect on ApplicationRef.isStable.

As mention above, when I turn on your library in my application, especially run this line `appInsights.loadAppInsights(); `.
From this moment `ApplicationRef.isStable` only return false. When I comment this line  `appInsights.loadAppInsights(); `, `ApplicationRef.isStable` work corrrect and return true.

Probably I have committed fault because production mode doesn't have matter for it, the problem occurs regardless of mode (production or not).

This post [about isStable](https://lukaonik.medium.com/demystifying-the-applicationref-isstable-event-in-angular-20c546fe617e) can be helpful with understanding what can cause problems with stable.

To give you a big picture of why it is important for me. Angular Universal use TransferHttpCacheModule to cache some request, but TransferHttpCacheModule need to have the correct working ApplicationRef.isStable, without it cause some unexpected problems.

**Comment by xiao-lix** [comment]
Did you try using Angular plugin? https://github.com/microsoft/applicationinsights-angularplugin-js

**Comment by marzc** [comment]
@xiao-lix No, I haven't tried. I will check this plugin and share information about the results.

**Comment by duvet86** [comment]
> Did you try using Angular plugin? https://github.com/microsoft/applicationinsights-angularplugin-js

I have, some thing.  IsStable never returns true,

**Comment by Karlie-777** [comment]
@duvet86 My assumption is that under default app configs, we will _**batch telemetry and set timer**_ (default is 15000ms) and the timer probably leads to "unstable" state. Do you mind trying using `appInsights.flush()` before logging ApplicationRef state since the `flush` method will clear any timers set for sender, or you could try reset `maxBatchInterval` to reduce timer interval https://github.com/microsoft/ApplicationInsights-JS#:~:text=batch%20is%20started-,maxBatchInterval,-numeric

**Comment by duvet86** [comment]
@Karlie-777 I was able to solve the issue follwing these steps. It might help you find a proper solution. https://github.com/microsoft/ApplicationInsights-JS/issues/535#issuecomment-787119788
Thanks.

**Comment by DavidMarquezF** [comment]
Can confirm that @duvet86  proposed solution works. However I'm a bit scared of patching xhr.open since it is called so much. Have you had any problems patching this function to run outside the angular zone??

**Comment by duvet86** [comment]
@DavidMarquezF 
`ngZone.runOutsideAngular(() => {
     appInsights?.loadAppInsights();
     appInsights?.trackPageView();
});`

This is what we've done and it works.
No need to change anything if you don't want to. My suggestion is to extend the documentation mentioning that if they are using pwa features the app won't get stable unless they run `loadAppInsights` and `trackPageView` outside of ngZone.
Tested with angular 13.
