### ISSUE TITLE
[BUG] DataSanitizer.sanitizeString fails without logger

### ISSUE THREAD

**Issue by huli1234** [microsoft/ApplicationInsights-JS#1565]
**Description/Screenshot**
The class TelemetryTrace calls DataSanitizer.sanatizeString Method here:  https://github.com/microsoft/ApplicationInsights-JS/blob/029d2962ad67cb59dc149f8d45e7f836c9998f1a/extensions/applicationinsights-properties-js/src/Context/TelemetryTrace.ts#L24

The method requires a logger to be present  (https://github.com/microsoft/ApplicationInsights-JS/blob/029d2962ad67cb59dc149f8d45e7f836c9998f1a/shared/AppInsightsCommon/src/Telemetry/Common/DataSanitizer.ts#L87), but the TelemetryTrace class doesnt require the logger.

This causes issues when using TelemetryTrace without a logger but with a too long URL that needs to be sanitized.

**Steps to Reproduce**

Happens in every setup.

**Expected behavior**
Logger in DataSanitizer should also be optional, and not used if not present

**Comment by MSNev** [comment]
Why are you using TelemetryTrace directly?

This class is no meant to be used by an end user application as it should only be initialized from the TelemetryContext, which in turn is always initialized with a core instance that has a logger?
