### ISSUE TITLE
AlmondJS 

### ISSUE THREAD

**Issue by rinobatin** [microsoft/ApplicationInsights-JS#1566]
I got an ASP.NET Core MVC web app with Application Insights. AI is setup using [Snippet Setup](https://github.com/microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup) with no other custom code related to AI. 

There is a group of forms in the web app that is using AlmondJS. The code here has no reference to AI. A year ago (around March 2020) we started getting errors like below. It seems random. Now, we getting it more often. 

Does anyone have an idea what could be the reason and how to fix it?

```json
"message": "Uncaught Error: See almond README: incorrect module build, no module name",
"stack": [
{
	"columnNumber": 19,
	"lineNumber": 414,
	"fileName": "http://server1:37000/dist/lib/js/almond.js?v=ijt5Z1YMH6gCsqvBf7sezJW1FFnlRbvpKiGrMxhRx4E",
	"functionName": "define",
	"source": "    at define (http://server1:37000/dist/lib/js/almond.js?v=ijt5Z1YMH6gCsqvBf7sezJW1FFnlRbvpKiGrMxhRx4E:414:19)"
},
{
	"columnNumber": 23,
	"lineNumber": 57,
	"fileName": "https://az416426.vo.msecnd.net/scripts/dist-esm/Init.js",
	"functionName": "message"
}
]
```

**Comment by MSNev** [comment]
Does your site use or load require.js?

There is a possible race condition around the default package format and pages that use requirejs before the SDK is initialized, in that in can cause the SDK to fail to initialize. Not sure if this is the same issue as you are seeing, as this mostly occurs in sharepoint hosted pages.

To work around this we now also publish a global (iife) module to the CDN that you could try using it, just update the src file for the snippet configuration.
- https://js.monitor.azure.com/scripts/b/ai.2.gbl.min.js

The only difference is how rollup creates and initializes the module, all other code is identical.

**Comment by rinobatin** [comment]
@MSNev  thanks for the reply.

RequireJS is not used.

I will review your suggestion. Thank you so much!
