### ISSUE TITLE
[BUG] Unit of "PageVisitTime" is well hidden

### ISSUE THREAD

**Issue by onionhammer** [microsoft/ApplicationInsights-JS#1567]
I assume its milliseconds?

**Comment by MSNev** [comment]
Yes, it's milliseconds (I had to dig into the code to confirm as well).

Will Keep this issue open to add documentation around this.

Fix notes
- We need to add/update any existing documentation (within this repo *.md and on AzureDocs) to identify unit value of this field, and if it's not already documented add additional describing how it's calculated (via Date.now())

**Comment by MSNev** [comment]
Now fully deployed to all CDN endpoints
