### ISSUE TITLE
track request takes too much time

### ISSUE THREAD

**Issue by roman-76** [microsoft/ApplicationInsights-JS#157]
Sometimes the track operation takes relatively very long time to complete and other requests are blocked till track completes.
![long track](https://cloud.githubusercontent.com/assets/6941230/13797378/61f7ab72-eaca-11e5-8140-1dd82ae5d4af.jpg)
Testing on Windows 10, IE version 11.162.10586.

Is there any way to take this request from critical path?

**Comment by SergeyKanzhelev** [comment]
Side note: 

@lukekim - OPTIONS call takes quite some time. I'm not sure whether it's blocking all other traffic, but it will be great to speed up this call anyway as it's preventing us from sending telemetry.

**Comment by AlexBulankou** [comment]
OPTIONS call is a CORS requirement (https://www.w3.org/TR/cors/#preflight-request). Can you include the breakdown of where these 2 seconds are going - my guess is that big part of it is DNS lookup and Connect, which depends on how the request is routed and not something we can address from SDK. 
Also the OPTIONS call to /track is not blocking - it is only blocking GET /track call, but not other AJAX or resource calls on the page.

**Comment by lukekim** [comment]
We'll take a look into it.

**Comment by roman-76** [comment]
![long track2](https://cloud.githubusercontent.com/assets/6941230/13853060/3bdb0336-ec22-11e5-8352-261e59494c1e.jpg)
Most of the time goes to download.

**Comment by roman-76** [comment]
@AlexBulankou, I didn't see GET /track calls, do you mean /POST or I'm using wrong JS script on my page? I took it from azure portal about month ago.

**Comment by MaxShehovtsov** [comment]
@roman-76 POST /track (there's no get /track)

**Comment by AlexBulankou** [comment]
Discussed some more offline - the next step is to temporarily enable telemetry to record how long the call to Track() takes on average and then compare this for various locations.

**Comment by markwolff** [comment]
I believe this issue has gone stale. Reopen if you are still seeing long track times
