### ISSUE TITLE
Does applicationInsights SDK support send batch event synchronously 

### ISSUE THREAD

**Issue by ruowan** [microsoft/ApplicationInsights-JS#1577]
**Is your feature request related to a problem? Please describe.**
Here is my service scenario. Worker service subscribe Azure eventhub, process events from eventhub and output result to ApplicationInsights.  As I know applicationInsights SDK process result and telemetry asynchronously.  But worker service seems applicationInsights process rate is slower than process events from eventhub. When there are high traffic event comming in, it cause many result items pipe up in applicationInsights SDK buffer and memory goes up to limit finally OOM.

I think maybe there is a bottleneck in applicationInsights. 

**Describe the solution you'd like**

I would like to make applicationInsights SDK process event synchronously. For example, worker service pull batch events from eventhub and output batch result to applicationInsights synchronoulsy. it means worker service will not pull next batch events from eventhub until the current batch is prccessed and applicationInsights SDK buffer is flushed.

I want applicationInsights support two features:

- expose current buffer length, so we could monitoring whether there are some data is block in applicationInsights buffer or queue.
- support explicitly send batch result or telemetry synchronously 

**Describe alternatives you've considered**

**Additional context**
Really apprecicate you could give some advice or some techincal detials. Thanks~

**Comment by ruowan** [comment]
Thanks for your answer. How can I add my customized NotificationListener? I am using applicationInisights-nodejs sdk.

**Comment by MSNev** [comment]
Ah, I don't work on that project. But looking at the code (https://github.com/microsoft/ApplicationInsights-node.js) it doesn't seem to support the NotificationListener or manager interface so I think the answer is you can't. And the primary person for this project is currently away...

**Comment by ruowan** [comment]
So sad.. Btw, what's the difference between applicationInsights-node.js and ApplicationInsights-JS

**Comment by xiao-lix** [comment]
@ruowan [applicationInsights-node.js](https://docs.microsoft.com/en-us/azure/azure-monitor/app/nodejs) monitors your backend services and components, [ApplicationInsights-JS](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript) monitors the performance and usage of your web page or app.
