### ISSUE TITLE
[BUG] URL without host fails in CanIncludeCorrelationHeader

### ISSUE THREAD

**Issue by panda7789** [microsoft/ApplicationInsights-JS#1580]
**Description**

When fetching url without host like this:
`"../../api/v01/as/descriptions/Attributes?className=Polozky_smlouvy"`
in method canIncludeCorrelationHeader it fails on parsing host, because url doesnt have host (missing www.host.com on begin).

![image](https://user-images.githubusercontent.com/6593380/121994909-6b190880-cda6-11eb-970f-da06eaa631f8.png)
![image](https://user-images.githubusercontent.com/6593380/121994946-79ffbb00-cda6-11eb-8077-9e0a00592673.png)

**Steps to Reproduce**

 - OS/Browser: Edge
 - SDK Version [e.g. 22]: `@microsoft/applicationinsights-web:` `2.6.2`
 - How you initialized the SDK: 
 ```javascript
 new ApplicationInsights({
        config: {
            instrumentationKey: iKey,
            disableCorrelationHeaders: false,
            disableFetchTracking: false,
            disableAjaxTracking: false,
            enableRequestHeaderTracking: true,
            maxAjaxCallsPerView: 200,
            correlationHeaderDomains: ["app2.loc", "app1.loc", "portal.loc/api/"]
        }
```

**Expected behavior**

It shouldn't fail, local api calls should be ok.

**Comment by MSNev** [comment]
Agree it should not fail / throw

**Comment by MSNev** [comment]
Now fully deployed to all CDN endpoints
