### ISSUE TITLE
[BUG] trackDepencyData is not called but my application keep sending AJAX trace to appInsight

### ISSUE THREAD

**Issue by graphicsxp** [microsoft/ApplicationInsights-JS#1584]
I see that RemoteDepencyData is sent to appInsight although in my logger service I did not call `trackDependencyData` anywhere.
![image](https://user-images.githubusercontent.com/4160415/122353646-8758a900-cf50-11eb-94db-1c7c8a13477a.png)

How can I turn this feature off ?

**Comment by xiao-lix** [comment]
Ajax requests are automatically tracked. You can turn off Ajax tracking by configuring `disableAjaxTracking: true` and this will turn off all ajax tracking, it is false by default. If you want to exclude specific route tracking,  we just added a configuration to do that (for both ajax and fetch requests): `excludeRequestFromAutoTrackingPatterns: string[] | RegExp[]`. This will be in next release.

**Comment by MSNev** [comment]
Ajax requests don't call the public ```trackDependencyData``` api, they directly call an internal helper.
