### ISSUE TITLE
ai_user cookie not present after reenabling the cookie

### ISSUE THREAD

**Issue by julen-folky** [microsoft/ApplicationInsights-JS#1585]
My app (Vue) starts with the cookies disabled (`disableCookiesUsage` set to `true`).
When the user consents cookies, the app enables the cookies (`getCookieMgr().setEnabled(true)`).
After a breve navigation the `ai_session` is set but the `ai_user` is not.
I recently moved to the lastest version of the package (from 2.5.X to 2.6.2).
Is this an issue, somehting I am missing or just the `ai_user` is no longer used?

**Comment by MSNev** [comment]
Simply, re-enabling cookies does not cause the code that creates cookies to execute -- likewise disabling cookies doesn't delete them.

The ai_user cookie is still used, but it's only "created" as part of the creating (loading) of the SDK...

The assumption is that the next time your app/page loads cookies will be enabled and therefore the ai_user would get created...

As your using Vue, can I assume your case is a SPA and you won't be "reloading" and therefore "creating" an instance?

**Comment by julen-folky** [comment]
Exactly, after the first load the page will not be load again.
If the ai_user is not set, I guess some info is not going to be collected (before your reply I assume that if ai_session would be in charge of that in 2.6.2).
Should I manually set the cookie? But, how can I know its value?
(BTW, thank you for your help)

**Comment by MSNev** [comment]
users and sessions are slightly different concepts.
So with no user cookie the user would be considered to be effectively "anonymous" (same as if the user blocked cookies on the browser) and therefore they would be lumped together (I'm not sure how this is visualized in the portal)
And the session is "refreshed" after around 30mins (depending on whether the user stays active)

In theory you could set the value yourself but that is not supported and will be potentially broken in a future release.

We already have a ```setAuthenticatedUser``` which you could possibly use as a fudge to workaround this (when stored in the cookie it is a session cookie)
```_self.setAuthenticatedUserContext = (authenticatedUserId: string, accountId?: string, storeInCookie = false) => {```

I'm going to mark this Issue as an enhancement on the basis that we should add a new function suggestion ```setUserCookie``` to handle this scenario. Not currently sure on the timing of when this might get added.

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints
