### ISSUE TITLE
[BUG] namePrefix is not getting assigned to ai_user Cookie

### ISSUE THREAD

**Issue by ThaminduDilshan** [microsoft/ApplicationInsights-JS#1586]
**Description/Screenshot**
As for the documentation we can set a name postfix for localStorage and cookie name (by passing the config parameter `namePrefix`). But this postfix only get assigned to the `ai_session` cookie and not for the `ai_user` cookie.

I'm using the javascript sdk with react plugin for a react frontend application.

 - OS/Browser: Google chrome 91.0.4472.101
 - SDK Version [e.g. 22]: 2.6.2
 - How you initialized the SDK: NPM Setup

**Expected behavior**
After removing cookies and letting sdk to recreate them, following are the cookie names,
- `ai_session<postfix>`
- `ai_user`

**Comment by MSNev** [comment]
Now fully deployed to all CDN endpoints
