### ISSUE TITLE
trackMetric does not support setting custom properties

### ISSUE THREAD

**Issue by phmiller** [Microsoft/ApplicationInsights-JS#159]
Unlike the .NET library, this library does not allow you to pass in additional properties to the .trackMetric function.

You can do it for the other types of telemetry like events and dependencies, but not metrics.

ContractsModule.Contracts.MetricData object has a spot for properties, so doesn't seem like it would break the model.

**Comment by SergeyKanzhelev** [comment]
It does according to https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md
```
trackMetric(name: string, average: number, sampleCount?: number, min?: number, max?: number, properties?: {[string]:string})
```

**Comment by phmiller** [comment]
My apologies; I meant to open this issue for the NodeJS library at: https://github.com/Microsoft/ApplicationInsights-node.js

I'll close it out
