### ISSUE TITLE
Error in building application after using Application Insights Version 2.6.3

### ISSUE THREAD

**Issue by harlkaur** [microsoft/ApplicationInsights-JS#1598]
Hi Team,

When I try to do npm run prod using "@microsoft/applicationinsights-web": "2.6.3" version I get following error :
ERROR in ./src/app/pages/portal-pages.module.ngfactory.js
Module not found: Error: Can't resolve '@microsoft/applicationinsights-web/types/Initialization' in 'C:\....\src\app\pages'

While when I try to use "@microsoft/applicationinsights-web": "2.2.2" version, I am able to run the prod build fine with no errors.

Please Note : I have added this version under "dependencies" section in my package.json file.

I dont get this error when I use "@microsoft/applicationinsights-web": "2.2.2" version.
Kindly let me know if the issue is with "@microsoft/applicationinsights-web": "2.6.3" compatibility with NPM or I have missed anything from my end.

My package.json:
"dependencies": {
"@microsoft/applicationinsights-web": "2.6.3"
}

Main App Module
providers: [
{
provide: ApplicationInsights,
useFactory: (randomService: RandomService) => () => randomService.appInsightsFactory(),
deps: [RandomService]
}

I have also written utility class by passing instrumentation key and calling this class in my application:
appInsightsFactory(): ApplicationInsights {
return new ApplicationInsights({
config: {
instrumentationKey: "....."
}
});
}

Shall be waiting to hear back at the earliest.

Thanking in advance.

**Comment by MSNev** [comment]
I just downloaded and checked the npm package and everything looks fine.
- the types are included in the types/ folder
- the package.json reference to this folder is correct  ``` "types": "types/applicationinsights-web.d.ts",```
- And the local references to the ```Initialization``` class is also defined and referenced correctly...

We have not changed the version of TypeScript that we are using (yet) -- it's still compiled with TS 2.5.3, so there should be no reference / compatibility changes

The only differences that i see are 
- v2.6.3 we are now also including (in the dist folder) a rollup version of the declarations dist/applicationinsights-web.d.ts
- Previously the *.d.ts files where included in the dist-esm/ folder v2.2.2 and in v2.6.3 they are now included in the types/ folder

Perhaps your build system is still referencing or caching the older versions in the dist-esm folder???

**Comment by harlkaur** [comment]
Thanks for your response, then does it mean everytime we need to run npm clean to remove the previous referencing or caching.
Since in 2.2.2 I don't see any errors even when build happens multiple times at a time.

Are there any better ways to overcome this challenge in 2.6.3 version?

**Comment by MSNev** [comment]
Generally, whenever you "updated" versions it is goo d practice to do a clean build. In this case the issue (I think) is because during the upgrade the locations changed (we changed so that all of our components are now in the types/ folder -- this was (from memory) the only one that wasn't).

So once your up and running on the 2.6.3 version it should be the same as 2.2.2, for reference this was changed in v2.6.0 in response to bug #1496 with commit #1501

**Comment by Yohlo** [comment]
Having this same issue for a new project (so clean install, no previous version used) for version 2.6.4. We use the library in a separate project at version 2.2.4, so we rolled back this project to that version for now to get it working. Just wanted to share that we're getting the same issue when doing a clean build!

**Comment by harlkaur** [comment]
Even for me, I removed version 2.2.2 ( rolled back which I was using initially ) and did proper clean install and then added 2.6.3 version to my package.json file, installed it to have node_modules reflecting types folder and the changes added as part of 2.6.3 version.
Post this, I don't get error while trying to build my project locally but I do get same error while trying to build my application in production environment.

**Comment by MSNev** [comment]
Can either of you provide a simple repo? Does this only occur with an Angular Project?

**Comment by harlkaur** [comment]
Hi, I have shared sample util class in my first comment. and Yeah, I have only tried with Angular project and faced this issue. 
Haven't tried using appInsights with any other language.

**Comment by MSNev** [comment]
@xiao-lix can you have a look please.

**Comment by xiao-lix** [comment]
hi @harlkaur sorry for late reply, I missed the message above. 

I tried to repro your issue but was unable to do so, can you please take a look at the demo app I set up [here ](https://github.com/xiao-lix/angular-clean-app-with-AI/tree/lxiao/randomService)and see anything I'm missing? NOTE: on `lxiao/randomService` branch. I don't have building error but also not able to see appinsights sending any telemetries. 

We recommend to put AppInsights creation as early as possible, an example usage on angular app is [here](https://github.com/microsoft/applicationinsights-angularplugin-js#basic-usage). Also, you could try angular plugin, but that should not impact building without it. 

Please let me know how to properly repro your issue. Thanks.
