### ISSUE TITLE
[BUG] empty messages for unhandled promise rejections

### ISSUE THREAD

**Issue by JohnnyFun** [microsoft/ApplicationInsights-JS#1608]
**Description/Screenshot**
`message` is passed as `theEvent` from `Exception.CreateAutoException`. Should `evt` been passed instead? And/or should you fall back to `theEvent` if it's a `string`?

![image](https://user-images.githubusercontent.com/8106379/125534060-8fc0b808-b359-4ac0-b33e-538a90b0c8f5.png)

![image](https://user-images.githubusercontent.com/8106379/125533820-c10f5eb3-1288-4985-ad21-776cbb3add1d.png)

Results in these empty error messages, so I don't see the actual error.
![image](https://user-images.githubusercontent.com/8106379/125534276-2c76f2cd-816b-4daa-baf4-08d555411b02.png)

 - SDK Version: 2.6.4

**Comment by MSNev** [comment]
> Should evt been passed instead?

No

> And/or should you fall back to theEvent if it's a string?

Yes

**Comment by MSNev** [comment]
The fix is going to look like this

>        if (evtMessage && !isString(evtMessage)) {
>            evtMessage = theEvent[strMessage] || theEvent[strDescription] || evtMessage;
>        }

**Comment by JohnnyFun** [comment]
Sounds good, thanks for jumping on that. I'll just downgrade for now. When do you think that'll be released?

Fwiw, my stack trace also was empty. Looking at the code it _looks_ like it would've used `error.stack`, so not sure why that happened. But I'll let you know if I find anything.

**Comment by MSNev** [comment]
At the moment it will be the next cycle so we will start this process in the first week of August

**Comment by MSNev** [comment]
v2.6.5 is now fully deployed

**Comment by JohnnyFun** [comment]
Looks like message is coming through now, but there appears to be no stack trace.

It used to show up in this "details" section from azure insights UI:
![image](https://user-images.githubusercontent.com/8106379/134076534-bad76156-7a89-4cca-a8f1-86fa6ba61bc8.png)

The user was using chrome 92, so shouldn't be a browser issue where it just provides a terrible `error.stack` value or something.

Let me know if you need any other information. Worst case, I might just add that as a custom dimension for now.

**Comment by MSNev** [comment]
#1679
