### ISSUE TITLE
[BUG] error logging an error--need to null-check `reason`

### ISSUE THREAD

**Issue by JohnnyFun** [microsoft/ApplicationInsights-JS#1610]
**Description/Screenshot**
We receive some errors in our insights "undefined is not an object (evaluating 't.reason.toString')". That line of error-handling code just probably needs to not assume `reason` is there and maybe fallback to `message` or something?

**Steps to Reproduce**
Not sure what underlying error is, but it'd be an error without a `reason` property somehow. The error came from Mac OS X 10.13 Safari 12.1, so that might have something to do with it.

 - SDK Version [e.g. 22]: 2.6.2
 - How you initialized the SDK:

```
appInsights = new ApplicationInsights({
    config: {
      instrumentationKey,
      enableUnhandledPromiseRejectionTracking: true,
      // We only want to log errors for debugging.
      disableAjaxTracking: true,
      disableFetchTracking: true,
    },
  })

  appInsights.loadAppInsights()

  appInsights.addTelemetryInitializer(item => {
    const customDimensions = buildCustomDimensions(true)
    const props = (item.baseData.properties = item.baseData.properties || {})
    for (const key in customDimensions) props[key] = customDimensions[key]
  })
```

**Comment by MSNev** [comment]
Agree, this looks like it occurring within the onunhandledrejection promise handler.

**Comment by MSNev** [comment]
v2.6.5 is now fully deployed
