### ISSUE TITLE
Option to exclude HTTP OPTIONS (CORS Pre Flight requests) 

### ISSUE THREAD

**Issue by pulkitpatel95** [microsoft/ApplicationInsights-JS#1615]
I am using Application Insights in our application(.NET Core backend, Angular frontend). 
Currently all the requests are logged to Application Insights including the CORS pre-flight requests. This increases the unnecessary data which affects data throttling and sampling.

![image](https://user-images.githubusercontent.com/59560083/126322304-225bf157-b34e-4ceb-9eb6-98cf3cfe4712.png)
 

Is there a way/configuration to stop logging CORS pre-flight requests to Application Insights ?

**Comment by MSNev** [comment]
This is not occurring from the JS SDK side of things as we don't get to play with the OPTIONS call from JavaScript.

This will be from the server side of things, so the SDK you are using for the .Net Core backend, which version are you using and I'll try and find the correct place to redirect this question to.

For the JS SDK perspective you can confirm that this is not coming from the client by using fiddler (or F12) to monitor the network traffic for the events that are sent in the "track" request. Or you could also try using the Debug Plugin -https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-debugplugin-js to visualize the requests (this is designed to be used during development only)

**Comment by pulkitpatel95** [comment]
We are using Microsoft.ApplicationInsights.AspNetCore (2.12.1). Should we use ITelemetryProcessor to filter such requests?

Here is a code snippet

![Telemetry-Processor-AI](https://user-images.githubusercontent.com/59560083/126441888-4338cc9f-2c20-4f4f-b4bc-5767a1ca30d8.png)

**Comment by reyang** [comment]
> We are using Microsoft.ApplicationInsights.AspNetCore (2.12.1). Should we use ITelemetryProcessor to filter such requests?

Yes.

**Comment by pulkitpatel95** [comment]
Thanks, I was able to exclude OPTIONS request by implementing ITelemetryProcessor.
