### ISSUE TITLE
Help logging Authenticated User IDs

### ISSUE THREAD

**Issue by afogarty85** [microsoft/ApplicationInsights-JS#1616]
I would like to log authenticated users visiting my Azure static web app (using AAD). My App Insights is working with this snippet: https://github.com/Microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup, but I cannot figure out how to track the names of authenticated users with just this setup. In my App Insights logs, I have no entries for `user_AuthenticatedId`. Any *insight* for the non-webdev inclined is appreciated!

**Comment by MSNev** [comment]
By default the SDK does not gather authenticated user details, you need to call the ```appInsights.setAuthenticatedUserContext(...)```  to tell the SDK the details you want recorded and depending on your privacy / legal requirements you should also mask this value as it is normally PII (Personally identifiable information).

https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/API.md#setauthenticatedusercontext

**Comment by afogarty85** [comment]
Thanks for the feedback! Any idea how that would look in practice, exactly like below?

```
<script type="text/javascript">
... truncated for clarity
cfg: { // Application Insights Configuration
    instrumentationKey: "INSTRUMENTATION_KEY"
}});
setAuthenticatedUserContext(authenticatedUserId: string, accountId?: string, storeInCookie = false)
</script>
```

**Comment by MSNev** [comment]
As the snippet provides a proxy for this function yes, pretty much as you have it.

```
<script type="text/javascript">
... truncated for clarity
cfg: { // Application Insights Configuration
    instrumentationKey: "INSTRUMENTATION_KEY"
}});
var authUserId = "...";  // Set on the server ir lookup meta tags etc
var accountId = "...";
appInsights.setAuthenticatedUserContext(authUserId , accountId , true);
</script>
```

The other option would be to create and use an onInit() callback and set in there -- same result
https://github.com/microsoft/ApplicationInsights-JS#example-using-the-snippet-oninit-callback

**Comment by afogarty85** [comment]
Thank you very much; I was able to generate the information necessary with this extra help!
