### ISSUE TITLE
[BUG]: Plugin does not capture click events on div elements - applicationinsights-clickanalytics-js

### ISSUE THREAD

**Issue by msemkowicziwanow** [microsoft/ApplicationInsights-JS#1618]
**Description/Screenshot**
Using the plugin setup as in the example click events on div elements are not registered.
Rest of click actions on inputs, buttons etc. are send according to expectations 
**Steps to Reproduce**
1. Setup the plugin according to the given example
2. Set a data-custom-id="test" on a div element. 
3. Assign a simple onClick function (just a console.log()) to that div
4. Click on the div. Console print will be triggered but in the app insight you will never get the related event

 - OS/Browser: Win 10/ Chrome
 - SDK Version [e.g. 22]: 2.6.4
 - How you initialized the SDK: npm 

**Expected behavior**
Click events are also traced for div elements

**Comment by kryalama** [comment]
@msemkowicziwanow you have to use `parentDataTag` in the config to capture values from all the parent HTML elements of the clicked element. Here is an [example](https://github.com/Azure-Samples/Application-Insights-Click-Plugin-Demo) with  `parentDataTag` usage.

**Comment by timhoekstra** [comment]
As far as I can tell the only supported tags are A, AREA, IMG and INPUT when i look in the getClickTarget method in `DataCollector.ts`.

Would it be possible to expose `pageAction.capturePageAction` on the ClickAnalyticsPlugin in addition to the already exposed `pageAction.trackPageAction` so I can track a page action easily without having to fill in all the properties (like timeToAction and refUri) manually and only provide what I want to override?
