### ISSUE TITLE
[BUG] Request-Id header and telemetryItem.baseData.id do not match

### ISSUE THREAD

**Issue by thoo1** [microsoft/ApplicationInsights-JS#1625]
**Description/Screenshot**
We are using the Request-Id header as a key to add some extra info in our telemetry initializer which we add using `this.appInsights.addTelemetryInitializer`

In the telemetry initializer, we have access to the `telemetryItem: ITelemetryItem`. We are finding that `telemetryItem.baseData.id` is not the same as the Request-Id sent on each request

For example
Request-Id header (notice no trailing dot)
![image](https://user-images.githubusercontent.com/55852795/128089452-9febb368-de9c-4b76-bb52-9cad1a37e965.png)

`telemetryItem.baseData.id` in telemetry initializer:
![image](https://user-images.githubusercontent.com/55852795/128089405-665d1e0b-d5d4-4585-8534-26c93081190d.png)

**Steps to Reproduce**

 - OS/Browser: Windows/Chrome 92
 - SDK Version [e.g. 22]: 2.6.4
 - How you initialized the SDK: 
 ```
     this.appInsights = new ApplicationInsights({
      config: {
        instrumentationKey: Environment.config.appInsightsInstrumentationKey,
        endpointUrl: Environment.config.appInsightsEndpointUrl,
        extensions: [this.reactPlugin],
        extensionConfig: {
          [this.reactPlugin.identifier]: { history }
        },
        disableFetchTracking: false,
        disableAjaxTracking: false,
        enableCorsCorrelation: true,
        disableCorrelationHeaders: false,
        enableAutoRouteTracking: true,
        maxAjaxCallsPerView: -1,
        enableResponseHeaderTracking: true,
        correlationHeaderExcludedDomains: [plotlyDomain, dynatraceDomain, appInsightsDomain],
        idLength: 5
      }
    });
```

**Expected behavior**
That the two should match. The impact of them not matching is that the map our application maintains that contains this extra enrichment info, never gets a cache hit so the enrichment does not occur

**Additional context**

**Comment by MSNev** [comment]
Not sure I'm following... They look the same to me (except for the trailing ```.```) which is required for encoding purposes by the server for distributed tracing support.

**Comment by MSNev** [comment]
Note recommended: But if you disabled W3C Tracing (it's on by default) the ```.``` won't get added 
config.distributedTracingMode = DistributedTracingModes.AI

This will then revert to the legacy Application Insights format (which doesn't have the trailing ```.```) -- depending on your usage this may have adverse side effects in the portal with linking to other services etc.
