### ISSUE TITLE
[BUG] enableAjaxErrorStatusText: false (which is the default setting) does not turn off logging error response body

### ISSUE THREAD

**Issue by thoo1** [microsoft/ApplicationInsights-JS#1640]
**Description/Screenshot**
Our application does not set anything for `enableAjaxErrorStatusText` config. However we notice that our dependency logs contain `responseText`. I grepped for ["enableAjaxErrorStatusText" in the repo](https://github.com/microsoft/ApplicationInsights-JS/search?q=enableAjaxErrorStatusText) and could not find where the config was being checked (unless I'm missing something)

**Steps to Reproduce**
Do not set a value for `enableAjaxErrorStatusText` config - make an XHR call that returns an error that has some string in the body. Notice that the body is logged in the `responseText` customDimensions in application insights

 - OS/Browser: Windows 10/Chrome 92
 - SDK Version [e.g. 22]: 
 @microsoft/applicationinsights-web: 2.6.4
 @microsoft/applicationinsights-dependencies-js: 2.6.4

 - How you initialized the SDK:
 ```js
     this.appInsights = new ApplicationInsights({
      config: {
        instrumentationKey: Environment.config.appInsightsInstrumentationKey,
        endpointUrl: Environment.config.appInsightsEndpointUrl,
        extensions: [this.reactPlugin],
        extensionConfig: {
          [this.reactPlugin.identifier]: { history }
        },
        disableFetchTracking: false,
        disableAjaxTracking: false,
        enableCorsCorrelation: true,
        disableCorrelationHeaders: false,
        enableAutoRouteTracking: true,
        maxAjaxCallsPerView: -1,
        enableResponseHeaderTracking: true,
        correlationHeaderExcludedDomains: [plotlyDomain, dynatraceDomain, appInsightsDomain],
        idLength: 5
      }
    });
```

**Expected behavior**
The body of an xhr error should not be logged in the `responseText` customDimensions in application insights if `enableAjaxErrorStatusText` is false

**Additional context**

**Comment by swvickers** [comment]
It appears like the config check was removed in this commit https://github.com/microsoft/ApplicationInsights-JS/commit/7afceba8a2bcece44d24da42987341b77d6dca18#diff-1c3b823ec51f579cfe4d856af82e4dda4f6f05b38fb9bd7555b51d9db8ccc76d

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints
