### ISSUE TITLE
trackEvent() doesn't allow replacing the iKey

### ISSUE THREAD

**Issue by Karlie-777** [microsoft/ApplicationInsights-JS#1642]
`trackEvent()` doesn't allow replacing the iKey
need to add this as an optional value for the IEventTelemetry

**Comment by Karlie-777** [comment]
linked to issue https://github.com/microsoft/ApplicationInsights-JS/issues/1595

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints
