### ISSUE TITLE
[BUG] CustomMetrics not logging value attribute anymore

### ISSUE THREAD

**Issue by riteshbhoi** [microsoft/ApplicationInsights-JS#1652]
CustomMetrics not logging value attribute.

 - SDK Version [e.g. 22]: 2.5.7

We used to pass value to average attribute as below

`let metric = {
            name: name,
            average: value,
            max: max,
            min: min,
            sampleCount: sampleCount
};`

average was getting logged to value attribute (as shown below in portal.azure > app insights)
![image](https://user-images.githubusercontent.com/27738317/131581845-347f490c-5754-4199-9098-f9d8c4f96a1c.png)

But since yesterday, value attribute doesn't have any value 
![image](https://user-images.githubusercontent.com/27738317/131581925-ca66fd2a-225e-4f42-9fe6-20dc2948962e.png)

Find the network call in browser
![image](https://user-images.githubusercontent.com/27738317/131586915-f3afcf01-947d-4a9a-8641-6c79b442881b.png)

**Comment by MSNev** [comment]
There has been no updates to the SDK in the last few days and it looks like you are specifically using v2.5.7.

As such this doesn't appear to be an SDK issue (this GitHub is only for the JavaScript SDK issues), this looks like an ingestion / server issue. Especially as it looks like the data is still being sent from the SDK (the outbound network request).

**Comment by riteshbhoi** [comment]
Yes @MSNev , i believe this could be an ingestion issue. Will follow up with azure App Insights team for this. Thank you
