### ISSUE TITLE
[BUG] ITelemetryTrace parentId cannot be set to undefined

### ISSUE THREAD

**Issue by zmarty** [microsoft/ApplicationInsights-JS#1660]
App Insights Browser (JS) SDK

I think this is a bug in your TypeScript types and parentId shoud be nullable. I verified in the browser that the first time an operation starts its parent is set to undefined, so why can't I do the same? I specifically want to be able to set parentId to undefined for my purposes, since I track router changes myself.

The ITelemetryTrace interface says parentId should be string:
![image](https://user-images.githubusercontent.com/330396/132142976-c283210d-0950-4c8d-b4d7-64a08f44b6dd.png)

But TelemetryTrace (which implements ITelemetryTrace) allows setting it to undefined:
![image](https://user-images.githubusercontent.com/330396/132143012-bf792161-3f31-4eab-a4a0-bbe7f96ffcbf.png)

Here's the ugly workaround I used:
```javascript
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
this.appInsights.context.telemetryTrace.parentID = parentId!;
```

(where parentId can be undefined)

**Comment by MSNev** [comment]
I think the compile failure would be because of your eslint config, by default we are only using
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:security/recommended"

Having said that after looking at the code, I can't see any reason why this can't be optional

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints
