### ISSUE TITLE
Allow properly disposing AI

### ISSUE THREAD

**Issue by olee** [microsoft/ApplicationInsights-JS#1667]
I am using application insights through npm in a web application and also running the project in nodejs for jest tests.
However, because [`AppInsightsCore.pollInternalLogs`](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts#L72-L94) creates a `setInterval` which handle is never stored and there is no way to dispose of it, jest never manages to shut down properly.

Would you mind properly storing the returned handle from the `setInterval` and provide some kind of `dispose` function to stop this polling?

Alternatively, could it be possible to add an option by eg. setting `diagnosticLogInterval` to `0` to completely disable this polling?
From my tests I noticed that this internal queue never seems to be used anyway and always stays empty.

EDIT: For now I managed to disable this feature by executing this code before AI initialization:
```ts
        const ai = new ApplicationInsights({ config: { /* ... */ } });
        // Disable pollInternalLogs to prevent jest from properly shutting down
        ai.pollInternalLogs = () => undefined;
        ai.loadAppInsights();
```

**Comment by kryalama** [comment]
Setting the interval to 0 might not solve the problem. setInterval actually has a minimum amount which is implicit, and depends on the browser. I believe it is around 10ms. We can just return without creating a setInterval when diagnosticLogInterval is set to 0.

**Comment by olee** [comment]
@kryalama that was of course what I was implying.
If it worked that way, I would have solved it by setting it to 0 of course 😂
