### ISSUE TITLE
[BUG] v2.7.0 has unmet peer dependency "tslib@*""

### ISSUE THREAD

**Issue by zmarty** [microsoft/ApplicationInsights-JS#1670]
Upgrading @microsoft/applicationinsights-web from v2.6.5 to v2.7.0

"warning "@microsoft/applicationinsights-web > @microsoft/applicationinsights-common@2.7.0" has unmet peer dependency "tslib@*""

A couple of years ago there was an issue opened about a similar problem: https://github.com/microsoft/ApplicationInsights-JS/issues/1114

The solution for that issue was to move tslib to be a normal depenendency: https://github.com/microsoft/ApplicationInsights-JS/pull/1116/commits/c17211995a77006772537ab569b627b6fe8a7008

However, tslib was recently re-introduced as a peer dependency: https://github.com/microsoft/ApplicationInsights-JS/commit/f3f1a806c53d036a1bdcf92ecc44185bdce6b121#diff-d5c3a687c6bf5f5270b1404de1123ae678bd1546a159fd5c7b2d1cd6f21d247b

**Comment by MSNev** [comment]
I'm not sure we can simply "add" tslib as a dependency this time as it would cause people to complain about incompatible versions as we are supporting TypeScript versions which use tslib 1 and 2, hence the peerDependency of "*" stating that we work with any version.

Technically, we don't actually "need" tslib for the core components as we "rewrite" the generated *.js files to remove the tslib references. And it's here mostly for products that want to consume the *.ts files instead.

And as per #1114, it is expected that the consumer have it in their own ```package.json```

**Comment by MSNev** [comment]
What version of TypeScript, build environment and where are you seeing this warning?
Looking at local builds this warning does not appear to be produced while generating the product (but we do have a bunch of warnings (which we are working to reduce) -- so maybe I'm missing it)

**Comment by zmarty** [comment]
Windows 64, Node 16, TypeScript 4.3.4.

The solution is to add tslib in our project, which I did. So it's not a big issue, maybe needs some documentation?

Feel free to close the issue.
