### ISSUE TITLE
[BUG] applicationinsights-web v2.7.0 breaks telemetry in Next.js - isXhrSupported is not a function - needs investigation

### ISSUE THREAD

**Issue by zmarty** [microsoft/ApplicationInsights-JS#1671]
Upgrading @microsoft/applicationinsights-web from v2.6.5 to 2.7.0

Breaks loading of the package in [Next.js](https://nextjs.org/). Needs more investigation.

https://github.com/microsoft/ApplicationInsights-JS/commit/fcef0e04645de6f033b961c49ef50d7a1f10306d#diff-1c3b823ec51f579cfe4d856af82e4dda4f6f05b38fb9bd7555b51d9db8ccc76dL50

![image](https://user-images.githubusercontent.com/330396/133169459-ce0fc45c-2982-4a0b-84d8-02fd86551b2b.png)

![image](https://user-images.githubusercontent.com/330396/133169218-123b9e3d-3e46-4bd8-998e-c526192814e5.png)

**Comment by MSNev** [comment]
This looks like you have a version mismatch as the "isXhrSupported" is a new function added in v2.7.0 (Core) and is used from ajax.ts (dependencies) v2.7.0.

Can you please validate that you are using v2.7.0 for all applicationinsights modules

**Comment by zmarty** [comment]
Yeah that was my thought too. I did upgrade all app insights packages to 2.7.0. However, we also use another internal library (you know which one I mean) which depends on some older versions. So I am trying to remove that library entirely first. Will report back.

**Comment by zmarty** [comment]
@MSNev was right :) Thanks!
