### ISSUE TITLE
Provide an option to disable "SDK LOAD Failure errors"

### ISSUE THREAD

**Issue by Cisien** [microsoft/ApplicationInsights-JS#1672]
Please provide a feature that lets me opt-out of logging "SDK LOAD Failure: ..." errors as browser exceptions. This error frequently happens due to ad blockers and other conditions outside of my control, and I would rather not see the noise along side actual problems.

**Describe the solution you'd like**
I would like to see an option to disable SDK load failures in the javascript snippet.

**Describe alternatives you've considered**
As a workaround, I have removed this code from the snippet, but that's error prone and (for obvious reasons) not supportable by azure.

**Comment by kryalama** [comment]
To my understanding you dont want the snippet to send these failures to Application Insights whenever the SDK failed to load.  Is my understanding correct? We can provide a config to opt-out of logging the exceptions.  But IMHO you might want to know when the SDK failure happened.

**Comment by Cisien** [comment]
That's correct.

In my scenario, this failure has always been caused by ad blockers, or other methods that users are leveraging to block trackers. The end result is an error that I am unable to resolve as it's not a bug, leaving me with only one option, which is to tolerate it. For this reason, I'd like the option to disable this error from making it into the telemetry.
