### ISSUE TITLE
[BUG] Promise rejections missing stack trace

### ISSUE THREAD

**Issue by JohnnyFun** [microsoft/ApplicationInsights-JS#1675]
Stack trace used to show up in this "details" section from azure insights UI:
![image](https://user-images.githubusercontent.com/8106379/134600208-92d3afe4-2f1d-4454-8708-592228d1405f.png)

The user was using chrome 92, so shouldn't be a browser issue where it just provides a terrible `error.stack` value or something.

Let me know if you need any other information. For now, I'll see about adding the `error.stack` to my custom dimensions area.

And fwiw, that's a custom error that we explicitly throw from a js file: throw new Error('Should not call this with student persona.')

 - OS/Browser: chrome 92
 - SDK Version: 2.7.0
 - How we initialized the SDK:
```
appInsights = new ApplicationInsights({
    config: {
      instrumentationKey,
      enableUnhandledPromiseRejectionTracking: true,
      // We only want to log errors for debugging.
      disableAjaxTracking: true,
      disableFetchTracking: true,
    },
  })

  appInsights.loadAppInsights()

  appInsights.addTelemetryInitializer(item => {
    const customDimensions = buildCustomDimensions(true)
    const props = (item.baseData.properties = item.baseData.properties || {})
    for (const key in customDimensions) props[key] = customDimensions[key]
    if (isErrorBenign(item.data)) return false // Don't track item
  })
```

**Additional context**
Might be related to this issue's fix: https://github.com/microsoft/ApplicationInsights-JS/issues/1608. promise rejection stack traces used to show up in the "details" section.

**Comment by Karlie-777** [comment]
Hi @JohnnyFun 
it seems that the image is not attached to your comment, could you please update the image and we can better target the problem?
Thanks!

**Comment by JohnnyFun** [comment]
Oh, sorry about that--had copied/pasted my comment on the closed issue I linked to and didn't see I missed the image.

**Comment by JohnnyFun** [comment]
For now, I'm just tracking the `lastStack` by calling the following prior to setting up my `ApplicationInsights` instance and telemetry handler:

```
let lastStack
...
window.addEventListener('unhandledrejection', e => {
  lastStack = e?.reason?.stack
})

...instantiate app insights and telemetry handler...
```

And then adding `lastStack` into my `customDimensions` in my telemetry handler.

I confirmed that my `lastStack` _is_ populated for that error, but that app insights telemetry envelope has `hasFullStack` set to false. So the error goes into app insights code _with_ a stack trace and gets pooped out without one.

Fwiw, app insights seems to retain the rejected promise rejection's stack trace for simple tests like calling this function:

```
function intentionallyThrowInPromise() {
    new Promise(() => {
      setTimeout(() => {
        throw new Error('CN Dev tools button clicked (Test AppInsights unhandled Promise rejection)')
      }, 100)
    })
  }
```

But for some reason, it doesn't retain the stack trace for my example case where I throw a `new Error` from somewhere deeper. 

I'll let you know if I notice anything else. Let me know if you need/want any other details of my scenario.

**Comment by Karlie-777** [comment]
@JohnnyFun 
Thanks for the details!

After investigation, the major problem that leads to no error trace might be the way we parse `onunhandledrejection`. Currently we throw  `error.reason.toString()` to `Exception.CreateAutoException()` function and the `error.reason.toString()` will expose no detailed trace stack to  `Exception.CreateAutoException()` .  Instead we should use `error.reason.stack.toString()` to enable full trace tracking. 
 
and please let us know if you notice anything else!

**Comment by JohnnyFun** [comment]
Ah, looks like that `CreateAutoException` doesn't pass a `stack` parameter through:

![image](https://user-images.githubusercontent.com/8106379/135353629-a7f51608-75a4-4b69-987e-dc332de6765c.png)

So looks like you just need to pass that through with: `error.reason?.stack`

![image](https://user-images.githubusercontent.com/8106379/135353879-fe1b1aa6-da53-40ae-895d-ea67a45d2e4d.png)

**Comment by JohnnyFun** [comment]
I'm _pretty_ sure unhandled promise errors always put their exception on `reason`, so `error.reason?.stack` should suffice. But might want to double check that you don't need something like `error.stack ?? error.reason?.stack`.

**Comment by JohnnyFun** [comment]
Otherwise, yes looks like your strategy would also work since `stackDetails` null coalesce `stack` and fall back to `error`, but if that `stack` parameter is there and just not being passed, it would seem to me it should be passed? :shrug:

![image](https://user-images.githubusercontent.com/8106379/135354354-5ff01218-f9fa-4dbb-8952-635308a1ecbd.png)
