### ISSUE TITLE
Unhandled rejected promise tracking

### ISSUE THREAD

**Issue by oising** [microsoft/ApplicationInsights-JS#168]
http://lists.w3.org/Archives/Public/public-whatwg-archive/2014Sep/0024.html

Putting this here for future implementation. Chrome is currently the only browser that implements it.

**Comment by MaxShehovtsov** [comment]
Interesting! It also leads me to a slightly different idea of auto-instrumenting promises to achieve both rejection handling and performance/profiling of promises.

**Comment by oising** [comment]
A good discussion here, including some input from your own guys (MS)

https://bugs.chromium.org/p/v8/issues/detail?id=3093

**Comment by MSNev** [comment]
Closing this as it appears it will be addressed by #1013, feel free to reopen or commit if I've misread this issue.
