### ISSUE TITLE
Simplify deferred initialization execution with appInsights.queue

### ISSUE THREAD

**Issue by MaxShehovtsov** [microsoft/ApplicationInsights-JS#172]
In some cases this code is needed to ensure proper initialization: 

``` typescript
        if (_appInsights.context) {
            initContextAndInitializers();
        } else {
            // otherwise, schedule this initialization when AI script loaded
            (<any>_appInsights).queue.push(initContextAndInitializers);
        }
```

Let's review typical scenarios for deferred execution. The simplest/silly thing we could do is to make appInsights.queue.push always execute - before and after appInisghts is initialized. E.g. on initialization override queue.push so it executes stuff immediately:

``` typescript
   appInsights.queue.push = (func: () => any) => {
     func();
   }
```

This way initialization logic could become easier: 

``` typescript
(<any>_appInsights).queue.push(initContextAndInitializers);
```

without need to check if _appInsights.context is set.

**Comment by MSNev** [comment]
Closing due to old age and as v1 is no longer being actively maintained
