### ISSUE TITLE
[BUG] Cannot track exception from service worker

### ISSUE THREAD

**Issue by christopher-kiss** [microsoft/ApplicationInsights-JS#1727]
**Description/Screenshot**
Service worker will fail to trackException because there is an unchecked window reference for getting the stack.
![image](https://user-images.githubusercontent.com/24984762/144767757-ceb337c5-caae-4d9b-a07b-9af23c7b2a27.png)

**Steps to Reproduce**
 init app insights inside a service worker with following config: 
```
{ config: { instrumentationKey: 'key here', disableXhr: true, disableFetchTracking: false } })
```
call `trackException(new Error('error'))` and `flush()`

 - OS/Browser: Windows 10 / Chrome 96
 - SDK Version [e.g. 22]: 2.7.1
 - How you initialized the SDK: `new ApplicationInsights(snippet)`

**Expected behavior**
Should be able to send track exception to app insights

**Additional context**
This error happens because we call `window` directly here:
https://github.com/microsoft/ApplicationInsights-JS/blob/91ee603ae3ae6132b1910aabed414eef8890ad02/shared/AppInsightsCommon/src/Telemetry/Exception.ts#L154

This should most likely be `getGlobalInst('opera')` instead so that it safely bails out when window is not available.

**Comment by MSNev** [comment]
Now fully released
