### ISSUE TITLE
[BUG] column using data.name replaced with top-level name field in Telemetry Viewer

### ISSUE THREAD

**Issue by techtor** [microsoft/ApplicationInsights-JS#1734]
**Description/Screenshot**
When using [this config](https://microsoft.visualstudio.com/Universal%20Store/_git/XS.AMC.UX?path=/packages/core-1ds/extension/config.json) with the Telemetry Viewer, the "Name" column sometimes falls back to the `data.name` field. I expect this value to appear in the display, but the top-level `name` field is what actually displays.

![image](https://user-images.githubusercontent.com/421682/145073443-9e596e86-59e4-46af-80c3-63a4438ae3b9.png)

**Steps to Reproduce**

 - OS/Browser: W10 v22000.348, Edge v97.0.1072.13
 - SDK Version [e.g. 22]: N/A
 - How you initialized the SDK: Telemetry Viewer extension v0.2.0

**Expected behavior**
`data.name` field properly displayed instead of top-level `name`.

**Additional context**

**Comment by mbest** [comment]
Might make sense to change the order in [this line](https://github.com/microsoft/ApplicationInsights-JS/blob/00ac3a33decfba77bb53880121524321d18efedc/tools/chrome-debug-extension/src/dataSources/dataHelpers.ts#L144):

```
const value = _.get(dataEvent.data, names[lp]) || _.get(dataEvent, names[lp]);
```

**Comment by MSNev** [comment]
@KevBrown-MSFT does this change make sense from your historical perspective?

**Comment by KevBrown-MSFT** [comment]
If we made that change, how would you specify you want to display the name field in the root of the event?  Today you can specify name and it'll check name and fall back to data.name, or you can specify data.name and it'll find it when it checks the root of the event.

**Comment by mbest** [comment]
@techtor If this won't be fixed, we need to change the config to use `data.data.name` instead of just `data.name`.

**Comment by techtor** [comment]
@mbest Sure. If Nev and Kevin decide to close out this issue, please feel free to open an internal bug directly against me, and I'll update our stored config.

**Comment by MSNev** [comment]
I'm going to let Kevin make the call on this as we inherited this from the original version, so based on.

But the current order "feels" right based on the usage, ie. try on the passed object directly and if it's not there try accessing the "data" sub object (if present)
