### ISSUE TITLE
[BUG] New Fetch keepAlive support can cause duplicate events to be sent during unload processing

### ISSUE THREAD

**Issue by MSNev** [microsoft/ApplicationInsights-JS#1736]
When a browser supports fetch with keepAlive and this is used during page unload, if the page completes page navigation before the response can be processed any sent events will be sent on the next page load.

As a workaround you can disable the fetch keepalive support with the following config

`onunloadDisableFetch`: true

**Comment by MSNev** [comment]
This fix for this will be that when sending a fetch (with keepalive) enabled the code will need to "assume" this as a fire and forget operation (like it does for sendBeacon()) -- this does mean however, that if a partial response is received (generally unlikely) that events may be lost vs the current situation which causes event duplication.

**Comment by harleyz** [comment]
Recently I noticed the duplicate event issue for myself with using the unload event from JS.  I set onunloadDisableFetch flag to true and it is resolved the duplicate events.  I didn't see this on our angular apps, even though we use a similar approach.

**Putting a comment here to follow the issue**

\\ code without the flag set that was creating dups
` cfg: { // Application Insights Configuration
                    instrumentationKey: '@System.Configuration.ConfigurationManager.AppSettings["ApplicationInsightsInstrumentationKey"]',
                    disableFetchTracking: false,
                    disableCorrelationHeaders: false,
                    enableCorsCorrelation: true,
                    correlationHeaderExcludedDomains: ['google-analytics.com','stats.g.doubleclick.net'],
                }`

`    // unload handler
    var handleUnload = function () {
        $(window).on("beforeunload", function () {
            if (!isSessionComplete) {
                var _properties;
                if (IdleTimeout.getIdleCount() > 0) {
                    var _properties = { "idleCount": IdleTimeout.getIdleCount() };
                }
                stopTrackEvent("quoteTimeToRun", _properties);
            }
            return undefined;
        });
    };   `

**Comment by MSNev** [comment]
Deploying to final CDN endpoint
