### ISSUE TITLE
Using a fixed version of the JS SDK snippet

### ISSUE THREAD

**Issue by Piedone** [microsoft/ApplicationInsights-JS#1738]
I was redirected from here: https://github.com/microsoft/ApplicationInsights-dotnet/issues/2165

**Is your feature request related to a problem? Please describe.**

The version of the JS AI SDK changes automatically if you use the auto-updating https://js.monitor.azure.com/scripts/b/ai.2.min.js script. This has bitten me when something changed there, breaking the code I extended it with, without me changing anything. 

**Describe the solution you'd like**
I'd like all AI SDK changes in my .NET app, using the AI .NET SDK to happen explicitly. This is given with the versioning of the .NET SDK's NuGet package, it doesn't auto-update in production, I update it explicitly and then test it when needed. However, the JS SDK used by `JavaScriptSnippet` seems to always be the latest one. 

I'd like to somehow say that "now I'm using the JS SDK version 1.2.3". This can be as simple as providing different versions of the script continuously under their own, version-suffixed URLs.

My code in question is BTW one that sets the operation ID for page view-request correlation because that somehow didn't work for me automatically (Razor, using the .NET SDK):

```html
<script>
    appInsights.queue.push(function () {{
        // Up until a couple days ago this used appInsights.-->properties<--.context.telemetryTrace.traceID.
        appInsights.context.telemetryTrace.traceID = '@System.Diagnostics.Activity.Current.RootId';
    }});
</script>
```

**Describe alternatives you've considered**
I thought about using a hand-crafted version of the snippet but I don't see how such a version could be specified. All snippets just use the auto-updating https://js.monitor.azure.com/scripts/b/ai.2.min.js script.

**Additional context**
N/A

**Comment by Karlie-777** [comment]
Hi @Piedone, if you do not want to auto update snippet,  you can add version number to the snippet URL. For example: https://js.monitor.azure.com/scripts/b/ai.2.7.1.min.js and it will use version 2.7.1 only

**Comment by Piedone** [comment]
Ah, so the "providing different versions of the script continuously under their own, version-suffixed URLs" is actually supported. Great, thanks!
