### ISSUE TITLE
[BUG] excludeRequestFromAutoTrackingPatterns values are not properly excluding dependencies

### ISSUE THREAD

**Issue by vanpyrzericj** [microsoft/ApplicationInsights-JS#1740]
**Description/Screenshot**
It is my understanding that `excludeRequestFromAutoTrackingPatterns` can be used to exclude certain AJAX/XHR/Fetch requests (which show up as `Dependencies` in App Insights dashboards) from being tracked. I have several third-party analytics platforms that regularly send telemetry every few seconds, and are cluttering things up.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/4707908/148630654-49b4c645-4f4d-48da-866e-0dfad1a1d4d8.png">

**Steps to Reproduce**
Using the following configuration:
```
{
        instrumentationKey: '123123',
        autoTrackPageVisitTime: true,
        distributedTracingMode: DistributedTracingModes.W3C,
        correlationHeaderDomains: ['*.myappdomain.com'],
        disableFetchTracking: false,
        enableCorsCorrelation: true,
        enableAjaxPerfTracking: true,
        enableAjaxErrorStatusText: true,
        enableRequestHeaderTracking: true,
        enableResponseHeaderTracking: true,
        excludeRequestFromAutoTrackingPatterns: [/^((?!myappdomain).)*$/gm],
        correlationHeaderExcludePatterns: [/^((?!myappdomain).)*$/gm],
}
```

 - OS/Browser: All
 - SDK Version [e.g. 22]: 2.7.2
 - How you initialized the SDK: pulling from npm, initializing in VueJS app

**Expected behavior**
All requests that do NOT go to `api.mydomain.com` would be excluded in AI telemetry and do not show up as dependencies (being matched by the pattern of `/^((?!stagehub).)*$/gm`

**Additional context**
Examples of calls that are being tracked (see screenshot above):
```
app.posthog.com
bam.nr-data.com
pub.highlight.run
```

I may be misunderstanding the difference between `correlationHeaderDomains` and `correlationHeaderExcludePatterns`

**Comment by MSNev** [comment]
Looking at your regex and the code that "excludes" the dependencies, I believe that this is correct.
i.e. ```excludeRequestFromAutoTrackingPatterns``` means do not report matching entries as dependencies.

Are you using fetch or XHR requests?

This is where the code processes the provided config
https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-dependencies-js/src/ajax.ts#L567-L576

Can you try debugging an unminified version of your VueJS App? as that would be useful to determine 
- Is the config being initialized correctly (i.e. isit being passed down to this code)
- Is there something about how the request is being called that is causing the ```theUrl``` to not be the expected value.
