### ISSUE TITLE
[BUG] tslib should be listed under "dependencies" not "peerDependencies"

### ISSUE THREAD

**Issue by aschultz** [microsoft/ApplicationInsights-JS#1748]
The TypeScript transpiler emits function calls like `__assign` and `__extends` that need a runtime implementation. When the `--importHelpers` flag is supplied to the transpiler, the expectation is that those functions are made available at runtime through the tslib library instead of having the implementations injected into each file.

However, the version of tslib needed at runtime is tightly coupled to the version of the TypeScript transpiler used. TypeScript 3.8.4 or earlier, for example, needs tslib 1.x while TypeScript 3.9.2 or later needs tslib 2.x.

By specifying tslib as a "peerDependency", AppInsights will be consuming whatever version of tslib is injected by the downstream consuming application. That may be incompatible with the JS code made available in the AppInsights npm package.

AppInsights should instead list tslib under `dependencies` with a version compatible with the TypeScript version. This will ensure that, at runtime, compatible implementations of the helper functions are available to AppInsights code. If the downstream app is using a different version of tslib, both versions of tslib will be loaded into the app's memory and the appropriate version used in each case. If the downstream app is using the same tslib version as AppInsights, npm will dedupe and only a single copy of tslib will be loaded into the application.

**Comment by MSNev** [comment]
```peerDependency``` is the correct location for Application Insights as during the build / bundling process we re-write the default tslib __asssign, __extends with the applicationinsights-shim implementation, so the final package does not include or use the tslib version.

The reason for including as a peerDependency is for users that consume the *.ts files rather than the bundled *.js versions that we use.

**Comment by aschultz** [comment]
Gotcha. Sorry for the noise!
