### ISSUE TITLE
[BUG] README blog post link is not working

### ISSUE THREAD

**Issue by prabushi** [microsoft/ApplicationInsights-JS#1761]
**Description/Screenshot**
The **blog post** link under [(Alternative Setup Method) Include AI JS SDK script and initialize statically](https://github.com/microsoft/applicationinsights-js#alternative-setup-method-include-ai-js-sdk-script-and-initialize-statically) is directed to a broken link.
<img width="916" alt="Screenshot 2022-02-17 at 21 05 43" src="https://user-images.githubusercontent.com/5234623/154516044-7711aad8-8d0e-48c1-8cc5-d5ea22d7a8ef.png">

<img width="1648" alt="Screenshot 2022-02-17 at 21 07 03" src="https://user-images.githubusercontent.com/5234623/154516394-9beca56b-8a63-4cce-a609-2555cb06aee1.png">

**Steps to Reproduce**
Click on the `this blog post` link.

 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**

**Additional context**

**Comment by MSNev** [comment]
Not sure why we are linking out to whatever that blog post was saying -- need to more to an Azure Docs link or add details to GitHub (this later is probably the better option -- perhaps raising and linking to an issue with the details).

**Comment by MSNev** [comment]
@Karlie-777 can you please have a look at this when you get a chance

**Comment by Karlie-777** [comment]
https://github.com/microsoft/ApplicationInsights-JS/pull/1771

**Comment by MSNev** [comment]
v2.8.1 is now fully deployed

**Comment by MSNev** [comment]
Rolled back CDN to v2.7.4 due to #1822

**Comment by MSNev** [comment]
v2.8.3 is now fully deployed to the CDN
