### ISSUE TITLE
[BUG] link  on AISKULight goes to not found page

### ISSUE THREAD

**Issue by velociwabbit** [microsoft/ApplicationInsights-JS#1794]
Refer to  https://github.com/microsoft/ApplicationInsights-JS/blob/master/README.MD for more details on getting started. ... Go ahead I dare you :)

**Comment by satisshhhhhh** [comment]
> Refer to https://github.com/microsoft/ApplicationInsights-JS/blob/master/README.MD for more details on getting started. ... Go ahead I dare you :)

Hey, the URL you shared is broken :(
![image](https://user-images.githubusercontent.com/58567211/176987949-da03bce1-ce4c-46e0-9148-22464becca9c.png)

**Comment by velociwabbit** [comment]
that is the point it is broken... it should point to something
