### ISSUE TITLE
Bring API consistensy between SDKs

### ISSUE THREAD

**Issue by MaxShehovtsov** [microsoft/ApplicationInsights-JS#18]
trackXXX methods should be consistent across .net and JS sdks

**Comment by seanmcne** [comment]
One suggestion on this topic would be to allow telling appInsights the datatype of the data, one I'm struggling with is a TimeSpan.  Our application does not reload the page every time, instead it pulls in data and binds it.  I wish to tell AppInsights how long that process took, versus appinsights figuring out how long it took to load the underlying form or something else. Thx!

**Comment by MaxShehovtsov** [comment]
Can you show the example of what you're trying to do? (I'm missing the part with TimeSpan and telling appInsights the datatype of the data)

**Comment by seanmcne** [comment]
Hey Max, thanks for responding.  The app we're monitoring is a boxed software product that loads custom script in an alternate iframe.  To track true load time we're calculating a custom metric with the number of milliseconds the user had to wait for the data to appear on their screen in an ideal world we could tell TrackPageView what the duration was (as an override), but additionally it would be good to tell appinsights that our numeric value is a duration/timespan and not just a numeric value (ie: 8600ms/8.6 seconds, versus just 8,600).   Hopefully that makes sense - if not let me know - thanks!

**Comment by MaxShehovtsov** [comment]
Have you considered startTrackPage()/stopTrackPage() - https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/appInsights.ts#L114

Alternatively, construct an item manually like we do (should be fairly simple) - https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/appInsights.ts#L114

Overall I think your suggestion (that trackPageView accepts duration as an optional param) makes sense. However it's not a priority right now, so I can't guarantee we'd look at it at all in the near future. Will happily accept your contribution though if you'll be willing to write code/tests.

Thanks!
