### ISSUE TITLE
[BUG] Browser exceptions are no longer automatically tracked after 2.8.0

### ISSUE THREAD

**Issue by WoodyWoodsta** [microsoft/ApplicationInsights-JS#1812]
**Description/Screenshot**
Using `2.8.0`, browser exceptions are no longer automatically caught and tracked. No error handler is present on the `window`.

**Steps to Reproduce**
1. Install `2.8.0` and throw an exception in the browser. Check Application Insights failures panel for errors. No exceptions are presented. No exceptions are added to the `/track` network request payload.
2. Install `2.7.4` and repeat. Exceptions are tracked, and the handler is present on the `window`.

 - OS/Browser: MacOS/Chrome
 - SDK Version: `2.8.0`
 - How you initialized the SDK:
```ts
export const appInsights = new ApplicationInsights({
  config: {
    instrumentationKey,
    extensions: [reactPlugin],
    enableDebug,
    loggingLevelConsole: enableDebug ? 2 : 0,
    loggingLevelTelemetry: enableDebug ? 2 : 1,
    autoTrackPageVisitTime: true,
    enableAutoRouteTracking: true,
    enableDebugExceptions: enableDebug,
    enableUnhandledPromiseRejectionTracking: true,
    enableCorsCorrelation: false,
    enableRequestHeaderTracking: true,
    enableResponseHeaderTracking: true,
  },
});
```

`enableDebug=true`

**Expected behavior**

As above, the exceptions thrown in the browser are tracked - the handler is present on the `window`.

**Comment by MSNev** [comment]
OK, the issue seems to be the way we are now hooking the window.onerror.
With a local repro I am getting the error events.

I'll restore to the "standard" method of hooking the onError rather than the monkey patching that 2.8.0 is currently using (this was done to support unloading)

**Comment by MSNev** [comment]
Actually it looks a little more nuanced as the hooking mechanism does assign the entry -- but, we also tag the endpoint that this is hooked -- so I suspect that part is causing the hook to fail *sigh*.

**Comment by WoodyWoodsta** [comment]
@MSNev Thank you for raising #1815 to fix this issue :)

**Comment by MSNev** [comment]
v2.8.1 is now fully deployed

**Comment by MSNev** [comment]
Rolled back CDN to v2.7.4 due to #1822

**Comment by MSNev** [comment]
On investigating #1822, while the fix for this issue doesn't throw anymore it also appears that it's still not correctly hooking the onerror function either

**Comment by WoodyWoodsta** [comment]
@MSNev Please let me know if there is anything I can do to help.

**Comment by MSNev** [comment]
I think, I've got it covered IE ends up throwing when the code attempts to set window.onerror because of the way it responds to the lookup code. Should have a PR published soon and then I'll publish a release

**Comment by MSNev** [comment]
v2.8.3 is now fully deployed to the CDN
