### ISSUE TITLE
[BUG]SPFx React  project doesn't build after  latest version of @microsoft/application-insights-core-js v.2.8.0 got published

### ISSUE THREAD

**Issue by AnjaliAgarwal123** [microsoft/ApplicationInsights-JS#1814]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/104159144/164509809-9ad260a6-16ab-448e-ba5e-6ce681aac7b0.png">
getting build issues..

**Comment by samithaHewawasam** [comment]
Same issue in React 16.8 too

`TypeScript error in node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Enums/EnumHelperFuncs.d.ts(33,30):
',' expected.  TS1005

    31 |  */
    32 | export declare function createValueMap<E, V = E>(values: {
  > 33 |     [key in keyof E]: [eValue: E[keyof E], mapValue: V[keyof V]];
       |                              ^
    34 | }): V;
    35 |
`

**Comment by MSNev** [comment]
PR #1810

**Comment by AnjaliAgarwal123** [comment]
> Ack, we will be releasing a v2.8.1 (planned for today) that will restore TypeScript 3.x support that should resolve this issue, the PR to fix has already been checked i

**Comment by AnjaliAgarwal123** [comment]
> Ack, we will be releasing a v2.8.1 (planned for today) that will restore TypeScript 3.x support that should resolve this issue, the PR to fix has already been checked in

Can you please suggest some workaround so that we can still use the ol version till the new version is released

**Comment by MSNev** [comment]
The only workaround would be to rollback to an older version, I agree with keeping this issue open as I track and only close issues once the release is fully deployed to the CDN (which is what the "fixed - waiting release" tag is about.

Apart from using the 2.7.4 version NPM package for 2.8.1 should be created today, you can track the milestone https://github.com/microsoft/ApplicationInsights-JS/milestone/62 and I'll add the "released - NPM" tag once the NPM has been published

**Comment by samithaHewawasam** [comment]
This has been fixed after released 2.8.1

**Comment by AnjaliAgarwal123** [comment]
Thanks...The build error is gone after released of v2.8.1

**Comment by MSNev** [comment]
v2.8.1 is now fully deployed

**Comment by MSNev** [comment]
Rolled back CDN to v2.7.4 due to #1822

**Comment by MSNev** [comment]
v2.8.3 is now fully deployed to the CDN
