### ISSUE TITLE
Error 405: Method not allowed

### ISSUE THREAD

**Issue by arcadiogarcia** [Microsoft/ApplicationInsights-JS#183]
I'm using the JS SDK inside a Windows 10 app, and when it tries to perform a POST xhr to dc.services.visualstudio.com/v2/track in the line 1734, I get a 405: Method not allowed error.

The weird thing is that I tried to do the request manually via curl, and the endpoint seems to only accept POST requests and give a 405 for GET requests. However the code is making a POST request (line 1730):

`xhr.open("POST, this._config.endpointUrl(), isAsync);`

Why am I getting a 405 error then? Is this a bug or am I missing something? I am using the code from dist/ai.js, is that the right one?

**Comment by MaxShehovtsov** [comment]
can you check in Fiddler (or similar) and paste here your raw request and response. Thanks!

**Comment by arcadiogarcia** [comment]
Seems like the issue was the endpointUrl, adding  `http:` to `"//dc.visualstudio..."` did the trick.

**Comment by arcadiogarcia** [comment]
Out of curiosity, why the protocol is omitted from the URL? Adding it would solve problems like this one.

**Comment by kamilszostak** [comment]
Currently JS SDK is using the same protocol to sent telemetry as the page. So if the page works over http, the SDK will send telemetry over http.

I'm changing this logic to always (if possible) send telemetry over https - #258.
