### ISSUE TITLE
Axios integration question

### ISSUE THREAD

**Issue by tudor33sud** [microsoft/ApplicationInsights-JS#1836]
Hello,

I am trying to correlate requests between frontend and the backend. Is there any recommended way of sending application insights telemetry to all axios requests? I can't seem to find ways of doing that. I would like to be able to correlate operations on the frontend( i.e. click of a button, to the appropriate requests chain from the backend).

I load appInsights as soon as the user is logged in, but requests have no x-ms headers with telemetry context. I would like to know the recommended way of achieving what I'm doing, or maybe if I should use some other thing.

**Comment by MSNev** [comment]
Which version of the SDK are you using.
The current version 2.8.3 enables this by default for both XHR and fetch based requests (which should be the transport used by axios), the correlation is performed using the W3C traceparent header using the Client as the initator to the server.

If you want to have the requests correlated from the initial server request that generates the client page and then have the correlation back to the server again this requires a little more work, as you need to tell the SDK what the initial server side (parent) id is https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript?tabs=snippet#advanced-correlation

**Comment by tudor33sud** [comment]
Finally someone else worked on the frontend and integration went smoothly inside the angular application. I will close this until further issues.
