### ISSUE TITLE
NONUSRACT_MissingRequiredFieldSpecification

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-JS#184]
Unique weekly ikeys: 20
Message: AI (Internal): NONUSRACT_MissingRequiredFieldSpecification message:"Missing required field specification. The field is required but not present on source" props:"{field:name,name:baseData}"

Looks like this one is related:
Unique weekly ikeys: 30
Message: AI (Internal): NONUSRACT_TrackPVFailedCalc message:"trackPageView failed on page load calculation: " props:"{exception:[object String]\out of memory\}"

**Comment by kamilszostak** [comment]
I have a fix - #194.
