### ISSUE TITLE
[BUG]urlCollectQuery not work for applicationinsights-clickanalytics-js

### ISSUE THREAD

**Issue by lingfeidiewu** [microsoft/ApplicationInsights-JS#1863]
**Description/Screenshot**
In the ReadMe of applicationinsights-clickanalytics-js, there are two configuration urlCollectQuery and urlCollectHash. But after I set these two configuration as true, the uri in the event data still doesn't include the query string in url. I also cannot find any code related to urlCollectQuery in the repository. Are these two configurations useful to collect query string in url for auto captured click events?

**Comment by MSNev** [comment]
Looking at the code, I'm not finding any references to these properties -- looks like they got removed before the project was released. I don't have the details on why, will need to assign someone to investigate further...

@lingfeidiewu Right now, No these two configurations are not useful, at the very minimum this is a documentation bug. But we may be able to do something.

@Karlie-777, I'll raise a task and assign for August review.

**Comment by lingfeidiewu** [comment]
Thanks. I think these two configurations are needed, now the query string are discarded in the click events data.

**Comment by Karlie-777** [comment]
The configs are removed in this PR: https://github.com/microsoft/ApplicationInsights-JS/pull/1444
