### ISSUE TITLE
Sourcemaps versioning in blob storage is unclear in docs

### ISSUE THREAD

**Issue by baxxos** [microsoft/ApplicationInsights-JS#1907]
**Is your feature request related to a problem? Please describe.**
I've successfully managed to set up the whole Application Insights ecosystem in our React app - including the "_Unminify_" feature. However, due to the algorithm used for searching sourcemaps in the corresponding Azure blob storage, we are forced to use a flat folder structure:

```yaml
# Our JS file requrests are hosted by a .NET server at:
# https://myapp.com/static/js/main.a123bc.chunk.js

myStorageAccount
|_ sourceMapsContainer
    |_ main.a123bc.js.map  # Corresponds to app release v100 in Azure DevOps
    |_ main.b456af.js.map  # Corresponds to app release v101 in Azure DevOps
    |_ ...
```
The "_Unminify_" feature works quite well for now, however the container is already becoming cluttered due to the number of map files. Ideally, I would like to achieve something like this:
```yaml
myStorageAccount
|_ sourceMapsContainer
   |_ v100
      |_ main.a123bc.js.map  # Corresponds to app version 100 in Azure DevOps
   |_ v101
      |_ main.b456af.js.map  # Corresponds to app version 101 in Azure DevOps
   |_ ...
```
The [docs](https://learn.microsoft.com/en-us/azure/azure-monitor/app/source-map-support) briefly mention the possibility of versioning the map files, **however**, if I understand correctly, it has to be done on build level so the static files are served to clients like this: `https://myapp.com/v101/static/js/main.a123bc.chunk.js`. 

I believe the versioning would work out of the box this way, but it also means that in case of a React app created using CRA I would have to alter my whole build & deployment process:
1. Eject from CRA
2. Modify my Webpack config to build into a different folder
3. Pass the current app version to Webpack when calling build
4. Modify my .NET server to serve static files from a dynamically named folder (instead of always using `ClientApp/build/static`)
 
**Describe the solution you'd like**
It would be much easier if we could somehow configure the sourcemap path prefix directly from Azure itself - e.g. from the App Insights properties page:

![image](https://user-images.githubusercontent.com/17254686/192979965-439d2e32-1ecf-47b0-b367-262c8a7958ef.png)

The path could be configured in various ways using regexes and [predefined Azure variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml).

**Describe alternatives you've considered**
The only alternative that I know about is sticking to a flat sourcemap container structure and relying on the uniqueness of the Webpack content hashes. Or maybe I'm missing something really obvious here - in that case, please let me know:)

**Additional context**
#1318 is similar to this issue, however, the versioning process is not discussed in depth there (nor is it in the [docs](https://learn.microsoft.com/en-us/azure/azure-monitor/app/source-map-support)).

**Comment by Karlie-777** [comment]
@baxxos I am not quite sure if I understand it correctly. You are mentioning that CRA puts build files into a folder that is not easily used by source map and re-config build path and process is not easy. I am curious what CRA version you are using? It seems that you can config build path from .env, click [here ](https://create-react-app.dev/docs/advanced-configuration/#:~:text=host%20your%20application.-,BUILD_PATH,-%F0%9F%9A%AB%20Ignored)for details and it seems that you can use this way to manage build file versions (correct me if I am wrong).

**Comment by baxxos** [comment]
@Karlie-777 you're right, I didn't know about that particular option. However, if I understand you correctly, I still need to alter the way I serve my static files like this to achieve versioned sourcemaps, right? `https://myapp.com/v101/static/js/main.a123bc.chunk.js`

What I mean is that there's no way of doing this without altering the build/deployment process (which can be a major pain for large/distributed apps). 

So I guess my question is mostly about the possibility of leveraging the release/build version variables which are already present in Azure DevOps for versioning of the Application Insights sourcemap files (without the need of altering my code or CI/CD pipelines).

**Comment by Karlie-777** [comment]
@baxxos Yes, the current workaround is still to alter file path! The sourcemap feature is implemented from UI side and we are not sure of the capability to add this feature😊

**Comment by baxxos** [comment]
@Karlie-777 thanks for the clarification nevertheless.
