### ISSUE TITLE
Error 429 (Too much data: 31406)

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/ApplicationInsights-JS#191]
What does this mean?  Is it the 200 dp/s limit?  Or is it saying I am trying to send 30+ MB of data?  Thanks!

![image](https://cloud.githubusercontent.com/assets/4112046/15217756/980b5242-1822-11e6-8152-d0edf4b8172a.png)

**Comment by dnduffy** [comment]
It's a non-fatal quota error that you've sent too much in too short a period of time.
I'm not familiar with the backend code but the message seems to imply there is "too much data".
If you retry the trace a few seconds later does it succeed?
If you capture the payload and try sending it alone from a test app do you still get the error or does it succeed when there is no other traffic?

**Comment by kamilszostak** [comment]
There is a limit of 500 event per second (per app iKey) and it looks like your app sent 31,406 events and was throttled.

**Comment by gregjhogan** [comment]
Confirmed ... I found "Microsoft.Insights/throttling/limit" messages in the audit logs.  Thanks!
