### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by pelikhan** [microsoft/ApplicationInsights-JS#1911]
This call blows up when trying to build AI with gatsbyjs. Is this function missing "else" statement? It seems from the description that the globalThis should be but in practice each clause gets entered until the global check fails.

https://github.com/microsoft/ApplicationInsights-JS/blob/06c14692f4038b54cc81cbd78b51710def90253e/tools/shims/src/Helpers.ts#L38

**Comment by MSNev** [comment]
Yeh, this shouldn't keep "replacing" the `_cachedGlobal` once it's found the "global"

**Comment by MSNev** [comment]
This issue has "just" missed the release of 2.8.8, so it's currently scheduled for v2.8.9 (which will normally rollout at the end of oct (early November)) and that will be the last scheduled release of 2022.

**Comment by MSNev** [comment]
Shims v2.0.2 is now published with this fix.
v2.8.9 of AI will be updated to consume
