### ISSUE TITLE
TypeError: appInsights.loadAppInsights is not a function Jest React 18

### ISSUE THREAD

**Issue by MarianoVeloso** [microsoft/ApplicationInsights-JS#1942]
Hi! I'm trying to create test cases for my modules and when I need to mock app `applicationinsights-web` i'm getting ` TypeError: appInsights.loadAppInsights is not a function` 

My test:
```

jest.mock('@microsoft/applicationinsights-web');

describe('Example | ', function () {
	test('Renders Example paragraph', () => {
		render(
			<Home />);
		const linkElement = screen.getByText(/Home/i);
		expect(linkElement).toBeInTheDocument();
	});
});

```
My component: 

```
function Home() {	
	const generateException = () => {
		trackException(' Exception UI Test ');
	};
	const generateTrace = () => {
		trackTrace(' Trace UI Test ');
	};
	const generateEvent = () => {
		trackEvent(' Event UI Test ');
	};
	return (
		<Container maxWidth="sm">
			<Box sx={{ my: 4 }}>
				<Typography variant="h4" component="h1" gutterBottom> Home </Typography>
			</Box>
			<Box sx={{ my: 1 }}>
				<Button variant="contained" onClick={generateException}>Exception Test</Button>
			</Box>
			<Box sx={{ my: 1 }}>
				<Button variant="contained" onClick={generateTrace}>Trace Test</Button>
			</Box>
			<Box sx={{ my: 1 }}>
				<Button variant="contained" onClick={generateEvent}>Event Test</Button>
			</Box>
		</Container>
	);
}
```

My Telemetry service
```
import { ApplicationInsights, ITelemetryItem } from '@microsoft/applicationinsights-web';
import { ReactPlugin } from '@microsoft/applicationinsights-react-js';

const reactPlugin = new ReactPlugin();

const appInsights = new ApplicationInsights({
	config: {
		connectionString: process.env.REACT_APP_APPINSIGHTS_CONNECTION,
		extensions: [reactPlugin],
		extensionConfig: {},
		enableAutoRouteTracking: true,
		disableAjaxTracking: false,
		autoTrackPageVisitTime: true,
		enableCorsCorrelation: true,
		enableRequestHeaderTracking: true,
		enableResponseHeaderTracking: true
	}
});
appInsights.loadAppInsights();

appInsights.addTelemetryInitializer((env:ITelemetryItem) => {
	env.tags = env.tags || [];
	env.tags['ai.cloud.role'] = 'testTag';
});`
```
My App:
```

import { AppInsightsContext } from '@microsoft/applicationinsights-react-js';
import { reactPlugin } from './shared/appInsights/TelemetryService';

function App() {
	
	return (
		<BrowserRouter>
			<AppInsightsContext.Provider value={reactPlugin}>
				<div className="App">
					<Routes>
						<Route path="/" element={<Home/>} />
						<Route path="/home" element={<Home/>} />
					</Routes>
					<Footer/>
				</div>
			</AppInsightsContext.Provider>
		</BrowserRouter>
	);
}
```

Stack: 

```
    "dotenv": "^16.0.3",
    "jest": "^28.1.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router": "^6.4.3",
    "react-router-dom": "^6.4.3",
    "react-scripts": "5.0.1",
    "@microsoft/applicationinsights-react-js": "^3.4.0",
    "@microsoft/applicationinsights-web": "^2.8.9",
```

Any advice on this one? Thanks!

**Comment by MSNev** [comment]
Yes, this is a "side-effect" of how we are creating the class for better minification in the browser. There are several options but the easiest way it to simply "create" an instance of the class just prior to setting up the mock. As the "prototype" level functions don't exist until that first instance is created.

**Comment by MarianoVeloso** [comment]
> Yes, this is a "side-effect" of how we are creating the class for better minification in the browser. There are several options but the easiest way it to simply "create" an instance of the class just prior to setting up the mock. As the "prototype" level functions don't exist until that first instance is created.

Can you elaborate a bit more on how can I set up the mock? I'm getting a different error with this code, for example 
```
const mockObject = new ApplicationInsights({
	config: {
		connectionString: 'test',
		extensions: [reactPlugin],
		extensionConfig: {},
		enableAutoRouteTracking: true,
		disableAjaxTracking: false,
		autoTrackPageVisitTime: true,
		enableCorsCorrelation: true,
		enableRequestHeaderTracking: true,
		enableResponseHeaderTracking: true
	}
});

jest.mock('@microsoft/applicationinsights-web', () => ({ ApplicationInsights: mockObject, }));
```

`ReferenceError: Cannot access 'mockObject' before initialization`

Is there any documentation to run test cases with Jest in React?

**Comment by MSNev** [comment]
No, there is no documentation for jest as we don't use jest internally.

> TypeError: _applicationinsightsWeb.ApplicationInsights is not a constructor

This error seems like jest is trying to use the provided `mockObject` as a constructor, which it isn't it's an instance at that point...

Once you have created the first instance of the ApplicationInsights object all of the prototype functions will exist on the ApplicationInsights class... Sooo, I would expected that this "should" then work as (I assume) it does for other normal class definitions.

`jest.mock('@microsoft/applicationinsights-web');`

This "assumes" however, that jest is not creating and using it's own module level (eg requireJS internally) "copy" of the class (which it might be).

Assuming that my assumption of this error is correct
> TypeError: _applicationinsightsWeb.ApplicationInsights is not a constructor

Then you might be able to just pass the `ApplicationIsights` class name

```
const mockObject = new ApplicationInsights({
	config: {
		connectionString: 'test',
		extensions: [reactPlugin],
		extensionConfig: {},
		enableAutoRouteTracking: true,
		disableAjaxTracking: false,
		autoTrackPageVisitTime: true,
		enableCorsCorrelation: true,
		enableRequestHeaderTracking: true,
		enableResponseHeaderTracking: true
	}
});

// I'm guessing at what this is doing, but basically just telling it to return the current class as the class instance
// There might be a better syntax to do this
jest.mock('@microsoft/applicationinsights-web', () =>  ({ ApplicationInsights: () => ApplicationInsights }));

// Maybe just???
jest.mock('@microsoft/applicationinsights-web', ApplicationInsights);
```

**Comment by MarianoVeloso** [comment]
None of those solutions works
1) jest.mock('@microsoft/applicationinsights-web'); : 
Seems that Jest doesn't care if you create before the instance so this is the same that not doing any before

2) jest.mock('@microsoft/applicationinsights-web', () =>  ({ ApplicationInsights: () => ApplicationInsights })); 
This solution was what I was thinking but when the test case runs Jest tells that you can't give a type as an argument  `The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.`

3) jest.mock('@microsoft/applicationinsights-web', ApplicationInsights);
The same reply as before but this brakes the test before runs 
```
Argument of type 'typeof Initialization' is not assignable to parameter of type '() => unknown'.
  Type 'typeof Initialization' provides no match for the signature '(): unknown'
```
The project is on sprint 0 so I think the best course will be to get rid of Jest

**Comment by MSNev** [comment]
Oh, nice!
In that case if you mocking everything then, you might also be able to simply either
- pass a valid looking `instrumentationKey` or
- pass an invalid value (we use values like "testiKey") and also include `disableInstrumentationKeyValidation` as true so that the SDK will still attempt to initialize.

**Comment by MarianoVeloso** [comment]
That just really cool to know! I just added to configuration for Jest and to my env variables.
