### ISSUE TITLE
[BUG] Invalid workspace

### ISSUE THREAD

**Issue by DavidMarquezF** [microsoft/ApplicationInsights-JS#1947]
**Description/Screenshot**

All of a sudden all the api calls to azure insights started giving me Invalid workspace error.

I've made sure the connection strings are correct so I don't know why this could be happening
```
{
  "itemsReceived": 8,
  "itemsAccepted": 0,
  "errors": [
    {
      "index": 0,
      "statusCode": 400,
      "message": "Invalid workspace"
    },
    {
      "index": 1,
      "statusCode": 400,
      "message": "Invalid workspace"
    },
    {
      "index": 2,
      "statusCode": 400,
      "message": "Invalid workspace"
    },
    {
      "index": 3,
      "statusCode": 400,
      "message": "Invalid workspace"
    },
    {
      "index": 4,
      "statusCode": 400,
      "message": "Invalid workspace"
    },
    {
      "index": 5,
      "statusCode": 400,
      "message": "Invalid workspace"
    },
    {
      "index": 6,
      "statusCode": 400,
      "message": "Invalid workspace"
    },
    {
      "index": 7,
      "statusCode": 400,
      "message": "Invalid workspace"
    }
  ]
}
```
**Steps to Reproduce**

 - OS/Browser: Version 107.0.5304.107 (Official Build) (64-bit)
 - SDK Version [e.g. 22]: 2.8.9
 - How you initialized the SDK:

Using version 2.8.9
```typescript
 this.appInsights = this._zone.runOutsideAngular(() => new ApplicationInsights({
      config: {
        connectionString: environment.appInsightsConnectionKey
      },
    }));

    this._zone.runOutsideAngular(() => {
      this.appInsights.loadAppInsights();
      this.appInsights.context.application.ver = version;
    });
```
**Expected behavior**

Should work with the correct connection string.

**Additional context**
Is it possible that this has something to do when creating the resource between Classic and Workspace based?

**Comment by Karlie-777** [comment]
@DavidMarquezF have you tried other connection strings? is "invalid workspace" error still shown?

**Comment by DavidMarquezF** [comment]
I understood that the insights resource only had one connection string no? Either way I also tried it with another insights resource and it gives me the same error.

**Comment by Karlie-777** [comment]
@DavidMarquezF you can create multiple application insights under one workspace.  So what's the access level of your workspace? (reference [link](https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal) on how to assign proper [roles](https://learn.microsoft.com/en-us/azure/role-based-access-control/overview))

**Comment by DavidMarquezF** [comment]
I just recreated the resources and now it works again. Thanks tho!
