### ISSUE TITLE
[BUG] Fire unload event

### ISSUE THREAD

**Issue by Lulubul** [microsoft/ApplicationInsights-JS#1948]
**Description/Screenshot**
I tried to migrate from 2.5.11 to 2.8.9 version for @microsoft/applicationinsights-web and i receive a new error in lighthouse.

The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Consider using the `pagehide` or `visibilitychange` events instead.

https://developer.chrome.com/blog/page-lifecycle-api/#the-unload-event

![image](https://user-images.githubusercontent.com/6178639/203015006-b40961f9-7ae6-4403-a0b4-7205f6580755.png)

**Steps to Reproduce**
Migrate from @microsoft/applicationinsights-web 2.5.11  to 2.8.9 version and run lighthouse.

 - OS/Browser: Edge
 - SDK Version [e.g. 22]:  2.8.9
 - How you initialized the SDK:  npm install

**Expected behavior**
The unload event should not be fired since is a issue in some browser https://developer.chrome.com/blog/page-lifecycle-api/#the-unload-event
**Additional context**
I'm not sure if in version 3 this is fixed but since this is beta new need  a stable version.

**Comment by Karlie-777** [comment]
@Lulubul extra configurations are provided to customize unload events, see details [here ](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts#:~:text=disablePageUnloadEvents%3F%3A%20string%5B%5D%3B) please let us know if this resolve the issue.

**Comment by Lulubul** [comment]
It worked thank you very much.
