### ISSUE TITLE
[BUG] window.appInsights is `undefined`

### ISSUE THREAD

**Issue by Snailedlt** [microsoft/ApplicationInsights-JS#1951]
## Edit

So apparantly this isn't a bug, but it's still very confusing since it doesn't work the way that's described in the deocumentation. The documentation needs to be updated to mention that the npm version doesn't populate window.appInsights, so it needs to be exported to be used in other components. See this comment below for an example: https://github.com/microsoft/ApplicationInsights-JS/issues/1951#issuecomment-1329154828

## Original description

**Description/Screenshot**
window.appInsights is undefined, so I'm unable to use any appInsights methods in other files than the one where I declared appInsights. I'm using Svelte if that matters, and appInsights is initialized in `App.svelte`

in vscode:
![image](https://user-images.githubusercontent.com/43886029/203752901-b8a5caa2-56a0-4faa-be2d-3122ee0287cc.png)

in google chrome:
![image](https://user-images.githubusercontent.com/43886029/203753337-7a8ae81b-884d-474a-b8f4-e7b955a10dc1.png)

code: 
```ts
    const appInsights = new ApplicationInsights({
      config: {
        connectionString:
          process.env.AZURE_APPLICATION_INNSIGHTS_CONNECTION_STRING,
      },
    });
    appInsights.loadAppInsights();
    appInsights.trackPageView(); // Manually call trackPageView to establish the current user/session/pageview

    window.appInsights.trackEvent('Test');
```

error messages:
> Property 'appInsights' does not exist on type 'Window & typeof globalThis'.ts(2339)

> App.svelte:29 Uncaught TypeError: Cannot read properties of undefined (reading 'trackEvent')
    at instance (App.svelte:29:24)
    at init (index.mjs:1997:11)
    at new App (App.svelte:45:40)
    at main.js:3:13
    at main.js:5:2

**Steps to Reproduce**

 - OS/Browser: Windows 10 / Chrome Version 107.0.5304.107 (Official Build) (64-bit)
 - SDK Version [e.g. 22]: 2.8.9
 - How you initialized the SDK: [npm-based](https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript?tabs=snippet#npm-based-setup)

**Expected behavior**
window.appInsights is NOT undefined

**Additional context**

**Comment by Karlie-777** [comment]
@Snailedlt if I am understanding it correctly, you are using npm(click [here](https://github.com/microsoft/ApplicationInsights-JS#npm-setup-ignore-if-using-snippet-setup) for details) to initialize ApplicationInsights. So under this scenario, ApplicationInsights is not global. But if you are snippet initialization (click [here](https://github.com/microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup) for details), you can access  `window.appInsights` directly

**Comment by Snailedlt** [comment]
@Karlie-777 yes, that is correct, I'm using the npm version. I don't see anything in the documentation saying it's not global. How would I go about accessing it globally, and what's the reason it's not global in the first place?

My usecase is that I want to call trackEvent from multiple different files, should I be using the snippet based initialisation for rhat instead?

**Comment by Karlie-777** [comment]
@Snailedlt so if you are using npm initialization, you can create an application Insights component ( see example [here](https://github.com/microsoft/applicationinsights-react-js/blob/main/sample/applicationinsights-react-sample/src/ApplicationInsightsService.tsx) ). If you want to easily use `window.appInsights`, snippet initialization is recommended.

**Comment by Snailedlt** [comment]
@Karlie-777 I see, thank you!
So if I use the snippet initialization, do I just need to initialize it once, and then I can access it through `window.appInsights` after that, or do I need to initialize it in every file I want to use it?

**Comment by Karlie-777** [comment]
@Snailedlt snippet initialization creates global instance. so as long as you can access `window` object, you can access `window.app Insights` directly!

**Comment by Snailedlt** [comment]
Okey, so what I'm getting is... If I want to use it in one file only, go for npm, otherwise go for the snippet?

**Comment by Karlie-777** [comment]
@Snailedlt depends on your website structure. For npm, if you creates [applicationInsights component](https://github.com/microsoft/applicationinsights-react-js/blob/main/sample/applicationinsights-react-sample/src/TestPage.tsx#:~:text=import%20%7B%20appInsights%7D%20from%20%27./ApplicationInsightsService%27%3B) and it can be accessed by all files also.

**Comment by Snailedlt** [comment]
So when I try to use the snippet based version I need to initialize it as early as possible. I tried pasting this into the index.html file of our app. I only replaced the connectionString with `process.env.AZURE_APPLICATION_INNSIGHTS_CONNECTION_STRING` from our .env file. But I get an error saying `ReferenceError: “process is not defined”`.
I assume the error comes because the file is accessed before the .env is initialized, so process is undefined at that moment. 

Gonna try putting the npm snippet into a component like you suggested earlier.

**Comment by Snailedlt** [comment]
I ended up just exporting appInsights like so:
```ts
import { ApplicationInsights } from '@microsoft/applicationinsights-web';

export const appInsights = new ApplicationInsights({
  config: {
    connectionString: process.env.AZURE_APPLICATION_INNSIGHTS_CONNECTION_STRING,
  },
});
```

And then loading it in App.svelte
```ts
  import { appInsights } from './util/appInsights';

  appInsights.loadAppInsights();
  appInsights.trackPageView(); // Manually call trackPageView to establish the current user/session/pageview
```

And finally using it in any other file by importing it:
```ts
  import { appInsights } from '../util/appInsights';
  ...
  ...
    // Log to Azure Application Insights
    if (
      process.env.isProd ||
      process.env.AZURE_APPLICATION_INNSIGHTS_CONNECTION_STRING
    ) {
      appInsights.trackEvent(
        {
          name: `FeatureForm${featureName}`,
        },
        {
          feature: {
            featureName: featureName,
            featureDescription: description,
          },
          userInput: {
            userHasOpinion: userHasOpinion,
            selectedAnswer: selectedAnswer,
            text: userText,
            email: userEmail,
          },
        }
      );
    } else {
      console.log('Application Insights is NOT active!');
    }
```

**Comment by Snailedlt** [comment]
Nice, thanks!

It works now, so I edited the description to reflect the issue with misinformational documentation

**Comment by krishnasaga** [comment]
> Nice, thanks!
> 
> It works now, so I edited the description to reflect the issue with misinformational documentation

I'm not able to see it as a problem with documentation as it assumes that familiarly of JS

**Comment by Snailedlt** [comment]
@Karlie-777 Thanks. We ended up just making a utility function that gets the instance :)
