### ISSUE TITLE
[BUG] Some Cookies Generated By Application Insights Can Trigger OWASP WAF Rules

### ISSUE THREAD

**Issue by aolszowka** [microsoft/ApplicationInsights-JS#1974]
This issue has been reported several times before across several platforms; prior recommended readings include:

#942 
#1499 
#1643 

And the following StackOverflow Posts:
https://stackoverflow.com/questions/71589519/app-insights-cookies-are-blocked-by-azure-firewall
https://stackoverflow.com/questions/31280710/managing-application-insights-cookies
https://stackoverflow.com/questions/49867291/azure-application-gateway-waf-blocks-common-asp-net-core-requests

This issue serves to try and add additional flavor to what has already been posted, along with a possible solution for the Developers.

## Problem Statement
Several OWASP Web Application Firewall (WAF) Rules (https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-crs-rulegroups-rules?tabs=owasp32) can be inadvertently triggered by the following cookies generated by Application Insights:

* ai_session

## Example
In this screenshot taken from the Log Analytics workspace with the following query:

![image](https://user-images.githubusercontent.com/2592881/214352249-fdcbba67-f7d0-4919-8ca6-8f4350dda2ff.png)

```
AzureDiagnostics
| where TimeGenerated > ago(1d)
| where Category == "ApplicationGatewayFirewallLog"
| where ruleId_s == 942450
```

https://docs.microsoft.com/azure/azure-monitor/reference/tables/AzureDiagnostics

## Analysis
Most of this is due to over-zealous/false positive reporting by the WAF which is a known limitation of this "Security Solution". Unfortunately as more companies adopt these solutions as recommended by various cloud vendors, including Microsoft, the occurrence of these reports is likely to climb.

I am not familiar enough with the Application Insights Library to figure out exactly where Cookies are created; but this comment indicates that:

```
Internally we are using "|" as the encoded field separator and when we create a 22 character random value we only use these values
const base64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
```

(From https://github.com/microsoft/ApplicationInsights-JS/issues/1499#issuecomment-801513965)

A search indicates that this is probably using this helper method: https://github.com/microsoft/ApplicationInsights-JS/blob/0c76d710a0cd465f0b8b5e143250898122511874/shared/AppInsightsCore/src/JavaScriptSDK/RandomHelper.ts#L125-L145

There is nothing wrong with this method, it is simply generating a random token for use.

The problem becomes the OWASP rules; in the above example it is complaining about a violation of `942450 - SQL Hex Encoding Identified` (https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-crs-rulegroups-rules?tabs=owasp32) if you boil down that rule it triggers off of the following Regular Expression when found in a `REQUEST_COOKIE`:

```
(?i:(?:\A|[^\d])0x[a-f\d]{3,})
```

Here's some example tokens from Application Insights that were generated by the SDK, which I have manually muxed (but attempted to keep the same shape, to avoid leaking any data):

```
g29xaJN4O+V5ME0Xc94eHK|45428045050689|4852872041289
v029Af5qwguJy+u0XDBFZ+|15450513415946|4562429315946
```

Dumping this into RegEx 101 shows a bingo:

![image](https://user-images.githubusercontent.com/2592881/214352360-7934489c-274d-4d18-85ca-4858033b73cf.png)

More simply put this Regex is just looking for anything that looks like a Hex representation in a cookie. The author of this bug report has refrained from giving additional opinion on the effectiveness of such systems from a security standpoint.

Due to the random nature of the generation of cookies its unlike you're going to get something that reproduces consistently.

## Recommendations
The initial recommendation would be to evaluate your application to understand if this OWASP rule should really be enabled, taking into consideration how `REQUEST_COOKIES` are utilized by their application. The intent of this WAF rule, from OWASP, appears to be to try and protect scenarios in which the `REQUEST_COOKIE` is blindly passed into a SQL Request.

The author of this bug report makes no claims to the soundness of such a design, but does wish to point out that such designs already inherently violate OWASP guidance, which indicates that user input, including cookies, always be sanitized by the application prior to processing.

Should you find yourself in an environment in which you are unable to disable this rule the next best request is to try and work with the vendors who generate cookies which fail this rule.

While not ideal in this authors opinion, a request could be made to the author of the SDK (`ApplicationInsights-JS`) to add additional checks (overhead) to their cookie generation process to see if such a cookie violates known OWASP Regular Expression rules and then attempt to regenerate. Alternatively changing the random generator to avoid such patterns might also work, at the cost of removing entropy from such systems.

Many if not all of the existing reports indicate various other OWASP Rules, the author of this bug report suspects, but has no evidence at this time, that these are all variations of the same underlying cause.

The author of this bug report can commit to providing RegEx's for other rules that are being hit by this utility if so requested.

**Comment by MSNev** [comment]
As previously mentioned in the linked bugs and you have highlighted here, this is not an issue with the SDK and not unique to Application Insights.
