### ISSUE TITLE
Run-time Telemetry initializers for Ajax requests

### ISSUE THREAD

**Issue by MaxShehovtsov** [microsoft/ApplicationInsights-JS#198]
Allow some sort of telemetry initializers which are invoked at the time ajax request it sent to collect data which is not accessible after it's sent (like http headers).

**Comment by henryctam** [comment]
Like!

**Comment by jasmcc** [comment]
This would be very handy, as we're in the scenario that 95% of our dependency calls are useless and not worth paying to track, but the remaining 5% are very useful.  Currently it's just all or nothing due to lack of telemetry initializer support.

**Comment by MSNev** [comment]
As part of https://github.com/microsoft/ApplicationInsights-JS/pull/1705, I'm adding the concept of a `IDependencyListener` callback function, this will have limited functionality and it will be called before the correlation headers are added (but you will be able to change the values used and you can also derive the actual used values will be.

**Comment by MSNev** [comment]
Splitting out from the previous PR and linking to #1846
