### ISSUE TITLE
Field 'assembly' on type 'StackFrame' is too long. Expected: 1024 characters [BUG]

### ISSUE THREAD

**Issue by zach-thrivetribe** [microsoft/ApplicationInsights-JS#1990]
**Description/Screenshot**

I am attempting to log an exception in response I get a 400 response with the following: 
```
{
	"itemsReceived": 1,
	"itemsAccepted": 0,
	"errors": [
		{
			"index": 0,
			"statusCode": 400,
			"message": "100: Field 'assembly' on type 'StackFrame' is too long. Expected: 1024 characters"
		}
	]
}
```

This is part of the "parsedStack" data and the value is essentially a really long url coming from a third party so I can't make any changes to it. I know some of the values get shortened by the "DataSantizer", but this one clearly isn't. Not sure if this is a bug or a matter of configuration. Would really appreciate any help on this! Thanks!

**Steps to Reproduce**

 - OS/Browser: any
 - SDK Version [e.g. 22]:
    "@microsoft/applicationinsights-react-js": "^3.4.0",
    "@microsoft/applicationinsights-web": "^2.8.9",
 - How you initialized the SDK: Connection string

**Expected behavior**
Error is logged. 

**Additional context**
Other errors are logged as expected, it's just this particular error and call stack that contains a long url that is over 1024 characters.

**Comment by MSNev** [comment]
In the short term, you should be able to use a telemetry initializer to truncate this value.
https://github.com/Microsoft/ApplicationInsights-JS#telemetry-initializers

Where you will need to inspect the `name` of the event (called envelope in the readme), just be aware that a telemetry initializer callback function is called for every event that is sent, so you should make sure that when updating the event that any embedded object may not exist and you should limit the amount of code that is executed unnecessarily.

Another option with using a telemetry initializer, is that if this is coming from a 3rd party and you don't want it to be included in your AzureMonitor portal exception data you can simply `return false;` from the initializer which will cause the event to never be sent.

**Comment by MSNev** [comment]
@siyuniu-ms this is probably a good first item for you to look at, basically we need to reproduce and add some additional code to sanitize (truncate) this field using the existing functions.
tagging @Karlie-777 for awareness

**Comment by Karlie-777** [comment]
@siyuniu-ms so this function https://github.com/microsoft/ApplicationInsights-JS/blob/044384b9b644f0bb966c3c5d0c7c22935b738c00/shared/AppInsightsCommon/src/Telemetry/Exception.ts#L194 transform error stack object into string. you may add `dataSanitizeString` to this value as well to make sure it is not exceeding max-string length as well
