### ISSUE TITLE
[BUG] Unhandled errors not logged

### ISSUE THREAD

**Issue by maxburs** [microsoft/ApplicationInsights-JS#2013]
**Description/Screenshot**
Unhandled exceptions are not logged in our app.

**Steps to Reproduce**

 - OS/Browser: Chrome/Macos
 - SDK Version [e.g. 22]: Repros on 2.7.3 and 2.8.11
 - How you initialized the SDK:
```ts
import { ApplicationInsights } from '@microsoft/applicationinsights-web';

// Inside init function
const appInsights = new ApplicationInsights({
    config: {
        enableDebug: true,
        enableDebugExceptions: true,
    },
});

appInsights.loadAppInsights();
appInsights.context.application.ver = KWE_CONSTANTS.env.appVersion;
appInsights.context.session.id = sessionId;
```

**Expected behavior**

**Additional context**

I saw some references to the "unhandledrejection" event in node_modules/@microsoft/applicationinsights-web/browser, but don't see that event listener on our window:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/8890312/223894923-1a8937bd-8fec-46b4-9be7-7c412ac0f9c1.png">

**Comment by MSNev** [comment]
Application Insights hooks and uses the `window.onerror` to capture the unhandled exceptions, and it's not registered as an event (via addEventListener etc)

So if you are using a framework that is also wrapping the `onerror` then depending how it's handling that and whether it passes it only any previous `onerror` handler will determine if they are captured.

This will require some debugging to check whether the onerror is being hooked and called.
This all occurs here https://github.com/microsoft/ApplicationInsights-JS/blob/c037b93aaecc50a5370cccb23cb161ea21d10c30/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/AnalyticsPlugin.ts#L703-L719, so putting a breakpoint on line 705 will confirm that your configuration is allowing exceptions to be gathered (which it does by default) and then when an exception occurs the `rsp` callback function on lines 708..717 will get called.

On you config items above, these are actually not for "unhandled errors", they are used to help track down issues which internally call the `throwInternal` messages which indicate that the SDK is not configured correctly etc.

https://github.com/microsoft/ApplicationInsights-JS/blob/c037b93aaecc50a5370cccb23cb161ea21d10c30/shared/AppInsightsCore/src/JavaScriptSDK/DiagnosticLogger.ts#L125-L127

Actually, digging into the code the `enableDebug`  looks like a left over config from v1 as it was replaced by `enableDebugExceptions`

**Comment by maxburs** [comment]
@MSNev 

I checked and `window.onerror` is from AppInsights.

`window.onerror` is not called in all of the cases the "unhandledrejection" event is fired. I need logging for these events as well. This includes unhandled exceptions, which `window.onerror` doesn't appear to track (1).

It looks like you have support for tracking this event here: https://github.com/microsoft/ApplicationInsights-JS/blob/200bb9b563dcfc2ab29277a8e73a3444f2ff107e/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/AnalyticsPlugin.ts#L840

Any idea why this isn't getting run?

**Comment by MSNev** [comment]
Yep, we have an  additional configuration for that `enableUnhandledPromiseRejectionTracking` (which is off by default for backward compatibility). Enabling that [this code you linked](https://github.com/microsoft/ApplicationInsights-JS/blob/200bb9b563dcfc2ab29277a8e73a3444f2ff107e/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/AnalyticsPlugin.ts#L835-L859) which attaches itself to the `window.onunhandledrejection` event.

**Comment by maxburs** [comment]
@MSNev That fixed it! Sorry for opening this issue when it was a config problem. I did try searching through the docs  and googling before opening this, but didn't turn up anything.
