### ISSUE TITLE
[BUG] The documentation for `enableDebug` is incorrect, it should reference `enableDebugExceptions`

### ISSUE THREAD

**Issue by MSNev** [microsoft/ApplicationInsights-JS#2014]
As part of investigating the configuration for #2013 we identified that the documented `enableDebug` flag is not used during the initialization of the SDK and instead is using `enableDebugExceptions`

For previous released versions (v2.x) we should update the documentation to point out that this is called `enableDebugExceptions`, and for later releases we shoudl "consider" whether to use the `enableDebug` with a fallback to `enableDebugExceptions`.

As this is really a developer time (non-production) setting, I'm inclined to only support 1 value rather than 2 (from a code size perspective).

**Comment by celluj34** [comment]
IMO, v3 is a great time to remove it entirely (and put it in the migration notes).

**Comment by MSNev** [comment]
Yeh, for v3 I'm changing this to only support `enableDebug`, but I'll keep this issue open and we will patch v2.x to support both as one was defined in `IConfiguration` and the other in `IConfig` ☹️
