### ISSUE TITLE
[BUG] Beacon API emitting warnings in console

### ISSUE THREAD

**Issue by celluj34** [microsoft/ApplicationInsights-JS#2024]
**Description/Screenshot**

I am trying to use the Beacon API to send telemetry. However I am getting a warning from Edge:

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://eastus2-3.in.applicationinsights.azure.com//v2/track with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

I do see my events in App Insights.

**Steps to Reproduce**

Initialize app insights with connection string, set `isBeaconApiDisabled` to `false` (to enable the api). Additionally, double-negatives are awful for developer experience.

 - OS/Browser: Windows 10
 - SDK Version [e.g. 22]: 2.8.11
 - How you initialized the SDK: NPM

**Expected behavior**

There are no warnings in the console.

**Additional context**

my setup code:

```typescript
const appInsights = new ApplicationInsights({
  config: {
    connectionString: config.appInsightsConnectionString, // use connection string instead of just key
    disableAjaxTracking: true, // we don't use ajax
    disableFetchTracking: true, //don't auto-track fetch calls (too high usage)
    disableExceptionTracking: true, // don't auto-collect exceptions, they'll be sent manually
    disableXhr: true, // don't use XMLHttpRequest
    enableCorsCorrelation: true, // correlate requests with backend requests
    maxAjaxCallsPerView: -1, //track ALL calls from a single page view
    isBeaconApiDisabled: false, // use Beacon API
  },
});
```

**Comment by celluj34** [comment]
Sorry - I was looking at the wrong instance of app insights. Our events ARE being logged, but the warning remains. I will update the issue with correct details.

**Comment by MSNev** [comment]
if you set `disableAjaxTracking` to true this disables all XHR and fetch tracking (so you don't need to set `disableFetchTracking` and `disableXhr`.

And the warning was investigated in #1653 and is not an SDK issue.

**Comment by celluj34** [comment]
Gotcha - I wasn't sure was exactly was generating the error. Sounds like a browser problem, but can be ignored?

**Comment by Karlie-777** [comment]
@celluj34 since the message is raised from browser, do you mind trying to launch browser with `--disable-features=CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating `,  does the warning still remain?

**Comment by celluj34** [comment]
Our app actually run from inside Excel, so I don't know if I can start it with extra arguments. I will try and get back to you.

**Comment by MSNev** [comment]
> Sounds like a browser problem, but can be ignored?

Yes, that is our understanding. And as we don't need to read the response the events will still be recorded.

**Comment by celluj34** [comment]
> @celluj34 since the message is from browser, do you mind trying to launch browser with `--disable-features=CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating `, does the warning still remain?

If I did this correctly (`"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --disable-features=CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating`) then it still logged a warning into the console.

**Comment by celluj34** [comment]
> > Sounds like a browser problem, but can be ignored?
> 
> Yes, that is our understanding. And as we don't need to read the response the events will still be recorded.

Okay, that's fine with me. If there's nothing for you guys to do specifically, I am fine with closing this issue!

**Comment by Karlie-777** [comment]
> > @celluj34 since the message is from browser, do you mind trying to launch browser with `--disable-features=CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating `, does the warning still remain?
> 
> If I did this correctly (`"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --disable-features=CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating`) then it still logged a warning into the console.

Just curious, when launching Edge with line arguments, the error remains on previous running Edge instance or new Edge instance (like close all Edge related OS tasks and open a new browser window)?

**Comment by celluj34** [comment]
Although, now that I think about it, I didn't close all applications (e.g. Outlook) which may have had an instance of the WebView active.

**Comment by Karlie-777** [comment]
> Although, now that I think about it, I didn't close all applications (e.g. Outlook) which may have had an instance of the WebView active.

when you visiting `edge://version` does the `Command-line` includes the arguments?

**Comment by Karlie-777** [comment]
> Cross-Origin Read Blocking (CORB) blocked cross-origin response

Just double checked, the disableCrossSiteBlocking was actually removed from recent chromium versions! visit `edge://flags/` to see which tags are available from your browser. And it seems that maybe you need to disable web security to block messages

**Comment by celluj34** [comment]
If all that is just for not having to see the warnings in the console, I think I'm fine with them showing up. I can't ask all of our end-users to do the same 😅

Originally I wanted to ensure that that warning wasn't blocking info from actually getting sent to App Insights, and it's not. Unless there's anything for you guys to do to ensure it won't be a problem in the future, I will close the ticket. It sounds like there's nothing for you all to do.
