### ISSUE TITLE
[Feature Request] eliminate double-negatives in config setup

### ISSUE THREAD

**Issue by celluj34** [microsoft/ApplicationInsights-JS#2025]
**Is your feature request related to a problem? Please describe.**

Referencing the documentation on how to set different config items is sometimes confusing (e.g. `diableFetch: false` to _enable_ fetch tracking).

**Describe the solution you'd like**

I would like all config options to use more straightforward language (e.g. `enableFetch: true`, `enableXhr: false`).

**Describe alternatives you've considered**

There aren't any alternatives, we just have to take extra time to grok setting config for app insights setup.

**Additional context**

n/a

**Comment by MSNev** [comment]
This is due to historical and backward compatibility reasons.

The default for `disableFetch` is now `false` it was previously `true`.

Likewise, the defaults are now "enabled by default" so if you want to disable you have to specify which one you want to disable.

**Comment by celluj34** [comment]
Yes, sorry, I didn't specify in my original request. Is this something that could be done for v3? Or is it something, in general, that you won't want to do?

**Comment by MSNev** [comment]
We won't be doing this for v3 either, as with v2 these are already enabled by default. And there is already enough significant breaking issues that flipping these around would cause more grief for those customers that have these explicitly disabled to cut down on requests.

**Comment by celluj34** [comment]
Maybe v4 then ;)

Okay, thank you for your time!

**Comment by MSNev** [comment]
Timeline wise we are preparing to promote the beta (v3) to soft launch (NPM only) next week. At which point the beta's should stop their nightly publishing and it becomes just v3-nightly instead.

v3 has already been promoted to the `main` branch and is no longer maintained on the `beta` branch. (The default branch is still `master` until the promotion next week)
