### ISSUE TITLE
[BUG] `hasDocument` should be invoked as function

### ISSUE THREAD

**Issue by scalvert** [microsoft/ApplicationInsights-JS#2061]
**Description/Screenshot**

We maintain a [Docusaurus app insights plugin](https://github.com/microsoft/docusaurus-plugins) (within the MSFT org). As part of adding the `ClickAnalyticsPlugin`, we encountered an issue where code that is intended for the browser is being evaluated at build time on the node side.

It turns out that the `hasDocument` function is being imported and used, but not invoked as a function. 

https://github.com/search?q=repo%3Amicrosoft%2FApplicationInsights-JS%20hasDocument&type=code

All callsites should be updated to correctly invoke `hasDocument` as a function.

**Steps to Reproduce**

 - OS/Browser: macosx/Chrome
 - SDK Version [e.g. 22]: Not sure? This is an issue in the latest published npm package
 - How you initialized the SDK: yarn install

**Steps**
- clone the Docusaurus Plugins repo: `git clone https://github.com/microsoft/docusaurus-plugins`
- checkout the branch that exhibits this issue: `git checkout click-analytics-to-client`
- install deps: `yarn install`
- run a build: `yarn build`

**Expected behavior**

`hasDocument` should be invoked as a function to correctly evaluate whether we're in a browser environment.

**Additional context**
N/A

**Comment by MSNev** [comment]
Will also be released as part of https://github.com/microsoft/ApplicationInsights-JS/milestone/82

**Comment by scalvert** [comment]
Thanks for the fix, @MSNev. I had a branch I was going to push (before I was pulled away) but you beat me to it!

**Comment by MSNev** [comment]
These should be included in the automated nightly and nightly3 releases, which will publish with these tags.

**Comment by scalvert** [comment]
@MSNev when can we expect this to be released? A v3.0.2 would be great.

**Comment by scalvert** [comment]
@MSNev is there any chance of getting a bugfix version out sooner than that timeframe? We're in the middle of a large migration of hundreds of GitHub Pages sites from piwik to app insights, and this bug is a blocker for continuing that work. If we have to wait a month for a fix, this is going to push back our ability to progress to that goal.

**Comment by MSNev** [comment]
@scalvert I've just pinged you on teams to move the scheduling discussion to their, rather than here.
