### ISSUE TITLE
[BUG] trackEvent return undefined

### ISSUE THREAD

**Issue by madebymt** [microsoft/ApplicationInsights-JS#2076]
**Description/Screenshot**
Trying to track click event but `appInsight.trackEvent(eventName)` return undefined, and will not show up at the log

**Steps to Reproduce**
1. npm install package
2. AppInsight file, so I can call it for places have button click

AppInsight.js
```
import { ApplicationInsights } from '@microsoft/applicationinsights-web';

export class TrackAppInsights {
  constructor() {
    this.appInsight = new ApplicationInsights({
      config: {
        connectionString:  'staging.url',
        enableAutoRouteTracking: true,
      },
    });
  }

  initAppInsights() {
    this.appInsight.loadAppInsights();
  }

  trackAppEvent(event) {
    console.log('app', this.appInsight)  // log result in image 1
    console.log('app-2', this.appInsight.appInsights); // log result in image 2
    console.log('this.appInsight', this.appInsight.trackEvent(event));   // <---- show undefined
    this.appInsight.trackEvent(event);
  }
}

```
test.js

```
import { AppInsightsService } from './AppInsight';
const appInsights = new AppInsightsService();

.....
// When button click I use this code
appInsights.trackAppEvent({
   name: 'click-test',
});
```

 - OS/Browser: Chrome 120.0
 - SDK Version [e.g. 22]: ` "@microsoft/applicationinsights-web": "^3.0.0",`
 - How you initialized the SDK: npm

**Expected behavior**
- Should show up in the app insight report --> transaction search ---> custom event select it

**Image 1**
<img width="559" alt="Screenshot 2023-05-16 at 3 06 04 PM" src="https://github.com/microsoft/ApplicationInsights-JS/assets/26178313/5c7585be-ac77-4070-84db-44a6865233e3">

**image 2**
<img width="481" alt="Screenshot 2023-05-16 at 3 05 57 PM" src="https://github.com/microsoft/ApplicationInsights-JS/assets/26178313/aa4642e0-d768-4dc6-a9e1-685decc51bc5">

Thanks for any suggestion.

**Comment by MSNev** [comment]
I'm not sure I'm following...
`console.log('this.appInsight', this.appInsight.trackEvent(event));   // <---- show undefined`
This is expected as the `this.appInsight.trackEvent(event);` doesn't return anything so it will always be `undefined`

Depending on the content of the `event` your passing in it might be that it's considered to be invalid, for some reason but...

> Should show up in the app insight report --> transaction search ---> custom event select it
I Agree, and the usage you have with the name looks fine.

You might want to install the chrome debug extension https://github.com/microsoft/ApplicationInsights-JS/tree/main/tools/chrome-debug-extension which not only shows the sent events but will also show some internal error messages and failures return from the endpoint.

**Comment by madebymt** [comment]
Thanks! I'll check that.

**Comment by madebymt** [comment]
I download it, do see any particular error still don't see custom event log in app insight.
<img width="575" alt="Screenshot 2023-05-16 at 3 48 37 PM" src="https://github.com/microsoft/ApplicationInsights-JS/assets/26178313/05f0e26a-2511-4178-a789-e6dfb7d772c5">
<img width="250" alt="Screenshot 2023-05-16 at 3 50 32 PM" src="https://github.com/microsoft/ApplicationInsights-JS/assets/26178313/9a586c69-39d7-4aac-895b-44f1c5732e96">

**Comment by MSNev** [comment]
The screen shot is only showing the notifications (telling me that the internal network requests are being sent), as the events are not showing I assume that you have the "Network" unchecked.

![image](https://github.com/microsoft/ApplicationInsights-JS/assets/54870357/e3caab6c-611c-415a-93b9-bd38b1a74b81)

If you enable that you can use the "Filter..." text box to just type in your "click-test" (without the quotes) to find all references in the instance. If it's not being sent (and as you are not seeing any errors) then will probably need to debug into the code to see why the event is getting dropped / ignored (as the provided code fragments should work)
