### ISSUE TITLE
[BUG] Authorization header is not supported by AI service

### ISSUE THREAD

**Issue by cloudsere** [microsoft/ApplicationInsights-JS#2082]
**Description/Screenshot**

Request rejected by AI service when I tried to send track request in browser using `fetch` with `Authorization` header set.
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/9955832/deb2d4a6-f61d-4d82-a61a-117ab20c5138)

**Additional context**
AI service actually accepts `Authorization` token now: https://learn.microsoft.com/en-us/azure/azure-monitor/logs/api/app-insights-azure-ad-api
I think the AI service should add `Authorization` in `Access-Control-Allowed-Headers` for be able to send these requests in browser environment.

**Comment by MSNev** [comment]
Authorization is not supported from a browser.
I'll forward the request onto the internal team that manages the service.
