### ISSUE TITLE
[BUG] - Automatic dependency collection inside of an SPFx list view extension breaks after some time

### ISSUE THREAD

**Issue by hazzinator1** [microsoft/ApplicationInsights-JS#2101]
**Description/Screenshot**
I created a panel within a SPFx ListView extension, from which I have been making calls to various graph API endpoints using PnPJS. There is nothing particularly weird about my setup, the code itself is quite simple and doesn't do anything strange. I have done this in previous applications, but all of those have been hosted via web servers and accessed as standard websites. The only thing I'm doing differently here is that I am running this inside a panel within a SharePoint extension. 

What I have noticed is that a small amount of time after setting up the app insights instance (via the NPM method), the `fetch` method that is normally overwritten by the app insights version is **re-overwritten** by the default version. I have done some `console.log(fetch)`s within my application to demonstrate this over time.
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/124360604/f642cbce-04ba-4b26-95c4-dda37eb69509)

My only guess is that there is some background SharePoint process that seems to be overwriting `fetch` or resetting it back to the default version after some time. Not sure if there's anyway to work around that from you guys' side, but there is one workaround I have found for now (see below).

**Steps to Reproduce**
- Setup an SPFx React application from https://github.com/kkazala/spfx-Panel/
- Install and setup the NPM version of Application Insights JS somewhere in the code
- Inside the panel, run a fetch request to https://httpbin.org/get at regular intervals
- After awhile, app insight will stop logging the fetch requests to app insights and a call to `console.log(fetch)` in the console will return the native code version.

**Environment**
 - OS/Browser: Chrome
 - SDK Version [e.g. 22]: 3.0.2, though was present on all older version that I tried going back to 2.8.xxx
 - How you initialized the SDK: via NPM, constants created within a .ts file
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/124360604/454bc610-200f-4d80-b825-d385582925a8)

**Expected behavior**
All fetch requests will be logged inside of the panel

**Additional context**
I have a workaround at the moment by saving the instance of `fetch` directly after calling `appInsights.loadAppInsights()`. This will have the ai.hook version of `fetch`, which I can then access globally in my applicaton instead of using `fetch(...)`, which will quickly get overwritten.
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/124360604/1a85d36c-ecb7-43b7-8ef3-2df7215a2e6a)

**Comment by MSNev** [comment]
Yeah, apart from polling and checking there is not much we could do about this.

Can I suggest that you raise an issue with Sharepoint for this, including the version that you are using etc.

We would prefer not to introduce any "polling" mechanism by default as we have consumers that run on mobile / low power devices where having an interval or regular timer causes power consumption issues...

**Comment by hazzinator1** [comment]
No problem, thanks for the quick reply. I'll post something on Sharepoint's end
