### ISSUE TITLE
[BUG]: TS error using reactPlugin as an extension in new ApplicationInsights

### ISSUE THREAD

**Issue by karolis-666** [microsoft/ApplicationInsights-JS#2103]
**Description/Screenshot**
After upgrading packages `@microsoft/applicationinsights-react-js` and `@microsoft/applicationinsights-web`  to newest an TS error occurred:

<img width="692" alt="image" src="https://github.com/microsoft/ApplicationInsights-JS/assets/79225490/11223dd1-f8cc-4829-89b4-0b3b3b72fe58">

**Steps to Reproduce**

- Clone repo from here https://github.com/karolis-666/azure-insight-demo/tree/main
- Install node_modules
- Run typescript in IDE to detect TS error

**Expected behavior**
- No TS error

**Additional context**
Code was made following docs as shown here https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-framework-extensions?tabs=react

**Comment by karolis-666** [comment]
"typescript": "^4.9.5",
    "@microsoft/applicationinsights-react-js": "^3.4.3",
    "@microsoft/applicationinsights-web": "^3.0.2",

Upgrading typescript to v5 has no impact on the issue

**Comment by MSNev** [comment]
An updated version of the React Plugin has now been published -- closing
