### ISSUE TITLE
Consider export `IClickAnalyticsConfiguration` from the click plugin?

### ISSUE THREAD

**Issue by gao-sun** [microsoft/ApplicationInsights-JS#2106]
**Is your feature request related to a problem? Please describe.**
As we are using TypeScript, exporting `IClickAnalyticsConfiguration` will be helpful to ensure the config is in the correct shape when passing the plugin configuration object to `extensionConfig`. We were using the workaround but it doesn't work in v3.x:

```ts
import { type IClickAnalyticsConfiguration } from '@microsoft/applicationinsights-clickanalytics-js/types/applicationinsights-clickanalytics-js';
```

**Describe the solution you'd like**
Export `IClickAnalyticsConfiguration` from the click plugin, or in general, export plugin config types.

**Describe alternatives you've considered**
Use a weak type `Record<string, unknown>` for plugin configuration, but it feels not safe in the long run.

**Comment by MSNev** [comment]
Agree, tagging as a bug as this should have been defined to be exported.
