### ISSUE TITLE
ai_user and ai_session cookies only get sent from localhost

### ISSUE THREAD

**Issue by danielhart1414** [microsoft/ApplicationInsights-JS#2121]
**Description/Screenshot**
I have a React front-end and .NET back-end. Both have their own App Insights instance, and both have the App Insights SDK installed. I want the API to receive the user and session from the front-end to use in analyzing API telemetry. From what I've read, this should happen automatically when you have the App Insights SDK installed on both front-end and back-end. It works when I run the front-end on localhost and send requests to my API deployed in Azure, and user and session cookies get sent as expected. However, when I deploy the UI to Azure, the user and session cookies are not sent. They are generated and appear in application storage, but they are not sent with the request.

Local request
![localhost_request](https://github.com/microsoft/ApplicationInsights-JS/assets/22263745/95b07f23-8aac-4a49-b492-7a1824982ac1)

Azure request
![azure_request](https://github.com/microsoft/ApplicationInsights-JS/assets/22263745/66830a27-e708-40a4-a0de-7ac07315433e)

OS/Browser
Chrome 115.0.5790.110 and Firefox 114.0.2
 
SDK Version
 - Microsoft.ApplicationInsights.AspNetCore 2.21.0
 - @microsoft/applicationinsights-react-js: 3.4.2
 - "@microsoft/applicationinsights-web: 2.8.12
 
 How you initialized the SDK:
```
const appInsights = new ApplicationInsights({
  config: {
    connectionString: EnvironmentService.getAppInsightsConnection(),
    correlationHeaderDomains: [EnvironmentService.getApiDomain()], // I got the same results without this
    enableCorsCorrelation: true, // and without this
    extensions: [reactPlugin],
    extensionConfig: {
      [reactPlugin.identifier]: { history: browserHistory }
    }
  }
});
```

**Expected behavior**
Both locally and when deployed in Azure, the App Insights UI should send the user and session cookies in API requests.

**Additional context**
I am using axios for API requests. I've tried adding withCredentials to those requests. When I do, the user and session cookies are still not included in the request. However, one of the ARRAffinity cookies is sent as a Request Cookie instead of a Response Cookie, and the other is left out.

Thank you for your time!

**Comment by MSNev** [comment]
The `ai_user` and `ai_session` are rooted to the domain of the page and will not be sent to other domains (except for sub-domains), this is standard browser behavior and is not controlled by the SDK.

ie. Cookies are only sent to the domains in which the cookies belong to.

**Comment by danielhart1414** [comment]
Thank you for your response! In my situation, the UI runs on something akin to ui.example.com, while the API is on something like api.example.com. So the primary domains are the same.

I was trying to find where I read that the API SDK should pick up the user and session ids sent from the UI SDK. The following documentation at least seems to imply that: "The user ID is also set in a session cookie and sent to the server. If the server SDK is installed, the authenticated user ID is sent as part of the context properties of both client and server telemetry. You can then filter and search on it." 
https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#authenticated-users

Granted, I'm currently only using the ids that the App Insights UI generates and not authenticated ones, but I would imagine it would still work. It does when the UI is running on localhost.

I'd appreciate any insights you might have regarding this.

**Comment by danielhart1414** [comment]
Thanks for your response! Your point that the cookies are just randomly generated values gave me an idea for a work-around. In my API, I can take the Name Identifier claim from the user's token and add it as a custom property to the request telemetry. Since the API app insights instance can use that in queries now, it doesn't need the `ai_user` and `ai_session` cookies. I pushed this fix to my dev environment in Azure, and it works great!

Thanks again for your help! As long as you think everything is working as expected with the `ai_user` and `ai_session` cookies, please feel free to close this issue.
