### ISSUE TITLE
Version 3.0.2 - Npm outdated error after 2.8.15 released

### ISSUE THREAD

**Issue by bdbvb** [microsoft/ApplicationInsights-JS#2126]
After the release of version 2.8.15, npm outdated now gives an error (result code 1) when 3.0.2 is actually installed. Indicates that 2.8.15 is the "latest" version when in fact it's 3.0.2. 

![image](https://github.com/microsoft/ApplicationInsights-JS/assets/11095196/1752ff15-289f-4743-9f69-ff48d4b8604a)

**Comment by MSNev** [comment]
Well, technically 2.8.15 is the "latest" (most recent release)...

But yes I agree it would be preferable for the latest version to remain as the "latest" and not previous release with "fixes"

**Comment by MSNev** [comment]
I've manually set 3.0.2 back to the "latest", I'll continue with all of the other packages published yesterday as well then I'll close this issue.

**Comment by MSNev** [comment]
All versions manually reset -- the linked PR is an automated script to make this easier in the future should it occur again.
