### ISSUE TITLE
[BUG] Submitting `NaN` via `trackEvent` results in HTTP 400 Error Code

### ISSUE THREAD

**Issue by fahey252** [microsoft/ApplicationInsights-JS#2132]
**Description/Screenshot**

Submitting various JavaScript data types via track event works except for `NaN` values. <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN>.  When when `trackEvent` submits the HTTP requests to `https://dc.services.visualstudio.com/v2/track` and the properties contains values of  `NaN`, you get an HTTP 400 with the response of `message": "200: Child value 'NaN' for key 'notANumber' is of incorrect type. Expected: number, Actual: string"`. 

All other JavaScript types seem to be supported or removed from the payload without error. Notice that `NaN` was moved from `properties` to `measurements` in the request payload with the other Number typed values. See Steps to Reproduce below for sample payload and how they there transformed in the request payload or stripped out.

HTTP Request Payload:
<img width="976" alt="request-payload" src="https://github.com/microsoft/ApplicationInsights-JS/assets/757838/c6cc4ad1-8520-4831-8b1f-8c8ee42e2a2f">

HTTP Response Payload:
<img width="1303" alt="response-payload" src="https://github.com/microsoft/ApplicationInsights-JS/assets/757838/03abdbad-9fad-42bb-9f19-a5016f3f3714">

**Steps to Reproduce**

```javascript
const properties = {
    bigInt: 9999999999999999,
    booleanValue: true,
    callback: () => { },
    emoji: '🤷‍♀️',
    largeValue: Infinity,
    listOfValues: [1, 3],
    nullValue: null,
    number: 5,
    object: {
      property1: {
        nestedProperty: 'nested object'
      }
    },
    notANumber: NaN,
    regex: /test/g,
    someClass: Alert,
    someDate: new Date(),
    symbol: Symbol,
    undefinedValue: undefined
  }
const eventName = 'DataTypeTesting'

appInsights.trackEvent({ name: eventName }, properties);
```

 - OS/Browser: React Native Debugger, Chrome 114
 - SDK Version [e.g. 22]:  `"@microsoft/applicationinsights-web": "^3.0.2",` and `"@microsoft/applicationinsights-react-native": "^4.0.0",`
 - How you initialized the SDK: `yarn`

**Expected behavior**

When a data type such as a regex is submitted via `trackEvent`, its value is converted to `undefined`. `NaN` values should be treated the same or converted to `'NaN'` string values.

**Additional context**

Fixed with this JavaScript in our code base to support `NaN` values and how it appears in Azure Monitor Logs:
```javascript
const sanitizedProperties = Object.keys(properties).reduce(((accumulator, key) => {
      // AppInsights doesn't support NaN values, HTTP request fails and receives no telemetry. Convert NaN's to string value
      if (Number.isNaN(accumulator[key])) {
        accumulator[key] = String(accumulator[key]);
      }

      return accumulator;
    }), properties);

    appInsights.trackEvent({ name: eventName }, sanitizedProperties);
```
Logs with `NaN` values as as string:
<img width="395" alt="logs" src="https://github.com/microsoft/ApplicationInsights-JS/assets/757838/799306a0-f054-4cb0-abc7-aead6767682f">

**Comment by MSNev** [comment]
Nice find, this has probably been here for a long time and the error message indicates that the JS SDK is "passing" the value through to the server and it's the server that is rejecting the value.

Tagging as an enhancement (so it won't get auto closed), not sure when we be able to schedule this issue at this point in time.

We will need to review the field validation / conversion to see if there is a way to achieve this in a performant manner, as it looks like the issue could occur on any field (even ones that are not strictly defined by the event -- eg. user properties).
