### ISSUE TITLE
[BUG] Fetch with empty string as first parameter ignores second parameter when fetch tracking is enabled

### ISSUE THREAD

**Issue by jorupp** [microsoft/ApplicationInsights-JS#2149]
**Description/Screenshot**
When `disableFetchTracking: false`, `fetch` calls with an empty string (`''`) as their first argument have all the data in their second argument ignored.  This causes `POST` calls to be made as `GET`, loses headers, etc.

**Steps to Reproduce**

 - OS/Browser: Windows 10/Chrome 116.0.5845.180
 - SDK Version [e.g. 22]: Current snippet from <https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-sdk?tabs=javascriptwebsdkloaderscript>.
 - How you initialized the SDK: Javascript snippet

**Expected behavior**
Repro: <https://jorupp.github.io/ai-post-test/with-ai.html> and open dev tools, network tab.
Click "POST with URL" - as expected, it does a POST (which gets a 405).
Click "POST with empty string" - it does a GET (which gets a 200), instead of a POST to the current page.

**Additional context**
<https://jorupp.github.io/ai-post-test/without-ai.html> has the same code without the AI SDK loaded, and does a POST for both buttons (which returns 405s).

I believe the culprit is <https://github.com/microsoft/ApplicationInsights-JS/blob/c6c27fc3b5fe0e7743ace5cd5180581fb0b808f5/extensions/applicationinsights-dependencies-js/src/ajax.ts#L413> - changing that to `if (input || input === '')` locally resolves the issue for me.

This manifested as client-triggered server events for a NextJS 13 app-router application not working: <https://github.com/vercel/next.js/discussions/55405>.

**Comment by MSNev** [comment]
Thanks, which version of the SDK are you using?
v2.x and / or v3.x?

If you want, please feel free to submit a PR to fix this issue, if it's in v2.x this is managed from the `master` branch and we will also need to either cherry-pick or duplicate the fix on `main` for v3.x. Or if your using v3.x we can just fix on `main`.

**Comment by jorupp** [comment]
The repro I created used `https://js.monitor.azure.com/scripts/b/ai.2.min.js` which I'm guessing is v2 based on the name, and locally, I was using 2.7.3.

I'll look into getting a PR for it.
