### ISSUE TITLE
[BUG] Readme Issue for perfmarkmeasure @microsoft/applicationinsights-applicationinsights-perfmarkmeasure-js@

### ISSUE THREAD

**Issue by zhucalvin** [microsoft/ApplicationInsights-JS#2150]
https://github.com/microsoft/ApplicationInsights-JS/blob/main/extensions/applicationinsights-perfmarkmeasure-js/README.md

The npm install command should be:

npm install --save @microsoft/applicationinsights-perfmarkmeasure-js @microsoft/applicationinsights-web

instead of:

npm install --save @microsoft/applicationinsights-applicationinsights-perfmarkmeasure-js @microsoft/applicationinsights-web

**Comment by zhucalvin** [comment]
57 error code E404
58 error 404 Not Found - GET https://registry.npmjs.org/@microsoft%2fapplicationinsights-applicationinsights-perfmarkmeasure-js - Not found
59 error 404
60 error 404  '@microsoft/applicationinsights-applicationinsights-perfmarkmeasure-js@*' is not in this registry.
61 error 404
61 error 404 Note that you can also install from a
62 error 404 tarball, folder, http url, or git url.
63 verbose exit 1
64 timing npm Completed in 1410ms
65 verbose unfinished npm timer reify 1694803010221
66 verbose unfinished npm timer reify:loadTrees 1694803010226
67 verbose code 1

**Comment by MSNev** [comment]
yikes! Nice catch
