### ISSUE TITLE
Can I separate customDimensions in trackEvent log?

### ISSUE THREAD

**Issue by madebymt** [microsoft/ApplicationInsights-JS#2153]
**Is your feature request related to a problem? Please describe.**
I am using this trackEvent to log my app event, but anything in `properties` show up in the log is a object not a separate columns, so it's easier for us to track the data. 

Thank you!

```
appInsights.trackEvent({
  name: 'some event',
  properties: { // accepts any type
    prop1: 'string',
    prop2: 123.45,
    prop3: { nested: 'objects are okay too' }
  }
});
```

Here's the CSV I export form appInsight --> Transaction search ---> view log ---> Export 
![Screenshot 2023-09-18 at 3 12 39 PM](https://github.com/microsoft/ApplicationInsights-JS/assets/26178313/2b231e63-d48e-476f-bf2f-ed3d538317a4)

**Describe the solution you'd like**
I want each object field to be their own column

**Additional context**

Version I use:
 @microsoft/applicationinsights-web: "^3.0.0",

**Comment by johncrim** [comment]
You can use `project` or `extend` KQL operators to flatten, select, and rename the properties you want, before exporting to CSV.

https://learn.microsoft.com/en-us/azure/azure-monitor/logs/get-started-queries#use-project-and-extend-to-select-and-compute-columns
