### ISSUE TITLE
How this package works - Nextjs

### ISSUE THREAD

**Issue by Ramemis** [microsoft/ApplicationInsights-JS#2182]
I have nextJs application. 

`Telemetry.ts`
```
import { ApplicationInsights } from '@microsoft/applicationinsights-web';

const appInsights = new ApplicationInsights({
  config: {
    connectionString:
      'InstrumentationKey=<<connectionString>>',
  },
});

appInsights.loadAppInsights();
export { appInsights };

```

`Document.ts`
```
import { Html, Head, Main, NextScript } from 'next/document';
import Script from 'next/script';
import { appInsights } from 'services/telemetry';

appInsights.trackPageView();
appInsights.startTrackPage();
const Document = () => {
return ();
}
```

1. The document page is the homepage. So when ever I hit the homepage I can able to see the PageViews logs are getting populated in the log table. But it doesn't give any information like below. What I expect is atleast the url of the page which loads this application. But the below information doesn't provide anything.
![image](https://github.com/microsoft/ApplicationInsights-node.js/assets/121164498/c019c678-8a81-4f7c-b1a9-7fac0842a8fd)

2. I read that difference between operation vs dependency. That the request will be tagged under operations and the response will be under dependency (correct me if I'm wrong). But in the above case even though I can see the page views in logs. I don't see the graph spike for request count in neither the operation nor the dependency. Is there anything I'm missing.

3. How to log each request(url and page information) for each page views I'm visiting. Is there anything apart from the above need to be done.

**Comment by MSNev** [comment]
The URL for this Web based SDK is obtained from the `location.href`, if this code is running on the Server side (in the NextJS runtime), then this would indicate that these values are either not available, or the server request is not supplying a mocked version of the `location` object.

How to populate this (for the automatic) request (on the server) is unknown (we don't use NextJS). However, if you don't have the automatic PageView enabled (`enableAutoRouteTracking`) and you are manually calling `trackPageView()` during the initialization, then you can pass in the uri yourself.

```
appInsights.trackPageView({
    uri: "https://my.url.com/abc"
});
```
