### ISSUE TITLE
[BUG] Custom properties added with addTelemetryInitializer are ignored for first PageVisitTime track event

### ISSUE THREAD

**Issue by Nosfit** [microsoft/ApplicationInsights-JS#2187]
**Description/Screenshot**
When I set autoTrackPageVisitTime to true in the ApplicationInsights configuration, the first payload for PageVisitTime does not contain any custom parameters that I added using the addTelemetryInitialiser method.

![Screenshot 2023-10-26 at 15 01 54](https://github.com/microsoft/ApplicationInsights-JS/assets/12278612/b23a74c0-10f3-48f1-ae99-db5d7f8bcae3)

**Steps to Reproduce**
init telemetry with custom properties: 
```
const appInsights = new ApplicationInsights({
      config: {
        appId: 'test-bug-report',
        connectionString: this.connectionString,
        autoTrackPageVisitTime: true,
      },
    });
    appInsights.loadAppInsights();
    appInsights.trackPageView();
    appInsights.addTelemetryInitializer(this.enrichTelemetry);

    ///

   enrichTelemetry = (item: ITelemetryItem): void => {
      if (item.tags == null) {
        item.tags = [];
      }
      item.tags['ai.cloud.role'] = 'test-bug-report-roleName';
      item.tags['ai.cloud.roleInstance'] = 'test-bug-report-roleInstance';
    };
  ```
  then visit your application and see on first track request in network section. 
  
 - OS/Browser: 
 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'
 - SDK Version [e.g. 22]:
 "@microsoft/applicationinsights-web": "^3.0.4"
 - How you initialized the SDK:

**Expected behavior**

**Additional context**

**Comment by MSNev** [comment]
Yes, this is because you are adding the telemetry initializer "AFTER" you are triggering the page view

flip the order of these 2 functions
```ts
    appInsights.trackPageView();
    appInsights.addTelemetryInitializer(this.enrichTelemetry);
```
to 
```ts
    appInsights.addTelemetryInitializer(this.enrichTelemetry);
    appInsights.trackPageView();
```

**Comment by Nosfit** [comment]
Thanks. That helps
