### ISSUE TITLE
Can clickanalyticsplugin can track the sharepoint webpart 

### ISSUE THREAD

**Issue by GeethuMR-Alstom** [microsoft/ApplicationInsights-JS#2194]
For example, if user click on a link from quick links webpart, will it show the webpart name as well.
How can we track the webpart name

**Comment by MSNev** [comment]
I don't know the answer specifically as the Click Analytics plugin is designed for sites to supply additional meta-data / (data attributes) onto the html and not specifically for Sharepoint.

If you can "add" additional data attributes onto the DOM elements (AND) all clicks propagate (bubble) up to the `document` (which is how this plugin listens to user clicks), then I would expect it to be possible. 

But it knows nothing explicitly about any SharePoint specific meta-data.
