### ISSUE TITLE
What is the future of this package with the recent shift to Open Telemetry?

### ISSUE THREAD

**Issue by wertzui** [microsoft/ApplicationInsights-JS#2199]
Seeing the shift at Microsoft to Open Telemetry, I wanted to know if we should still rely on this plugin or rather use the [Open Telemetry JS plugins](https://github.com/open-telemetry/opentelemetry-js) with the [Azure Monitor exporter for Open Telemetry in JavaScript](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/monitor/monitor-opentelemetry-exporter).

**Comment by wertzui** [comment]
Thanks for the clarification, that was really helpful!

While this is still the preferred package for JavaScript running in a browser, could you clarify if it integrates when the backend API (ASP.Net Core) is using Open Telemetry to export to Azure Monitor?
Especially the Application Map and End-to-End tracing?

**Comment by MSNev** [comment]
Yes, we have been sending the `traceparent` header for quite a while now, this includes the `traceid` (from the page) and a unique `spanid` for each ajax request.

In terms of actual "page loads" there is no way to include the current page `traceid` to the server, so for full page navigations there is not (out of the box) way to trace that scenario.

**Comment by wertzui** [comment]
Thanks, I'll stick to this package in the frontend and move my backend to Open Telemetry then.

**Comment by wertzui** [comment]
Thanks
