### ISSUE TITLE
Provide a way log only Ajax failures (not all Ajax calls)

### ISSUE THREAD

**Issue by kamilszostak** [Microsoft/ApplicationInsights-JS#220]
* Option 1: add a new configuration field to disable/enable ajax failures tracking 
* Option 2: implement more generic solution to filter specific ajax events based on regex or response code

**Comment by dnduffy** [comment]
I like both, independently, for different reasons and use cases.
#1 may be desirable by some customers on its own.
#2 sounds good to me for a generic solution to response codes since maybe we can tie the retry logic into it that looks at 206 etc.

**Comment by AlexBulankou** [comment]
why is using telemetry initializer to filter out successful ajax not an option? Since we have this mechanism, perhaps we don't need anything extra?

**Comment by kamilszostak** [comment]
Right, this can be done using telemetry initializer. Here is a sample code: 

```
appInsights.queue.push(function () {
    appInsights.context.addTelemetryInitializer(function (envelope) {
        var telemetryItem = envelope.data.baseData;

        // To check the telemetry item’s type:
        if (envelope.name === Microsoft.ApplicationInsights.Telemetry.RemoteDependencyData.envelopeType) {
            return telemetryItem.success;
        }
    });
});
```

See [API Reference doc](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#addtelemetryinitializer) for more information about telemetry intitializers.
