### ISSUE TITLE
npm package is a bit of a mess

### ISSUE THREAD

**Issue by ArturDorochowicz** [Microsoft/ApplicationInsights-JS#221]
```
$ npm install applicationinsights-js
└── applicationinsights-js@0.22.17 
```

1. It contains everything, including NuGet.exe, PowerShell files etc.

   ```
$ tree node_modules/applicationinsights-js/ -L 2 
node_modules/applicationinsights-js/
├── API-reference.md
├── bower.json
├── changeSdkVersion.ps1
├── Common.props
├── dist
│   ├── ai.0.js
│   └── ai.js
├── EnlistmentRoot.marker
├── Global.props
├── JavaScript
│   ├── JavaScriptSDK
│   ├── JavaScriptSDK.Tests
│   ├── Microsoft.ApplicationInsights.JavaScript.sln
│   ├── NuGet.JavaScript
│   ├── NuGet.TypeScript
│   └── PostTestScript.cmd
├── LICENSE
├── NuGet.config
├── NuGet.exe
├── NuGet.targets
├── package.json
├── Package.targets
├── PostTestScript.cmd
├── PushNugetPackages.cmd
├── README.md
├── runAllTests.cmd
├── RunTestsInBrowser.ps1
├── ThirdPartyNotices.txt
└── uploadFilesToAzureStorage.ps1

6 directories, 23 files
   ```

2. `main` field in `package.json` points to `JavaScriptSDK/AppInsightsModule`. I doubt it's supposed to point to a TypeScript file, but if so it skips the `JavaScript` directory. Preferably it should point to `dist/ai.js` (i.e. unminified file), I think.

3. The one usable thing in here which are the javascript files in `dist` are actually different version (0.22.15).

4. The minified file is `ai.0.js`. That's a bit unconventional, I would expect `ai.min.js`.

Besides, what's the story here? Is it supposed to be an npm package with TypeScript? Or the point of the package is the JavaScript in `dist` directory?

The readme file in "Import as a module and initialize dynamically (download full Application Insights script from CDN)" talks about "modern JS application", however the code example is TypeScript and the `downloadAndSetup` method can only be found in the package in TypeScript files. That was a bit confusing to me. Please, make this scenario available in JS (that is without me compiling the package).

**Comment by AlexBulankou** [comment]
Thanks @ArturDorochowicz! We'll work on improving this early next week, will have another update Monday on this.

**Comment by AlexBulankou** [comment]
With the latest release to npm we addressed issues (2) (published AppInsightsModule.js that is now default entry point) and (3) (updated JS files in dist folder to the latest version - 0.22.18). Won't fix for (1) and (4).

**Comment by AlexBulankou** [comment]
Please reopen if you feel you're still blocked from using AppInsights via npm

**Comment by AlexBulankou** [comment]
Reactivating, looks like AppInsightsModule.js wasn't published correctly, opened PR for this: https://github.com/Microsoft/ApplicationInsights-JS/pull/227

**Comment by AlexBulankou** [comment]
Addressed

**Comment by sondreb** [comment]
I installed the "applicationinsights-js" package now (first of June 2016) and it's still a messy package with a lot of content that really doesn't need to be there.

There are obj/Debug and obj/Release folders laying around, but the biggest issues are the size and the inclusion of multiple .exe files.

chromedriver.exe
IEDriverServer.exe
NuGet.exe

Most of the time I advice against copying and deploying node_modules directly to the server, in the very first beta release of ASP.NET 5, Microsoft had configured and advised for developers to publish bower/node packages directly into the web folder. That is very scary, considering some packages might include files such as .cs (which there are in your package, like IISExpress.cs) and .exe files, and with the wrong IIS configuration, attackers could potentially execute code on the server.

You clearly know about .npmignore to exclude files, as there is multiple of them in the repo, I hope you can go through and remove other files that are really not needed.

When a project already have many NPM packages, which is the nature of npm, it is clearly not welcome to have an extra 13MB package when all that is really needed in the package is a JavaScript file of 206KB. Until it is cleaned up, I have to simply copy the dist/ai.js and manually include it in our projects.

**Comment by MaxShehovtsov** [comment]
Thanks, we'll fix it!

**Comment by AlexBulankou** [comment]
Just pushed .npmignore file #248, which cleaned it up. Thanks for raising this issue, please feel free to reactivate if there are any concerns.
