### ISSUE TITLE
Question: Where does the id show up?

### ISSUE THREAD

**Issue by cbtgit** [microsoft/ApplicationInsights-JS#2225]
Where in the App. insights interface can i see/search for the id that can be supplied for the IExceptionTelemetry interface?

`export declare interface IExceptionTelemetry extends IPartC {
    /**
     * Unique guid identifying this error
     */
    id?: string;
    /**
     * @deprecated
     * @type {Error}
     * @memberof IExceptionTelemetry
     * @description DEPRECATED: Please use exception instead. Behavior/usage for exception remains the same as this field.
     */
    error?: Error;
    /**
     * @type {Error}
     * @memberof IExceptionTelemetry
     * @description Error Object(s)
     */
    exception?: Error | IAutoExceptionTelemetry;
    /**
     * @description Specified severity of exception for use with
     * telemetry filtering in dashboard
     * @type {(SeverityLevel | number)}
     * @memberof IExceptionTelemetry
     */
    severityLevel?: SeverityLevel | number;
}`

**Comment by MSNev** [comment]
By Default the automatic captured errors don't populate the `id`, you can however call the `trackException()` yourself and as part of the `IExceptionTelemetry` object you pass in you can specify the `id` yourself.

We treat any passed instance as a simple object and not some type of class.
Here is the code we use to "construct" the automatic error isntances (effectively from the window.onerror) https://github.com/microsoft/ApplicationInsights-JS/blob/ac9c516d421be79ae956ccceb50d9c9e0533282e/shared/AppInsightsCommon/src/Telemetry/Exception.ts#L404-L428

**Comment by cbtgit** [comment]
@MSNev Thank you for your reply. I am calling trackException myself and passing in, an id generated with the uuid npm package. If i go to Logs and exceptions in the App. insights UI, I can't seem to find a column containing my id - there is a itemId column, with a diff. id, but no column with my generated id?

**Comment by siyuniu-ms** [comment]
hi @cbtgit sorry for the late response.
Here is my local test result:
1.      appInsights.trackException({id:"siyuTest1", error: new Error("test local exception"), severityLevel: 3});
this one would not show id in azure portal
2.            appInsights.trackException({id:"siyuTest2",  severityLevel: 3});
and this one would pass the id to the azure portal
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/123212536/5ef779fc-a22e-4b13-9541-36e9faa29d74)
Seems like in the option 1, the error message overwrite the id. Will continue investigate...
