### ISSUE TITLE
how to fix "NullInjectorError: No provider for AppInsightsSku!"

### ISSUE THREAD

**Issue by WeizhouWang** [microsoft/ApplicationInsights-JS#2226]
try to add appInsights in an angular project following 
https://software-ranjit.medium.com/how-to-integrate-azure-application-insights-to-an-angular-application-15ffff977cc6, 
and get error:
 NullInjectorError: No provider for AppInsightsSku!

What should I do?

Thanks

**Comment by MSNev** [comment]
This sounds like an angular configuration issue, where you have not registered the provide for application insights. That is beyond to general knowledge of our team.

Suggest that you ask a question of the author of the post you reference, or check that you haven't missed something. It may also be some sort of difference between the version on Angular that the author documented vs the version you are using.

**Comment by WeizhouWang** [comment]
Thanks Nev,

It is because I imported wrong service. Now it works.
