### ISSUE TITLE
[BUG] Event time is not set

### ISSUE THREAD

**Issue by estebane97** [microsoft/ApplicationInsights-JS#2283]
Hi,

I have a setup using react plugin and autoRouteTracking enabled.

I found that all events on App Insights are recorded at the **T00:00:00Z**.

When I looked at the data sent, I found that the time property only contains the date part and not the time.

```
{
  data:   { baseType: "RemoteDependencyData",… },
  iKey: "XXX-XXX-XXX"
  name: "Microsoft.ApplicationInsights.8bd3ed35b6684d76894290692a725241.RemoteDependency"
  tags : {ai.user.id: "xxxx", ai.session.id: "xxxx",…}
  time "2024-02-28"
}
``` 

This also produce an error based on timezone difference where app insights returns a 400 error.
The message is:
**104: Field 'time' on type 'Envelope' is newer than the max date. Expected: now + 7200000ms**

![image](https://github.com/microsoft/ApplicationInsights-JS/assets/6700963/98d43937-af20-4b38-80a6-1137d3e85100)

**Steps to Reproduce**

 - OS/Browser:
 Chrome latest

 - SDK Version:
```
 "@microsoft/applicationinsights-react-js": "17.1.0",
 "@microsoft/applicationinsights-web": "3.1.0",
``` 

 - How you initialized the SDK:
 
```typescript
reactPlugin = new ReactPlugin();
    appInsights = new ApplicationInsights({
      config: {
        connectionString: CONNECTION_STRING,
        enableAutoRouteTracking: true,
        extensions: [reactPlugin]
      }
    });
    appInsights.loadAppInsights();
``` 

**Expected behavior**
Date and time should be set 

**Additional context**

**Comment by siyuniu-ms** [comment]
Hi, could you provide the code of how you send out the event that contains time also?

**Comment by estebane97** [comment]
This is happening on all telemetry items, PageView, Event, RemoteDependency...

to call I just call the method without setting any specific time.

`appInsights.trackEvent({ name: eventName }, properties);`
`appInsights.trackPageView({ name: pageName, properties });`
`appInsights.trackException( { exception: error, severityLevel: SeverityLevel.Critical },  properties);`

That produce the payload with the time set on ISO string format and not time set.

Looking into the code there is only 1 place that is creating the time prop with that format using the `toISOString` method:

https://github.com/microsoft/ApplicationInsights-JS/blob/9d2267e0256a17bd5fd9bb29f74dbe70b6de1ff4/shared/AppInsightsCommon/src/TelemetryItemCreator.ts#L43

While other places create the time prop using the `_getTime` method which return the full time stamp

https://github.com/microsoft/ApplicationInsights-JS/blob/0aae7dbda79c49c8c808a6641cf43884b7c39d7f/tools/applicationinsights-web-snippet/src/snippet.ts#L146

**Comment by siyuniu-ms** [comment]
<img width="687" alt="image" src="https://github.com/microsoft/ApplicationInsights-JS/assets/123212536/e213e161-c825-4242-9b01-633eeb879905">
Hi, did a local test here. I could see the time-stamp here by calling appInsights.trackEvent("name", {a:3}); Is there anything I missed here?

**Comment by estebane97** [comment]
I found the problem, and it was not related to the app insights package, it was related to another library overriding the default toISOString, removed that and it is working fine.

Thanks for your help and time.
