### ISSUE TITLE
Type definitions are not up to date

### ISSUE THREAD

**Issue by ccrowhurstram** [Microsoft/ApplicationInsights-JS#230]
The type definitions maintained over at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/applicationinsights-js/applicationinsights-js.d.ts) seem to be out of sync with the current API.

Please can you **keep these typings in sync with API** otherwise it makes writing typescript consumers of the SDK very painful to write.

Thanks
Christian

## Example

*[Current API](https://github.com/Microsoft/ApplicationInsights-JS/blob/e369b6a96d8a738c6d5733131f19b66d60559815/JavaScript/JavaScriptSDK/Telemetry/PageView.ts#L7)*
```ts
module Microsoft.ApplicationInsights.Telemetry {
    "use strict";

    export class PageView extends AI.PageViewData implements ISerializable {
```
Visaul Studio code showing compiler failure:

![2016-06-09 18_40_21-appinsights ts - angular-cc-appinsights - visual studio code](https://cloud.githubusercontent.com/assets/8319020/15939927/d1cd259a-2e71-11e6-9f59-840f5388dd59.png)

**Comment by ccrowhurstram** [comment]
FYI, here are the extra [augmented] typings I needed for the code I references thus far in the SDK:

```ts

declare namespace AI {
    export enum DependencyKind {
        SQL = 0,
        Http = 1,
        Other = 2,
    }
}
declare namespace Microsoft.Telemetry {
    export interface Base {
        baseData: { 
            dependencyKind: AI.DependencyKind;
            properties: { [property: string] : any } 
        }
    }
}
declare namespace Microsoft.ApplicationInsights {
    export namespace Telemetry {
        // missing PageView class and its static members
        export namespace PageView {
            let envelopeType: string;
        }
        // missing PageView class and its static members
        export namespace RemoteDependencyData {
            let envelopeType: string;
        }
    }
}
```

**Comment by kamilszostak** [comment]
Thank you reporting this issue. We did some cleanup work and extracted interfaces to a separate project `JavaScriptSDK.Interfaces`. I'm working on updating DefinitelyTyped files. 

I have an initial version [here](https://github.com/kamilszostak/DefinitelyTyped/commit/2ba1fda2176fec175a1cd7aecab8c0a4f7cd48a8).

**Comment by ccrowhurstram** [comment]
Cool.

Out of interest, are you letting the `tsc` compiler generate the `d.ts` file(s) for you, or are you hand coding these?

I'm curious as I had the same decision to make when writing [angular-cc-appinsights](https://github.com/christianacca/angular-cc-appinsights).

For angular-cc-appinsights, I found that the `tsc` tool did a good job of generating the type definitions for my library.

**Comment by ccrowhurstram** [comment]
OK good to know

**Comment by kamilszostak** [comment]
I'll update type definitions in two steps: 

1. Update type definitions for files which are currently exposed in `JavaScriptSDK.Intefaces`:  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9651
2. Add interfaces for other classes (e.g `RemoteDependencyData`) to `JavaScriptSDK.Intefaces` and update DefinitelyTyped.

**Comment by ccrowhurstram** [comment]
Are you planning to make the definitions available using [typings project](https://github.com/typings/typings)?

**Comment by kamilszostak** [comment]
I wasn't aware of Typings project. I'll review it next few days. Thanks!

I send a pull request to DefinitelyTyped repo with definitions for all remaining  classes. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9789
