### ISSUE TITLE
AppInsightsModule hardcodes http path to the script

### ISSUE THREAD

**Issue by ArturDorochowicz** [Microsoft/ApplicationInsights-JS#233]
See:
https://github.com/Microsoft/ApplicationInsights-JS/blob/e739caed7bd9d9f051a54889bf2483e1e43b6db7/JavaScript/JavaScriptSDK.Module/AppInsightsModule.ts#L33

The original snippet uses protocol relative path.

**Comment by MaxShehovtsov** [comment]
Thanks! Looks like a bug.

**Comment by dlebedynskyi** [comment]
any change this fix will be released soon to npm?
