### ISSUE TITLE
[BUG] parentId is not_specified when it's defined on a parent element in DOM

### ISSUE THREAD

**Issue by kxmatejka** [microsoft/ApplicationInsights-JS#2344]
**Description/Screenshot**

I have copied example 3 from the [documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-feature-extensions?tabs=npmpackage#example-3), but `parentId` attribute is `not_specified`.

![image](https://github.com/microsoft/ApplicationInsights-JS/assets/7732437/bce40425-986f-4ed6-8fc0-a39aecfbd5dc)

![image](https://github.com/microsoft/ApplicationInsights-JS/assets/7732437/df79e986-b673-4fb0-b0db-6e0068158ff7)

**Steps to reproduce**
- go to playground https://codepen.io/krystof-matejka/pen/LYoYBQw
- replace `connectionString` on line 21

**Environment**
 - OS/Browser: Edge
 - SDK Version [e.g. 22]: `@microsoft/applicationinsights-clickanalytics-js: 3.2.0`
 - How you initialized the SDK: npm

**Expected behavior**

I expect that `parentId` is `test6parent` as the documentation says.

**Additional context**

**Comment by Karlie-777** [comment]
please try the following
1.   `parentElement.setAttribute("data-parentid", "testParentId")`;
or
2.  set  `parentDataTag:"parentgroup"` under clickanalytics plugin config, set `parentElement.setAttribute("data-parentgroup", "testParentGroup")`;
and let us know if any of these works!

**Comment by kxmatejka** [comment]
hello @Karlie-777 first solution does not work, but the second does! thanks 🙇

**Comment by kxmatejka** [comment]
i see what i did wrong, i haven't copied `parentDataTag: "group"` from the example. so there isn't any issue
