### ISSUE TITLE
"Add telemetry initializer" code snippet is broken

### ISSUE THREAD

**Issue by ischrei** [Microsoft/ApplicationInsights-JS#237]
I've added the code snippet like it said, immediately after the initialization snippet that I got from the portal, but then i get an error "TypeError: Cannot read property 'push' of undefined"
as the 'queue' isn't defined in appInsights.queue

**Comment by ischrei** [comment]
(In fact it happens when the code snippet is invoked twice, and in the second time there is no "queue" anymore. The solution is to wrap the code snippet with:
```
if (appInsights.queue) {
...
}
```

**Comment by missbruni** [comment]
for me this solution doesn't work, if I do the if statement my initializer simply just doesnt run at all.

**Comment by MSNev** [comment]
This must be placed after the snippet segment and in the same code block, otherwise, the queue will already have been processed (because AI in initialized) and is never looked at again.
