### ISSUE TITLE
[Question] Suppressing error messages

### ISSUE THREAD

**Issue by XoTENoC** [microsoft/ApplicationInsights-JS#2399]
I'm working on an application where part of our code is polling a blob, and we're expecting a 404 error until the resource becomes available. While the resource doesn't exist, every time we poll, Application Insights is logging the 404 error to the console. Is there a way to suppress these error messages?
Thanks.

**Comment by MSNev** [comment]
> Application Insights is logging the 404 error to the console

I don't believe that we are the source of logging to the console?? At least by default we should not be as we avoid using the console (by default).

We have a configuration (which defaults to disabled) called [`loggingLevelConsole`](https://microsoft.github.io/ApplicationInsights-JS/webSdk/applicationinsights-core-js/interfaces/IConfiguration.html#loggingLevelConsole).

Which specific version are you using?

**Comment by XoTENoC** [comment]
I'm running version 2.8.8

![changi-screenshot-AkPO9AMD@2x](https://github.com/user-attachments/assets/122506e0-7733-4775-817d-4db6043193b4)

Here is the error I'm encountering when trying to check if the object exists. The image of the error can be found directly above.

In the file util-app-insights.ts, the following code is used:

```typescript
import { ApplicationInsights } from "@microsoft/applicationinsights-web";

const appInsights = new ApplicationInsights({
    config: {
        instrumentationKey: document.querySelector<HTMLElement>(".js-body-form").dataset.appInstKey,
    },
});

appInsights.loadAppInsights();
appInsights.trackPageView();
```

Apologies if I should have provided this information earlier.

**Comment by MSNev** [comment]
That doesn't look like one of our error messages from the SDK, doing a quick search online this error message might be associated with the page not being able to "fetch" (something) from an azure blob store...

Can you check the F12 network tab to see if it can identify the resource (and request) that is returning the 404?

If this was a later version then I might suspect that access to our global cfg sync json file is being highlighted, but that wasn't added until v3.x

**Comment by XoTENoC** [comment]
@MSNev Cheers for your help I appreciate your time.
