### ISSUE TITLE
issues with module loading  and dynamic init

### ISSUE THREAD

**Issue by dlebedynskyi** [Microsoft/ApplicationInsights-JS#242]
Using script provided from readme
```
//1. bootstrap.jsx
import {AppInsights} from "applicationinsights-js"

/* Call downloadAndSetup to download full ApplicationInsights script from CDN and initialize it with instrumentation key */
AppInsights.downloadAndSetup({ instrumentationKey: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx" });
..
```
```
// 2. app.jsx
import {AppInsights} from 'applicationinsights-js';
AppInsights.trackPageView(..);
```
App is called after bootstrap. 
AppInsights.trackPageView can crush as undefined since was not init yet.

**Comment by AlexBulankou** [comment]
@dlebedynskyi do you mean, that if ``trackPageView`` is called before ``downloadAndSetup`` for any reason, than it would crash, while you would expect it merely to put item in the queue?

**Comment by dlebedynskyi** [comment]
@AlexBulankou yes you got it correct.

**Comment by AlexBulankou** [comment]
This is fixed, so the next release on npm will have the fix
