### ISSUE TITLE
stopTrackPage does not flush tracking immediately.

### ISSUE THREAD

**Issue by dlebedynskyi** [Microsoft/ApplicationInsights-JS#243]
stopTrackPage does not call flush immediately after called as you would expect from 

```
Stops the timer that was started by calling startTrackPage and sends the page view telemetry with the specified properties and measurements. 
```
It looks like it should since we might get a case when  page is closed right after call.

**Comment by kamilszostak** [comment]
This is correct, `stopTrackPage` doesn't send telemetry right away, but instead adds it to the buffer. The buffer is flushed every 15s or if it reaches a specific size (the interval and the batch size can be changed - see [IConfig](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#config)). The buffer is flushed when `beforeUnload` event triggers and in most cases there should be enough time to send telemetry from the buffer.

Do you have a scenario where this does't work? If you want to send telemetry immediately after `stopTrackPage` you can call `flush` method.

**Comment by dlebedynskyi** [comment]
@kamilszostak  thanks for explanation. Documentation was not that clear on that for me. 
I think i just missed the part for beforeUnload.

**Comment by kamilszostak** [comment]
Thanks! I opened an issue #247 to update the API Reference doc.
