### ISSUE TITLE
[AI][Sender] Sender Should Handle Status Code 0 During Offline Mode

### ISSUE THREAD

**Issue by Karlie-777** [microsoft/ApplicationInsights-JS#2436]

**Comment by MSNev** [comment]
Note: We do need to be careful with any changes around this -- because of Ad-blockers that cause a "0" response.

**Comment by Karlie-777** [comment]
Currently, sender will consider status code 0 as "add blocker turned on", therefore, we will not retry regardless of online status. (keep retrying under status code 0 might not be efficient as well)
