### ISSUE TITLE
How can i access post body for dependencies ?

### ISSUE THREAD

**Issue by lucas-garrido** [microsoft/ApplicationInsights-JS#2453]
Hello 🙌
i'm trying to read the body of the dependency request, my goal is to read the graphql query name to set it as a custom property.

is there a way to achieve this please ? thanks 🙏

**Comment by MSNev** [comment]
Hi @lucas-garrido, as per #2030, you will need to use a dependency listener and then it would depend on whether you are using `fetch` or `XMLHttpRequest` in 2030 I provided details about getting access to the `fetch` input or init (depending on how you are calling `fetch`).

The "type" of the details object that I mention there (is this object)[https://github.com/microsoft/ApplicationInsights-JS/blob/d2c53e483ff3868fa9096647869e93c7458c80d4/extensions/applicationinsights-dependencies-js/src/DependencyListener.ts#L6-L61]

So you can get full access to the XHR object or the fetch `input` / `init` objects. If the "caller" has encrypted or compressed the content, then you will see compressed content in the `details.init.body` field (most likely -- for a POST request), for an XHR request that's a little more problematic as these callbacks get called "after" the caller has called `send()` with the body and XHR doesn't give you a way to get the "body".

I should also note that the `context` (map) object of the `details` is also passed to both the `Initializer` and the `Listeners` -- the actual `details` object is ALWAYS a different object.
