### ISSUE TITLE
Sample for include AI JS SDK script and initialize statically is written in TypeScript (should be JavaScript)

### ISSUE THREAD

**Issue by sondreb** [Microsoft/ApplicationInsights-JS#252]
The sample on how to manually include the AI JS SDK script and initialize it, is written in TypeScript. Since the code includes examples with script tags, I presume the code is suppose to be placed within an HTML file.

https://github.com/Microsoft/ApplicationInsights-JS/blob/master/README.md#include-ai-js-sdk-script-and-initialize-statically

The `: any` on the snippet makes the JavaScript throw exception.

Code runs and work after removing the any type declaration.

**Comment by MaxShehovtsov** [comment]
Thank you for reporting it! I think the intention was to have a javascript snippet not typescript. I'll fix the readme file by removing ': any'

**Comment by MaxShehovtsov** [comment]
#253

**Comment by MaxShehovtsov** [comment]
resolved
