### ISSUE TITLE
appInsights with jquery-pjax

### ISSUE THREAD

**Issue by raphaelm22** [microsoft/ApplicationInsights-JS#262]
What would be the best way to use appInsights with [jquery-pjax](https://github.com/defunkt/jquery-pjax)?

Someone tell if the approach below would have any side effects?

`$(document).on('pjax:complete', function() {
appInsights.trackPageView();
});`

**Comment by kamilszostak** [comment]
I'm not familiar with jquery-pjax. Let me look into this and get back to you.

**Comment by dnduffy** [comment]
@raphaelm22 Your proposal looks correct to me (without actually having tried it).  I think it is logically similar to making jQuery load calls and pjax overlaps that functionality.

**Comment by raphaelm22** [comment]
@dnduffy  But the portal Azure in application insights, the indicators (the grid requests grouped by "Client performance page name") are not changed. I believe appInsights is counting otherwise, not as page view.

thank you

**Comment by dnduffy** [comment]
I haven't forgotten about this, I just haven't had a chance to investigate it yet.
