### ISSUE TITLE
Update the Typescript Definitions

### ISSUE THREAD

**Issue by JPVenson** [Microsoft/ApplicationInsights-JS#267]
Please update the d.ts files. The files are 3 months behind the javascript and are absolutely useless.

**Comment by kamilszostak** [comment]
Which d.ts files are you referring to? The latest definitions are available here https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/applicationinsights-js and they should be up to date.

**Comment by kamilszostak** [comment]
I'm closing this issue. Please re-active if you're still experiencing issues with d.ts files.
