### ISSUE TITLE
npm package doesn't contain any JS files

### ISSUE THREAD

**Issue by jmezach** [Microsoft/ApplicationInsights-JS#270]
I just tried installing the latest ApplicationInsights-JS package from npm, but it seems to be completely empty, except for a LICENSE, package.json and README.md file. There are no JavaScript files. This is with applicationinsights-js@0.23.1.

**Comment by AlexBulankou** [comment]
@jmezach thanks! Working on the fix.

**Comment by AlexBulankou** [comment]
Fixed with #271 and released to npm as 0.23.2. Please ```npm update```

**Comment by jmezach** [comment]
Awesome! Thanks for the quick response. I can confirm its working again now.
