### ISSUE TITLE
Unhandled browser exceptions not being tracked.

### ISSUE THREAD

**Issue by Iscgx** [Microsoft/ApplicationInsights-JS#282]
I've included the applicationinsights-js module and initialized it with my instrumentation key. I also tried tracking page views which do show up in the azure portal.

I've been trying to get unhandled browser exceptions to show up in the portal with no success. I've tried manually throwing the exceptions or faking invalid operations but neither of them are tracked by app insights. Is there something I'm missing or any way to get logging to show if app insights is ignoring my exceptions?

I encountered this issue with [this ](https://github.com/Microsoft/ApplicationInsights-JS#include-ai-js-sdk-script-and-initialize-statically) javascript example and [this ](https://github.com/Microsoft/ApplicationInsights-JS#import-as-a-module-and-initialize-dynamically-download-full-application-insights-script-from-cdn) example with typescript.

**Comment by kamilszostak** [comment]
There are two configuration settings which can help with debugging - see [IConfig](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#config). They are both set to `false` by default. You can enabled them in the snippet in the `config` object. 

```
    enableDebug: boolean;

    verboseLogging: boolean;
```

**Comment by Iscgx** [comment]
I tried enabling 'enableDebug' and 'verboseLogging' and I still don't see any exception data.

Here's a sample of our code:

```
import {AppInsights} from "applicationinsights-js";

AppInsights.downloadAndSetup({
    instrumentationKey: "something",
    enableDebug: true,
    verboseLogging: true
});

AppInsights.trackPageView("Test");

throw 5;
```

With this I can see the 'Test' page view in the azure app insights portal but not the exception. Where am I supposed to see the verbose logging? The only thing the Chrome console shows is the uncaught exception message.

**Comment by kamilszostak** [comment]
I haven't forgotten about this, I just haven't had a chance to investigate it yet.

**Comment by tdekoning** [comment]
I'm experiencing the same issue, any idea when we can see a solution for this?

**Comment by ArturDorochowicz** [comment]
I think I'm experiencing the same issue. 

Isn't the problem the fact that it's not `onerror` that is registered (and 'original' of which is captured) on `window`, but **`_onerror`**?

In `AppInsightsModule.ts` [1]:
```typescript
        // collect global errors
        if (!aiConfig.disableExceptionTracking) {
            AppInsightsModule._createLazyMethod("_onerror");
            var originalOnError = window["_onerror"];
            window["_onerror"] = function (message, url, lineNumber, columnNumber, error) {
                var handled = originalOnError && originalOnError(message, url, lineNumber, columnNumber, error);
                if (handled !== true) {
                    aiObject["_onerror"](message, url, lineNumber, columnNumber, error);
                }

                return handled;
            };
        }
```

AFAIS this is different than `snippet.js` [2]
```javascript
    // collect global errors
    if (!aiConfig.disableExceptionTracking) {
        method = "onerror";
        createLazyMethod("_" + method);
        var originalOnError = localWindow[method];
        localWindow[method] = function(message, url, lineNumber, columnNumber, error) {
            var handled = originalOnError && originalOnError(message, url, lineNumber, columnNumber, error);
            if (handled !== true) {
                appInsights["_" + method](message, url, lineNumber, columnNumber, error);
            }

            return handled;
        };
    }
```

[1] https://github.com/Microsoft/ApplicationInsights-JS/blob/f42f662bcb1669c791552382a395d5e2451b69b7/JavaScript/JavaScriptSDK.Module/AppInsightsModule.ts#L78

[2] https://github.com/Microsoft/ApplicationInsights-JS/blob/f42f662bcb1669c791552382a395d5e2451b69b7/JavaScript/JavaScriptSDK/snippet.js#L61

**Comment by KamilSzostak** [comment]
This is happening when you throw an error in the snippet's `<script>` block. The snippet is trying to loading the full SDK (the `ai.0.js` file), but because of an error the browser doesn't finish the operation and the SDK is never fully initialized. 

You can bypass this limitation by throwing error in a different `<script>` block. 

```
<script type="text/javascript">
    [snippet goes here]
</script>
<script type="text/javascript">
    throw new Error("uppps");
</script>
```
