### ISSUE TITLE
beforeunload event not working in web site using JS SDK

### ISSUE THREAD

**Issue by n1b0** [Microsoft/ApplicationInsights-JS#290]
I have implemented custom events in my web page using JS SDK to track when users are leaving. I have added custom js event for browser beforeunload event to send signal to appinsights. but this event is failing with this error "The request body did not contain the specified number of bytes. Got 0, expected 792". Any clue why this is failing?

**Comment by kamilszostak** [comment]
This is happening when user is navigating away and the browser is terminating the JavaScript execution before we set the body of the POST method.  

Sometimes the script execution is terminated right after we established the connection, but no method or content-length - 
![1](https://cloud.githubusercontent.com/assets/12164228/17784638/1684dbc8-6532-11e6-95bc-702d7be91bad.png)

Sometimes it’s terminated right after we opened a connection and set the header (POST, content-type), but no body - 
![2](https://cloud.githubusercontent.com/assets/12164228/17784622/07427e18-6532-11e6-9476-e0c50411b4fe.png)
 

In both cases, an answer from the backend (including the response code) is coming back to Fiddler long after the page is already closed and browser won’t receive it.  

This is a common problem when you execute code onBrowserUnload, you can never be sure if your script will be fully executed. 
This is why I implemented a session storage buffer, which is partially mitigating this issue. If user is navigating to a new page within the same session the unsent telemetry is saved in the session storage buffer and send on a target page. 
 
If user is navigating away or closing the browser, there is not much we can do. You can try to mitigate this by sending telemetry data more often, e.g. every 5-10 seconds so even if user closes the browser you will only loose last 5s. Hope this helps.
