### ISSUE TITLE
startTrackEvent is not stubbed/queued

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#293]
Moved from: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/252 (reported by @dfederm)

>It looks like in the JavaScriptSnippet, these events are stubbed out with an implementation that basically queues up the invocation until the real appInsights impl is on the page:
["Event","Exception","Metric","PageView","Trace","Ajax"]

>However, this does not encompass all functions on the appInsights object. For example startTrackEvent.

>This can cause lost instrumentation, as well as JS errors when the AI js fails to load (or is blocked by an adblocker in my case).

>Here is an example of the JS error as well as an example of the "trackEvent" function being stubbed out which avoids the JS error (although still loses the instrumentation due to the adblocker):
![image](https://cloud.githubusercontent.com/assets/6445614/17939188/3c807f70-69de-11e6-8a8d-b9e732605369.png)

**Comment by dfederm** [comment]
FYI, I was able to mitigate this by adding this just under the `@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)` call:

```
    <script>
        (function(t){function r(f){if(!t[f])t[f]=function(){var i=arguments;t.queue.push(function(){t[f].apply(t,i)})}};r("startTrackEvent");r("stopTrackEvent")})(appInsights)
    </script>

```
