### ISSUE TITLE
Support CommonJS

### ISSUE THREAD

**Issue by ramijarrar** [Microsoft/ApplicationInsights-JS#301]

**Comment by kamilszostak** [comment]
Could you provide more details so we can better understand you scenario?

**Comment by ramijarrar** [comment]
Where AMD loader is not available, the library should fall-back to CommonJS.

Something like [this](http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/).

**Comment by kamilszostak** [comment]
Thank you, I'll look into this in the next sprint.

**Comment by ramijarrar** [comment]
Any updates here?

**Comment by dbpieter** [comment]
@kamilszostak ? :)

**Comment by kamilszostak** [comment]
I apologize for the delay. I'll do my best to look into this item next week. 

In the mean time. Could you share a sample meteor app which I can use to validate a fix on application insights side? Thank you.

**Comment by kamilszostak** [comment]
I took a closer look at CommonJS support. TypeScript compiler allows to choose a module loading standards: AMD or CommonJS (see `-module` in [tsc options doc](https://www.typescriptlang.org/docs/handbook/compiler-options.html)).

Unfortunately, for CommonJS it doesn't support combining external modules and it's not possible to merge all output *.js files into one file. 

Could you explain your scenario a bit better? If your code is running on a server side, it might be OK if JS SDK files are not combined. If your code is running in the browser, AMD seems like a better choice.

**Comment by dbpieter** [comment]
@kamilszostak 

The main idea is to support es6 modules (import/export). An added advantage is that this library does not pollute to global scope when using a module loader (like webpack or systemjs).

You can wrap the dist code inside an umd wrapper.(https://github.com/umdjs/umd/blob/master/templates/returnExports.js#L41)

Thereby supporting both commonJs, AMD and window.
If you use the provided snippet do not forget to change root.returnExports to root.Microsoft.

**Comment by Fredkr** [comment]
Any updates on this?

**Comment by pviotti** [comment]
This Babel plugin can be useful as a workaround: [babel-plugin-transform-amd-to-commonjs](https://github.com/msrose/babel-plugin-transform-amd-to-commonjs).

**Comment by markwolff** [comment]
v2 sdk uses es6 modules for npm consumption and umd modules for CDN consumption. This should hopefully resolve all compatibility issues for now!
https://www.npmjs.com/package/@microsoft/applicationinsights-web#getting-started

**Comment by markwolff** [comment]
@pviotti Correct, that is the v2 version. There is no changelog yet since it is still in a beta stage, but it is meant to keep the same overall functionality as v1. Most of the differences are at the API layer, e.g arguments were switched to objects instead of positional ones. Since typings are included, intellisense should help with that. If you do run into issues, please do let me know!

**Comment by tommck** [comment]
@markwolff Is there a roadmap for v2?  Expected "gold" date?  Trying to plan a new implementation of AppInsights and don't want to use the old one just to be replaced soon

**Comment by markwolff** [comment]
@tommck Most likely January
