### ISSUE TITLE
Bower package outdated/wrong version

### ISSUE THREAD

**Issue by rudym87** [Microsoft/ApplicationInsights-JS#308]
Currently the Bower package has some versioning issues: it's still at version 1.0.0 (against current 1.0.3).
Furthermore, despite being marked as version 1.0.0, the bundled dist files are from version 0.23.4.

**Comment by kamilszostak** [comment]
Thanks for reporting. I'm investigating.

**Comment by kamilszostak** [comment]
I have just released a new version [v1.0.3](https://github.com/Microsoft/ApplicationInsights-JS/releases/tag/v1.0.3). I also updated NuGet and NPM packages.
