### ISSUE TITLE
Extract unit tests for TelemetryContext from AppInsightsTests to a new test class

### ISSUE THREAD

**Issue by olegsych** [Microsoft/ApplicationInsights-JS#31]
`TelemetryContext.track` method contains a lot of complex logic, however, we don't have unit tests for it. It appears we are testing it through the `AppInsights.track` methods in the `AppInsightsTests` class. Here is an example of such tests:
```JavaScript
this.testCase({
    name: "AppInsightsTests: application context is applied",
    test: () => {
        // setup
        var appInsights = new Microsoft.ApplicationInsights.AppInsights(this.getAppInsightsSnippet());
        appInsights.context._sessionManager._sessionHandler = null;
        appInsights.context.application.ver = "101";
        appInsights.context.application.build = "101";
        var trackStub = sinon.stub(appInsights.context._sender, "send");

        // verify
        var test = (action) => {
            action();
            this.clock.tick(1);
            var envelope = this.getFirstResult(action, trackStub);
            var contextKeys = new AI.ContextTagKeys();
            Assert.equal("101", envelope.tags[contextKeys.applicationVersion], "application.ver");
            Assert.equal("101", envelope.tags[contextKeys.applicationBuild], "application.build");
            trackStub.reset();
        };

        // act
        test(() => appInsights.trackEvent("testEvent"));
        test(() => appInsights.trackPageView());
        test(() => appInsights.trackMetric("testMetric", 0));
        test(() => appInsights.trackException(new Error()));
        test(() => appInsights.trackTrace("testTrace"));

        // teardown
        trackStub.restore();
    }
});
```

Notice how complex a test for `TelemetryContext` has to be here - it needs to use a `sinon.stub` to intercept `send` calls in order to inspect `envelope.tags`. It also has to call multiple `track` methods to ensure all paths to `send` are covered. When we add new methods, such as `trackDependency`, all of tests like this will have to be updated to call the new method ass well.

We can significantly simplify `AppInsightsTests` by introducing `TelemetryContextTests` to verify the `TelemetryContext.track` method separately. With that done, we only need to check that `AppInsights.track` methods call `TelemetryContext.track`, so a lot of these tests could be deleted.

**Comment by kamilszostak** [comment]
`TelemetryContext.tests` were added last year and they seem to cover `track `methods. I also see that the `AppInsightsTests` class was refactored and the code is much clearer now. 

If there are no objections, I'm closing this issue.
