### ISSUE TITLE
config is undefined

### ISSUE THREAD

**Issue by prprasad** [Microsoft/ApplicationInsights-JS#310]
Hi, i have included the js script in site.master file and i am able to see the script at run time. But i am not able to see any page views in azure subscriptions and i am getting config un-defined while debugging using F12.
please help to resolve this issue.
thanks in advance.

**Comment by kamilszostak** [comment]
Could you share this site.master file? What is the exact error message?

**Comment by prprasad** [comment]
Hi,
Thanks for your response. 
i have copied the js script available in https://azure.microsoft.com/en-us/documentation/articles/app-insights-javascript/ and pasted in master  page of our applicaiton. but i didn't see any telemetry . 

![client_side_telemetry_runtime_exception](https://cloud.githubusercontent.com/assets/22021394/18301814/d26ccc28-74f1-11e6-8fd9-499d4d2814f9.png)

**Comment by kamilszostak** [comment]
Sorry for the confusion. For some reason, the snippet in the Azure Portal was not updated. 
Please use the snippet from [readme](https://github.com/Microsoft/ApplicationInsights-JS#use-js-snippet-and-initialize-dynamically-download-full-application-insights-script-from-cdn). 

I'll update the snippet in all places and I'll improve our release process to ensure that the snippet is in sync in all places.

**Comment by prprasad** [comment]
Thanks for your response.
Still i am facing same issue after replacing the new script. 
I found that the page was loading / mapped to 2 different master pages which is having 2 different appinsights scripts which was causing the issue. i mean when i commented the existing appinsights script (which is available in mscom master page) i am able to see page load views in azure subscription whatever i did the changes.

Could you please let me know whether we can place 2 type of appinsights scripts in single web page or not? if not what will be the suggestion to execute 2 appinsights scripts in single page !

Attaching the mscom master page appinsight script FYR.
![master_pagescript](https://cloud.githubusercontent.com/assets/22021394/18346359/5b7522b8-75dd-11e6-89f5-739f9135072c.png)

**Comment by kamilszostak** [comment]
Just to confirm - is the "config is undefined" issue resolved? If yes, I'll close this issue. 

Regarding two AppInsights scripts. We don't support that, there should only be one snippet on each page. I don't see a scenario where this might be useful, but please open a new issue if you think this is something that we should implement.  Please also explain your scenario, so we can better understand the scope of this requirement.  

Thank you

**Comment by prprasad** [comment]
Hi,
thanks for your response. you can close this issue.  Will open new issue if required after discussing with my client.
