### ISSUE TITLE
Async version of flush?

### ISSUE THREAD

**Issue by sorgloomer** [Microsoft/ApplicationInsights-JS#313]
I am in an unfortunate scenario. The timing of the events on my page happens to be very similar to the one AppInsights-JS uses for scheduling the sending of tracked data.
If I do a page redirect afterwards, this often results in the `track` ajax request of appInsights getting canceled (At least that's what chrome dev tools says. A lot of data still appear in the azure portal anyway, I don't know if there are any missing data-points). 

![image](https://cloud.githubusercontent.com/assets/5985835/18445304/36e64e7a-791d-11e6-9eec-b9ee481d8349.png)

I am willing to delay the redirection of my page until the logs are sent, to prevent this "canceled" thing, but as I see there is no api to notify me about when those requests are finished.

Is it a good idea to wait for those logs to be sent in general?

**Comment by kamilszostak** [comment]
Yes, browsers will terminate AJAX calls (and JS execution) if a user is navigating to a new page. To mitigate this limitation the SDK stores a copy of all unsent items in a session storage and restores them on a target page (see [SessionStorageSendBuffer ](https://github.com/Microsoft/ApplicationInsights-JS/blob/dfd9dc162bf95ef7dd7e8d80d595d72b4f5a9878/JavaScript/JavaScriptSDK/SendBuffer.ts#L110). So as long as the user is navigating within your page all events will be collected. I'll add a documentation page to better explain this functionality. 

We are planning to add callbacks/events to notify that the SDK sent telemetry - #289.  Please let me know if that would work for you.

Thanks!

**Comment by sorgloomer** [comment]
Great, thank you for the info! Unfortunately the redirection target is usually outside the origin, and most of the users will never come back to this page, so I am still concerned. The onSuccess callback in #289 looks good, but seems like I will have to track if there are any pending items buffered. Something like a "readyCallback" would be even better for me. I could just call `appInsights.ready(() => { window.location = url; });`, and the framework would immediately call back if the buffer is currently empty.

**Comment by kamilszostak** [comment]
Thanks for updating #289. I'm not sure if I understand the `readyCallback`, when exactly would this event trigger? 

The SDK is calling `Flush` on beforeUnload event - see [addHousekeepingBeforeUnload](https://github.com/Microsoft/ApplicationInsights-JS/blob/dfd9dc162bf95ef7dd7e8d80d595d72b4f5a9878/JavaScript/JavaScriptSDK/Initialization.ts#L115).

**Comment by sorgloomer** [comment]
The callback would trigger exactly once immediately after all the telemetry data collected before registering the callback is sent. If there are no telemetry items or all of them is already sent at the time of subscribing the callback, it should fire asap. (This idea is from another telemetry tool.)

**Comment by kamilszostak** [comment]
OK. I'll implement it as part of #289. 

I'm closing this task, feel free to re-open if you want to add more comments. Thanks!
