### ISSUE TITLE
Pass properties object in `trackDependency`

### ISSUE THREAD

**Issue by ameyagholkar** [Microsoft/ApplicationInsights-JS#322]
Is there a plan to introduce `properties` in the `trackDependency` API ([ref](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/AppInsights.ts#L273)) like `trackException` or other API's?

In my case, I want to track some custom properties with my Ajax call which signifies the source component of the call (for eg.)

**Comment by SergeyKanzhelev** [comment]
It will be available in the next .NET SDK version: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Core/Managed/Shared/DataContracts/DependencyTelemetry.cs#L201 Nothing stops us implementing it for JS. @kamilszostak I'd suggest to pick up the latest public schema for JS SDK. I can give you details tomorrow
