### ISSUE TITLE
How do you Mock AppInsights trackTrace in Jasmine Unit Test

### ISSUE THREAD

**Issue by RaitingsAndCommenting-VSC** [Microsoft/ApplicationInsights-JS#323]
I have a question, how do you mock the AppInsights object in jasmine? I have attempted to mock the AppInsights object but when I debugged the test case I noticed the a real instance of the AppInsights object calls the lazy load trackTrace method. In my unit test code I would like to be able to mock the AppInsights.trackTrace code and have it return the values it was passed. Is there a recommended of doing this?

Unit Test Code:

``` js
  it('Call logInfo()', function () {
   util.logInfo('Unit Test Message.');
  });
```

Code to be Tested:

``` js
import { AppInsights } from 'applicationinsights-js';

export function logInfo(message) {
if (supportLogInfo) {
    window.console.info(message);
    AppInsights.trackTrace(message, { level: 'info', source: 'ui' });
}
}
```

The Below highlighted real AppInsights code gets called:

``` js
function AppInsightsModule() {
        }
        AppInsightsModule._createLazyMethod = function (name) {
            var aiObject = window[AppInsightsModule.appInsightsName];
            // Define a temporary method that queues-up a the real method call
            aiObject[name] = function () {
                // Capture the original arguments passed to the method
                var originalArguments = arguments;
                // If the queue is available, it means that the function wasn't yet replaced with actual function value
                if (aiObject.queue) {
                    aiObject.queue.push(function () { return aiObject[name].apply(aiObject, originalArguments); });
                }
                else {
                    // otherwise execute the function
                    aiObject[name].apply(aiObject, originalArguments);
                }
            };
        };
        ;
```

Thanks,
-jc

**Comment by kamilszostak** [comment]
The SDK contains two parts: a module definition (or a snippet if you're loading the SDK on a web page) and a library, which is downloaded dynamically. 
When you create a module it creates placeholders for all track* methods, which are later replaced with actual implementations. So if you're using the real AppInsights module in your unit tests it will behave exactly the same way.

IMHO the best solution is to create a stub for each track* methods (after all you're not testing the JS SDK, just the interaction with the SDK), and validate if a track method is called with correct parameters.
