### ISSUE TITLE
accountId in setAuthenticatedUserContext deprecated?

### ISSUE THREAD

**Issue by mpseidel** [Microsoft/ApplicationInsights-JS#326]
I did not change the way I call setAuthenticatedUserContext  but since a few days I can't seem to group by accuntId anymore in the portal. I see `context.user.accountId.hash is deprecated`. Am I missing something?

**Comment by SergeyKanzhelev** [comment]
@AlexBulankou do you know anything about it? Was the dimension removed?

@mpseidel - you can always run the query in Application Analytics and group by account there.

**Comment by mpseidel** [comment]
The dimension was one of the key things we used in our Azure dashboard AI charts. Would love to get it back 🙂

**Comment by kamilszostak** [comment]
Yes, the `context.user.accountId.hash` is deprecated and was removed from the UI. 

Could you share your query? It should be possible to achieve similar results by grouping by `accountId` in Application Analytics.

**Comment by kamilszostak** [comment]
Closing. Feel free to re-open if you want to discuss further.
