### ISSUE TITLE
Update azure docs

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#33]
@AlexBulankou, with this [commit](https://github.com/Microsoft/ApplicationInsights-JS/commit/de6a1b3e3b2d3ed51da48ae11919aaa9a4030f22) we may need to update [azure docs](https://azure.microsoft.com/en-us/documentation/articles/app-insights-javascript/) to reflect how we changed the math.

**Comment by MaxShehovtsov** [comment]
I think the doc is consistent with implementation now.
