### ISSUE TITLE
Why is disableCorrelationHeaders setting true by default?

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-JS#331]
Shouldn't it be enabled by default?
Another question is why do we need a check to only limit setting them for the same hostname only. In case my server-side application (instrumented with the same ikey) happens to be hosted on a sever with different name, I still will benefit from the feature. And if they are different applications, still no harm done, I just won't see correlated telemetry.

**Comment by kamilszostak** [comment]
I synced with @SergeyKanzhelev and changed the code to match the latest design. Pull request: #333.

**Comment by kamilszostak** [comment]
To add headers to CORS requests we need to ensure that our customer headers are in '[Access-Control-Allow-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Headers)'. I'll investigate what's the right thing to do here...

**Comment by SergeyKanzhelev** [comment]
Is it browser specific or the application configuration specific? In other words - will we have the same issue if we make a call from the C# code?

**Comment by kamilszostak** [comment]
C# should be OK, it is not sending OPTIONS calls. 

I'll disable correlation headers to unblock the release. #364.

**Comment by AlexBulankou** [comment]
@kamilszostak can you please clarify the problem with this setting being default
