### ISSUE TITLE
session.isFirst is not populated for the new sessions

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#332]
`session.isFirst` needed for new vs. returning users chart. I cannot find where it is set

**Comment by SergeyKanzhelev** [comment]
It seems that the chart was removed from UI. @AlexBulankou was it intentional?

**Comment by AlexBulankou** [comment]
It is populated for new sessions, I just verified.
![image](https://cloud.githubusercontent.com/assets/11968377/19747557/40a26e26-9b91-11e6-826d-4304444ca969.png)

**Comment by SergeyKanzhelev** [comment]
I couldn't find the code for it: https://github.com/Microsoft/ApplicationInsights-JS/search?utf8=%E2%9C%93&q=isFirst

**Comment by kamilszostak** [comment]
`isFirst` is set to `true` in [Session.ts](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/Context/Session.ts#L122) and later on changed to `undefined`.

**Comment by kamilszostak** [comment]
Closing.
