### ISSUE TITLE
Chrome latest is blocking inline addition of cross-origin script tags that block rendering

### ISSUE THREAD

**Issue by DamianEdwards** [microsoft/ApplicationInsights-JS#334]
Go to https://live.asp.net/ in Chrome with the dev toolbar open and look at the warnings/errors in the console (see image below).

Chrome is now blocking loading of scripts that are injected into the document in a render blocking fashion (including `document.write` and seemingly `document.createElement` if the `async` property isn't set to `true`).

This is preventing Application Insights scripts from loading.

![image](https://cloud.githubusercontent.com/assets/249088/19747627/b78f29c0-9b91-11e6-8fbd-90d196fa7d03.png)

**Comment by DamianEdwards** [comment]
Turns out part of this was actually caused by an extension I have, uBlock Origin.

However, even with it disabled some warnings persist, so you likely want to change how you load scripts to ensure it's always loaded (and without warning) in Chrome from now on.

**Comment by shkrishms** [comment]
Hi, is this getting fixed. I am blocked by the same issue.

**Comment by keremdemirer** [comment]
+1

**Comment by KamilSzostak** [comment]
I'll look into this ASAP.

**Comment by markwolff** [comment]
Is anyone still experiencing this issue? Even after enabling the `Block scripts loaded via document.write` chrome flag, I am able to send telemetry and do not see any warnings.

**Comment by markwolff** [comment]
Going to close this for now since it seems only `document.write` is still affected by this and not `document.createElement`
