### ISSUE TITLE
option to disable cookies completely

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/ApplicationInsights-JS#335]
In order to use AI with a customer, we need to remove all cookies. There is already `Util.canUseCookies()`, could this function take an global option to disable it? Same for localstorage.

**Comment by kamilszostak** [comment]
JS SDK is using cookies to store session and user ids. If you decide to disable them you won't be able to benefit from metrics associated with those two values. 

I'll expose a configuration to disable cookies in next release.

**Comment by pelikhan** [comment]
Privacy requirements from the customer. Other APIs like MixPanel offer complete control over how much data is stored on the client.
