### ISSUE TITLE
Add status code information in case of network errors

### ISSUE THREAD

**Issue by regexrowboat** [microsoft/ApplicationInsights-JS#338]
Currently, JavaScript SDK logs status code 0 when the connection between the client and server cannot be resolved. This makes diagnosing network errors very difficult, as there are many different problems that can cause 0 status code in failing dependency calls. 

The proposal is to log status code information that indicates whether a network error occurred and what type.

**Comment by MSNev** [comment]
The actual status code is (or should) already be logged, I'm not sure about the status text.

Generally, though the status code of "zero" means that this is the value returned to JavaScript in these scenario's, I've linked this with a new request about tracking whether the client code explicitly cancelled (called `abort()` on the XHR for example) to help provide additional information when available. When that item gets worked on this request will be reviewed as well.
