### ISSUE TITLE
Send telemetry on `visibilitychange` instead of `unload`

### ISSUE THREAD

**Issue by KamilSzostak** [microsoft/ApplicationInsights-JS#342]
According to W3C:

> `visibilitychange` event is the only event that is guaranteed to fire on mobile devices when the page transitions to background state (e.g. when user switches to a different application, goes to homescreen, etc), or is being unloaded. Developers should avoid relying on unload event because it will not fire whenever a page in background state (i.e. visiblityState equal to hidden) and the process is terminated by the mobile OS.

**Comment by MSNev** [comment]
This is not support on all browsers and for Opera and Opera Mobile specifically doesn't fire the visibilitychange event when the browser window is minimized, nor when hidden is set to true.

We could consider adding this as an additional event (based on config) that could cause the equivalent of the unload event, based on the spec though this does not necessarily mean that the site/app is being unloaded -- just that it's being hidden or displayed for some reason. A better option might be to have a new specific event...

**Comment by kyliau** [comment]
Using `unload` makes the page ineligible for back/forward cache [(bfcache)](https://web.dev/bfcache/#never-use-the-unload-event), it's best to use `pagehide` event as of April 2022.
`pagehide` is [supported](https://caniuse.com/mdn-api_window_pagehide_event) by all major browsers.

**Comment by MSNev** [comment]
In [version 2.7.1](https://github.com/microsoft/ApplicationInsights-JS/blob/master/RELEASES.md#271-nov-4th-2021) we added optional support for users to disable the default set of events. with #1683.

Documentation for these config settings are available on the interface definition.
https://github.com/microsoft/ApplicationInsights-JS/blame/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts#L150-L163

And while 'pagehide' might be available on all major browsers we currently support all browsers (ES3+) including IE 8+ so we have to keep the current set of events.

**Comment by MSNev** [comment]
Closing as I believe that this was addressed in v2.6.4 and v2.7.1
