### ISSUE TITLE
Cross Origin Operation Tracking

### ISSUE THREAD

**Issue by drub0y** [Microsoft/ApplicationInsights-JS#344]
We have a setup where our client, a SPA, is served from one domain and the ASP.NET WebAPI it calls is on a completely different domain. We noticed that operations between the SPA and WebAPI were not being correlated on a common operation id. A little spelunking into the AI JS revealed this:

```JavaScript
this.appInsights.config.disableCorrelationHeaders||t.UrlHelper.parseUrl(n.ajaxData.getAbsoluteUrl()).host!=this.currentWindowHost||n.setRequestHeader("x-ms-request-id",n.ajaxData.id)
```

So `disableCorrelationHeaders` is the default of `false`, but the next check is to make sure the target URL's host matches the `currentWindowHost` (which is initialized to `window.location.host`). Obviously this will not be `true` in the case of a cross origin call, thus the header would never be set.

This seems like an artificial limitation. If the header were just applied to the request, it would be validated during a CORS pre-flight `OPTIONS` request via the `Access-Control-Request-Headers` and the server could decide whether or not it wants to allow it.

Is there any reason why this host check exists? As it stands right now I have to live with no client<->server operation correlation which is a darn shame considering how awesome everything else is.

**Comment by kamilszostak** [comment]
We already have a fix for this: #333. It will be included in a next release (ETA beginning of next week).

**Comment by drub0y** [comment]
Excellent, looking fwd to seeing those requests sync up now.

**Comment by KamilSzostak** [comment]
The fix wasn't as easy as we thought it would be. We are tracking this issue in #419.
