### ISSUE TITLE
NONUSRACT_SessionRenewalDateIsZero exception and friends

### ISSUE THREAD

**Issue by vegar** [microsoft/ApplicationInsights-JS#347]
At what seems to be random times, we get a lot of the following errors in the browser console:

```
XHR finished loading: GET "https://localhost:44555/api/...".

Uncaught n
   message: "NONUSRACT_FailedMonitorAjaxRSC 
                message:"Failed to monitor XMLHttpRequest 'readystatechange' event handler, monitoring data for this ajax call may be incorrect." 
                props:"{
                   ajaxDiagnosticsMessage:(url: '/api/...'),
                   exception:[object Object]{\message\:\NONUSRACT_SessionRenewalDateIsZero message:\\\AI session renewal date is 0, session will be reset.\\\\,\messageId\:26}
                }""
   messageId: 16

Uncaught n
  message: "NONUSRACT_ExceptionWhileLoggingError 
                message:"_onerror threw exception while logging error, error will not be collected: " 
                props:"{
                       exception:[object Object]{\message\:\NONUSRACT_SessionRenewalDateIsZero message:\\\AI session renewal date is 0, session will be reset.\\\\,\messageId\:26},errorString:null
                }""
   messageId: 11

```

It seems like the error goes away if we delete the `ai_session` cookie.
It also looks like only one of the `ai_session` / `ai_user` cookies exist at some times.
In the case where only the `ai_user` cookie exist, the problem goes away if I delete it. Both the cookies will then be recreated at next request.

We initialize the appInsight instance with the script snippet, and have debug turned on.

**What is this error?**  
**What should we do to get rid of it?**

**Comment by kamilszostak** [comment]
Thanks for reporting. I'm investigating.

**Comment by MSNev** [comment]
This Issue will be closed in 30 days. Please remove the "Stale" label or comment to avoid closure with no action.
