### ISSUE TITLE
AJAX dependency is created with incorrect properties

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-JS#356]
Create a page that issues AJAX call. Here's [JSFiddle](https://jsfiddle.net/bulankou/v70t0wja/) that does it.
The call is this:

```
 var ajaxUrl = "https://stocksrv.azurewebsites.net/api/stock/AAPL?param1=test&param2=test";
    $.ajax(
                    {
                        url: ajaxUrl,
                        success: function (data) {
                          console.log(JSON.stringify(data));
                          },
                        error: function () {
                            console.log("AJAX call error");
                        }
                    });

```

The dependency properties that gets created is incorrect. The table compares expected vsactual
<table>
<tr>
 <th>Property</th>
 <th>Expected</th>
 <th>Actual</th>
</tr>
<tr>
 <td>target</td>
 <td>stocksrv.azurewebsites.net</td>
 <td>GET https://stocksrv.azurewebsites.net/api/stock/AAPL?param1=test&amp;param2=test</td>
</tr>
<tr>
 <td>name</td>
 <td>GET https://stocksrv.azurewebsites.net/api/stock/AAPL</td>
 <td>GET https://stocksrv.azurewebsites.net/api/stock/AAPL?param1=test&amp;param2=test</td>
</tr>
<tr>
 <td>data</td>
 <td>GET https://stocksrv.azurewebsites.net/api/stock/AAPL?param1=test&amp;param2=test</td>
 <td>/api/stock/AAPL</td>
</tr>
</table>

**Comment by AlexBulankou** [comment]
@Dmitry-Matveev, @kamilszostak  this is the issue we discussed with Dmitry earlier today. This is causing base name (target) explosion for client-side dependencies. @SergeyKanzhelev, do you know if these are Breeze changes to not apply url parsing for Web SDK, if already done, that caused this?

**Comment by SergeyKanzhelev** [comment]
Ideally JS should start parsing url and send target. Same as we do in .NET SDK. It may also be fixed in Breeze if needed.

**Comment by zakimaksyutov** [comment]
Looks like we need to chat with Usage team to make sure this change will not break them.

**Comment by OsvaldoRosado** [comment]
Is this related to https://github.com/Microsoft/ApplicationInsights-node.js/issues/295 ?

**Comment by jpiyali** [comment]
This issue is fixed, has been for a while (based on expected vs. actual result above). Closing.
