### ISSUE TITLE
Emit an automatic event when the browser is hitting an unknown tag or style (suggestion)

### ISSUE THREAD

**Issue by FrictionFree-zz** [microsoft/ApplicationInsights-JS#358]
One of the biggest pains with creating HTML5 applications is that the standard is not completely finalized and hence some of the tags and styles are not always supported on all browsers. Can the AI SDK emit an automatic event when the browser is hitting an unknown tag or style? It would be interesting for a developer to know how many users are getting a sub-optimal experience due to this common problem.

**Comment by MSNev** [comment]
I've removed the enhancement tag and I'm going to mark as stale as I think this would probably be better as a (v2) "add-on" which would either be injected with an appInsights instance or would look for the global.

Either way, based on the age and backlog items I don't believe that we will get to this at any time soon (if ever -- TBH)
