### ISSUE TITLE
PageView should have own ID for proper correlation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#361]
See https://github.com/Microsoft/ApplicationInsights-dotnet/issues/47#issuecomment-264928747

We should allow to tie together PageView and Dependencies. So PageView should have own `ID` field.

**Comment by TheXenocide** [comment]
It seems like maybe `PageViewTelemetry` should derive from `OperationTelemetry`, just the same as the other types that have their own ID? `DependencyTelemetry` and `RequestTelemetry` are contextual operations that similarly contain traces, exceptions, etc. and `PageViewTelemetry.Id` would be assigned to root operation ID of associated dependencies via `depTelem.Context.Operation.Id` which is exactly how operations are nested under other `OperationTelemetry` as roots (e.g. `RequestTelemetry`)

**Comment by Expecho** [comment]
Any update on this one? I am trying to instument a desktop application using AI but while I can get the requests and dependency working I cannot track a PageView using `StartOperation` and have the requests and dependencies as a suboperation of PageView.

**Comment by jpiyali** [comment]
This is actually available already today. For each new page in browser, unique id is set for page, that is also propagated as part of dependency data for outgoing requests in dependency id (id = | + pageview.id + util.newid())
