### ISSUE TITLE
Script error: Browser exception message not providing information type and method

### ISSUE THREAD

**Issue by beckylino** [microsoft/ApplicationInsights-JS#363]

**Comment by SergeyKanzhelev** [comment]
Do you have pictures/examples of what and when should be collected?

**Comment by kamilszostak** [comment]
Most common undefined JS errors: 
* Exception type: "Script error.", Failed method: "unknown" (Safari, Chrome, Firefox)
* Exception type: "Script error", Failed method: "window.onerror" (IE11, IE10, Edge)
* Exception type: "Script error.", Failed method: "window.onerror" (Safari, Edge, Chrome)
* Exception type: "Expected ';'", Failed method: "window.onerror" (IE 11)
* Exception type: "[object Event]", Failed method: "Unknown" (Android, Chrome)

**Comment by kamilszostak** [comment]
Script error with an "unknown" error message is reported by CORS scripts, this can be mitigated by adding `crossorigin="anonymous"` to the script tag.

**Comment by KamilSzostak** [comment]
`[object Event]` is logged when an Event is thrown and the SDK cannot serialize it. 

See our Wiki page for more info: [I'm seeing a lot of Uncaught [object Object] errors in Application Insights in Azure Portal](https://github.com/Microsoft/ApplicationInsights-JS/wiki/FAQ#im-seeing-a-lot-of-uncaught-object-object-errors-in-application-insights-in-azure-portal)

**Comment by spelltwister** [comment]
Is there a way to override this behavior?  Maybe specify an unknownErrorFormatter = function(error) { return formattedErrorToLog; } or something?  Or is there another work around that is available?  Currently, every single error logged is useless for us as it just says [object *Something*] and has no details what-so-ever about the error.

**Comment by MSNev** [comment]
The label "waiting for backend fix" as added to the wrong issue -- doh!
