### ISSUE TITLE
"Field 'name' on type 'RemoteDependencyData' is too long" with long URL

### ISSUE THREAD

**Issue by yentheo** [Microsoft/ApplicationInsights-JS#369]
I'm building a web app which uses SignalR and I'm using AppInsights to track errors in my application.
My SignalR-hubs are authorized, as they should be, but I'm using the Query-string to pass my authentication token. Because WebSockets currently don't support custom request headers. 

The SignalR connection gets tracked by AppInsights and appearently AppInsights uses the URL as name on the RemoteDependencyData object. Because of the token the URL is way to long for this name property and I get this error in my response of the track-request:

`100: Field 'name' on type 'RemoteDependencyData' is too long. Expected: 1024 characters, Actual: 1236`
![image](https://cloud.githubusercontent.com/assets/3296535/21457315/9e60dd20-c92e-11e6-97c8-311a1aa7e8a3.png)

This isn't a problem for my application, but it's not so clean.

**Comment by SergeyKanzhelev** [comment]
@kartang can you please comment on this as you are changing the schemas for the dependency tracking

**Comment by kartang** [comment]
@yentheo Sorry for that. We might run into these issues, as the complete method + url (including the query parameters) is assigned as name. We are having a fix for the issue, and in the updated schema, name will be the  base url without any query parameters. We will update you as soon as the fix is out which could be later this week.

**Comment by yentheo** [comment]
@kartang That would be great, thanks!

**Comment by kartang** [comment]
@yentheo The fix is in PROD, and we truncate the data to 1024 characters if too long. Please let us know if you continue to see this issue. Closing this for now.
