### ISSUE TITLE
Can't Install Using Vanilla Cordova (not Visual Studio)

### ISSUE THREAD

**Issue by teckel12** [Microsoft/ApplicationInsights-JS#370]
Trying to use Azure Application Insights with vanilla Cordova (not using Visual Studio at all as I can't install VS due to Windows installer lock-ups).  "Getting started" in Azure doesn't provide the code to use.  The README in the repository here doesn't include vanilla Cordova instructions either.

I'd really like to use Azure Application Insights, but I'm hitting a brick wall for the last week of attempts.  I'm not looking into Google Analytics as I'm not getting anywhere with Azure Application Insights.

Is it possible to provide simple and clear documentation on how to use Azure Application Insights with vanilla Cordova?  I understand if Microsoft isn't interested in supporting that platform and one must use Visual Studio instead.  But then just tell us that it's not supported and use Google Analytics instead.  Of course, not being able to install Visual Studio modules even after a complete system wipe is another common problem for people but a separate problem.

**Comment by SergeyKanzhelev** [comment]
@JoshuaWeber, @ashtom, do you have a good pointers to the Cordova getting started docs?

**Comment by dnduffy** [comment]
@teckel12 I haven't tried making a Cordova app for a few years but I suggest trying the [JavaScript SDK](https://github.com/Microsoft/ApplicationInsights-js) first and see if that will work for you (you obviously need to take a local copy of the script but even then it may make assumptions about the existence of a browser that won't work in a JS app, I don't recall).  If that doesn't work then maybe the [node](https://github.com/Microsoft/ApplicationInsights-node.js) version will, otherwise you could fork the JavaScript SDK and make a Cordova version from it.

**Comment by teckel12** [comment]
What application type for Application Insights would I select?  Am I to assume it's "General"?  This is exactly the kind of problems I'm having.  Nothing really says what to select and what to do, it's all kind of like "you know, just do it and it should work" with grand assumptions of knowledge.  Therefore, one can't get past the "Get an instrumentation key" on the Node.js instructions without starting to guess what to do.

While Cordova is built on Node.js, one doesn't use Node.js to develop the app.  We just create a 100% HTML/JavaScript/CSS app and Cordova does the building.  So, under "Usage" in the Node.js instructions, where it says to do the following:

```
import appInsights = require("applicationinsights");
appInsights.setup("<instrumentation_key>").start();
```

Where in what file would one include that?  Is it possible that Cordova just uses Node.js for npm and dependencies?  That's what it seems like.

Totally lost...

**Comment by AlexBulankou** [comment]
@teckel12 for Cordova the recommendation is to [Include JS SDK and initialize it statically](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/README.md#include-ai-js-sdk-script-and-initialize-statically). 
Please also check [this blog post](http://www.teamfoundation.co.za/2016/02/application-insights-and-typescript/) on using JS SDK with Cordova.
Also here's [another example](https://github.com/stopbystop/sbs-app/blob/master/src/cordova/scripts/index.ts#L58) of an using AI JS SDK with Cordova.

**Comment by AlexBulankou** [comment]
Please reopen if you have further questions.
