### ISSUE TITLE
How can I access appInsights.context from code

### ISSUE THREAD

**Issue by TimoWillemsen** [Microsoft/ApplicationInsights-JS#371]
I want to display the UserId on the website, so users can communicate it to us whenever they encounter a problem. However, in code, appInsights.context is undefined. How can I access this?

        window.appInsights = appInsights;
        appInsights.trackPageView();
        console.log(appInsights.context);

is logged as undefined. However, I can access it in the developer console when I run the application. It seems like the context is being removed/not added yet.

**Comment by kamilszostak** [comment]
Context is initialized when a full library (ai.0.js file) is downloaded. Snippet only creates stubs of all `track` methods and collects exceptions. Once the `ai.0.js` file is available the full version of JavaScript SDK library is initialized (including the context object). 

Could you explain your scenario a bit better? Can you call [trackEvent()](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#trackevent) to log a message from a user? UserId will be automatically added to the event data.

**Comment by AlexBulankou** [comment]
@TimoWillemsen you can push the code that tries to access `context` into the queue as it is not available until full script has loaded as @kamilszostak pointed out.
```JS
...
    window.appInsights = appInsights;
    appInsights.queue.push(function () {
    // context is available here
   console.log(appInsights.context);
   });
```

**Comment by AlexBulankou** [comment]
Please reopen if you have further questions.
