### ISSUE TITLE
trackDependency is not in typings

### ISSUE THREAD

**Issue by SvenTobback** [Microsoft/ApplicationInsights-JS#374]
Hi,

The trackDependency method is not present in the typings file of DefinitelyTyped. 

The trackAjax call is defined but I assume it is deprectated? The "method" property isn't filled in when you use trackAjax so it is not exactly the same.

Code:

            AppInsights.prototype.trackAjax = function (id, absoluteUrl, pathName, totalTime, success, resultCode, method) {
                this.trackDependency(id, null, absoluteUrl, pathName, totalTime, success, resultCode);
            };

Kind Regards,

**Comment by kamilszostak** [comment]
I sent a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14302) to DefinitelyTyped repo with a fix.
