### ISSUE TITLE
trackDependency output different since 1.0.6

### ISSUE THREAD

**Issue by nick-adriaenssens** [microsoft/ApplicationInsights-JS#386]
Since version **1.0.6** the localhost path is shown instead of the pathName that was passed to the trackDependency call.

![image](https://cloud.githubusercontent.com/assets/5507224/22247418/02f8668a-e23a-11e6-9187-c645070f09b8.png)

**Comment by SergeyKanzhelev** [comment]
@kartang - can you please take a look?
@NickAdriaenssens - would you pls share how you call `trackDependency` and what you'd expect to see?

**Comment by kartang** [comment]
@NickAdriaenssens Sorry about the confusion.
We started showing **target** which is the "**hostname + port**" as a part of the primary display in search (which is what we observe on the search results). The path name that is sent as a parameter, is actually the "**Command**", which can be seen on the specific details blade as below:

![image](https://cloud.githubusercontent.com/assets/12818796/22260996/25d393b0-e220-11e6-8e84-6a07f7e06c9f.png)

Please let us know if you don't see the path name (that is passed to trackDependency) under **"Command"** section of the details blade **_or_** if this is not what you expect.

Sorry about the confusion.

Thanks,
Karthik

**Comment by NickAdriaenssens** [comment]
@kartang thank you for clearing up the confusion. 

I can see the full path in the command section but this is not what we expect to see in the primary display. The API url (eg.: "POST /api/requestSomething") gives us a lot more information than just the hostname and the port. 

Is it possible to configure the value shown in the header? I will stay on 1.0.5 until I found a solution.
