### ISSUE TITLE
trackDependency assumes "Ajax"

### ISSUE THREAD

**Issue by jonlt** [Microsoft/ApplicationInsights-JS#390]
The dependency tracking is centered around tracking Ajax requests. I'm doing COM in an embedded browser control, and would like to be able to track the calls from javascript.

When using the `trackDependency`, the `type` is set to "Ajax", and the `target` and `name` parameters are set based on the URI passed to the method.

Am I doing it wrong, or are there no ways to set these values when using the `trackDependency` method?

**Comment by SergeyKanzhelev** [comment]
@kartang to answer

**Comment by kartang** [comment]
@jonlt 

Hello, javascript defaults the field **type** to **Ajax**, by default with auto-collection. We also assign the **name** and **target** based on the **url**. If any of the properties associated with the telemetry needs to be over-written, the ideal way is to add telemetry initializers. Please find more details on how to use telemetry initializers [here](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#addtelemetryinitializer) and let us know if this works as a solution to your scenarios. 

Thanks

**Comment by jonlt** [comment]
Thank you for your answer! Telemetry initializers does do the job. But since you ask me if it works as a solution, I'm going explain what I did in stead:

Using telemetry initializers meant that I would put values unrelated to HTTP-requests, into these arguments, along with a marker to tell the initializer to intercept, and fix it. It felt like going backwards 1 step, and then forward 2 steps.

In stead, I used this monster:

```
var dependencyData = toSerializable({
    baseType: "RemoteDependencyData",
    baseData: toSerializable({
        id: Microsoft.ApplicationInsights.Util.newId(),
        ver: 1,
        name: name,
        resultCode: resultCode,
        duration: duration,
        success: success,
        data: data,
        target: target,
        type: type,
    })
});

```

...wrapped inside a function with related arguments, that puts the data in an envelope and sends it using `track()`.

To me, its easier to reason about, than having to know that when pass X to the `pathName` argument of the `trackDependency` function, what i really mean is `data`.

I hope that I am doing something wrong though, as I'm sure the above wont be working a couple of versions down the line.

**Comment by kartang** [comment]
@jonlt Glad that track(envelope) worked. We have added a backlog task to improve the custom tracking scenarios. Closing this for now.

**Comment by jonlt** [comment]
for completeness I'll leave the whole "moster" here:
```

function trackDependency(type, target, name, data, duration, resultCode, success){

        function toSerializable(obj) {
            var contract = {}
            for (var i in obj) {
                contract[i] = Microsoft.ApplicationInsights.FieldType.Required;
            }
            obj.aiDataContract = contract;
            return obj;
        }

        var dependencyData = toSerializable({
            baseType: "RemoteDependencyData",
            baseData: toSerializable({
                id: Microsoft.ApplicationInsights.Util.newId(),
                ver: 1,
                name: type + " : " + target,
                resultCode: "",
                duration: duration,
                success: success,
                data: data,
                target: target,
                type: type,
            })
        });

        var envelope = new Microsoft.ApplicationInsights.Telemetry.Common.Envelope(dependencyData, "Microsoft.ApplicationInsights.{0}.RemoteDependency");
        appInsights.context.track(envelope);
}

```
