### ISSUE TITLE
Why was disableCorrelationHeaders default changed to false?

### ISSUE THREAD

**Issue by michaelkacher** [Microsoft/ApplicationInsights-JS#395]
Issue #331 inquired why disableCorrelationHeaders was true by default.  In response, in pull request #333 @kamilszostak changed it to false but I cannot find information on why it had to be changed.  nicosabena noted in #333 this is a breaking change if you are calling an external api that rejects extra headers.  This has occurred to an application I am working on but I do not understand the impact if I switch it back to true.

Other notes:
The disableCorrelationHeaders flag determines if  'x-ms-request-root-id' and 'x-ms-request-id' headers are added. The documentation (https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#config) does not have the disableCorrelationHeaders flag listed and searching for the headers does not bring back any results.

Any help on the impact of switching disableCorrelationHeaders explicitly to true is appreciated.

**Comment by SergeyKanzhelev** [comment]
It caused problems with some signed calls like Azure Storage REST API. @kamilszostak had plan to enable it back at some point. @kamilszostak?

**Comment by kamilszostak** [comment]
Yes, we had to disable correlation headers after we discovered a bug. We implemented a fix and will re-enable correlation headers (for all requests within the same domain) in the next release. 

You can manually enable the feature by setting `disableCorrelationHeaders = false`. Please let me know if you experience any issues. 

I updated the documentation and added a missing config filed - #396.

**Comment by taspeotis** [comment]
> We implemented a fix and will re-enable correlation headers ... in the next release.

https://azure.microsoft.com/en-au/blog/azure-application-insights-javascript-sdk-reliability-and-performance-improvements/

This article says "dependency correlation headers ... are now turned off by default." This is listed under "New JavaScript SDK features." It sounds like the blog post could be clearer that this isn't a new feature, rather a temporary situation. We could just ignore this guidance (to enable manually) and it will be fixed at a later date?

**Comment by cwoodland** [comment]
Has this fix been released?

I don't see x-ms-request-id anywhere in the code when I search in version 1.0.8?

Thanks
