### ISSUE TITLE
CustomDimensions field issue

### ISSUE THREAD

**Issue by saxenark** [Microsoft/ApplicationInsights-JS#397]
https://lxprdmsit.kusto.windows.net:443/d18d813be80b42fb90961be30643642f [Run in Kusto.Explorer] [Run in Kusto.Explorer on SAW] [Run in Kusto.WebExplorer] 
event 
| where app_Name == 'myorderproduction'
| where timestamp > ago(90d)
| where event_Name contains 'Submit Requisition' and isempty(tostring(customDimensions.POSubmittedDateTime))
| limit 10

event 
| where app_Name == 'myorderproduction'
| where timestamp > ago(90d)
| where event_Name contains 'Submit Requisition' and isnotempty(tostring(customDimensions.POSubmittedDateTime))
| limit 10

I am observing that, there are certain records that are being logged with customDimensions.POSubmittedDateTime as empty while others have some value. I am trying to figure out in our code reason for this difference, but so far, it appears that we should not be getting this behavior (logging from javascript) as there is one place from logging is happing. While, I continue to dig deeper, just wanted to check if there are any hints/pointers to this observation.

**Comment by kamilszostak** [comment]
JavaScript SDK doesn't set `POSubmittedDateTime` field. Is this something that your app is logging? Do you expect this field for all telemetry types (pageView, dependency, exception, etc.)?

**Comment by saxenark** [comment]
Yes, this is what we are logging as part of a customEvent.

**Comment by KamilSzostak** [comment]
Try using [Fiddler](http://www.telerik.com/fiddler) and look for all `/v2/track` requests. Check if all of them have a custom dimension populated. 
You can also use an [un-minified version of the JS SDK](https://az416426.vo.msecnd.net/scripts/a/ai.js) and set a breakpoint in trackEvent method to see if all events have that field.

**Comment by KamilSzostak** [comment]
Closing, please reopen if you're still seeing this issue.
