### ISSUE TITLE
How to Configure Application Insights  for WinJS applications (UWP Win 10 - Javascript) ??

### ISSUE THREAD

**Issue by ashwin4av** [Microsoft/ApplicationInsights-JS#399]
Can anyone please help me to configure application insights for WinJS application.. I have used code bits which are available in azure portal to monitor at the client side. But couldn't get data in portal. 

1.	<script type="text/javascript">
  var appInsights=window.appInsights||function(config){
    function i(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s="AuthenticatedUserContext",h="start",c="stop",
l="Track",a=l+"Event",v=l+"Page",y=u.createElement(o),r,f;y.src=config.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js";
u.getElementsByTagName(o)[0].parentNode.appendChild(y);try{t.cookie=u.cookie}catch(p){}for(t.queue=[],t.version="1.0",
r=["Event","Exception","Metric","PageView","Trace","Dependency"];r.length;)i("track"+r.pop());return i("set"+s),i("clear"+s),i(h+a),i(c+a),i(h+v),i(c+v),i("flush"),config.disableExceptionTracking||(r="onerror",i("_"+r),f=e[r],e[r]=function(config,i,u,e,o){var s=f&&f(config,i,u,e,o);return s!==!0&&t["_"+r](config,i,u,e,o),s}),t
    }({
        instrumentationKey:"xxxxxxx"
    });
       
    window.appInsights=appInsights;
    appInsights.trackPageView();
</script>

2.	/* import AppInsights */
import {AppInsights} from "applicationinsights-js"   -- Facing Error in this line of code 

/* Call downloadAndSetup to download full ApplicationInsights script from CDN and initialize it with instrumentation key */
AppInsights.downloadAndSetup({ instrumentationKey: "xxxxxxx x x x xx" });

/* example: track page view */
AppInsights.trackPageView(
    "IndexPage", /* (optional) page name */
    null, /* (optional) page url if available */
    { prop1: "prop1", prop2: "prop2" }, /* (optional) dimension dictionary */
    { measurement1: 1 }, /* (optional) metric dictionary */
    123 /* page view duration in milliseconds */
);
3.	I have added 
 ![dll](https://cloud.githubusercontent.com/assets/17904195/22777839/91f2f84e-eeda-11e6-94b2-9ab7158e3a5a.png)
4.	Folder created after installing above type script.  
![folder](https://cloud.githubusercontent.com/assets/17904195/22777856/ae7bd1a2-eeda-11e6-9f78-da6724946272.png)

5.	Trying to import {AppInsights} from "applicationinsights-js"   -- Facing Error in this line of code 

Could you please help me in configuring Application Insights for my application (WinJS - Javascript). If you can have free time , I would like to have a skype call with you. Please let me know.

@kamilszostak @MaxShehovtsov   Please help me. 

@v-rchida @v-boashw

**Comment by KamilSzostak** [comment]
Depending on how your project is structured you should choose one of available SDK [initialization methods](https://github.com/Microsoft/ApplicationInsights-js#initializing-application-insights-js-sdk-script). If you have an HTML template you can add a snippet right before the end of `<body>` tag. If you prefer a module approach you can use a JS SDK npm package.

**Comment by ashwin4av** [comment]
Thank you @KamilSzostak for your help, Could you please provide AI.js for WinJS applications. 

Thanks,
Ashwin.

**Comment by KamilSzostak** [comment]
Closing, please reopen if you're still having issue when initializing AI in UWP Win 10 app.
