### ISSUE TITLE
TrackTrace API does not have severity options (Warning, Error, Info)

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-JS#409]
Hi,
I used the below link to set up application Insights on my client side that is written in tS.

https://github.com/Microsoft/ApplicationInsights-JS

Some Information about my setup.
I used the below commands to install:
Npm install applicationinsights-js
Npm install @types/ applicationinsights-js.

The typings has TrackTrace(message, properties) signature with no mention of Severiry level (Warning, Error, Info). How do I achieve the equivalent to TraceInfo, TraceError, TraceWarning? 

In server side (.Net), am able to do something like
this.appInsightsClient.TrackTrace(message, SeverityLevel.Information, properties);

**Comment by KamilSzostak** [comment]
You're right, `trackTrace` doesn't take a severityLevel. To log an error with a given [severity level](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK.Interfaces/Contracts/Generated/SeverityLevel.ts) please use [`trackException` method](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#trackexception).

**Comment by shkrishms** [comment]
In Analytics window, the TrackException will log to the exceptions table right? I want to write to the Traces table where the server side request are going as well.  This will help me with correlating things.
How do I achieve this in Client? Could you let me know the reasoning behind not supporting SeverityLevel for Traces?

**Comment by KamilSzostak** [comment]
We will add `severityLevel` to `trackTrace` method to stay aligned with other SDK's.

**Comment by shkrishms** [comment]
Thanks
