### ISSUE TITLE
Alternatives to downloading script for application Insights on Client: Blocked by Ad Block software on Chrome

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-JS#411]
Hi,
I used the below link to set up application Insights on my client side that is written in tS.

https://github.com/Microsoft/ApplicationInsights-JS

Some Information about my setup.
1.	I used the below commands to install:
Npm install applicationinsights-js
Npm install @types/ applicationinsights-js.

I am using the below code to download the script from "https://az416426.vo.msecnd.net/scripts/a/ai.0.js"
 AppInsights.downloadAndSetup({
            instrumentationKey: "xxxxxxxxxx"
        })

But this has several disadvantages:
1. I am on chrome and using uOrigin ad-block. The above piece of code is blocked by the ad-block software.
GET https://az416426.vo.msecnd.net/scripts/a/ai.0.js net::ERR_BLOCKED_BY_CLIENT

2. Secondly, I am hesitant to have my UI download something from an external source due to security issues. What if "https://az416426.vo.msecnd.net/scripts/a/ai.0.js" is compromised?

It will be helpful if we can download the script using npm in advance and use it in our code. Is there a way to do that?

**Comment by KamilSzostak** [comment]
1) The goal of an ad-blocking software is to block all tracking and ad-serving scripts. App Insights JS SDK is tracking user's activity so (unfortunately 😢) it may be a valid script to block. IMHO we should respect users choice and shouldn't implement any "hacks" to bypass the uOrigin or ABP blocking mechanism. 

2) JS SDK is following the highest standards defined for the Azure cloud to ensure the security of the `az416426` CDN. It's not uncommon for a website to download scripts from external locations (e.g. FB "Like" button script or jQuery library from _cloudflare_ CDN). 

The full script is included in the npm package - `dist/ai.0.js`. You can change the default script location using the `url` configuration (see AppInsightsModule.js, line 61)

**Comment by shkrishms** [comment]
I did try mentioning the url. But I am hitting some issues. I have created the below issue? 
https://github.com/Microsoft/ApplicationInsights-JS/issues/412

**Comment by KamilSzostak** [comment]
I'm closing this issue. The `url` issue is tracked in #412.
