### ISSUE TITLE
Specifying Url in AppInsights.downloadAndSetup gives error

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-JS#412]
Hi,
I want to use AppInsights js file statically. I am using the below code:
   AppInsights.downloadAndSetup({
            instrumentationKey: "xxxxxx",
            url: "/src/ai.js"
        });

This gives the below error on browser:
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_applicationinsights_js__.AppInsights.downloadAndSetup is not a function.

Is there a way to specify the java file statically?

**Comment by KamilSzostak** [comment]
I'm unable to repro. Could you provide more details? 

This is a very simple app which I used. 

**index.js**

```
import { AppInsights } from "applicationinsights-js"

AppInsights.downloadAndSetup({
    instrumentationKey: "<ikey>",
    url: "src/ai.0.js"
});

AppInsights.trackEvent("TestEvent", { prop1: "prop1", prop2: "prop2" }, { measurement1: 1 });
```

**index.html**
```
<html>
    <body>
        <script src="app.bundle.js"></script>
    </body>
</html>
```

Run `webpack index.js app.bundle.js` and open `index.html` in the browser. I see that the `ai.0.js` file is downloaded from the `src` directory and I can see `/v2/track` request in fiddler (and later in the Azure Portal).

**Comment by shkrishms** [comment]
Hi Kamil,
I think I figured out the reason. I was playing around with different ways of initializing AppInsights(Through javascript and through downloadAndsetup). I removed the js version, but the browser has still cached the copy initialized through JS. That version could not recognize downloadAndSetUp function.

Thanks for the example snippet. 
-Sharanya
