### ISSUE TITLE
AI is not defined exception

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-JS#415]
when the below code is called,
AppInsights.trackException(error, "", properties, null, AI.SeverityLevel.Warning)

Hitting the exception:
AI is not defined.

Other methods work. AppInsights.trackTrace, AppInsights.trackEvent.

The one difference I notice is, the methods which works do not have AppInsight defined objects like AI.

This is how I have initialized app insights:
import { AppInsights } from "applicationinsights-js";
 AppInsights.downloadAndSetup({
                instrumentationKey,
            });

**Comment by KamilSzostak** [comment]
Thanks for reporting. It's a know issue #282. We will fix it in the next release (v.1.0.9).

**Comment by captainmorgan0** [comment]
I'm getting the same issue when calling
this.monitoringService.trackException(new Error(), null, null, null, AI.SeverityLevel.Error);
Is there still a bug? I've gotten around the error but using 4 instead of the Enum,

**Comment by Macadoshis** [comment]
this is still not fixed on version 1.0.20 ! 

why is it closed ??
