### ISSUE TITLE
Object doesn't support property or method 'setAuthenticatedUserContext'

### ISSUE THREAD

**Issue by tlmii** [Microsoft/ApplicationInsights-JS#416]
I'm sure I'm just doing something stupid, but I can't get setAuthenticatedUserContext to work. Here's the snippet I'm using:

```
<script type="text/javascript">
    var appInsights = window.appInsights || function (config) {
        function s(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, r = document, f = window, e = "script", o = r.createElement(e), i, u; for (o.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", r.getElementsByTagName(e)[0].parentNode.appendChild(o), t.cookie = r.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) s("track" + i.pop()); return config.disableExceptionTracking || (i = "onerror", s("_" + i), u = f[i], f[i] = function (config, r, f, e, o) { var s = u && u(config, r, f, e, o); return s !== !0 && t["_" + i](config, r, f, e, o), s }), t
    }({
        instrumentationKey: "<redacted>"
    });

    appInsights.setAuthenticatedUserContext("<redacted>");

    window.appInsights = appInsights;

    appInsights.queue.push(function () {
        appInsights.context.addTelemetryInitializer(function (envelope) {
            envelope.tags = envelope.tags || {};
            if (typeof screen !== "undefined") {
                envelope.tags["ai.device.screenResolution"] = screen.width + "x" + screen.height;
            }
        });
    });

    appInsights.trackPageView();
</script>
```

I've modified the default snippet in two ways - adding the call to setAuthenticatedUserContext, and adding the telemetryinitializer for the screen resolution, per https://github.com/Microsoft/ApplicationInsights-Announcements/issues/5. The latter works fine (if I remove the former). The call to setAuthenticatedUserContext fails with the error

Object doesn't support property or method 'setAuthenticatedUserContext'

and in fact if I examine the methods of the appInsights object, it doesn't see that function. Though I also don't see a lot of functions I'd expect to see. The only ones I _do_ see are shown here:

![image](https://cloud.githubusercontent.com/assets/9613109/23558562/2305eca0-0002-11e7-9ec2-6e9db7c62048.png)

I verified that the code downloads v1.0.8 of the js file, so I'm getting the latest. 
What am I doing wrong?

**Comment by KamilSzostak** [comment]
It looks like you're not using the latest snippet. We fixed this issue a couple months ago. You can find the latest snippet [here](https://github.com/Microsoft/ApplicationInsights-js#use-js-snippet-and-initialize-dynamically-download-full-application-insights-script-from-cdn) or in the _Getting Started_ page in Azure Portal. 

Let me quickly explain why you don't see all methods. The snippet only defines stubs of all `track*()` and `[set|clear]AuthenticatedUserContext` functions and records if they were invoked. When the full library is downloaded (from https://az416426.vo.msecnd.net/scripts/a/ai.0.js) all those stubs are replaced with real methods and all previously recorded methods are actually invoked and processed.

**Comment by KamilSzostak** [comment]
Thanks for this question, I added it to the [FAQ](https://github.com/Microsoft/ApplicationInsights-JS/wiki/FAQ).

**Comment by tlmii** [comment]
Thanks for the quick reply! I didn't realize that the snippet ever needed to be updated.
