### ISSUE TITLE
stopTrackEvent suppose to send duration to the server

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#43]
This action should send duration to the server as a custom property:

https://github.com/Microsoft/ApplicationInsights-JS/blob/9b68112e4f59e534414ca3d65a25dacbba280d50/JavaScript/JavaScriptSDK/appInsights.ts#L75

**Comment by MaxShehovtsov** [comment]
@SergeyKanzhelev I agree. However if custom property duration already exists we shouldn't override it - in this case the duration of this timed event won't be sent.

**Comment by SergeyKanzhelev** [comment]
API is confusing. We either need to remove it or fix it so it sends duration. Maybe the better option will be to remove this API and make use of trackAjax instead?

**Comment by MaxShehovtsov** [comment]
I think we should keep it as it's different from ajax/dependency call. Although it's more useful for 'usage' than 'diagnostics'. I'm going to stick with my proposal of setting 'duration' custom property if it's not already set, otherwise lose it.

**Comment by kamilszostak** [comment]
Fixed: https://github.com/Microsoft/ApplicationInsights-JS/pull/90
