### ISSUE TITLE
Bad/non working sample for setting default properties.

### ISSUE THREAD

**Issue by mattias-skold** [Microsoft/ApplicationInsights-JS#434]
The codesnippet on https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer  dosent work with SDK 107 

Compiling it with typescript gives the following errors.
Argument of type '(envelope: IEnvelope) => void' is not assignable to parameter of type '(envelope: IEnvelope) => boolean'
Property 'data' does not exist on type 'IEnvelope'

**Comment by KamilSzostak** [comment]
I'm also updating types in DefinitelyTyped repo - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17076
