### ISSUE TITLE
Application.Build should be deprecated

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#435]
[Application.Build](https://github.com/Microsoft/ApplicationInsights-JS/blob/178b7d66d8d7a741f9154012f8d19c3fbc52d503/JavaScript/JavaScriptSDK.Interfaces/Context/IApplication.ts#L14) was deprecated and should be removed from typing. See [schema](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/ContextTagKeys.bond) for the list of supported context properties

**Comment by KamilSzostak** [comment]
Will be fixed as part of #327.
