### ISSUE TITLE
Why was disableCorrelationHeaders default changed to false? #395 (FIXED??)

### ISSUE THREAD

**Issue by cwoodland** [Microsoft/ApplicationInsights-JS#437]
Has this fix been released?

I don't see x-ms-request-id anywhere in the code when I search in version 1.0.8?

Thanks

**Comment by KamilSzostak** [comment]
It will be release in [1.0.9](https://github.com/Microsoft/ApplicationInsights-JS/milestone/24). We are planning to release it next week.

**Comment by cwoodland** [comment]
Thanks!!  Is there a beta version I can try until then??

**Comment by cwoodland** [comment]
What day this week can we expect 1.0.9?
