### ISSUE TITLE
Why do we need the setting emitLineDelimitedJson?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#438]
What's the reason to have `emitLineDelimitedJson` setting in configuration? Should we get rid of it to unify the way we send telemetry between .NET and JS?

**Comment by AlexBulankou** [comment]
Just to confirm - are you suggesting we always send line-delimited JSON, right? If so, I agree.  Digging through old emails, I think originally we introduced this option for backward compat but now there's no reason why we still should be sending non line-delimited. 
@KamilSzostak thoughts/objections? If not, can you please schedule it for one of the upcoming milestones.

**Comment by SergeyKanzhelev** [comment]
yes, always send newline-delimited please

**Comment by KamilSzostak** [comment]
I agree. We should remove it, let's schedule it for next release.

**Comment by AbhyudayaSharma** [comment]
Hi! Can I work on this? If yes, could you please provide me with a code pointer?

**Comment by markwolff** [comment]
Looks like this setting is still needed for backwards compatibility for some internal endpoints, as per 7a028dc4.
