### ISSUE TITLE
What does verboseLogging do?

### ISSUE THREAD

**Issue by cwoodland** [Microsoft/ApplicationInsights-JS#439]
What does option verboseLogging do?  It is not outlined in the README.

Thanks

**Comment by KamilSzostak** [comment]
When `verboseLogging` is `true` the SDK will log all internal errors to the console and report them to AppInsights. By default, the SDK only logs and reports critical errors (one per error type). 

See [throwInternal](https://github.com/Microsoft/ApplicationInsights-JS/blob/4620cfdc47975f2e32e82f63c693f9b88fa50568/JavaScript/JavaScriptSDK/Logging.ts#L177) and [logInternalMessage](https://github.com/Microsoft/ApplicationInsights-JS/blob/4620cfdc47975f2e32e82f63c693f9b88fa50568/JavaScript/JavaScriptSDK/Logging.ts#L274).

**Comment by cwoodland** [comment]
Thanks!
