### ISSUE TITLE
All pages are not tracked in pageviews 

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-JS#446]
WE have a UI built on react. We have at least 8 different unique pages but only 3 of them are showing up in Application insights portal. Only these limited pages are considered for page load times as well.

I am currently on version : 1.0.8

**Comment by OsvaldoRosado** [comment]
Are these pages actual page loads or do you have a single-page application?

**Comment by shkrishms** [comment]
Its a single page application

**Comment by OsvaldoRosado** [comment]
Are you using `trackPageView` manually? This SDK does not currently handle SPAs out of the box without some manual instrumentation.

**Comment by shkrishms** [comment]
I see. I was not tracking manually. But once I noticed that page views are not accurate, I am using start track page and stop track page. This tracks the expected page views correctly. But there is some confusion about how page load time is calculated and how page view time (how long a user is on a page) is calculates. (see issue 447) #447

**Comment by shkrishms** [comment]
I think most people develop SPAs now and google analytics supports them. This should be a definite feature.

**Comment by shkrishms** [comment]
Even if ours is SPA, urls change . Shoulld appinsights track those?

**Comment by OsvaldoRosado** [comment]
It's my understanding that page changes on SPAs, regardless of synthetic URL changing have to be manually tracked. We don't yet have a comprehensive SPA solution because of how varying implementations can be, such as when to start and stop measuring "load time" for the next virtual page.
