### ISSUE TITLE
Does JS SDK retry failed tracked telemetry?

### ISSUE THREAD

**Issue by ischrei** [Microsoft/ApplicationInsights-JS#449]
Hi,

From time to time we notice missing telemetry for our JS clients.
I wanted to check please whether the current SDK retries sending telemetry when the request fails or when there is a partial success.
If there are no retries, I would also suggest try sending an exception with the previous errors.

Thanks,
Ido.

**Comment by KamilSzostak** [comment]
Yes, the SDK will retry if it couldn't reach the AppInsights endpoint or if the endpoint returned a retriable error (e.g. server error, but not for quota exceeded or JSON parse error). The SDK will also log exceptions, internal exceptions will have "AI:" or "AI (Internal):" prefix. 

Could you explain scenarios when you noticed missing telemetry?

**Comment by ischrei** [comment]
Hi,

For some custom events, the count of our JS client side events is different than the equivalent server side events. There could be various of reasons of course but I wanted to eliminate temporary connectivity issues or similar causes.
We've also found a bug in our telemetry which was hard to discover - from time to time events were rejected by AI as we set null instead of a numeric value in a measurement. an SDK exception is such cases would be very useful. 

Thanks a lot!
Ido.

**Comment by KamilSzostak** [comment]
The SDK will not send these type of errors by default. But you can enable `verboseLogging` - [see IConfig](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#config). With `verboseLogging` logging enabled the SDK will send all warnings and critical errors to AppInsights. 
You will be able to review them later in the Portal - search for Traces with 'AI ' prefix. 

Please re-open this issue if you have more questions or comments. Thank you!

**Comment by ischrei** [comment]
Great thank you very much.
