### ISSUE TITLE
Use http as a fallback option for non http and non https urls

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#45]
Consider using http as a fall back option for files opened as html file on file system or Windows JavaScript apps

https://github.com/Microsoft/ApplicationInsights-JS/blob/24c9a387dd1118e8e6e7bfecb1f10a4826161a8d/JavaScript/JavaScriptSDK/Initialization.ts#L142

**Comment by AlexBulankou** [comment]
Dupe of https://github.com/Microsoft/ApplicationInsights-JS/issues/93
