### ISSUE TITLE
startTrackPage is not a function at first time loading page

### ISSUE THREAD

**Issue by Firyuza** [Microsoft/ApplicationInsights-JS#451]
http://stackoverflow.com/questions/30058310/using-starttrackpage-in-application-insights

I have the same error that was described above in stackoverflow, but the answer doesn't help me.

**Comment by KamilSzostak** [comment]
Could you explain the issue a bit more? `startTrackPage` method is defined in the snippet and should always be available in the `appInsights` object. 

We are working on a fix for #300 which will fix an incorrect timestamp issue.

**Comment by Firyuza** [comment]
When I load my page where I use appInsights object and startTrackPage function, I get error that this function is undefined. But other functions like trackViewPage, trackEvent, trackDependency are available. Just after several time I do see this function in appInsights object.

**Comment by Firyuza** [comment]
But day ago we updated script(<script type="text/javascript">var appInsights=window.appInsights||function(config){ ...). And now I don't see this error.

**Comment by SergeyKanzhelev** [comment]
@Firyuza you may have had an outdated snippet. See this commit that was fixing the issue you describe: https://github.com/Microsoft/ApplicationInsights-JS/commit/a06716c1377d361a2d742140f5d899427c714fa8
