### ISSUE TITLE
How do you get the client browser screen resolution?

### ISSUE THREAD

**Issue by mikeblakeuk** [Microsoft/ApplicationInsights-JS#452]
How can i get the screen resolution when the client is a Browser? e.g. Windows 8, Chome, Screen res.
It looks like it will always be "browser"?

![image](https://cloud.githubusercontent.com/assets/1986660/25707510/a5a17918-30db-11e7-88f9-6bccc01d0560.png)

When is this set?
https://github.com/Microsoft/ApplicationInsights-JS/blob/178b7d66d8d7a741f9154012f8d19c3fbc52d503/JavaScript/JavaScriptSDK/Context/Device.ts#L37

**Comment by KamilSzostak** [comment]
The SDK doesn't collect screen resolution automatically anymore. The old code will be removed in #455. 

You need to record browser resolution manually. One idea is to add it as a property to `trackPageView`. 
Usually, `trackPageView` method is invoked in the snippet ([see](https://github.com/Microsoft/ApplicationInsights-js#use-js-snippet-and-initialize-dynamically-download-full-application-insights-script-from-cdn)). So you can add it directly in the snippet or use a [telemetryInitializer](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#addtelemetryinitializer) to inject it.
