### ISSUE TITLE
Clean up ContextTagKeys

### ISSUE THREAD

**Issue by KamilSzostak** [microsoft/ApplicationInsights-JS#455]
Current list of supported tags: [ContextTagKeys.md](https://github.com/Microsoft/ApplicationInsights-Home/blob/804a33e3e9abef9d01cfeca102f459e0b4edaed1/EndpointSpecs/Schemas/Docs/ContextTagKeys.md)

JS SDK: [ContextTagsKeys.ts](https://github.com/Microsoft/ApplicationInsights-JS/blob/178b7d66d8d7a741f9154012f8d19c3fbc52d503/JavaScript/JavaScriptSDK.Interfaces/Contracts/Generated/ContextTagKeys.ts)

**Comment by jpiyali** [comment]
Beta SDK supports it as context.device.resolution.
