### ISSUE TITLE
Trace tracking with POST events is too complicated

### ISSUE THREAD

**Issue by jsgoupil** [microsoft/ApplicationInsights-JS#458]
The documentation indicates that POST events are not tracked by default. You recommend to use trackTrace. However, to make trackTrace work properly, we need to connect it with the operationId.

The first problem, that operationId is burried on the XHR.ajaxData. Getting it back with an Angular 4 application is so complicated. We need to override the XHRBackend or the BrowserXhr and start tracking what is going on.

The second problem, with trackTrace, we can't specify the operation id, it's based on a context.

I am trying to call trackTrace to a specific operation id to find it easily in the portal when an AJAX request failed. Basically, if my response is not 2xx, I will call trackTrace with the post data.

My current work around is to return the x-ms-request-id from the server in the header with a filter:

    public sealed class AppInsightHeaderDataAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
        {
            IEnumerable<string> values;
            if (actionExecutedContext.Request.Headers.TryGetValues("x-ms-request-root-id", out values))
            {
                var requestId = values.FirstOrDefault();
                if (requestId != null)
                {
                    actionExecutedContext.Response.Headers.Add("x-ms-response-id", requestId);
                }
            }

            base.OnActionExecuted(actionExecutedContext);
        }
    }

Then on the client side, imitate what trackTrace does, but by changing the context just before calling track...

    private register(observableResponse: Observable<Response>, body: any = null, extraOptions: ExtraOptions) {
        let shared = observableResponse.do(null, (res: Response) => {
            if (!res.ok) {
                if (body && this.appInsightsService) {
                    let requestId = res.headers.get('x-ms-response-id');
                    if (window && (<any>window).appInsights && (<any>window).appInsights.context && (<any>window).Microsoft && (<any>window).Microsoft.ApplicationInsights) {
                        let telemetry = (<any>window).Microsoft.ApplicationInsights.Telemetry;
                        let f = new telemetry.Trace(JSON.stringify(body))
                            , e = new telemetry.Common.Data(telemetry.Trace.dataType, f)
                            , o = new telemetry.Common.Envelope(e, telemetry.Trace.envelopeType);

                        let previousOperation = JSON.parse(JSON.stringify((<any>window).appInsights.context.operation));
                        (<any>window).appInsights.context.operation = (<any>window).appInsights.context.operation || {};
                        (<any>window).appInsights.context.operation.id = requestId;
                        (<any>window).appInsights.context.track(o);
                        (<any>window).appInsights.context.operation = previousOperation;
                    }
                }
            }
        }).share();

        return shared;
    }

Even after all that work, I can't get that trace to light up properly in the portal... How am I supposed to connect the request with the trace properly??

![image](https://cloud.githubusercontent.com/assets/808649/25832958/e5b076ea-3422-11e7-9559-2f320a48d524.png)

**Comment by markwolff** [comment]
Seems this issue has gone stale, but reopen for further discussion. I would recommend using `trackDependencyData` instead of `trackTrace` for tracking ajax calls
