### ISSUE TITLE
Internal AI trace with no details

### ISSUE THREAD

**Issue by ischrei** [Microsoft/ApplicationInsights-JS#461]
Hi,

I've turned on verbose tracing in the JS SDK, and I see those kinds of traces:
_"AI (Internal): OnError message:"Failed to send telemetry." props:"{message:}"_

Unfortunately, there is no enough info to understand what went wrong.

Can you please advice?

Thanks,
Ido.

**Comment by KamilSzostak** [comment]
Thanks for reporting. Could you share your script (you can send it to kszostak@microsoft.com)? Could make it as small as possible to only highlight the issue? 

You may also follow [these steps](https://github.com/Microsoft/ApplicationInsights-JS/wiki/FAQ#something-weird-is-going-on-how-do-i-debug-the-js-sdk) to debug the SDK.
