### ISSUE TITLE
Cannot get custom events or Page Load View output

### ISSUE THREAD

**Issue by larrywa** [Microsoft/ApplicationInsights-JS#465]
I have an ASP.Net (.Net 4.5.1) application that I just added App Insights to. For some odd reason, I can't see any custom event data or Page Load View data.

For example, in .\Shared\_Layout.cshtml, I put:
<li>@Html.ActionLink("Tickets", "Index", "ServiceTickets", null, new { onclick = "appInsights.trackEvent('User clicked on Tickets');" })</li>

I know my instrumentation key is correct, I see all other traces etc that I put in my code.

Why would these two pieces of data not be shown?

If I create a brand new app from Visual Studio, the Page View Load time information shows as well as custom events.

**Comment by KamilSzostak** [comment]
Could you please confirm that you have the JavaScript SDK [snippet](https://github.com/Microsoft/ApplicationInsights-js#use-js-snippet-and-initialize-dynamically-download-full-application-insights-script-from-cdn) in the header? 

Is this action link navigating to a new page? If yes, the browser may terminate all JS execution before AppInsights manages to send any data. To workaround this issue, you can:
* send click telemetry on the target page
* block navigation until you collect required telemetry
* use Beacon API (experimental feature) - see `isBeaconApiDisabled` in [IConfig](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#config)

**Comment by KamilSzostak** [comment]
Closing, please reopen if you're still experiencing this issue.
