### ISSUE TITLE
BrowserLink telemetry being sent to Azure 

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#466]
Moved from https://github.com/Microsoft/ApplicationInsights-Home/issues/122

Reported by @ppumkin

Browserlink shows up as a dependency AJAX and is flooding my charts while debugging.

I had a look at the 

`<Add Type="Microsoft.ApplicationInsights.Web.SyntheticUserAgentTelemetryInitializer, Microsoft.AI.Web">`

and 

`<Add Type="Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule, Microsoft.AI.Web">`

but it is not entirely clear to me how to filter out browserLink from Visual Studio

I am currently evaluating on the free tier and I know I probably need to setup separate Azure Resources  but I really do not need to be sending and using data for browserlink any way. (especially when you have a large dev team) 

![image](https://cloud.githubusercontent.com/assets/1249683/26453609/405c12e8-415c-11e7-83e1-03bb22be7aaa.png)

**Comment by SergeyKanzhelev** [comment]
@KamilSzostak what would be your advice? Should it be a default telemetry initializer in JavaScript SDK to filter browser links?

**Comment by KamilSzostak** [comment]
@SergeyKanzhelev yes, I think the JS SDK should not report any  `*/browserLinkSignalR/pool` calls. I'll add it as a default telemetry initializer.
