### ISSUE TITLE
Client.flush() is not a function

### ISSUE THREAD

**Issue by kiewic** [Microsoft/ApplicationInsights-JS#467]
As I understand from the [Application Insights SDK JavaScript API][gh-docs] documentation, the Application Insights Client class has a `flush()` method, but I have tried to invoke it as an instance method and as a static method, but I always get `TypeError: appInsightsClient.flush is not a function` error. Here is an example:

    var appInsights = require("applicationinsights");
    var appInsightsClient = appInsights.getClient();
    appInsightsClient.trackTrace("hello world");
    appInsightsClient.flush();

I am using npm package `applicationinsights: 0.20.1`

Is this a known issue?

[gh-docs]: https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#flush

**Comment by KamilSzostak** [comment]
`applicationinsights: 0.20.1` is a Node.js SDK. `applicationinsights-js` is a JavaScript SDK. I know, it's a bit confusing ;/

As far as I remember, Node.js SDK has a `sendPendingData` method which acts similar to `flush`. Please refer to [Node.js SDK](https://github.com/Microsoft/ApplicationInsights-node.js/) documentation for details.

**Comment by kiewic** [comment]
Got it, thanks @KamilSzostak for the clarification
