### ISSUE TITLE
Allow cross-origin dependency correlation

### ISSUE THREAD

**Issue by KamilSzostak** [microsoft/ApplicationInsights-JS#479]
We have this restriction because of: #331.  
Possible solution: user can white-list a given host.
 
ref: https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/ajax/ajax.ts#L140

**Comment by TheeJamesLee** [comment]
@KamilSzostak is there an actual eta of when this will be available?  A little fundamental for any thick client application that has an api on another domain...

Thanks :)

**Comment by tomaszliptak** [comment]
It looks to me like the described restriction was removed in this PR: https://github.com/Microsoft/ApplicationInsights-JS/pull/565 
@KamilSzostak Can you confirm?
Can we assume then it will be included in milestone 1.0.16?
