### ISSUE TITLE
  What does this error mean ? ( FailedMonitorAjaxRSC )

### ISSUE THREAD

**Issue by 29er** [Microsoft/ApplicationInsights-JS#482]
"AI (Internal): FailedMonitorAjaxRSC message:"Failed to monitor XMLHttpRequest 'readystatechange' event handler, monitoring data for this ajax call may be incorrect." props:"{ajaxDiagnosticsMessage:(url: '/bomapi/knowledgebases/parts/meta'),exception:[object Object]{\messageId\:26,\message\:\AI (Internal): SessionRenewalDateIsZero message:\\\AI session renewal date is 0, session will be reset.\\\\}}""

we've been using App Insight for a few weeks now, and started seeing this error today ??

Thanks

**Comment by debugthings** [comment]
What browser does this happen in and what is the host name in the URL?

**Comment by juzkuz** [comment]
I have this same issue - I'm trying to run app insights from a cordova application (ionic) and am not able to get ajax to load. The same error occurs for me when I enabled debugging and verbose logging

**Comment by cdwaddell** [comment]
I am also having this issue in an Angular application.

**Comment by tlaak** [comment]
I'm also having the same issue in an Angular 4 application. The error message and the messageId varies a bit, depending which AppInsights function you're calling, but in the end there's always this `AI session renewal date is 0, session will be reset.` line.

**Comment by tlaak** [comment]
I deleted cookies and all localStorage and sessionStorage settings and I can't see the errors anymore. I have tried changing `sessionRenewalMs` and `sessionExpirationMs` settings to something lower, but I haven't been able to reproduce the issue yet.

**Comment by tlaak** [comment]
@KamilSzostak Any idea what would be causing this problem? I'm still getting errors like this, now with Angular 5.24, applicationinsights-js 1.0.15. and a totally different app than last time.

`ERROR e {messageId: 11, message: "AI (Internal): ExceptionWhileLoggingError message:…\}}\\\\},errorString:Error, [object ErrorEvent]}""}` and `Uncaught e {messageId: 37, message: "AI (Internal): TrackPVFailedCalc message:"trackPag… renewal date is 0, session will be reset.\\\\}}""}`

Deleting localStorage, sessionStorage and cookies will only be a temporary fix, the problem will reappear after 1-2 days or even longer.

This is also reported in [StackOverflow](https://stackoverflow.com/questions/32780611/application-insights-metrics#comment80898775_32780611)

**Comment by gmaughan** [comment]
If I turn off "cookie use" I no longer get the errors. I don't know what the implications are of this yet regarding session tracking.

`
AppInsights.downloadAndSetup({
        instrumentationKey: key,
        isCookieUseDisabled: true
      });
`

**Comment by cyrixmorten** [comment]
I am also seeing this error in an angular application and will disable cookie usage as suggested by @gmaughan 

Can any of the developers of this library advice on the implications it may have to disable cookies?

Or even better, identify what is causing and fix it. 

I see that `ai_session` has a value of `|0|0`

**Comment by markwolff** [comment]
@cyrixmorten [Implications of disabling cookies](https://azure.microsoft.com/en-us/blog/azure-application-insights-javascript-sdk-reliability-and-performance-improvements/)
You can try updating to the latest version (1.0.20), although I don't think this issue was ever addressed in an update. 

The session renewal date is 0 message is just a warning, letting you know that your session cookie is going to be renewed. It doesn't actually mean something is directly wrong. However, `enableDebugExceptions: true` might be making it throw something, causing the track calls to break; do you have this setting enabled in any of your test cases?

**Comment by cyrixmorten** [comment]
@markwolff Thank you for your reply

I had both `enableDebug` and `verboseLogging` options enabled. Do not see a `enableDebugExceptions` option and so have not set it anywhere. 

The fact that it is posted as an error made me think that it was in a bad state. Additionally did not notice the session being renewed, even after navigating the page a bit to trigger some more events being fired at app insights. Kept seeing `|0|0` in the `ai_session` cookie.

However, as the implications of disabling cookies seems rather high, I will revert back to having cookies enabled and see what happens.

**Comment by markwolff** [comment]
Is the error still happening with the debug information turned off?
Obviously, turning it on should not disable telemetry so it is probably something we will look into in a future milestone. Reopen if this did not solve your issue though!

**Comment by cyrixmorten** [comment]
Hi @markwolff 

Now have `enableDebug` set to false and there are no longer errors thrown by the library.

However think you are right that there may be something to look into regarding telemetry not being sent when having debug enabled and the session renewal error is thrown.
