### ISSUE TITLE
applicationinsights-js not compiling correctly using angular compiler

### ISSUE THREAD

**Issue by lvanderbijl** [Microsoft/ApplicationInsights-JS#483]
Hi,

I'm using applicationinsights as a dependency for an angular library I'm creating using the https://github.com/filipesilva/angular-quickstart-lib. This project uses ngc to compile the library and dependencies.

I'm using applicationinsights 1.0.4 and the @types/applicationinsights-js v1.0.4 (only because the typings doesn't have a 1.0.9...)

I'm using applicationinsights in a service like this: 
`import { AppInsights } from 'applicationinsights-js';`

However when the compiler converts it to an es2015 module, the import becomes: 
`import { AppInsights } from 'applicationinsights-js/index';`
(note the extra: /index at the end)

which is obviously wrong and breaks. Any ideas why this is occuring? I feel like it's something to do with the way the @types works but can't work out why.

Thanks for your time
Leander

**Comment by MarkPieszak** [comment]
I'm not sure how you're doing Ngc but don't have any problems here in my angular & app insight module using the sdk? Check to see if you're doing it similarly.

https://github.com/MarkPieszak/aspnetcore-angular2-universal

**Comment by KamilSzostak** [comment]
Thanks, @MarkPieszak for helping!

Closing, please re-open if you're still experiencing the issue or have more questions.
