### ISSUE TITLE
Missing .map files in npm package

### ISSUE THREAD

**Issue by Zenuka** [Microsoft/ApplicationInsights-JS#484]
The current latest version (v1.0.9) has the following line in `AppInsightsModule.js`
```javascript
//# sourceMappingURL=AppInsightsModule.js.map
```
But since the .map file is missing I'm getting errors from other tools (for example aurelia-cli) that there is a missing .map file. Could the line be removed or could the .map file be included?
mttmccb also referenced this issue in his comment: https://github.com/Microsoft/ApplicationInsights-JS/issues/178#issuecomment-292472479

**Comment by KamilSzostak** [comment]
The latest npm package v1.0.13 contains the missing file.
