### ISSUE TITLE
New 1.0.10 release breaks build

### ISSUE THREAD

**Issue by marcowenneker** [Microsoft/ApplicationInsights-JS#488]
Module not found: Error: Can't resolve 'applicationinsights-js' in 'myfile'

myfile.ts
import { AppInsights } from 'applicationinsights-js'; // Used to work this way, now doesn't ???
...
AppInsights.trackEvent etc

FYI also updated to @types/applicationinsights-js": "^1.0.4"

Are there breaking changes?

**Comment by munyirik** [comment]
I started seeing this as well today

**Comment by KamilSzostak** [comment]
I'm investigating
