### ISSUE TITLE
Doesn't work with .Net Core 1.1

### ISSUE THREAD

**Issue by rastogi-nitin** [Microsoft/ApplicationInsights-JS#491]
I tried to install the package in a asp.net core project and it fails with this error

Unable to resolve 'applicationinsights-js (>= 1.0.11)' for '.NETCoreApp,Version=v1.1'.

Are we planning to support .net core?

Regards,
Nitin

**Comment by jpiyali** [comment]
@rastogi-nitin  - the .net core SDK already include pulling in the JS sdk.a already. Please retry and let us know if this is still an issue. 
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/9e93f22e7e10dbbe2d43f8c4c45bea8fd33185d1/CHANGELOG.md.
