### ISSUE TITLE
After enabling Sampling, Users/Authenticated Users Statistics seems to be broken

### ISSUE THREAD

**Issue by dimonok** [Microsoft/ApplicationInsights-JS#497]
After enabling Sampling (5%), the Users/Authenticated User statistics seems to be broken.

At the red line we enabled sampling:
![image](https://user-images.githubusercontent.com/7802826/28621165-57062044-7210-11e7-9264-e7b65926f85a.png)

AI configuration:
`{
            instrumentationKey: "...",
            samplingPercentage: 5
}`

Used AI Script:
https://az416426.vo.msecnd.net/scripts/a/ai.0.js

On Backend we are using Application Insights for Java 1.0.6 without Sampling.

**Comment by KamilSzostak** [comment]
The JS SDK is passing a `userId` to a `isSampledIn` function which tells if an event should be sampled in or out. This way the SDK can collect all events for a given session and not cause any inconsistency (e.g. collect telemetry for only 1 out of 3 ajax requests on the same page view). 

The `isSampledIn` uses a djb hashing function which provides enough randomness, but it won't provide fully accurate data if there is not enough data (in this case 10k event * 5% = 500). 

To get more accurate data try aggregating users/auth user data over a bigger time range or increase the sampling rate. 

For more details see how the [hash function](https://github.com/Microsoft/ApplicationInsights-JS/blob/178b7d66d8d7a741f9154012f8d19c3fbc52d503/JavaScript/JavaScriptSDK/SamplingScoreGenerator.ts#L16) is implemented.
