### ISSUE TITLE
For EU cookie compliance, we need to set the max expiry date of cookies to 2 years instead of 13 years

### ISSUE THREAD

**Issue by prannayb** [Microsoft/ApplicationInsights-JS#499]
EU cookie laws say the any session/post-authentication cookie can have a max expiry of 2 years. Right now the app insights MicrosoftApplicationsTelemetryDeviceId and MicrosoftApplicationsTelemetryFirstLaunchTime cookies are set with 13 years expiry. This  violates EU privacy compliance. Therefore we need the ability to set cookie expiry date for app insights cookies.

**Comment by markwolff** [comment]
Closing as all cookies expire after at most 1 year
