### ISSUE TITLE
Do not force OPTIONS by setting content-type header

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-JS#500]
According to [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) `OPTIONS` pre-flight request will not be required if our SDK will not set the `Content-Type` header. 

Since Application Insights endpoint accepts data from everybody - we can eliminate the pre-flight request and improve SDK performance by removing this header.

**Comment by AlexBulankou** [comment]
If you remove content-type="application/json", will it require changes on the server side to interpret the payload as JSON?

**Comment by SergeyKanzhelev** [comment]
Tried in Fiddler - it seems to be accepting data. Need to document it though so future versions will not break it

**Comment by cwoodland** [comment]
When will this be done?

**Comment by MSNev** [comment]
Closing as this was originally for v1 (and is now very old) and v2 automatically adds a "Sdk-Context" to request the appId which would then trigger an OPTIONS call as well (even if we removed the Content-Type)
