### ISSUE TITLE
ICM Webhook

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-JS#501]
Hi,
We are MS team and we would like to know if azure appinsights supports ICM web hook for alerts out of the box?

**Comment by SergeyKanzhelev** [comment]
For non-public facing questions I'd suggest to use links from [here](https://ai-wiki.com/index.php?title=Customer_Escalation_Process) to ask the question. DL that listed there will be the best bet for this question. Yes, there is a solution for ICM that a few teams are using today and I can share the link on DL.
