### ISSUE TITLE
AI should work without using global window scope

### ISSUE THREAD

**Issue by kkorsakov** [microsoft/ApplicationInsights-JS#502]
We as a service provider use AI JS lib to collect telemetry from our code. We provide HTML code that is inserted into web page by our customers (some kind of widget). Our code works in top window context, iframes are not used. So we would like to isolate "our" instance of AI not to conflict with "customer's AI" if he/she also uses AI for own site. This is not possible now because AI becomes broken.

**Comment by xiao-lix** [comment]
This is now supported via new NPM package. https://www.npmjs.com/package/@microsoft/applicationinsights-web
