### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

### ISSUE THREAD

**Issue by kwilliams1987** [Microsoft/ApplicationInsights-JS#504]
ai.0.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

XMLHttpRequest.open | @ | ai.0.js:1
-- | -- | --
  | logVisit | @ | WebResource.axd?d=FhxcwkNW0UIftGOUOy2Atk_M1l8_QLTQ0e7MIY2dTnlxinWVrU-ChWII4…ThfnML55H3ssOZOJ4YnRhUNdlJazXpiO2uqFq6sKuN2ZJonnHk1&t=636336464426870360:8
  | LogVisit | @ | WebResource.axd?d=FhxcwkNW0UIftGOUOy2Atk_M1l8_QLTQ0e7MIY2dTnlxinWVrU-ChWII4…hfnML55H3ssOZOJ4YnRhUNdlJazXpiO2uqFq6sKuN2ZJonnHk1&t=636336464426870360:13
  | (anonymous) | @ | (index):1951

Not sure how long until Synchronous XMLHttpRequest gets bumped from deprecated to unsupported, but would be nice to get fixed, my clients keep complaining...

**Comment by markwolff** [comment]
It should be sending it as async by default right now. Reopen if this is not the case!
