### ISSUE TITLE
setAuthenticatedUserContext works fine with Edge but fail in Chrome.

### ISSUE THREAD

**Issue by aksMS** [Microsoft/ApplicationInsights-JS#506]
setAuthenticatedUserContext works fine with Edge but fail in Chrome. Following is code snippet we are using. We have use strict set for most of .js file.

<script type="text/javascript">
        var appInsights=window.appInsights||function(config){
        function i(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s="AuthenticatedUserContext",h="start",c="stop",l="Track",a=l+"Event",v=l+"Page",y=u.createElement(o),r,f;y.src=config.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js";u.getElementsByTagName(o)[0].parentNode.appendChild(y);try{t.cookie=u.cookie}catch(p){}for(t.queue=[],t.version="1.0",r=["Event","Exception","Metric","PageView","Trace","Dependency"];r.length;)i("track"+r.pop());return i("set"+s),i("clear"+s),i(h+a),i(c+a),i(h+v),i(c+v),i("flush"),config.disableExceptionTracking||(r="onerror",i("_"+r),f=e[r],e[r]=function(config,i,u,e,o){var s=f&&f(config,i,u,e,o);return s!==!0&&t["_"+r](config,i,u,e,o),s}),t
        }({
            instrumentationKey: "xxxxx"
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
</script>
<script type="text/javascript">
        var username='@Model.UserInfo.Alias';
        appInsights.setAuthenticatedUserContext(username);
</script>

**Comment by aksMS** [comment]
In chrome we get error "setAuthenticatedUserContext is not a function..

**Comment by jeffwilcox** [comment]
This may actually be fixed, we're using `setAuthenticatedUserContext` fine in Chrome at the moment, brand new app setup just within the last few days, using the preload snippet provided by the portal in Azure after creating a new app insights account...

**Comment by jpiyali** [comment]
Please reopen if this is still an issue.
