### ISSUE TITLE
Insights-Js Problem In Ie8

### ISSUE THREAD

**Issue by virtualcca** [Microsoft/ApplicationInsights-JS#510]
Maybe in 2017-8-29 or 2017-8-30
In ie8 can not send ajax request, I try comment insights-js reference, it can work, so i think is insights-js affect ajax
but when i use ie dev-tools change to ie7, it can work(had insights-js)

pic had some company info, i think i should delete pic

oddly, i can work on ie9 and above or ie7 but ie8 can't work,and i remove insight-js reference that is fine

**Comment by virtualcca** [comment]
it not had any js error

**Comment by cijothomas** [comment]
Workaround:  use a previous version of the JS SDK. To do that add the url: "http://az416426.vo.msecnd.net/scripts/a/ai.1.0.11.min.js"  to the snippet, right after the iKey.

**Comment by virtualcca** [comment]
Now i judge browser is not ie8 that use insight sdk, it can work find. but it will ignore ie8 data.

**Comment by KamilSzostak** [comment]
I'm investigating. 

Also, @filipetoniolo reported the following error: 
"error: Unhandled exception at line 2, column 3681 in http://az416426.vo.msecnd.net/scripts/a/ai.0.js 0x800a138f - JavaScript runtime error: Can not get the 'apply' property of an undefined or null reference."

**Comment by KamilSzostak** [comment]
We did roll back the JS SDK to v1.0.11 while we are investigating this issue.

**Comment by KamilSzostak** [comment]
@filipetoniolo and @virtualcca could you share screenshots from your apps and show where the exceptions are happening? You can send them to kszostak@microsoft.com 

I rolled back the release but one customer is still saying that he is experiencing this issue. I'm suspecting that there was some other change (outside of JS SDK) which might have caused the issue (for instance an external javascript library was updated which is also loaded on the page and interfering with JS SDK). 

Thank you!
