### ISSUE TITLE
Problems using frontend in webapages with applicationinsights

### ISSUE THREAD

**Issue by filipetoniolo** [Microsoft/ApplicationInsights-JS#512]
I have this problem in using application insights, the same started yesterday 08/29/2017, I already identified that occurs in the application frontend in the use of the script that is inserted in the masterpage.

var appInsights = window.appInsights || Function (config) {function r (config) {t [config] = function () {var i = arguments; (S) = sv = sv = sv = sv = sv = svv = svv = svv = svv = svv = U.createElement (o), i, f; For (s.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", u.getElementsByTagName (o) [0] .parentNode.appendChild (s), T.cookie = u.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace" I.pop ()); Return r ("setAuthenticatedUserContext"), r ("clearAuthenticatedUserContext"), config.disableExceptionTracking || (Config, r, u, e, o) {var s = f && f (config, r, u, R, u, e, o), return s! ==! 0 && t ["_" + i] (config, r, u, = Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.InstrumentationKey%> "}); Window.appInsights = appInsights; AppInsights.trackPageView ();

error: Unhandled exception at line 2, column 3681 in http://az416426.vo.msecnd.net/scripts/a/ai.0.js 0x800a138f - JavaScript runtime error: Can not get the 'apply' property of an undefined or null reference.

Is someone having this problem or has it already had the same problem?

Thank you!

**Comment by KamilSzostak** [comment]
Thank you for reporting this. I'm investigating.
