### ISSUE TITLE
AppInsightsModule.js is blocking my ability to run the Jest test. "defined is not defined" error

### ISSUE THREAD

**Issue by anigogate** [Microsoft/ApplicationInsights-JS#518]
Hi,

"I am trying to set up jest for my application built using React. I am using ApplicationInsights-js however, whenever I try to run my tests, I keep getting "define is undefined" on any of my tests using components that import ApplicationInsights."

This seems to be same issue as [476](https://github.com/Microsoft/ApplicationInsights-JS/issues/476) Seems it got closed in 1.0.10 but I am facing it in 1.0.12 again.

Error:

    Test suite failed to run

    ReferenceError: define is not defined

      at Object.<anonymous> (node_modules/applicationinsights-js/bundle/ai.module.js:178:1)

**Comment by OR13** [comment]
Same issue, I happen to be using TypeScript with Jest as well.

**Comment by anigogate** [comment]
Yup, I am using typescript too.

**Comment by KamilSzostak** [comment]
Thanks for reporting. I reopened the original issue: #476.
