### ISSUE TITLE
The SDK should handle cookies correctly when user is switching between secure and insecure connection (HTTPS -> HTTP)

### ISSUE THREAD

**Issue by mjcarrabine** [microsoft/ApplicationInsights-JS#524]
We deployed a new app to production on  Monday, and the Application Insights reports are showing we have 350 unique users when in fact we have 5. Our users are using Chrome. It appears that userid is not being persisted between pageviews.

We can reproduce this bug in a new web project as follows.:

###  Steps to Reproduce:

- In VS 2017 update 3, create a new ASP.NET WEb Applicatoni (.NET Framework) project with MVC
- Right-click on project and Configure Application Insights
- Update SDK from v2.2.0 to v2.4.1
- Register a new Application Insights Resource
- Start debugging the app
- Click through 4 pages in Edge (14.14393)
- Click through 4 pages in Chrome (61.0)
- Open Application Insights Analytics and run 
`pageViews
| limit 1000 `

### Expected Behavior:

8 rows, with:
- the 4 from Edge have the same UserId
- the 4 from Chrome have the same UserId

Application Insights Reports will then show 2 unique users.

### Observed Behavior:

8 rows, with:
- the 4 from Edge have the same UserId
**- the 4 from Chrome each have a unique UserId**

**Application Insights Reports will then show 5 unique users.**

**Comment by KamilSzostak** [comment]
I'm unable to repro. The SDK stores a userId in an 'ai_user' cookie. Could you confirm that the cookie is set in the browser? If it is, the same value will be used for all pageviews. 

![image](https://user-images.githubusercontent.com/12164228/30981142-3d75da66-a438-11e7-9594-15f7ca76439d.png)

![image](https://user-images.githubusercontent.com/12164228/30981097-1f66745e-a438-11e7-9cb4-1059c9f3dbb6.png)

**Comment by mjcarrabine** [comment]
Thank you for getting back to me so quickly. It looks like my issue is being caused by [Strict Secure Cookies](https://www.chromestatus.com/feature/4506322921848832), a feature enabled by default in Chrome 58. You should now be able to reproduce it by switching from secure connection to a non-secure connection.

Workarounds to this issue appear to be clearing cookies or only accessing the site over a secure connection.

In the steps to reproduce, if you first enable SSL and click through the pages in Chrome, then the cookies for ai_authUser, ai_session, and ai_user are created as secure, and the correct data is sent to App Insights. 
![image](https://user-images.githubusercontent.com/7231551/30993465-2803a16e-a47d-11e7-9a3d-d8dac5b104b2.png)

If you stop debugging, these 3 cookies are still there; however, you can see they are secure.
![image](https://user-images.githubusercontent.com/7231551/30993797-9ddd019a-a47e-11e7-8580-ea0b8e94505a.png)

If you now disable SSL, and click through the pages in Chrome, the 3 secure cookies are not visible because they are secure cookies now being accessed by insecure origins. The result is that Util.setCookie silently fails to set these 3 cookies, and the data sent to App Insights has a new unique ai.user.id on each page view.
![image](https://user-images.githubusercontent.com/7231551/30993670-09f9eeca-a47e-11e7-8610-534580c01c70.png)

**Comment by KamilSzostak** [comment]
Thank you for providing repro steps and explaining what is causing the issue. 

To fix this we will need to make a change to the SDK. It should check if it can set a cookie, and instead of failing silently it should delete the secure cookie and create an insecure cookie for not secure connection.

**Comment by MSNev** [comment]
Closing this issue as switching between secure and insecure is not a supported pattern especially with the coming cookie changes in chrome 80 where secure cookies will be required to have samesite.
