### ISSUE TITLE
add bower.json for bower package managment

### ISSUE THREAD

**Issue by tedvanderveen** [Microsoft/ApplicationInsights-JS#53]

**Comment by olegsych** [comment]
Thanks for the suggestion, @tedvanderveen. Could you describe how you'd want bower support to work in _your scenarios_?

**Comment by tedvanderveen** [comment]
We use bower for package/dependency/version/build management, locate .min file and other goodies.
Alternatively a package.json file would be good for NPM support. Nuget support is nive offcourse, but not everyone is on Visual Studio and many depend on other build/compile tools like Grunt/Guld.

**Comment by MaxShehovtsov** [comment]
@tedvanderveen Just to make sure I understand you - you want to install the whole SDK with bower and deploy it to prod - instead of letting users download it with every request from our CDN. Is that correct? Is CDN load time a concern or are you working on not web application?

**Comment by tedvanderveen** [comment]
@MaxShehovtsov yes. In our build process we use https://github.com/OverZealous/gulp-cdnizer to rewtite resouces of any applicable depenency to it's CDN hosted location inclusing the correct version etc. For that also we depend on a bower/npm depenency package version.
This is a quite common scenario actually.

**Comment by tedvanderveen** [comment]
@olegsych @maxshehovtsov what is your take on this? Do you agree that NPM support is more than an 'enhancement' to any developer that does / cannot not depend on Nuget support only?

**Comment by MaxShehovtsov** [comment]
This is definitely a valid ask. Would it be enough to publish on bower the same contents we have in nuget? (i.e. snippet + the minified and non minified javascripts)

**Comment by MaxShehovtsov** [comment]
@tedvanderveen This is definitely a valid ask. I'm currently investigating what it'll take, hopefully will be able to publish sometime soon. Thanks!

**Comment by MaxShehovtsov** [comment]
TODO/questions:
1) use Semver git tag - will "v0.16.20150806.0" work or we need 3 digit? Will 20150806 be ok as 3rd digit?
2) create a package.json (should be straightforward without specifying sources/dev dependencies)
3) create a folder like "dist" and put ai.js and ai.min.js there (and update our team instructions to keep it updated or get an automation)
4) publish (obviously) 
Am I missing anything?

**Comment by olegsych** [comment]
Date as patch version number does not meet requirements 2, 6 and 7 of the [semver](http://semver.org) specification.

**Comment by tedvanderveen** [comment]
@maxshehovtso regarding todo 2) you should actually supply devDependencies in the package.json to specify the test libs you depend on. See also http://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

**Comment by tedvanderveen** [comment]
Maybe get in touch on this with your collegues working on https://github.com/AzureAD/azure-activedirectory-library-for-js

**Comment by MaxShehovtsov** [comment]
@tedvanderveen  I've created very basic bower.json - we definitely need to fix it with right versioning/authors, etc. However I'm not sure we need dev dependencies - as our compilation relies on msbuild which I believe doesn't exist on bower. So my proposal is to incrementally get to desired state base on your and other folks' feedback. 
For now bower install ApplicationInsights-JS should give you sources along with "dist" folder which is the main thing you need.

**Comment by MaxShehovtsov** [comment]
@tedvanderveen Also recently published on npm
