### ISSUE TITLE
Exclude spammy remote dependencies by default

### ISSUE THREAD

**Issue by jakenuts** [Microsoft/ApplicationInsights-JS#531]
The server side SDK includes a default filter for "bot" traffic, the javascript SDK should also have some easy way to say "I don't care about the user's 10 browser extensions that generate 10 network requests on every page view".. It's incredibly noisy, hush.

**Comment by KamilSzostak** [comment]
Could you provide names of those extensions and sample events which the SDK logged? 

I'm not sure if the SDK should have any filtering logic for browser extensions. You can create a telemetry initializer function to exclude those events - see ["How do I exclude parts of telemetry from sending?"](https://github.com/Microsoft/ApplicationInsights-JS/wiki/FAQ#how-do-i-exclude-parts-of-telemetry-from-sending)
