### ISSUE TITLE
DataSanitizer.MAX_URL_LENGTH does not exceed 1024 characters

### ISSUE THREAD

**Issue by 1antares1** [Microsoft/ApplicationInsights-JS#532]
I was denoting that **ai.js** has set lengths to trim the lengths of the properties when I invoke: **trackTrace();** method: 
```javascript                   
                   /**
                    * Max length allowed for custom names.
                    */
                    DataSanitizer.MAX_NAME_LENGTH = 150;
                    /**
                     * Max length allowed for custom values.
                     */
                    DataSanitizer.MAX_STRING_LENGTH = 1024;
                    /**
                     * Max length allowed for url.
                     */
                    DataSanitizer.MAX_URL_LENGTH = 2048;
                    /**
                     * Max length allowed for messages.
                     */
                    DataSanitizer.MAX_MESSAGE_LENGTH = 32768;
                    /**
                     * Max length allowed for exceptions.
                     */
                    DataSanitizer.MAX_EXCEPTION_LENGTH = 32768;
                    return DataSanitizer;
```

Is it possible to extend this lenght limit? Init config-way or recommendation on the framework to avoid not truncating the payload properties.

I tried to triple the lengths in _"debug mode"_ and the request wasn't rejected.

Thank you for your help.
![ai_tracktrace-method_truncated](https://user-images.githubusercontent.com/14783925/31393832-088171f6-adb3-11e7-9185-252b080dcd38.png)

**Comment by KamilSzostak** [comment]
Those limits are set to match the schema, e.g. [EventData.bond](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/EventData.bond). The SDK doesn't allow to change these limits because the AppInsights backend will reject any event which doesn't match the schema (e.g. if a name is longer than 150 chars).
