### ISSUE TITLE
Report column number in parsed stack

### ISSUE THREAD

**Issue by defr0zen** [Microsoft/ApplicationInsights-JS#533]
Modern browsers report column numbers in exception stack traces. This information is essential in mapping minified JS code back to its original version.
Why shouldn't AppInsights JS SDK parse column number together with line number?

**Comment by markwolff** [comment]
hey @defr0zen are you or anyone else still experiencing this issue? If so, please reopen this issue. Also, when you saw the problem, was other information being reported as well (line number, error info, etc)?
