### ISSUE TITLE
How to set cloud_rolename to monitor multi role apps.

### ISSUE THREAD

**Issue by BennyM** [Microsoft/ApplicationInsights-JS#541]
I have the same angular frontend deployed several times with different AppServices. I want to be able to distinguish them as each connects to a single AppService using the approach mentioned here: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-multi-role-apps.

So I assume I need to set the cloud_rolename clientside as well but I can't seem to find any reference on how to do this. My AppServices already show up using the cloud rolename.

**Comment by KamilSzostak** [comment]
To set a customer `cloud_rolename` you need to write a [telemetryInitializer](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#addtelemetryinitializer) function and set an `ai.device.roleName` tag on each envelope. 

For a full list of tags check [ContextTagKeys.ts](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK.Interfaces/Contracts/Generated/ContextTagKeys.ts).

**Comment by BennyM** [comment]
Thank you.

I've edited my code as such:
```
            AppInsights.queue.push(() => {
                AppInsights.context.addTelemetryInitializer((envelope: Microsoft.ApplicationInsights.IEnvelope) => {
                    const telemetryItem = envelope.data.baseData;
                    envelope.tags['ai.device.roleName'] = "MyClientApp";
                });
            });
```

When analysing the page views I can now select the filter 'Cloud role name' which matches 'MyClientApp'.

And I know this is probably not the place for it :) but the application does not show up in the Application Map overview.

**Comment by KamilSzostak** [comment]
I'm glad to hear that it's working. Sorry, I can't help with the App Map, could you ask this question in the MSDN forum - https://social.msdn.microsoft.com/Forums/en-US/home?forum=ApplicationInsights, thanks!

**Comment by BennyM** [comment]
Ok thanks for all the info, I've created a [question on the MSDN](https://social.msdn.microsoft.com/Forums/en-US/854ff4fa-146a-401a-9eab-2c7b6d3b66e1/setting-cloud-role-name-in-clientside-javascript-does-not-affect-application-map?forum=ApplicationInsights) forum.

**Comment by lamuertepeluda** [comment]
This seems no longer valid! :(

**Comment by avs099** [comment]
as per this issue https://github.com/microsoft/ApplicationInsights-JS/issues/523#issuecomment-333035326, the tag we should use is `ai.cloud.role`
