### ISSUE TITLE
What is the correct tracking code snippet to use?

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/ApplicationInsights-JS#546]
Option 1, suggested by the Azure Portal "Client side telemetry" QuickStart page:
```html
<script type="text/javascript">
  var appInsights=window.appInsights||function(config){
    function i(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s="AuthenticatedUserContext",h="start",c="stop",l="Track",a=l+"Event",v=l+"Page",y=u.createElement(o),r,f;y.src=config.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js";u.getElementsByTagName(o)[0].parentNode.appendChild(y);try{t.cookie=u.cookie}catch(p){}for(t.queue=[],t.version="1.0",r=["Event","Exception","Metric","PageView","Trace","Dependency"];r.length;)i("track"+r.pop());return i("set"+s),i("clear"+s),i(h+a),i(c+a),i(h+v),i(c+v),i("flush"),config.disableExceptionTracking||(r="onerror",i("_"+r),f=e[r],e[r]=function(config,i,u,e,o){var s=f&&f(config,i,u,e,o);return s!==!0&&t["_"+r](config,i,u,e,o),s}),t
    }({
        instrumentationKey:"INSTRUMENTATION_KEY"
    });
    window.appInsights=appInsights;
    appInsights.trackPageView();
</script>
```

Option 2:
https://github.com/Microsoft/ApplicationInsights-JS/blob/master/snippet/snippet.html

Option 3:
https://github.com/Microsoft/ApplicationInsights-JS#use-js-snippet-and-initialize-dynamically-download-full-application-insights-script-from-cdn

Note that in Google Analytics, I can always go to my admin page, click "Tracking Info" and immediately get the undisputed, most up to date tracking code for my site. By contrast, I don't think it's even possible to get to the "Client side telemetry" QuickStart pane in the Application Insights Azure Portal pane (for option 1 above) once it's already initialized and operational. At least I couldn't figure out how (barring possible trickery with the URL).

**Comment by xt0rted** [comment]
You can get the tracking code in the portal by going to Configure > Get Started

![image](https://user-images.githubusercontent.com/831974/32659504-14e9f362-c5ed-11e7-91c6-c3392a0f486e.png)

**Comment by jeffwilcox** [comment]
It does seem to me that in some of the app types, the getting started pane does not show the telemetry snippet. If you create an ASP.NET type of app insights instance, though, it does.

**Comment by ohadschn** [comment]
so I take it the "Getting Started" snippet is the canonical one to use?

BTW I have an ASP.NET AI instance and I don't have this pane:
![image](https://user-images.githubusercontent.com/8555641/32668991-c946864a-c647-11e7-91a9-ae13e2ddd209.png)

**Comment by TobiasXy** [comment]
It seems I have the same problem.

If I have a PHP web app (with HTML/JS frontend) and a "General" type Application Insight instance for it. For the backend code I use the corresponding [PHP SDK](https://github.com/Microsoft/ApplicationInsights-PHP), but for the frontend there seems to be no way to get the snippet from within the Azure portal.
That makes it look like Javascript is not supported if you don't use an ASP.NET backend. But that is not the case, right? Should I just take the snippet posted above and insert my instrumentation key?

**Comment by xt0rted** [comment]
While playing with a new asp.net core project I found that the JS snippet is included with the asp.net core SDK for easy inclusion. The snippet they're using is https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/3b146b54fa3f01d9662039ce6ebbbf2d12a20050/src/Microsoft.ApplicationInsights.AspNetCore/Resources.resx#L124-L135 which seems to match up the the snippet above, and what shows up in the portal depending on your setup.

**Comment by ohadschn** [comment]
The ASP.NET template snippet is indeed the same as the one in the portal (option 1 above), but it is not the same as the one in the README (at least not according to KDiff, it might be equivalent JavaScript).

**Comment by KamilSzostak** [comment]
The https://github.com/Microsoft/ApplicationInsights-JS/blob/master/snippet/snippet.html is the most current snippet. I'll update other places to keep the snippet code in sync.

**Comment by KamilSzostak** [comment]
I also updated the Getting started page, changes will be reflected mid next week.
