### ISSUE TITLE
convert the ikey part to lowercase in Telemetry name

### ISSUE THREAD

**Issue by XiaoliangHuang** [Microsoft/ApplicationInsights-JS#547]
# Issue:

in the backend sdk, the telemetry name sending out will convert the ikey part to lowercase, but the fronend java script will not. 

# Impacts:

1. then there will be some inconsistent if both frontend/backend are uses.

2. and for microsoft internal users, who sending data to Xpert, this difference will causing the creation of 2 different source node, one is in lowercase, and another is not.

# Fix
Add  tolower case in file
```
\ApplicationInsights-JS\JavaScript\JavaScriptSDK\TelemetryContext.ts, line 205
```
``` JS
if (!doNotSendItem) {
    this._fixDepricatedValues(envelope);

    if (envelope.name === Telemetry.Metric.envelopeType ||
        this.sample.isSampledIn(envelope)) {
       // Add toLowerCase() in this line
        var iKeyNoDashes = this._config.instrumentationKey().replace(/-/g, "").toLowerCase(); 
        envelope.name = envelope.name.replace("{0}", iKeyNoDashes);
        this._sender.send(envelope);
    } else {
        _InternalLogging.throwInternal(LoggingSeverity.WARNING, _InternalMessageId.TelemetrySampledAndNotSent,
            "Telemetry is sampled and not sent to the AI service.", { SampleRate: this.sample.sampleRate }, true);
    }
}
```

**Comment by KamilSzostak** [comment]
Could you send a pull request with the proposed fix?

**Comment by jpiyali** [comment]
@XiaoliangHuang, please reactivate if this is still required.
