### ISSUE TITLE
NativeScript implementation

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/ApplicationInsights-JS#548]
Hi guys,
Exist any implementation with NativeScript-Angular?

Thanks in advance

**Comment by KamilSzostak** [comment]
For mobile apps, I recommend using [HockeyApp](https://hockeyapp.net/).

**Comment by jdnichollsc** [comment]
ohh ok, thanks for the suggestion! HockeyApp or AppCenter 👍
