### ISSUE TITLE
ApplicationInsights-JS With ReactJS

### ISSUE THREAD

**Issue by ifflanb** [Microsoft/ApplicationInsights-JS#549]
Hi. I am trying to use this in my ReactJS application. I have a couple of questions:
1) Where should I put AppInsights.downloadAndSetup? Is there somewhere global that I can set it once?
2) I can get exception to log to App Insights if I use **AppInsights.trackException**, but if I just throw a JS exception like this throw new Error(), the exception is not logged (e.g. the auto-catching of exceptions is not working.

**Comment by KamilSzostak** [comment]
Please check []this blog post](https://blogs.msdn.microsoft.com/premier_developer/2017/05/11/add-application-insights-to-an-angular-spa/). It shows how to integrate the JS SDK with Angular, but the same approach applies to ReactJS.

**Comment by KamilSzostak** [comment]
Closing, please re-open if you're still experiencing the issue or have more questions. Thanks!
