### ISSUE TITLE
How to control automatic injection?

### ISSUE THREAD

**Issue by NoahStahl** [microsoft/ApplicationInsights-JS#555]
Both Visual Studio and Azure App Services extensions for AI apparently inject the script snippet automatically. How can I disable this and include the script statically as shown in the readme? Currently doing that results in the snippet on the page twice resulting in duplicate page view calls.

(ASP.NET Core 2.0, VS 2017 15.5, Azure App Service AI extension 2.4.6)

**Comment by SergeyKanzhelev** [comment]
@cijothomas please help here

**Comment by SergeyKanzhelev** [comment]
@KamilSzostak, @YuliaSafarova I thought double inclusion should not send two pageViews? I believe you did it for Azure Web Apps scenarios. Is it not the case?

**Comment by NoahStahl** [comment]
(I also started a [StackOverflow question](https://stackoverflow.com/questions/47681778/controlling-application-insights-javascript-injection) before I found this repo)

**Comment by KamilSzostak** [comment]
Yes, pageview events shouldn't be duplicated. Are you using the latest snippet from the [README](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/README.md#use-js-snippet-and-initialize-dynamically-download-full-application-insights-script-from-cdn) file?

**Comment by NoahStahl** [comment]
I switched over to relying on the environment to inject the script (Visual Studio locally and Azure App Service extension), because I never found a way to stop it. If I find that to be configurable, I may revisit.
