### ISSUE TITLE
Pageviewload time is same for all the page.

### ISSUE THREAD

**Issue by sibaj** [Microsoft/ApplicationInsights-JS#557]
I am calling trackpageview from different page(components) in angular 4 application. Pageviewload time is same for all the page. should I use startTrackPage. Will it help me to measure my page load time??

**Comment by KamilSzostak** [comment]
`trackPageView` will only measure a PLT when the whole page is loaded. If you're using Angular, I assume you have an SPA app, please use `startTrackPage` and `stopTrackPage` to indicate when the page navigation is happening.

**Comment by KamilSzostak** [comment]
Closing, please re-open if you have more questions.
