### ISSUE TITLE
Android 7.0 Being listed as Linux in Telemetry collection

### ISSUE THREAD

**Issue by isaac2004** [Microsoft/ApplicationInsights-JS#558]
I am testing some telemetry collection using mobile and client_OS is being listed as Linux. Should it not say Android?

**Comment by SergeyKanzhelev** [comment]
@acearun you had plans to improve OS detection logic. Any ETA's on this?

@isaac2004 do you by chance know what user agent your device sends?

**Comment by isaac2004** [comment]
@SergeyKanzhelev what field is agent? Is it on a particular content type? I can query analytics to get it.

**Comment by SergeyKanzhelev** [comment]
No, we do not store user agent in our backend. This is why I'm asking if you by chance can get this value some other way. Maybe visit http://www.useragentstring.com or something similar from the same browser

**Comment by isaac2004** [comment]
No worries, I just remote connected to my phone to get it.

> User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Safari/537.36

**Comment by SergeyKanzhelev** [comment]
It seems that this user agent string doesn't carry any information to say it's an Android. Maybe it's intentionally made in Chrome. Perhaps some logic can be implemented in JavaScript to make os detection more precise. Something like described [here](https://stackoverflow.com/questions/9514179/how-to-find-the-operating-system-version-using-javascript).

You can implement it yourself. Similar to how you can add [network properties](http://apmtips.com/blog/2017/10/30/use-network-information-api-with-application-insights/). Just implement a telemetry initializer and populate the client OS version yourself.

I understand you'd prefer it to be part of SDK. I'd let @acearun and @KamilSzostak comment on whether it should be implemented natively.

**Comment by isaac2004** [comment]
So what is bizarre here is that this UA does not match what Google says
https://developer.chrome.com/multidevice/user-agent

![image](https://user-images.githubusercontent.com/8878502/34266964-2109fcec-e649-11e7-94c1-db9546cdeec5.png)

**Comment by KamilSzostak** [comment]
Currently, the OS detection is only happening on the backend side (not in JS SDK) and AFAIK it's only based on the user agent string. 

We may increase the accuracy by adding `window.navigator.platform` ([details](https://www.w3.org/TR/html5/webappapis.html#dom-navigatorid-platform)) to each event. @SergeyKanzhelev would `ai.device.oemName` tag be a good place o store this OS info? The only drawback is that this will increase the size of each telemetry event.

**Comment by SergeyKanzhelev** [comment]
`oemName` is not the proper field for `window.navigator.platform`. I was suggesting to implement client side OS detection. Looking at possible values in standard - perhaps we can use platform as OS name? And fall back to user agent  to OS conversion when platform returned empty string?

**Comment by OsvaldoRosado** [comment]
I'm not sure `window.navigator.platform` is particularly useful in some cases. For example, in Edge I get returned `Win32` - which would cause us to lose the entire OS version (and says the wrong number of bits!)

Note that user agent instead reports `Windows NT 10.0; Win64; x64`. It looks like that field is held in `window.navigator.appVersion`, but it's almost exactly the same as the entire user agent string so it would need parsing logic to handle.

**Comment by isaac2004** [comment]
@markwolff is this closed because it is fixed?

**Comment by jpiyali** [comment]
@isaac2004  - we will not add this functionality in SDK as it would increase sdk size and possibly not be still 100% correct based on response from Osvaldo for other OS. Please try the workaround Sergey suggested above (using addTelemetryInitializer) if it solves for target platforms for your product.

**Comment by isaac2004** [comment]
@jpiyali fair enough. Thanks for the quick response
