### ISSUE TITLE
Duplicate custom events for IE and Edge

### ISSUE THREAD

**Issue by madhavpatel6** [Microsoft/ApplicationInsights-JS#560]
I am currently using App Insights to track user clicks on a website (for example if the user uses the navigation bar as opposed to the buttons in the body of the webpage). For Internet Explorer and Microsoft Edge, I am receiving intermittent duplicate custom events (only on button clicks that perform a GET/POST). I can guarantee that the call to appInsights.trackEvent only occurs once. Is this a known bug, or do you have any suggestions on what I can do to fix this issue?

Thanks

**Comment by KamilSzostak** [comment]
This might be a side effect of session storage buffer feature, which is preventing events from being lost when a user is navigating between pages but may cause some duplication.

Could you disable it and check if this solved the problem? To disable the feature set 'enableSessionStorageBuffer: false' in the [config](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#config) object.
