### ISSUE TITLE
Application Insights no longer track dependencies entries from JS Client

### ISSUE THREAD

**Issue by sharmajnu** [Microsoft/ApplicationInsights-JS#562]
We are using application insight to track our angular application. Everything was working perfectly. But without doing any changes in the application we are not seeing any AJAX dependencies anymore. The last tracked dependency was on 5th September 2017. However all page views and exceptions that we were sending from JS app-insight api are still logged and displayed correctly. Is something changed in the app insight api?

I saw that we were having old app insight snippet and the new snippet is changed, I even put the new snippet in our page but the dependencies are still not working. This is the latest code snippet that I am using now.

```    <script type="text/javascript">
  var appInsights=window.appInsights||function(config){
    function i(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s="AuthenticatedUserContext",h="start",c="stop",l="Track",a=l+"Event",v=l+"Page",y=u.createElement(o),r,f;y.src=config.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js";u.getElementsByTagName(o)[0].parentNode.appendChild(y);try{t.cookie=u.cookie}catch(p){}for(t.queue=[],t.version="1.0",r=["Event","Exception","Metric","PageView","Trace","Dependency"];r.length;)i("track"+r.pop());return i("set"+s),i("clear"+s),i(h+a),i(c+a),i(h+v),i(c+v),i("flush"),config.disableExceptionTracking||(r="onerror",i("_"+r),f=e[r],e[r]=function(config,i,u,e,o){var s=f&&f(config,i,u,e,o);return s!==!0&&t["_"+r](config,i,u,e,o),s}),t
    }({
        instrumentationKey:"XXX" // Replaced the actual key with XXX the key for privacy reason
    });

    window.appInsights=appInsights;
    appInsights.trackPageView();
</script>
```
Is something changed in the application insight?

**Comment by ccrowhurstram** [comment]
I am experiencing the same problem (see screen shot below).

You can reproduce the problem very easily using my [AppInsightsDotNetDemo](https://github.com/ccrowhurstram/AppInsightsDotNetDemo/) git repo 
(checkout the branch [no-page-request-correlation](https://github.com/ccrowhurstram/AppInsightsDotNetDemo/tree/no-page-request-correlation))

![image](https://user-images.githubusercontent.com/8319020/43358769-be5a7ade-928e-11e8-8c54-5567355c2cde.png)

**Comment by ccrowhurstram** [comment]
Sorry I meant to post this comment to https://github.com/Microsoft/ApplicationInsights-JS/issues/574#issuecomment-408621227

**Comment by jpiyali** [comment]
@sharmajnu - please reply if this is still an issue with latest SDK version 1.0.20

**Comment by sharmajnu** [comment]
Works fine with latest version.
