### ISSUE TITLE
Windows OS cuts up string variables to 1024 letters

### ISSUE THREAD

**Issue by biosis21** [Microsoft/ApplicationInsights-JS#566]
Hi!
When I send data via trackEvent method and attribute **properties** contains array type of data you will see serealized as a string.
`{identifiers: ['1', '2', '3', ... , '5000' ]}` - I sent to the application insight library method
received `{identifiers: '1,2, 3, ... , 5000'}` - Track event sent to server
Windows platform cannot support this and browser tab is broken. I cannot do anything with my browser. Warning message is:
![screenshot_3 jpgss jpg](https://user-images.githubusercontent.com/6310176/35973577-a1874c38-0cde-11e8-83ea-bba8f660fafb.jpg)

**Comment by SergeyKanzhelev** [comment]
Yes. `sanitizeProperties` should sanitize values to [8192](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/EventData.bond#L19), not 1024 as it does today:
https://github.com/Microsoft/ApplicationInsights-JS/blob/cac7b363a7f59147adff510f698bc3f4943f2ab0/JavaScript/JavaScriptSDK/Telemetry/Common/DataSanitizer.ts#L70-L81

@jpiyali can you take a look?

**Comment by jpiyali** [comment]
sorry, missed this thread earlier, @SergeyKanzhelev - current max string length is 1024. Where is the 8192 definition coming from?
* Max length allowed for custom values.
*/
        private static MAX_STRING_LENGTH = 1024;

**Comment by SergeyKanzhelev** [comment]
I'm not sure where the current string limit comes from. Every field has it's own limit. For the custom property value - the limit is 8K.

**Comment by jpiyali** [comment]
Thanks @SergeyKanzhelev, I confirmed in collector that this should be 8k as well. @biosis21 - we'll fix this in the next release. I'll post a release date soon.

**Comment by jpiyali** [comment]
We are trying to push this fix out this week.

**Comment by jpiyali** [comment]
Fix released in 1.0.16. Closing issue.
