### ISSUE TITLE
Start tracking Referer urls for page views

### ISSUE THREAD

**Issue by acearun** [Microsoft/ApplicationInsights-JS#572]
This will allow apps owners to understand the sources of incoming traffic to their pages. Value in this field is similar to the ones in [HTTP referer header](https://en.wikipedia.org/wiki/HTTP_referer).

**Comment by OsvaldoRosado** [comment]
This could be really helpful. Would this be a new schema field? Or an automatically populated custom property when we autocollect PageViewData?

**Comment by acearun** [comment]
I would expect it to be a new auto-collected field in the page views schema. 

For other types like requests,  it would be nice to have optional (opt-in) support to collect this info as a custom property. This part is lower priority.

**Comment by markwolff** [comment]
Added in `2.0.0-rc1`
