### ISSUE TITLE
Issues with client side page view not linking up with server side telems

### ISSUE THREAD

**Issue by Tarig0** [microsoft/ApplicationInsights-JS#574]
Microsoft/ApplicationInsights-dotnet-server#826

Utilizing the snipet
```html
<script type="text/javascript">
    var appInsights=window.appInsights||function(a){
        function b(a){c[a]=function(){var b=arguments;c.queue.push(function(){c[a].apply(c,b)})}}var c={config:a},d=document,e=window;setTimeout(function(){var b=d.createElement("script");b.src=a.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js",d.getElementsByTagName("script")[0].parentNode.appendChild(b)});try{c.cookie=d.cookie}catch(a){}c.queue=[];for(var f=["Event","Exception","Metric","PageView","Trace","Dependency"];f.length;)b("track"+f.pop());if(b("setAuthenticatedUserContext"),b("clearAuthenticatedUserContext"),b("startTrackEvent"),b("stopTrackEvent"),b("startTrackPage"),b("stopTrackPage"),b("flush"),!a.disableExceptionTracking){f="onerror",b("_"+f);var g=e[f];e[f]=function(a,b,d,e,h){var i=g&&g(a,b,d,e,h);return!0!==i&&c["_"+f](a,b,d,e,h),i}}return c
    }({
        instrumentationKey: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
    });
    
    window.appInsights=appInsights,appInsights.queue&&0===appInsights.queue.length&&appInsights.trackPageView();
</script>
```

I am getting the following data with no dependencies 

![image](https://user-images.githubusercontent.com/4108180/36877797-fec5a0fa-1d89-11e8-992a-e1f022fe8663.png)

**Comment by MS-TimothyMothra** [comment]
@jpiyali 
It seems that there's a problem with client-side dependency telemetry not getting created. That process should be annotating requests to server-side with the necessary operation ids for correlation.

#562 might also be related.

**Comment by MS-TimothyMothra** [comment]
@jpiyali do you have any updates? Can you follow up with the customer, he was very good about responding. See [Microsoft/ApplicationInsights-dotnet-server#826](https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/826) for context

**Comment by jpiyali** [comment]
@Tarig0 - can you please check if you have any AI specific traces in your telemetry. Please run this query and let us know if any of the errors may look related to capturing dependency data in your app:

traces
| where timestamp >= ago(6h) and timestamp <= now()
| where sdkVersion contains "javascript"
| where message startswith "AI:" or message startswith "AI (Internal)"
| extend errorType = tostring(split(message, "\"")[0])
| summarize count() by errorType, bin(timestamp, 10min)

Also, to confirm, you do see dependency data (with operation_Id and parent_OperationId not as expected).

Thanks,
Piyali

**Comment by SergeyKanzhelev** [comment]
Also you can look at this [blog post](http://apmtips.com/blog/2017/05/11/page-view-and-telemetry-correlation/) that outlines different desired correlation scenarios.

**Comment by Tarig0** [comment]
No errors

The operation ids don't match

![image](https://user-images.githubusercontent.com/4108180/39150062-1804b3cc-470f-11e8-8ceb-d1903432d0ef.png)

**Comment by Tarig0** [comment]
Ah I think I see the disconnect. I'm looking for request-> pageview not pageview -> request.

**Comment by Tarig0** [comment]
@SergeyKanzhelev Is the script you use in your blog making a new request telemetry object and making that correlate with the pageView?

I'm having a hard time reading the code and applying it to what I have in my snippet.

**Comment by SergeyKanzhelev** [comment]
>//<== what is this string doing?

This line takes a `RequestTelemetry` object stored in `HttpContext` and uses it's `Id` to initialize `PageView`. Is it's asp.net core application - code will look a little bit differently.

**Comment by ccrowhurstram** [comment]
I am experiencing the same problem (see screen shot below).

You can reproduce the problem very easily using my [AppInsightsDotNetDemo](https://github.com/ccrowhurstram/AppInsightsDotNetDemo/) git repo 
(checkout the branch [no-page-request-correlation](https://github.com/ccrowhurstram/AppInsightsDotNetDemo/tree/no-page-request-correlation))

![image](https://user-images.githubusercontent.com/8319020/43358829-e669a38c-928f-11e8-81f0-d73532f6f385.png)

**Comment by rvanmaanen** [comment]
This issue has been open for well over a year. Found it because I'm also having this issue. Single ASP.NET Core application with Razor Pages.

Using NuGet package Microsoft.ApplicationInsights.AspNetCore version 2.8.2 and the JS snippet directly from the readme:

`    <script type="text/javascript">
        var sdkInstance = "appInsightsSDK"; window[sdkInstance] = "appInsights"; var aiName = window[sdkInstance], aisdk = window[aiName] || function (e) { function n(e) { t[e] = function () { var n = arguments; t.queue.push(function () { t[e].apply(t, n) }) } } var t = { config: e }; t.initialize = !0; var i = document, a = window; setTimeout(function () { var n = i.createElement("script"); n.src = e.url || "https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js", i.getElementsByTagName("script")[0].parentNode.appendChild(n) }); try { t.cookie = i.cookie } catch (e) { } t.queue = [], t.version = 2; for (var r = ["Event", "PageView", "Exception", "Trace", "DependencyData", "Metric", "PageViewPerformance"]; r.length;)n("track" + r.pop()); n("startTrackPage"), n("stopTrackPage"); var s = "Track" + r[0]; if (n("start" + s), n("stop" + s), n("addTelemetryInitializer"), n("setAuthenticatedUserContext"), n("clearAuthenticatedUserContext"), n("flush"), t.SeverityLevel = { Verbose: 0, Information: 1, Warning: 2, Error: 3, Critical: 4 }, !(!0 === e.disableExceptionTracking || e.extensionConfig && e.extensionConfig.ApplicationInsightsAnalytics && !0 === e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)) { n("_" + (r = "onerror")); var o = a[r]; a[r] = function (e, n, i, a, s) { var c = o && o(e, n, i, a, s); return !0 !== c && t["_" + r]({ message: e, url: n, lineNumber: i, columnNumber: a, error: s }), c }, e.autoExceptionInstrumented = !0 } return t }(
            {
                instrumentationKey: "",
                distributedTracingMode: 1, //AI=0, AI_AND_W3C=1, W3C=2
                autoTrackPageVisitTime: true
            }
        ); window[aiName] = aisdk, aisdk.queue && 0 === aisdk.queue.length && aisdk.trackPageView({});
    </script>`

Seeing the requests and dependencies, nicely correlated. Also seeing the pageviews, but they have different operation_Id values.

Any updates on this?

**Comment by aKzenT** [comment]
I also want to know this. Is this supposed to work out of the box or is there something you need to enable/write custom code for it?

**Comment by markwolff** [comment]
If your backend services are on a different origin than your frontend, you will need to add `enableCorsCorrelation: true` to your snippet configuration for your frontend. Otherwise, the required HTTP headers to perform correlation will not be passed from your frontend to your backends

**Comment by rvanmaanen** [comment]
I was testing a single app on localhost, but will try the cors setting.

**Comment by aKzenT** [comment]
@markwolff in my case it is all on the same domain as well and I can see the correlation headers being sent.

But again: is this scenario (page view being grouped together with server-side-request) supposed to work out of the box or does it require custom code?

**Comment by markwolff** [comment]
It should work OOB. Each pageview should be a separate operation, with every request being a child of the pageview.

**Comment by aKzenT** [comment]
It does work in my case for requests triggered from the page (e.g. via XHR), but it does not work for the initial server request that triggers the page view. Are you referring to the former or the latter?

**Comment by markwolff** [comment]
The former, I think the latter wouldn't work OOB. If I am understanding your scenario correctly, some operation already exists and is returning a page and that PageView doesn't correlate to the operation. This SDK makes the assumption that it is always the root of every operation, which obviously isn't the case here :)

To solve this, you would need to use the latest snippet (1.0.18 this won't be supported) and modify the trackPageView call in the snippet to include trackPageView({ id: "<parentId of operation>" }). We might not read from this field yet (it's currently only internally used), so if thats the case I'll need to update it to make that work here. Also you'll need to pass the parentId to the snippet somehow.

**Comment by aKzenT** [comment]
I think my scenario is fairly standard. I just have an ASP.NET Core web application running the server side application insights SDK and rendering more or less static webpages. These webpages run this client-side SDK.

I will try your solution and report back next week.

**Comment by matjanos** [comment]
Hi,

Not sure how about you guys, but for my case setting the
`enableCorsCorrelation: true`
in the frontend AI configuration pretty much solved the issue. 
It's not as perfect as I expected, but eventually I managed to correlate all PageViews and backend request/dependencies/traces in a one session. 

I would maybe expect all calls to be nested under the PageView element, but it still looks good.
![image](https://user-images.githubusercontent.com/2236369/73498082-8a371600-43bc-11ea-9ccf-3fa999e47070.png)
