### ISSUE TITLE
CustomEvents not sent when navigating

### ISSUE THREAD

**Issue by lukos** [Microsoft/ApplicationInsights-JS#577]
We have a site that needs to log lots of custom events from Javascript for actions that do not hit the MVC backend. However, most of these are not sent, despite calling trackEvent() and then immediately calling flush().

In the network tab of dev tools, when tracking the event, and then navigating away, I can see the track call as (canceled) and then the page navigates and the event is not logged in App Insights. Sometimes the events make it, other times they don't.

Various comments seem to say that flush is not synchronous to Azure, which seems a bit pointless, since that is the only time I would ever need to use flush. Also, why does the event onwindowunload not send the remainder of the queue to App Insights before navigating away?

**Comment by lukos** [comment]
Further info. It seems that if the call is fast enough, it succeeds but if it takes longer than about 500ms, it gets cancelled.

**Comment by jpiyali** [comment]
@lukos we do hook into the unonload event to try to send the items in queue asynchronously to avoid any user experience impact. This works to a certain degree  in most browsers except firefox. This is controlled by configuration disableFlushOnBeforeUnload (this defaults to false and hence we do try to hook up to onunload event to send.
