### ISSUE TITLE
Hardcoded "appInsights" prevents multiple JS clients

### ISSUE THREAD

**Issue by lukos** [Microsoft/ApplicationInsights-JS#578]
I have tried to create 2 telemetry clients for JS to send server data to one AI account and custom metrics to another (shared) AI account. I can't get it to work if I call it anything other than window.appInsights.

e.g. If I set window.appInsights to the page view one, that works but if I have another window.sharedAppInsights with a different key, it doesn't send anything (and doesn't error).

The culprit seems to be the hard-coded "appInsights" in Init.ts which is the only name that will cause initialisation to be carried out.

Ideally, the JS for app insights should not assume the name of a global variable set in user code. At very least, it should permit the name of the global to be specified in config when creating the client so that more than one client can be used.

I couldn't find another way to achieve this other than using one setup during page load and then overwriting window.appInsights in the method that sends custom events to use the second client.

**Comment by SergeyKanzhelev** [comment]
similar to https://github.com/Microsoft/ApplicationInsights-JS/issues/576

We have multi-client support on our roadmap. Would something similar to our node.js SDK work for you? In [node.js](https://github.com/Microsoft/ApplicationInsights-node.js) you can create multiple instances of `new appInsights.TelemetryClient()`.

**Comment by lukos** [comment]
OK, I'll close as duplicate. Yes, it would be useful to be completely OO so that we can either create `new TelemetryClient()` or have a factory method that injects all config and does not call back onto global variables, so that it can be called multiple times.
