### ISSUE TITLE
Api Reference: remove autoCollectErrors, add disableExceptionTracking

### ISSUE THREAD

**Issue by MaxShehovtsov** [Microsoft/ApplicationInsights-JS#59]
autoCollectErrors seems to not exist in the SDK, however the docs say that it controlls automatic exception tracking (which actually does not).
On other hand the disableExceptionTracking setting is the one that controls automatic exception collection, and it's not mentioned in the api reference.

**Comment by MaxShehovtsov** [comment]
The proposal is to replace autoCollectErrors with disableExceptionTracking in the API-reference

**Comment by SergeyKanzhelev** [comment]
Make sure to make it consistent with `autoTrackAjax`. Maybe it also requires renaming

**Comment by MaxShehovtsov** [comment]
RE 'autoTrackAjax', i think it's better to rename it to 'disableAjaxTracking' - @AlexBulankou @SergeyKanzhelev what do you guys think? That highlights the intention to collect ajaxes by default.

RE 'disableExceptionTracking' - i'd keep it as it because:
1) It's used in snippet, and we don't want to change the snippet
2) it's consistent with 'disableTelemetry'

**Comment by AlexBulankou** [comment]
I agree best to keep consistent with existing disableX. Thanks!
