### ISSUE TITLE
ReferenceError: s is not defined

### ISSUE THREAD

**Issue by ahhalder** [Microsoft/ApplicationInsights-JS#606]
Hi All,

I am implementing AppInsight in client side(javascript) for my web application.

I added below method in main.master.cs

 public string AddAppInsightScript()
    {
        string AnalyticsScript = string.Empty;
        bool enableAppInsight = false;
        enableAppInsight = (ConfigurationManager.AppSettings["EnableAppInsight"] ?? "false").ToLower() == "true";
        var instrumentationKey = ConfigurationManager.AppSettings["InstrumentationKey"];
        TelemetryConfiguration.Active.DisableTelemetry = !enableAppInsight;
        if (enableAppInsight && !string.IsNullOrEmpty(instrumentationKey))
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("<script type=\"text/javascript\">");
            sb.Append(" var appInsights=window.appInsights||function(a){");
            sb.Append(
                "function b(a){c[a]=function(){var b=arguments;c.queue.push(function(){c[a].apply(c,b)})}}var c={config:a},d=document,e=window;setTimeout(function(){");
            sb.Append("var b=d.createElement(\"script\");b.src=a.url||\"https://az416426.vo.msecnd.net/scripts/a/ai.0.js\",d.getElementsByTagName(\"script\")[0].parentNode.appendChild(b)});try{c.cookie=d.cookie}catch(a){}c.queue=[];for(var ");
            sb.Append("f=[\"Event\",\"Exception\",\"Metric\",\"PageView\",\"Trace\",\"Dependency\"];f.length;)b(\"track\"+f.pop());if(b(\"setAuthenticatedUserContext\"),b(\"clearAuthenticatedUserContext\")");
            sb.Append(" ,b(\"startTrackEvent\"),b(\"stopTrackEvent\"),b(\"startTrackPage\"),b(\"stopTrackPage\"),b(\"flush\"),!a.disableExceptionTracking){f=\"onerror\",b(\"_\"+f);var ");
            sb.Append("g=e[f];e[f]=function(a,b,d,e,h){var i=g&&g(a,b,d,e,h);return!0!==i&&c[\"_\"+f](a,b,d,e,h),i}}return c");
            sb.Append(" }({");
            sb.Append("instrumentationKey:\"");
            sb.Append(instrumentationKey);
            sb.Append("\" });");
            sb.Append("window.appInsights=appInsights,appInsights.queue&&0===appInsights.queue.length&&appInsights.trackPageView();");
            sb.Append("</script>");
            AnalyticsScript = sb.ToString();
        }
        return AnalyticsScript;
    }

Then calling this method in main.mater templete

<head id="PageHeader" runat="server">
    <%#AddAppInsightScript()%>
</head>

Now I am sending custom event from one of the myAnalytics.js file like below.

logEvent: function (origin,source,label) {
            var appInsights = window.appInsights;
            if (appInsights != null) {
                var appName = _$AppWindowRef.Session.AppName ? _$AppWindowRef.Session.AppName : "NA";
                var role = _$AppWindowRef.Session.role ? _$AppWindowRef.Session.role : "NA";
                appInsights.trackEvent(origin);
                appInsights.flush();
            }         
        },

But I get the exception as below in the method appInsight.trackEvent();
"ReferenceError: s is not defined
    at eval (eval at n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84032), <anonymous>:1:1)
    at Object.n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84032)
    at Object.logEvent (http://localhost/SaaS/scripts/logging/heat.analytics.js?t=20180522120516:129:29)
    at SaaS.WebUI.ObjectLayoutPanel.<anonymous> (http://localhost/SaaS/scripts/saas.webui/objectlayout/objectlayoutpanel.js?t=20180321090747:533:28)
    at EXTUTIL.Event.fire (http://localhost/SaaS/lib/ext-js-31/pkgs/ext-foundation-debug.js?t=20180321090641:2339:34)
    at Ext.Frs.ObjectViewToolbar.fireEvent (http://localhost/SaaS/lib/ext-js-31/pkgs/ext-foundation-debug.js?t=20180321090641:1983:31)
    at Ext.Frs.ObjectViewToolbar.<anonymous> (http://localhost/SaaS/scripts/ext.frs/objectviewtoolbar.js?t=20180321090742:464:53)
    at sb.onClick (http://localhost/SaaS/lib/ext-js-31/pkgs/pkg-buttons-debug.js?t=20180321090641:625:30)
    at HTMLTableElement.h (http://localhost/SaaS/lib/ext-js-31/pkgs/ext-foundation-debug.js?t=20180321090641:2768:16)"

Appreciate your help in this.

**Comment by ahhalder** [comment]
exception thrown in AppInsight.ts file method  below and in the line this.context.track(envelope);

 public trackEvent(name: string, properties?: Object, measurements?: Object) {
            try {
                var eventTelemetry = new Telemetry.Event(name, properties, measurements);
                var data = new ApplicationInsights.Telemetry.Common.Data<ApplicationInsights.Telemetry.Event>(Telemetry.Event.dataType, eventTelemetry);
                var envelope = new Telemetry.Common.Envelope(data, Telemetry.Event.envelopeType);
                this.context.track(envelope);
            } catch (e) {
                _InternalLogging.throwInternal(LoggingSeverity.CRITICAL,
                    _InternalMessageId.TrackEventFailed,
                    "trackEvent failed, event will not be collected: " + Util.getExceptionName(e),
                    { exception: Util.dump(e) });
            }
        }

**Comment by jpiyali** [comment]
Closing issue, no follow up received.

**Comment by jonicabrown** [comment]
I'm getting the same error; exception being caught and logged "internally" (according to the code, not sure what that means?); not showing up in the console.

appInsights is definitely defined with valid instrumentation key; standard telemetry showing up in Azure Portal.

I pared down my request to bare minimum and still getting it:
appInsights.trackEvent("sendXitiPage");

Stack trace:
-------------
message: "s is not defined"
stack: "ReferenceError: s is not defined↵    at eval (eval at n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84831), <anonymous>:1:1)↵    at Object.n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84831)↵    at Object.module.sendXitiPage (http://vue.racecentre.fep.local/Components/CommonServices/utils/general.js:305:21)↵    at b.$scope.fetchMessage (http://vue.racecentre.fep.local/Components/Curtain/Directive/curtain.js:23:37)↵    at controller (http://vue.racecentre.fep.local/Components/Curtain/Directive/curtain.js:92:20)↵    at Object.invoke (http://vue.racecentre.fep.local/ThirdParty/angular/angular.min.js:41:376)↵    at R.instance (http://vue.racecentre.fep.local/ThirdParty/angular/angular.min.js:89:399)↵    at m (http://vue.racecentre.fep.local/ThirdParty/angular/angular.min.js:65:65)↵    at http://vue.racecentre.fep.local/ThirdParty/angular/angular.min.js:76:459↵    at http://vue.racecentre.fep.local/ThirdParty/angular/angular.min.js:130:409"
__proto__: Error

![image](https://user-images.githubusercontent.com/36988370/46133366-93e8c080-c240-11e8-89e6-60b5a96d52a1.png)
