### ISSUE TITLE
Add performance.mark and performance.measure for performance browser tool integration

### ISSUE THREAD

**Issue by toddreifsteck** [microsoft/ApplicationInsights-JS#617]
Various performance tools for all major browsers including Edge and Chrome can display performance.mark and performance.measure data in the default tooling. In addition to this, the various native profilers used by the teams that build those browsers allow these events to be viewed.

I'm a performance expert working on the Microsoft Edge team. When working with teams that use AppInsights to measure their performance, we have found that those teams have to do additional work to add performance.mark/measure to their code.

In an ideal world, App Insights would emit these events allowing those websites to easily describe their start/end events that they'd like us to analyze.

**Comment by nolanlawson** [comment]
(I'm Todd's colleague on the Microsoft Edge team. 😃) At a minimum, it would be nice if performance.mark/performance.measure could be enabled via query parameter flags or some other mechanism. We rely on marks and measures when doing performance trace analysis.

**Comment by MSNev** [comment]
New extension created to provide this capability
https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-perfmarkmeasure-js

**Comment by MSNev** [comment]
Waiting for NPMJS Admins to create the new package name so we can publish, this will also be released as a self contained CDN downloadable component, which is a separate deployment than the NPM deployment

**Comment by MSNev** [comment]
# CDN Deployments
https://js.monitor.azure.com/beta/ext/ai.prfmm-mgr.2.7.0.min.js
https://js.monitor.azure.com/next/ext/ai.prfmm-mgr.2.7.0.min.js
https://js.monitor.azure.com/scripts/b/ext/ai.prfmm-mgr.2.7.0.min.js

## Primary version
Beta: https://js.monitor.azure.com/beta/ext/ai.prfmm-mgr.2.min.js
Next: https://js.monitor.azure.com/next/ext/ai.prfmm-mgr.2.min.js
Public (Mon, Sept 13th, 2021): https://js.monitor.azure.com/scripts/b/ext/ai.prfmm-mgr.2.min.js

**Comment by MSNev** [comment]
Now also published to NPM
https://www.npmjs.com/package/@microsoft/applicationinsights-perfmarkmeasure-js

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints
