### ISSUE TITLE
trackException not passing properties

### ISSUE THREAD

**Issue by gmaughan** [Microsoft/ApplicationInsights-JS#623]
When calling:

`AppInsights.trackException(error, 'notused', { 'action': 'mytestaction' } );`

The error is tracked, but the properties do not get passed through. The 'properties' element in the track call is always empty.

All other tracking works, including passing custom properties.

Using version 1.0.18 in an Angular 6 application.

**Comment by jpiyali** [comment]
@gmaughan - please check in fiddler if your envelop that is sent to dc.services.visualstudio.com have the properties set. this will confirm if the data is being sent to the ingestion endpoint.

We have exception tracking using same SDK version in other applications where properties element is captured.

**Comment by gmaughan** [comment]
This is my TypeScript code for emitting an error:

```javascript
    public emitError(error: Error, action?: string) {
        const properties: any = {};
        if (action) {
            properties['action'] = action;
        }
        AppInsights.trackException(error, 'notused', properties);
    }
```

If I call this with a non-null `action` then it still sends an empty `properties` element.

The JSON sent in the track call is as follows:

```json
[
  {
    "time":"2018-07-02T01:19:31.275Z",
    "iKey":"XXXXXXXX",
    "name":"Microsoft.ApplicationInsights.0a0b13c9b03f437bb8a829c19ec7bd11.Exception",
    "tags":{
      "ai.session.id":"AasUV",
      "ai.session.isFirst":"true",
      "ai.device.id":"browser",
      "ai.device.type":"Browser",
      "ai.internal.sdkVersion":"javascript:1.0.18",
      "ai.user.id":"j2ENT",
      "ai.operation.id":"ULGwn",
      "ai.operation.name":"/",
      "ai.cloud.role":"XXXX",
      "ai.cloud.roleInstance":"XXXXXX",
      "ai.application.ver":"1.0.0"
    },
    "data":{
      "baseType":"ExceptionData",
      "baseData":{
        "ver":2,
        "exceptions":[
          {
            "typeName":"Error",
            "message":"Communication Error 404 - OK ",
            "hasFullStack":true,
            "stack":"... removed for brevity...",
            "parsedStack":[
              "...removed for brevity..."
            ]
          }
        ],
        "properties":{

        }
      }
    }
  }
]
```
Is this an issue with how I'm constructing the properties object?

Thanks
Glenn.

**Comment by jpiyali** [comment]
@gmaughan  - thanks for confirming, so looks like properties is not being propagated at all. The object creation looks fine to me. Can you debug and check why properties are not being propagated? File AppInsights.ts has the method trackException().

**Comment by gmaughan** [comment]
I am unable to debug this. I'm using the npm package 'applicationinsights-js' and it has minified/bundled source files.

**Comment by markwolff** [comment]
Hi @gmaughan - I've been unable to repro your issue. It'd be great if you could provide any additional info, from console or otherwise, about this. Can you also try adding more than one custom property to your property bag and see if the problem persists. Please reopen once you have more info

**Comment by gmaughan** [comment]
Added one more custom property to the property bag. Still no properties sent with track request.

    const properties: { [key: string]: string } = {
        'dummy': 'dummy',
        'dummy2': 'dummy'
    };

    AppInsights.trackException(error, 'notused', properties);

Screenshot of request data from Chrome network tab:

![image](https://user-images.githubusercontent.com/936398/43691666-40630750-9963-11e8-924c-04a5dd11b58d.png)

Perhaps I'm miss-reading the output above where `properties` is `{}`. 

Glenn.

**Comment by gmaughan** [comment]
Found it. My telemetry initializer was resetting the properties. I had assumed that the two property bags, one from the initialiser and one from the trackException call, were merged. Now that I understand that they are the same bag I don't reset the properties in the initialiser, I just add additional properties.

Sorry for leading down the wrong path. Thanks for the help debugging!

Glenn.
