### ISSUE TITLE
Will ApplicationInsights-JS support "Request-Id" header for "fetch" method in client's CORS requests?

### ISSUE THREAD

**Issue by yuejiaozhs** [Microsoft/ApplicationInsights-JS#625]
Currently ApplicationInsights-JS only allow XHR to add correlation headers, which blocked some projects that using "fetch" and want to use AI's correlation feature. Will ApplicationInsights-JS support fetch in the future? ( #166 seems mentioned the same issue)

*attach CORS and correlation headers config used in this issue:
{
  disableCorrelationHeaders: false,
  enableCorsCorrelation: true
}

![image](https://user-images.githubusercontent.com/20440051/41833182-cfda1782-7881-11e8-8a87-17d2b349016c.png)

**Comment by jpiyali** [comment]
We have a new iteration of the sdk under works currently which will have the ability to use fetch for sending data as well.

**Comment by jpiyali** [comment]
#595

**Comment by yuejiaozhs** [comment]
wow, wonderful news, looking forward to new iteration.

**Comment by MaximBalaganskiy** [comment]
@yuejiaozhs judging by the answer it's planned to **use** fetch to send data. Not monitor fetch calls. Anyhow, while you're waiting
https://github.com/MaximBalaganskiy/application-insights-fetch-monitor

**Comment by SergeyKanzhelev** [comment]
Do you want to send PR into this repo?

**Comment by MaximBalaganskiy** [comment]
I will. I needed it yesterday hence a separate  project.

**Comment by SergeyKanzhelev** [comment]
Great

**Comment by FelschR** [comment]
I'm using `@microsoft/applicationinsights-web@1.0.0-beta.11` which seems to add the request-id for OPTIONS requests but not for the actual requests themselves.
This is my config:
```json5
config: {
    instrumentationKey: "--key--",
    disableFetchTracking: false,
    enableCorsCorrelation: true
}
```

**Comment by markwolff** [comment]
Hey @FelschR, it should be adding `request-id` to the list of `Access-Control-Request-Headers` in the OPTIONS call, and then fills in the `request-id` for the actual fetch. Is this different from what you are seeing?

The OPTONS call
![image](https://user-images.githubusercontent.com/5515583/53435347-74032780-39ad-11e9-9006-03b4d1585230.png)

The fetch
![image](https://user-images.githubusercontent.com/5515583/53435436-a6ad2000-39ad-11e9-90ab-9612f6fa0160.png)
