### ISSUE TITLE
ai_user cookie is not HttpOnly. 

### ISSUE THREAD

**Issue by jimmic** [Microsoft/ApplicationInsights-JS#626]
I know a property was added to disable the cookie but if you need the cookie then the cookie is still not HttpOnly. 

This issue was closed by doing the above https://github.com/Microsoft/ApplicationInsights-JS/issues/14 but doesn't really solve the issue.

**Comment by SergeyKanzhelev** [comment]
Making this cookie httponly defeats the purpose of the cookie. Doing so will not allow to associate user id with telemetry JS sdk produces.

Workaround would be to inject cookie value into the page html on server side. You can easily implement this work around if needed. Let me know if you need more details on how to do it.

**Comment by jimmic** [comment]
@SergeyKanzhelev Ok great thanks, yes if you could help me with a work around that would be great

**Comment by jimmic** [comment]
@SergeyKanzhelev Can I add the cookie from the server side and set `isCookieUseDisabled: true` ? Rather than using the context to get the user id?
