### ISSUE TITLE
Nodejs app insights occasionally shows 500 exception 

### ISSUE THREAD

**Issue by Kannaj** [Microsoft/ApplicationInsights-JS#627]
Hello,

I'm tring to use app insights in my nodejs app and see a couple of failed requests in azure. The thing is they dont seem to be associated necessarily with my code. I would love to know further about this.

Operation Name: GET Home/Index
severityLevel: 4
type: System.UnauthorizedAccessException
problemId: System.UnauthorizedAccessException at ASP._Page_Views_Home_Index_cshtml.Execute

please let me know if i need to provide further details. From the looks of it, it looks like theres something wrong with the local app insights profiler?

Thanks

**Comment by jpiyali** [comment]
Are you using the node SDK (https://github.com/Microsoft/ApplicationInsights-node.js)?

**Comment by Kannaj** [comment]
oops - sorry. reopened in the right repo
