### ISSUE TITLE
Aurelia-cli import issue

### ISSUE THREAD

**Issue by Zenuka** [Microsoft/ApplicationInsights-JS#629]
Hi,

We've been fiddling around for quite some time,how to get the latest version (1.0.18) working in Aurelia (using the aurelia-cli). I'm wondering; is there a reason the module (```bundle/ai.module.js```) is named ```define('JavaScriptSDK.Module/AppInsightsModule', ...)``` and not ```define('applicationinsights-js', ...)'```?
If we want Application Insights to be working we need the following to map everything together:
```define('applicationinsights-js', ['JavaScriptSDK.Module/AppInsightsModule'], function(ai) { return ai; });```
Maybe this is just a problem with Aurelia but if the name could be ```applicationinsights-js``` our problems would be fixed ;-)

**Comment by jpiyali** [comment]
@Zenuka  - it looks like the typescript compilation produced this define to include folder name JavascriptSDK.Module. Are you not able to use the define? What issue are you seeing?

**Comment by Zenuka** [comment]
When I use ```import { AppInsights } from "applicationinsights-js";``` requirejs looks for a module named ```'applicationinsights-js'``` and not ```'JavaScriptSDK.Module/AppInsightsModule'```. So when I try to use AppInsights it's null because it has no module ```'applicationinsights-js'``` defined.

**Comment by JontyMC** [comment]
Anyone got an answer to this?

**Comment by jpiyali** [comment]
Can you please try beta sdk version @Microsoft/applicationinsights-web and reply if that resolves the issue. Beta usage is on home page.
