### ISSUE TITLE
Adaptive Sampling in JS?

### ISSUE THREAD

**Issue by Ruud-cb** [Microsoft/ApplicationInsights-JS#630]
Hi,
I have a ASP.NET Core app which I finally found out how to disable / exclude items from adaptive sampling. (Side note: The UI in Azure only displays details for ASP.NET Framework projects containing applicationinsights.config).

Now I am wondering how to manage/disable adaptive sampling in the front-end, with this library. To my knowledge, I need to exclude Events and PageViews from being sampled. I manually add page views like so:

```
import { AppInsights } from "applicationinsights-js";
....
 AppInsights.trackPageView("page");
```
reason: SPA application, no real page refresh so it is not tracked when I don't do it manually.

So how do I exclude these page views (and also trace logs please) from adaptive sampling? Or how do I disable it all together?

Thanks!

**Comment by rand0me** [comment]
@Ruud-cb I think I couldn't understand you. Can you please clarify what you mean by "sampling"?

**Comment by markwolff** [comment]
@Ruud-cb - Here is a relevant docs page:
41174d3cf1d64d16e90779ea4f17c7f219b9afe2

**Comment by markwolff** [comment]
@Ruud-cb - Here is a relevant docs page:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-sampling#sampling-and-the-javascript-sdk
@Dmitry-Matveev is there a way to disable certain telemetry types from being sampled? As far as I know, the JS SDK does not support adaptive sampling, it is left to back end (.NET only). Although it may handle it as referenced in linked doc

**Comment by Dmitry-Matveev** [comment]
JS SDK only has `samplingPercentage` setting on `config`. You cannot exclude specific types from sampling via configuration in JS SDK, at least that's what I see in the code [here](https://github.com/Microsoft/ApplicationInsights-JS/blob/e1c1c6aead4f7f218a8ecc81a1354ee7f9f0c571/ApplicationInsights/JavaScriptSDK/TelemetryContext.ts#L208), it simply excludes metrics from sampling but seems to sample everything else.

I can think of a workaround - implement [Telemetry Initializer](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#addtelemetryinitializer) and set sampleRate to 100 for the telemetry types you'd like to exclude from sampling.

**Comment by markwolff** [comment]
@Dmitry-Matveev thanks for the reply. If js sdk is set up with same iKey as .NET sdk will it obey the `<IncludeTypes>` and `<ExcludeTypes>` specified in server-side, similar to how it matches the "users" to sample in (doc ref quoted below)?

> The client-side (JavaScript) SDK participates in fixed-rate sampling in conjunction with the server-side SDK. The instrumented pages will only send client-side telemetry from the same users for which the server-side made its decision to "sample in."

**Comment by Dmitry-Matveev** [comment]
@markwolff , unfortunately, not, at least as per my knowledge. The outlined about users was true for a while due to the way hashing algorithm in sampling was implemented - it calculated the same hash for the same user ID value on JS side and on Server side. There was [a change](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/625) a while ago, however, to make server-side sampling rely on Operation Id hash but not User Id hash, which I think may affect the truthfulness of the statement you referenced.

**Comment by jpiyali** [comment]
Please refer to solution by @Dmitry-Matveev - implement Telemetry Initializer and set sampleRate to 100 for the telemetry types you'd like to exclude from sampling.
