### ISSUE TITLE
How to access Util.newId() in a typescript Angular 6 project

### ISSUE THREAD

**Issue by HopperTech** [Microsoft/ApplicationInsights-JS#633]
The trackDependency method documentation recommends using Util.newId(), but does not give any examples of how to access the Util class. Util does not appear to be declared in the ai.module.d.ts

Is there another means of including this within an Angular 6 service class?

thxs

**Comment by clementpuell** [comment]
Same problem here.

I worked around the problem by using this Typescript syntax to invoke the static `newId` method:
```typescript
let uniqueId = (<any>Microsoft.ApplicationInsights).Util.newId();
```

**Comment by markwolff** [comment]
This issue will be addressed in a future release. The workaround suggested by @clementpuell is correct, ie just workaround the compilation fail.

**Comment by markwolff** [comment]
`Util.newId()` is accessible as of release 1.0.19 https://github.com/Microsoft/ApplicationInsights-JS/releases/tag/1.0
