### ISSUE TITLE
Weird isArray check inside _serializeObject method

### ISSUE THREAD

**Issue by svr93** [microsoft/ApplicationInsights-JS#634]
Hi,
I have explored repository code and found potential problem:
```
var isArray = contract & FieldType.Array; // bitwise operator with "contract" variable as function
```
"contract" variable can be a function as value of "aiDataContract" object:
```ts
this.aiDataContract = {
  time: FieldType.Required,
  iKey: FieldType.Required,
  name: FieldType.Required,
  sampleRate: () => {
    return (this.sampleRate == 100) ? FieldType.Hidden : FieldType.Required;
  },
  tags: FieldType.Required,
  data: FieldType.Required
};
```

Commit: https://github.com/Microsoft/ApplicationInsights-JS/commit/20f15be50e86529bca36370fdf1917da40449816#diff-50448b6589765ffb1b061b78c42605d9R78

Is it works as intended?

Thanks!

**Comment by markwolff** [comment]
Intended
