### ISSUE TITLE
Allow the tracking cookies to operate across subdomains

### ISSUE THREAD

**Issue by logisticpeach** [Microsoft/ApplicationInsights-JS#64]
It would be useful to have the tracking cookies `ai` and `ai_user` visible on all subdomains for a given application. 

This would allow support for apps where the js based front end is served from one domain - say `www.example.com` and the back-end also collects telemetry and is served from, for example `api.example.com`.

Having browsed through the code, it looks like this isn't currently a supported scenario. Perhaps having this domain configurable would be a win.

**Comment by SergeyKanzhelev** [comment]
Yes, you are right - method [setCookie](https://github.com/Microsoft/ApplicationInsights-JS/blob/6bb5235fe65802fcfc422450d640a48f003489ab/JavaScript/JavaScriptSDK/Util.ts#L178) doesn't set domain explicitly. In your scenario would you prefer to set domain from config or just use the current? What if the first request hit subdomain like ```www.example.com``` and only after that it will go to ```example.com``` - would it be better to override user ID or not set it at all?

**Comment by logisticpeach** [comment]
I'd be happy to explicitly opt-in to this behaviour by setting the domain in config. Sorry, I'm not exactly sure what you mean about overriding the user id?

**Comment by SergeyKanzhelev** [comment]
I wasn't sure whether you can set cookie for ```example.com``` from ```www.example.com``` or ```sub1.sub2.example.com```. It seems that this is possible at least on modern browsers. In your scenario - do you use the same instrumentation key across sub domains? Do you envision using separate keys for any of your subdomains? Will you need to count users and detect new vs. returning users for that subdomain?

**Comment by logisticpeach** [comment]
I see what you're saying. In our specific example it's all one single application context so we do use the same user id and instrumentation key across subdomains. Simply having the cookie domain set to `.example.com` would solve our problem.

I guess there are potentially more complex scenarios where allowing a different "context" (instruumentation key, user id etc.) per subdomain could be extremely powerful and would suppport apps that intentionally want to isolate telemetry across components.

**Comment by AlexBulankou** [comment]
One more question about it. We should consider it especially since GA supports it. http://stackoverflow.com/questions/5671451/creating-a-javascript-cookie-on-a-domain-and-reading-it-across-sub-domains it can as easy as setting domain parameter when creating a cookie.

**Comment by jamesthurley** [comment]
I asked the recent SO question (http://stackoverflow.com/q/35275212/37725) about this and @AlexBulankou directed me to this GitHub issue.

For a solution I'd be happy either to opt-in with a config setting or to have it enabled by default.

In the mean time I think I could work around it by extracting the cookie information in javascript and adding it to my request headers, and then having a custom `TelemetryInitializer` on the back-end extract the information from the headers and add it to the `RequestTelemetry` object.  However if an update for this is likely to be released soon then I'd rather just wait :)

**Comment by MaxShehovtsov** [comment]
I believe the fix should be straightforward - this is the function that sets all our cookies, we could change it according to the solution on SO (Alex's link http://stackoverflow.com/questions/5671451/creating-a-javascript-cookie-on-a-domain-and-reading-it-across-sub-domains): 

https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/Util.ts#L190

**Comment by ivanfioravanti** [comment]
Any news on this issue?

**Comment by MaxShehovtsov** [comment]
No updates yet, assigned to the next sprint

**Comment by kamilszostak** [comment]
Pull request: https://github.com/Microsoft/ApplicationInsights-JS/pull/147
