### ISSUE TITLE
Request header field X-XHR-Logon is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by aes421** [Microsoft/ApplicationInsights-JS#645]
I have added the code to my web application using Dynamic loading with snippet.  However, when my page runs I get the following error: 
Failed to load https://dc.services.visualstudio.com/v2/track: Request header field X-XHR-Logon is not allowed by Access-Control-Allow-Headers in preflight response.

I am not sure what could be going wrong.  I did not change any of the code except to add my key.

**Comment by aes421** [comment]
If it helps,  this is the request from the chrome network tab.

![image](https://user-images.githubusercontent.com/10823042/43958656-c9d249f4-9c71-11e8-8342-2ea16889dd21.png)

**Comment by barustum** [comment]
Hi Ashley,

So are you adding this "x-xhr-logon" header to the request? If so, it's failing because the ingestion endpoint does not recognize this header, hence the pre-flight request fails. And because the pre-flight request fails, it doesn't bother of making a POST call.

Thanks

**Comment by aes421** [comment]
@barustum 
I did not add anything custom.  I copy and pasted this code from the readme and added my own instrumentation key.

```
<script type="text/javascript">
    var appInsights=window.appInsights||function(a){
        function b(a){c[a]=function(){var b=arguments;c.queue.push(function(){c[a].apply(c,b)})}}var c={config:a},d=document,e=window;setTimeout(function(){var b=d.createElement("script");b.src=a.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js",d.getElementsByTagName("script")[0].parentNode.appendChild(b)});try{c.cookie=d.cookie}catch(a){}c.queue=[];for(var f=["Event","Exception","Metric","PageView","Trace","Dependency"];f.length;)b("track"+f.pop());if(b("setAuthenticatedUserContext"),b("clearAuthenticatedUserContext"),b("startTrackEvent"),b("stopTrackEvent"),b("startTrackPage"),b("stopTrackPage"),b("flush"),!a.disableExceptionTracking){f="onerror",b("_"+f);var g=e[f];e[f]=function(a,b,d,e,h){var i=g&&g(a,b,d,e,h);return!0!==i&&c["_"+f](a,b,d,e,h),i}}return c
    }({
        instrumentationKey: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
    });
    
    window.appInsights=appInsights,appInsights.queue&&0===appInsights.queue.length&&appInsights.trackPageView();
</script>
```

**Comment by aes421** [comment]
I am beginning to wonder if the framework I am using is adding this header.  I am adding application insights inside a SAP Fiori Application

**Comment by barustum** [comment]
I think you're right. After digging through the code, we don't add this header anywhere. I am guessing the framework is doing this. I found this thread of other people running into this:
https://archive.sap.com/discussions/thread/3788892

**Comment by aes421** [comment]
We can close this then, since it's not an AI issue, and I'll take a look at it from the SAP side.
