### ISSUE TITLE
JS AI SDK duplicates data when two different instances opened in different iframes served from the same host name

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-JS#646]
Hello,

We noticed that some telemetry in InsightsPortal app is duplicated. Troubleshooting showed:

1.	JS code does trackEvent only once (as expected)
2.	Fiddler showed that there are two network calls to /v2/track, each one containing unique items. But majority of items are contained in both messages
3.	We have two AI SDK instances in InsightsPortal – one in the main extension and another one loaded in iframe. They are served from the same host name.

Our current hypothesis is that AI JS SDK stores items for sending in local storage and as a result both SDK instances send the same items.

If this hypothesis is correct then it means that we should be duplicating telemetry if user opens two tabs with the same app as well.

Do you know what should be our next steps to make sure that our customers are not affected?

Thank you!
Zaki

**Comment by jpiyali** [comment]
This is fixed in https://www.npmjs.com/package/@microsoft/applicationinsights-web/v/2.0.0-beta.3  beta SDK. 
Beta SDK has the ability to provide prefix for localstorage/cookie name. Setting:
{
instrumentationKey: "xxxxxxx"
namePrefix: "App1"

}
