### ISSUE TITLE
W3C distributed tracing-compatible operation id

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-JS#647]
Currently, ApplicationInsights SDKs support Request-Id header for correlation that looks like |<root-id>.

[W3C distributed tracing protocol](https://github.com/w3c/distributed-tracing/tree/master/trace_context) is going to replace current `Request-Id` format and is being implemented in ApplicationInsights SDKs.

The first phase of implementing it is a change of the rootId format.

Currently it's 5 base64 chars, but to enable compatibility with W3C standard, it should be 32 chars [a-z][0-9], lowercase. All zeros is considered invalid. 
Example of the valid id: `0af7651916cd43dd8448eb211c80319c`. 

It could be implemented as a lowercase guid without dashes or 16 random bytes encoded into hex string. 

The rest: header names and hierarchy in Request-Id could still be preserved (i.e. `|0af7651916cd43dd8448eb211c80319c.` is a valid Request-Id).

**Comment by jpiyali** [comment]
@lmolkova - how is the change being rolled out across all SDKs (timeline)? Potentially the change needs to be rolled out in adjacent time frame?

**Comment by lmolkova** [comment]
nope, the SDK is loose about the format now and this change can be rolled out at any moment without breaking anyone

**Comment by jpiyali** [comment]
@lmolkova - thanks. So, the requirement is to change the way we generate operationId in the SDK. I've scheduled this work on our backlog for coming sprint/next. Can you share information about the rest of the changes?

**Comment by markwolff** [comment]
Added in #973
