### ISSUE TITLE
Adding more top level properties to CustomEvents?

### ISSUE THREAD

**Issue by csteez** [Microsoft/ApplicationInsights-JS#659]
I looked though the documentation and I don't see a way to do this. Is it possible to add properties (not the custom dimension property bag) to Application Insights? It seems like there's an option in C#/other backend packages to add properties - how does this work for front end telemetry? Is it possible with this sdk? I've looked into the CustomDimensions but it doesn't quite do what I'm looking for.

**Comment by jpiyali** [comment]
Properties are associated with a specific telemetry type in general. What are you viewing properties against in the .net sdks? custom dimensions intention is to attach any custom property to a telemetry event. They also support custom metrics.

**Comment by jpiyali** [comment]
Please open issue with .net sdk behavior. As far as I know, logging dimensions standalone is not supported.
