### ISSUE TITLE
Make type definitions available through TSD installation

### ISSUE THREAD

**Issue by tedvanderveen** [Microsoft/ApplicationInsights-JS#66]
Add applicationinsights.d.ts TS definitions file to https://github.com/borisyankov/DefinitelyTyped

**Comment by MaxShehovtsov** [comment]
Thanks for the idea.

**Comment by hrboyceiii** [comment]
:+1: 
However, this could lead to confusion as applicationinsights.d.ts already exists there, though it appears to be for the nodejs library, not the javascript library :-( See the contributors page for more info https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/CONTRIBUTORS.md

**Comment by AlexBulankou** [comment]
We should make it clear that these are definitions for JS SDK. Suggested path: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/applicationinsights/applicationinsights-js.d.ts

**Comment by kamilszostak** [comment]
I added definition files for all methods described in the [API Reference doc](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md)

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9409

We may have to add trackAjax method once this is done: #196

**Comment by kamilszostak** [comment]
Added. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9409
