### ISSUE TITLE
Issue Loading the module

### ISSUE THREAD

**Issue by vishnu2017** [Microsoft/ApplicationInsights-JS#661]
I have the package of application insights in the node modules folder but the module is failing to load upon Running it in the browser.

Pls let the know the root cause.

![image](https://user-images.githubusercontent.com/20475543/45139993-2f04f200-b1cf-11e8-96ba-929dcade1956.png)

**Comment by vishnu2017** [comment]
![image](https://user-images.githubusercontent.com/20475543/45140121-7a1f0500-b1cf-11e8-8756-0a777fb797f3.png)

**Comment by vishnu2017** [comment]
fiddler screenshot

![image](https://user-images.githubusercontent.com/20475543/45140258-d84be800-b1cf-11e8-9080-a23cde95845b.png)

**Comment by piyalijana** [comment]
The error shows 404. can  you check the contents of the folder from second screenshot for the full path of module file?
