### ISSUE TITLE
AngularJS SPA browserTImings

### ISSUE THREAD

**Issue by raheelimtiaz** [microsoft/ApplicationInsights-JS#685]
After reading through some issues here I have fixed the SPA Page View Tracking by invoking startTrackPage and stopTrackPage on stateChangeStart and stateChangeSuccess events in an AngularJS SPA. But now the issue is I don't see any data being logged in browserTimings table. Is there anyway we can detect the client side browser timings and log those? I am thinking there must be some SPA events that can be used to manually trace the network, request, response and page loads.

**Comment by markwolff** [comment]
You can use `enableAutoRouteTracking: true` to track route changes. However, there is no well-defined meaning of what a "duration" should be for a SPA route change, so it will currently be sent as 0.
