### ISSUE TITLE
AngularJS Telemetry Corelation

### ISSUE THREAD

**Issue by raheelimtiaz** [microsoft/ApplicationInsights-JS#686]
How does operation id update? I have an Angular JS SPA with a .Net MVC API. The issue is once a user logs in, the operation id remains the same throughout the session. It only changes when the user  starts a new session.

Can we know how/when does the operation id change? Or can we manually change the operation id on a specific business use case? Also, how would this operation id be transmitted to the API?

**Comment by pajzo** [comment]
I have the same "issue", and looking for a solution :)

**Comment by raheelimtiaz** [comment]
What I have done in the meanwhile is to generate a new GUID on each state change in my angular app and use that GUID as the operation id. And then we start passing this GUID in subsequent dependency calls.

**Comment by pajzo** [comment]
But it could be nice if the SDK has an method like `generateNewId()` in the `context.operation`

There is an function to generate it, but i don´t think its accessible for us.

https://github.com/Microsoft/ApplicationInsights-JS/blob/edd3045c6129ab6aad44897a28c43b1683c8eda9/JavaScript/JavaScriptSDK/Context/Operation.ts

**Comment by pajzo** [comment]
Maybe this could be a solution?

https://github.com/pajzo/ApplicationInsights-JS/commit/c5e5e3d1c97c74632f9694aed530ef6a42e71fc7

**Comment by pajzo** [comment]
@raheelimtiaz i have code an suggestion and created a PR

**Comment by jpiyali** [comment]
@markwolff  - we did expose newId() in the last release. Perhaps we need to update docs?

**Comment by markwolff** [comment]
Closing with general guidance on SPA support until we start providing it by default in the SDK
https://github.com/microsoft/ApplicationInsights-JS#single-page-applications
