### ISSUE TITLE
AI web app does not use the value of setAuthenticatedUserContext() for user id

### ISSUE THREAD

**Issue by alanboy** [Microsoft/ApplicationInsights-JS#693]
I am using `setAuthenticatedUserContext` to my own custom user id: 

    appInsights.setAuthenticatedUserContext(someId, null, true/*storeInCookie*/);

However when I visit the web application I still get the auto-generated Id:

![image](https://user-images.githubusercontent.com/527987/46444709-10d7d680-c728-11e8-93e6-2ed11fdf00ac.png)

Only when writing custom queries I can use the custom user id:

![image](https://user-images.githubusercontent.com/527987/46444876-d589d780-c728-11e8-9ba2-7bee5228e230.png)

I am not using the server side app insights SDKs, this is all JavaScript (if that makes a difference). Is this the expected behavior? It's confusing and it makes all the pre-built tools not very usable.

**Comment by jpiyali** [comment]
This is expected behavior currently. The user timeline experience was not built around user_AuthenticatedId. It was built around user_Id. There are plans to add support for user_AuthenticatedId to the user timeline, but it is in the backlog.
