### ISSUE TITLE
How to access Util.newId() in v1.0.20

### ISSUE THREAD

**Issue by tedypranolo** [Microsoft/ApplicationInsights-JS#707]
I am using dist/ai.js of the npm package. And calling `import {AppInsights} from "applicationinsights-js"` and using the `@types/applicationinsights-js` type definition. I can't seem to find a way to access Util.newId()

**Comment by markwolff** [comment]
Hi @tedypranolo - you can now use `Util.newId()` by directly importing `Util`

```
import { Util } from applicationinsights-js'
Util.newId()
```
