### ISSUE TITLE
Root operation life cycle across client-server boundary

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-JS#71]
I wanted to follow up from our discussion yesterday and propose a default lifetime model for root operations when crossing server-client boundary.

These are the basic rules:
    1.  Every client to server request starts new root operation
    2.  Server to server request **does not** start a new operation
    3.  When new physical page is initialized by the client, all telemetry logged by this page has root operation of the server request that **served the page**.
    4.  New virtual pages (user calling `trackPageView()` ) does not change root operation

During the discussion yesterday we considered an idea of every call to `trackPageView()` initializing new root operation and having subsequent operations be rooted to it. However at a given point of time client does not have a single active page, instead there could be multiple panels (consider OWA with task list, email list, new email panel opened) and opening of each new panel is likely recorded by a call to `trackPageView()`.

Here's a diagram showing client->server->RDD interaction with distinct root operations color-coded:

![image](https://cloud.githubusercontent.com/assets/11968377/11004086/1503a3d6-846b-11e5-9cac-9920972f1941.png)

What it means that by default if we take all telemetry for a root operation ID, we should be able to produce a topology diagram that includes page request, RDD requests needed to render the page and client-side telemetry logged by the page after it was served to the client. However it will **not** include AJAX requests initiated by this page.

We should consider allowing user to override this default behavior and pass root operation ID with AJAX requests, which will result in the following model:
![image](https://cloud.githubusercontent.com/assets/11968377/11003965/80706966-846a-11e5-82b7-7b8ba227b60c.png)

Note that with this model, for a long-running single page app root operation ID becomes equivalent to session ID. I believe this should **not** be the default model, but there should be a way to implement it if needed.

**Comment by gregjhogan** [comment]
In your suggested model (first diagram), AJAX requests could pass the client root operation ID and still generate a new root operation ID on the server.  Tracking the correlated root operation IDs would give you the ability to draw a topology diagram including AJAX requests.  Will you be doing that?  I think a timeline visualization for a page request showing client and server events would be a huge improvement!

**Comment by jpiyali** [comment]
This is already implemented with the dependency tracking and appId in server resquest/response header.
