### ISSUE TITLE
Add custom properties and measurements to trackDependency() in IAppInsights interface

### ISSUE THREAD

**Issue by mizeljko** [Microsoft/ApplicationInsights-JS#725]
Hi,

We are using trackDependency() in IAppInsights interface and would like to set custom properties and measurements in the call, but the interface doesn't seem to allow it. Do you know what is the way to accomplish this with IAppInsights?

Thanks

**Comment by jpiyali** [comment]
@mizeljko - which SDK version are you using?

**Comment by mizeljko** [comment]
We are using applicationinsights-js 1.0.20

**Comment by markwolff** [comment]
hey @mizeljko thanks for pointing this out. Latest typings package should fix this
`npm i @types/applicationinsights-js@1.0.8 --save-dev`
