### ISSUE TITLE
Angularjs paths after hashprefix not tracked

### ISSUE THREAD

**Issue by lyvyu** [Microsoft/ApplicationInsights-JS#726]
Hey everyone,

so I've got a problem out here, the idea is that the pages aren't tracked after hashprefix in url,
we have something like `/backoffice/#/path/to/smth` and on app insights dashboard we can see only `/backoffice/` path, everything after hash is missing.

Does anyone know a workaround without removing the hashprefix ??

Thanks in advance.

**Comment by markwolff** [comment]
We grab the url from `window.location.href`, can you verify that this contains the path you want? Alternatively, you can manually specify the URL (https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#trackpageview). I'll close this for now, but reopen if manually setting it doesn't work for you.

**Comment by jpiyali** [comment]
@lyvyu - we dont have automated page tracking for different angular routes, you'll need to manaully track these instead of depending on initial automatic trackPageView.

**Comment by lyvyu** [comment]
@markwolff indeed, `window.location.href ` returns full url including path after hash, but what I have observed, in app insights dashboard, when I want to see the performance data for an application that has this prefix, operation name for url with hash is missing, but we can see full url in details.

@jpiyali I don't think is the matter of angular, instead I think that you guys, somehow, filter url's with hash and take only first part of it. Can you please confirm if this is so ? it would be really helpful.

Thanks guys.

**Comment by jpiyali** [comment]
https://github.com/Microsoft/ApplicationInsights-JS/blob/164530950b58120679e2193c8a7528d835943fee/JavaScript/JavaScriptSDK/Context/Operation.ts -> operation.name is set from window.location.pathname and not taken from window.location.href

**Comment by lyvyu** [comment]
@jpiyali oh, I see, but is there any thing I can do programatically to send to app insights the right path name dinamically ? maybe a callback when the tracking is done ?

**Comment by jpiyali** [comment]
Please look at this issue for code sample on how to setup addTelemetryinitializer that enables you to define a call back that will update the field name when trackpageview is called. https://github.com/Microsoft/ApplicationInsights-JS/issues/571

**Comment by lyvyu** [comment]
@jpiyali thanks, will try and let you know if this helped !!!

**Comment by lyvyu** [comment]
@jpiyali thanks, that worked for me, just grabbed pathname after hashprefix and changed it with one from the script !! 

Thank you guys for fast responses.
