### ISSUE TITLE
Get all dependencies for a page in log Analytics.

### ISSUE THREAD

**Issue by satyamamit** [Microsoft/ApplicationInsights-JS#727]
What’s a easy way to get all dependencies for a page in log analytics. I found that Id/operation_id column in pageViews is not unique and may be it is same for 1 user session. My requirement is very specific to all the dependencies for single page.

**Comment by jpiyali** [comment]
For  SDK version 1.0.20, For non SPA applications, id of the page (you can access it through appInsights.context.id) does refresh for new pages (across same user session). For SPA application, you will need to refresh the context manually. Please hook up to route change for these scenarios and set appInsights.context.operation = new Microsoft.ApplicationInsights.Context.Operation()

**Comment by KapitanIglo** [comment]
In my Angular application with the SDK version 1.0.20 the context not exists on the object ApplicationInsights (see bold below).

My code looks like:
    AppInsights.context.operation = new Microsoft.ApplicationInsights.**Context**.Operation();
    AppInsights.context.operation.name = name;

What are going wrong?

**Comment by tscislo** [comment]
Same here!

**Comment by AlissonRS** [comment]
@jpiyali would you mind checking the issue mentioned above, seems like I'm the third having this:

![image](https://user-images.githubusercontent.com/4753901/86969665-84501880-c144-11ea-9b34-2e4a56d8ec0e.png)

**Comment by MSNev** [comment]
Looking at the legacy code (currently v1.0.21 - which is also not actively maintained) the Namespace is correct
If you look at the unminified code https://az416426.vo.msecnd.net/scripts/a/ai.1.0.21.js

var Microsoft;
(function (Microsoft) {
    var ApplicationInsights;
    (function (ApplicationInsights) {
        var Context;
        (function (Context) {
            "use strict";
            var Operation = /** @class */ (function () {
                function Operation() {
                    this.id = ApplicationInsights.Util.newId();
                    if (window && window.location && window.location.pathname) {
                        this.name = window.location.pathname;
                    }
                }
                return Operation;
            }());
            Context.Operation = Operation;

And the config listed in #1320 is for v2 and is not available in v1
