### ISSUE TITLE
Do not collect locale and screen resolution by default

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#73]

**Comment by MaxShehovtsov** [comment]
@SergeyKanzhelev what do you mean 'by default'? Should there be a config parameter turning on this collection?

**Comment by SergeyKanzhelev** [comment]
customer can create a telemetry initializer or insert initialization in config snippet, right? We may document it

**Comment by AlexBulankou** [comment]
This is not a bug in existing product, that was intended by design, so I removed bug label and added enhancement label.
