### ISSUE TITLE
Feature Request: tracking headers in dependency

### ISSUE THREAD

**Issue by abdulkareemnalband** [microsoft/ApplicationInsights-JS#736]
## Feature Request

Allow tracking specific headers from **`Response`** ( also from **`Request`** would be nice)

## Rationale

A third party service which we use returns some diagnostic information in `Headers` , we want to track them along with dependencies.

**Comment by jacobslusser** [comment]
I would like to do the same.

Is there any workaround for doing this now?

I've looked a bit into using `trackDependency` manually, but I think I'm going to end up reinventing quite a bit of the existing SDK. Having the SDK automatically track AJAX calls is a huge value-add that would be a shame to have to bypass to get this one feature.

**Comment by jpiyali** [comment]
An approach could be to allow an array of headers that you want captured in the auto tracked dependency data.

**Comment by markwolff** [comment]
Added in 2.2.0
