### ISSUE TITLE
Pageviews getting captured intermittently

### ISSUE THREAD

**Issue by gap123pawar** [Microsoft/ApplicationInsights-JS#740]
Hi,

We are using node module in spfx extension to capture pageviews,but we found that all pageviews are not getting captured. After investigating further we found that event though code is getting called correctly only sometimes we could view http Track request in browser's network tab. Can anyone help why node module is behaving in this way ? Even if we are trying to call AppInsights.trackpageview("sometext") in browser's console after complete page load it works intermittently.

We are using AppInsights.downloadAndSetup to initialize instrumentation key as shown below:
 
import {AppInsights} from "applicationinsights-js"
......
..........
AppInsights.downloadAndSetup({ instrumentationKey: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx" });
........
...........
AppInsights.trackPageView(....);  

Please help !

**Comment by markwolff** [comment]
Hey @gap123pawar, can you enable `verboseLogging` and `enableDebug` and report back if any errors are occurring?

**Comment by jpiyali** [comment]
If this issue is not resolved, Please try above and if that does not resolve, please include which version of sdk you are using when you reopen the issue.
