### ISSUE TITLE
With `enableDebug: true` nothing gets logged to AppInsights when message exceeds max length

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-clarksons** [Microsoft/ApplicationInsights-JS#750]
*Context:* We would like to use `enableDebug: true` for local development, but the current behavior is a blocker for this practice.

**Current behavior:**
When the message exceeds the maximum allowed length, it [will be truncated by `AppInsights`](https://github.com/Microsoft/ApplicationInsights-JS/blob/e89cac6a3e5992cf03c3175370d02e43fa0eecd9/AppInsightsCommon/src/Telemetry/Common/DataSanitizer.ts#L103), but nothing will be logged when `enableDebug: true`, because the `throwInternal` called just after [will throw](https://github.com/Microsoft/ApplicationInsights-JS/blob/164530950b58120679e2193c8a7528d835943fee/JavaScript/JavaScriptSDK/Logging.ts#L174), and also, the whole execution flow will be broken by the throw.

**Expected behavior:**
Message truncation should be treated specially and never throw (so, it should not looking at the `enableDebug` flag), but only log a warning to the console (or `ApplicationInsights-JS`
could consider changing it to `console.error` when `enableDebug: true`).

**Rationale:**
Most of the time, it's unreasonable to tell developers to add, to otherwise very simple business logic, a noisy concern for selecting only useful information from the error and ensuring it doesn't exceed the maximum. Especially when the error was thrown from a 3rd party.
Relying on the messages being truncated automatically for AppInsights, while logged full to the console, is often really good enough.

**Comment by markwolff** [comment]
Hi @slawomir-brzezinski-at-clarksons, thanks for the report. Consider using `consoleLoggingLevel: 2`, which is a new config option to `console.warn` all of the internal errors/warnings instead of throwing them. Also, `enableDebug` will need to be `false` to use this setting

https://github.com/Microsoft/ApplicationInsights-JS/tree/master/AISKU#configuration

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Thank you for swift response @markwolff . If I understand correctly, the flag only exists in the beta version of the API, which actually didn't notice yet. We will switch to it in due course.

I supposed then that the `enableDebug` flag will stay as is, so it seems to me that it's not really useful to users of the library. As such, perhaps it should not be advertised as a public part of the API? In any case, it would be good if documentation made it clear what is the desired setting for outside of production, especially developer machines.

**Comment by markwolff** [comment]
Thanks for the feedback @slawomir-brzezinski-at-clarksons, I will definitely update the docs to clarify this!

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Thanks @markwolff I like the new documentation.
