### ISSUE TITLE
Pageview firing but not showing in portal 

### ISSUE THREAD

**Issue by ThibaultGobert** [Microsoft/ApplicationInsights-JS#759]
I'm using ApplicationInsights-js in a react SPA.
```
const ReactAI = {
  init(appInsightsOptions) {
    AppInsights.downloadAndSetup(appInsightsOptions)
    AppInsights.trackPageView("beforeListen")
    history.listen(location => AppInsights.trackPageView(location.pathname))
  },
}
```

The only metric I see in the azure portal, is several pageviews "beforeListen".
When I debug this, I see that history.listen is triggered on each router change (as it should be) and the code is being executed. But the location path name is not shown as a pageview in the portal

**Comment by markwolff** [comment]
Thanks for the repro. Are you using react-router v4?

**Comment by jpiyali** [comment]
Please check traces and exceptions for any errors as well.

**Comment by ThibaultGobert** [comment]
Yes, I use react-router v4 and verified logs on location.pathname. 
As @jpiyali suggested I went back to have another look and it seemed to be a problem with Content-Security-Policy. It logs in the portal now, thanks for your time
