### ISSUE TITLE
Trace Message: AI (Internal): Telemetry transmission failed, some telemetry will be lost

### ISSUE THREAD

**Issue by lubozic** [Microsoft/ApplicationInsights-JS#76]
I've stumbled upon some strange traces logged by AI js SDK. And it all happens on IE 11 browser

AI (Internal): Telemetry transmission failed, some telemetry will be lost: [object Error]{ stack: 'Error: Not enough storage is available to complete this operation.

   at t.prototype._xhrSender (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:30534)
   at t.prototype.triggerSend (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:29875)
   at Anonymous function (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:29278)', message: 'Not enough storage is available to complete this operation.
', name: 'Error'

![ai internal-telemetry transmission failed](https://cloud.githubusercontent.com/assets/15822652/11129466/bba96bc6-897f-11e5-9cff-eab73f9f2712.jpg)

**Comment by AlexBulankou** [comment]
Thanks for reporting this issue and sorry for delayed response. The issue you are seeing is a common problem with AJAX on IE browser when it cannot find a temporary storage needed to prepare the payload to send. This is won't fix at this point as the impact is limited to IE browser and usually for certain specific scenario. To mitigate the issue (if you know are you are logging multiple events and/or trace operations) you can use appInsights.flush() to flush payload early.
