### ISSUE TITLE
Capture all the Events on a Page

### ISSUE THREAD

**Issue by rlingineni** [Microsoft/ApplicationInsights-JS#767]
We're trying to capture all of the events on a page and stream them back to App Insights. Is this supported, or in the plans?

**Comment by markwolff** [comment]
Hi @rlingineni which events specifically are you looking for?

**Comment by rlingineni** [comment]
Things ranging from click events to hover, to drag and scrolls. Honestly, anything that captures user information. @markwolff

**Comment by jpiyali** [comment]
Thanks for the followup questions. Please reopen issue once there is proposal available for autocapture behavior. As mentioned telemetry types are in proposal for ClickAction and ContentUpdate.
