### ISSUE TITLE
[Beta] Initialization class does not implements IApplicationInsights correctly

### ISSUE THREAD

**Issue by kawazoe** [Microsoft/ApplicationInsights-JS#768]
In many places in the Initialization class for the new application insights beta SDK, some optional properties from the IApplicationInsights interface are not implemented correctly. I would expect this class to passthrough all track calls down to the `this.appInsights` property but it appears to be skipping some `customProperties`.

```ts
    /**
     * Logs that a page, or similar container was displayed to the user.
     * @param {IPageViewTelemetry} pageView
     * @param {{ [key: string]: any; }} [customProperties]
     * @memberof Initialization
     */
    public trackPageView(pageView: IPageViewTelemetry) {
        this.appInsights.trackPageView(pageView);
    }
```
[Source](https://github.com/Microsoft/ApplicationInsights-JS/blob/0e6d1929dddf0392d30cce4a4fef30d39d0b3084/AISKU/src/Initialization.ts#L87)

As you can see, there are two properties in the doc (an in the interface) but only one in the implementation.

In this case, it prevents us from sending custom properties on page views, even though the underlining class expects them.

**Comment by markwolff** [comment]
Thanks for the report @kawazoe. Please use the `properties` and `measurements` field of `IPageViewTelemetry` to send custom properties and measurements. I will update the JSDoc comment to remove `customProperties`

**Comment by kawazoe** [comment]
Thanks! Just to be sure, are those supposed to be the new pattern? I am just asking because I still see a lot of code that uses the `customProperties` parameter (like for the duration metric in page views).
