### ISSUE TITLE
Update APIs to create full Part B before passing along to other plugins

### ISSUE THREAD

**Issue by markwolff** [Microsoft/ApplicationInsights-JS#772]
Currently, correct baseData is generated in channel.
https://github.com/Microsoft/applicationinsights-channel-js/blob/10407728124a0e00ef8cd1c537f5de5fc37c913b/src/EnvelopeCreator.ts#L379-L382

The `let baseData = new Exception(...)` line can be moved to where API args are parsed, as shown below.
https://github.com/Microsoft/ApplicationInsights-JS/blob/4cffc8f7c9c0d806d4cf030ece6b97b1e66676e6/ApplicationInsights/src/JavaScriptSDK/ApplicationInsights.ts#L357-L366

This change should probably be propagated to all of the other APIs as a way to verify that our API argument fields completely match the "part B classes" in Common.

**Comment by jpiyali** [comment]
This one is tracking for Exception type only right @markwolff ? Remaining should already be correct for the beta sdk.

**Comment by markwolff** [comment]
Yes remaining are correct right now. But if we make any changes, they would have to be made in channel as well. It might be good to move all Part B stuff here.
