### ISSUE TITLE
Generating new Operation id for each pageView in an angular app(SPA)

### ISSUE THREAD

**Issue by ranjitkrishnan** [Microsoft/ApplicationInsights-JS#782]
I am trying to instrument an Angular 6 app where i am hitting the same issue mentioned in the blog below regarding SPA.

http://apmtips.com/blog/2017/05/11/page-view-and-telemetry-correlation/

Where the subsequent page views are nested under one page view with the same operation id. 
The solution mentioned in the blog is to use "@this.Context.GetRequestTelemetry().Context.Operation.Id"; which will fetch the RequestTelemetry object from the server and assign that as the operation id.  Want to know how to do that in Angular. 

I am calling trackPageView in each route change..  

@SergeyKanzhelev  I am moving the discussion from the blog to github based on your suggestion.

**Comment by jpiyali** [comment]
@ranjitkrishnan - please refer to solution provided in #727 . Thanks!
