### ISSUE TITLE
Log application_Version in App Insights 

### ISSUE THREAD

**Issue by Keyan-Wang** [Microsoft/ApplicationInsights-JS#785]
how to log application_Version in App insights use js

**Comment by pajzo** [comment]
I use this script:

            var appVersion = this.appConfigService.appConfig.application.version;
            AppInsights.queue.push(function () {
                AppInsights.context.addTelemetryInitializer(function (envelope) {
                    envelope.tags["ai.cloud.role"] = "MyApp";
                    envelope.tags["ai.application.ver"] = appVersion;
                });
            });
