### ISSUE TITLE
Module not found when using ES6 Module

### ISSUE THREAD

**Issue by FelschR** [Microsoft/ApplicationInsights-JS#789]
The latest update to `@microsoft\applicationinsights-web` (`1.0.0-beta.12`) introduced the following issue for me:
```sh
ERROR in ../node_modules/@microsoft/applicationinsights-web/dist-esm/applicationinsights-web.js
Module not found: Error: Can't resolve '@microsoft/applicationinsights-channel-js' in 'C:\Users\felix_schroeter\Documents\Projects\fitnesspilot-web\node_modules\@microsoft\applicationinsights-web\dist-esm'
 @ ../node_modules/@microsoft/applicationinsights-web/dist-esm/applicationinsights-web.js 6:0-67 6:0-67
```

This issue occurred in a webpack setup with babel using `@babel/preset-env`.
The previous version `1.0.0-beta.11` is working fine.

**Comment by markwolff** [comment]
Hi @FelschR, was `@microsoft/applicationinsights-channel-js` present in your node_modules folder?

**Comment by jpiyali** [comment]
@FelschR  - closing this issue, please reply if you are sitll having issues finding module. We tried this a couple of times for version 1.0.0.beta-12 and not seeing the issue you pasted.
