### ISSUE TITLE
The events not captured in IE 8 compatibility mode

### ISSUE THREAD

**Issue by vcrudu** [microsoft/ApplicationInsights-JS#790]
Our application is developed for IE8 and when using Using initialization snippet to add Javascript SDK to the page it sends the telemetry from IE Edge and Chrome but not when the compatibility level is set to IE8.
The application needs a huge amount of effort to switch to IE Edge. Can you please help?

**Comment by markwolff** [comment]
Which version of the SDK are you using? What errors are being reported?

**Comment by markwolff** [comment]
The SDK does not support compatibility mode for IE8 or lower, but should work correctly in IE8 directly.

**Comment by vcrudu** [comment]
Mark,  do you suggest to use an older version that might be supported by compatibility mode for IE8? Which version would you suggest? 
We would need like half a year of adjusting our very un-maintainable  code to make it working well in IE Edge. Any help to avoid that will be very much appreciated.
Thanks,

**Comment by markwolff** [comment]
AFAIK, the SDK never supported IE8 compatibility mode, so no older version exists where this is possible. Are any errors being reported in your usage? Does your app use `https`?
