### ISSUE TITLE
Whitelist in CSP policy

### ISSUE THREAD

**Issue by jean-moldovan** [microsoft/ApplicationInsights-JS#791]
Hello!

When using `script-src 'self'` "Content-Security-Policy" `ai.0.js` file loaded via sdk is blocked by the browser, which is expected.

What would be the correct setting to whitelist it? Which part of the url is dynamic and very likely to change over time `https://az416426.vo.msecnd.net/scripts/a/ai.0.js` ?

Thanks!

**Comment by jean-moldovan** [comment]
Looks like it's making calls to `https://dc.services.visualstudio.com/v2/track`. Might need to whitelist as well.

A section in the docs would be very appreciated. Thanks!

**Comment by markwolff** [comment]
You are correct; both are constant and can be whitelisted as is.
