### ISSUE TITLE
TypeError: Cannot read property 'throwInternal' of undefined

### ISSUE THREAD

**Issue by Socolin** [Microsoft/ApplicationInsights-JS#810]
Hi,

When I'm trying to log a trace or an exception I got the following error:

```js
this.applicationInsights = new ApplicationInsights({
  config: {
    instrumentationKey: "some-key"
  }
});
this.applicationInsights.trackTrace({
  message: 'test'
});
```

```
logger-service.ts:38 Failed to setup Application Insights TypeError: Cannot read property 'throwInternal' of undefined
    at e.trackTrace (ApplicationInsights.js:114)
    at e.trackTrace (Initialization.js:85)
```

In `_setTelemetryNameAndIKey` the value `this._globalconfig` is undefined.
The method `_initialize` dont seems to be called.

Regards,

**Comment by Socolin** [comment]
Here a repro
https://bitbucket.org/bertrandprovost/repro-bug-appinsight-js/commits/branch/issue_810
(branch `issue_810`)

Just run `yarn test`

**Comment by jpiyali** [comment]
@Socolin - can you please also invoke loadAppInsights().

this.applicationInsights = new ApplicationInsights({
  config: {
    instrumentationKey: "some-key"
  }
});
this.applicationInsights.loadApplicationInsights();

this.applicationInsights.trackTrace({
  message: 'test'
});

**Comment by Socolin** [comment]
It worked, thank you.

**Comment by ImDmj** [comment]
@jpiyali 
i am writing test cases with JEST, and i get the same error and all the other test suites fail. 
is there any way to avoid invoking loadAppInsights() multiple times?
can i just mock "loadAppInsights()"

**Comment by markwolff** [comment]
loadAppInsights should be idempotent. Are you seeing a case where tests fail only after calling it multiple times?
