### ISSUE TITLE
TrackPVFailedCalc error

### ISSUE THREAD

**Issue by dmcweeney** [Microsoft/ApplicationInsights-JS#812]
Folks,

Started getting a lot of the following errors when debugging on localhost.

"AI (Internal): TrackPVFailedCalc message:"trackPageView failed on page load calculation: " 
props:"{exception:[object Object]{\messageId\:8,\message\:\AI (Internal): ClientPerformanceMathError message:\\\client performance math error.\\\ props:\\\{total:33723,network:2,request:19914,response:578,dom:13238}\\\\}}""

Which is strange as I have configured AI as follows:
- overridePageViewDuration: true,
- autoTrackPageVisitTime: false

And I am specifying my own duration value (Its an SPA).

Using "applicationinsights-js": "^1.0.20"

Any ideas greatly appreciated.

Thanks Donal

**Comment by markwolff** [comment]
Hey @dmcweeney are you manually calling trackPageView or trackPageViewPerformance? Can you post your snippet?

**Comment by dmcweeney** [comment]
Hi @markwolff I'm manually calling trackPageView as follows:

`AppInsights.trackPageView( eventData.pageName, eventData.pageUrl, eventData.properties, eventData.measurements, eventData.duration ) ;
`

duration is defined as a number, sometimes 0, but a lot of the time it could be sometime like 248.06782. I've only started getting the error the last 2 days, out of the blue - it was fine before that for the last few weeks.

I would not have expected to see a ClientPerformanceMathError as I think I have the auto page performance tracking turned off.

**Comment by markwolff** [comment]
There is currently no way to explictly disable performance timing. Are you modifying the `window.performance.timing` object at all? This error occurs when the sum of the timings exceed `navigationStart` --> `loadEventEnd`

https://github.com/Microsoft/ApplicationInsights-JS/blob/164530950b58120679e2193c8a7528d835943fee/JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts#L96-L105

**Comment by dmcweeney** [comment]
I'm using window.performance.now for calculating the page load timing - definitely not manipulating the timing object. I will investigate more on Tuesday.

**Comment by dmcweeney** [comment]
Hi @markwolff I've spend a few hours trying to narrow this down to something consistently reproducible but could not. I could only reproduce in Chrome when running on VS 2017 (15.9.9) in debug mode. The version of Chrome was 72.0.3626.121 (64-bit).
When I updated to latest Chrome 73.0.3683.75 (64-bit) I cannot repro at all!!!!!!!
I'll close this and reopen if I can repro again.

Thanks, Donal
