### ISSUE TITLE
Telemetry data is lost when telemetry API calls fail

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/ApplicationInsights-JS#82]
It appears that when sending telemetry to the app insights API fails, the telemetry is completely lost.  I think there would be a lot of benefit in a store and forward model (write telemetry out to local storage first, attempt to send it after).

**Comment by AlexBulankou** [comment]
Dupe of https://github.com/Microsoft/ApplicationInsights-JS/issues/69
