### ISSUE TITLE
Licence file missing for 0.11.0 version

### ISSUE THREAD

**Issue by Praveenpvs** [Microsoft/ApplicationInsights-JS#820]
Hi Team,

We had used this package (Microsoft.ApplicationInsights.JavaScript), version-0.11.0-build09387 in one of our web apps earlier. As part of licensing & audit assessment, we are looking for Licence terms associated with this particular version.
Nuget site hosting this package has a broken link to the Licence Info page. 
https://www.nuget.org/packages/Microsoft.ApplicationInsights.JavaScript/0.11.0-build09387

Can you please provide the license info related to this OR confirm if the latest licence (MIT) is also applicable for this version-0.11.0.

Thanks, Praveen

**Comment by markwolff** [comment]
Hi @Praveenpvs the latest license is applicable for that version as well

**Comment by SergeyKanzhelev** [comment]
Looks like a dup for https://github.com/Microsoft/ApplicationInsights-Home/issues/334

**Comment by Praveenpvs** [comment]
Thank you for confirming about the license!
