### ISSUE TITLE
Missing license info for  Microsoft.ApplicationInsights.JavaScript (0.11.0-build09387)

### ISSUE THREAD

**Issue by Praveenpvs** [Microsoft/ApplicationInsights-JS#821]
Hi Team,

We had used Nuget package: "**Microsoft.ApplicationInsights.JavaScript**", version: **0.11.0-build09387** in one of our components. 
As part of assessment, we are looking for licence terms associated with this version. The "License info" link in the Nuget website is taking to a 404-Not found page. https://www.nuget.org/packages/Microsoft.ApplicationInsights.JavaScript/0.11.0-build09387

Can you please provide the licence terms for this file or can you confirm the generic license that is there on home page is applicable for this **0.11.0-build09387** version as well.

Generic License: 
https://www.nuget.org/packages/Microsoft.ApplicationInsights.JavaScript
License info: https://github.com/Microsoft/ApplicationInsights-Home/blob/master/LICENSE

Thanks, 
Praveen Polepalli

**Comment by SergeyKanzhelev** [comment]
closed as duplicate

**Comment by SergeyKanzhelev** [comment]
https://github.com/Microsoft/ApplicationInsights-JS/issues/820
