### ISSUE TITLE
appInsights.queue not executed

### ISSUE THREAD

**Issue by StefanRiedmann** [Microsoft/ApplicationInsights-JS#824]
I'm trying to add user data to the appInsights logs by adding a telemetryInitializer. To ensure that the context is loaded, I'm adding it to the queue. But it never gets executed. 

```javascript
appInsights.queue.push(() =>
 {
  appInsights.context.addTelemetryInitializer((envelope: Microsoft.ApplicationInsights.IEnvelope) =>
  {
    const identity = this.authService.getCurrentIdentity(); //my auth service
    const user = identity && identity.user ? identity.user.username : undefined;
     envelope.userId = user;
  });
});
appInsights.downloadAndSetup({instrumentationKey: config.appInsightsKey,
                              disableExceptionTracking: false,
                              disableTelemetry: false
                            });
appInsights.trackTrace('appinsights initialised');
```

**Comment by StefanRiedmann** [comment]
Looks like I got mixed up between npm and script snippet examples. Had to create an instance of ApplicationInsights(...) first (and call loadAppInsights()), then it works.

**Comment by markwolff** [comment]
@StefanRiedmann The docs in our readme were recently changed to reflect v2 of the SDK. Are you using applicationinsights-js `1.2.0`? Those were moved to [here](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/legacy_README.md)

**Comment by StefanRiedmann** [comment]
@markwolff I'm using https://www.npmjs.com/package/@microsoft/applicationinsights-web now, and the 'NPM only' mode works perfectly in my Angular application. 

Keep up the good work, ApplicationInsights is awesome!
