### ISSUE TITLE
Lack of namePrefix leads to duplicate events when used for multiple frames on one domain

### ISSUE THREAD

**Issue by jasmcc** [Microsoft/ApplicationInsights-JS#828]
We are having an interesting problem with the currently live version (
https://az416426.vo.msecnd.net/scripts/a/ai.0.js) that still seems to be an issue with the betaRC2 version.

**Bug**
If multiple pages on one domain name use appInsights, there are race conditions

**Repro**
1. Add appInsights script reference to the head of a page, using ikey1.
2. Add a child iframe and with appInsights script reference in its head, using ikey2.
3. Send events from both frames.
4. Subject to timing race conditions, you will see duplicate events being sent in Fiddler.  The usual repro is that you have a call to dc.visualstudio…. with a few events from ikey1, then another event very shortly thereafter with the same events from ikey1 + some ikey2 events.

**Cause**
This appears to be the result of all AI script references on a single domain name sharing local storage, and all of them have the same hardcoded name for their buffer management:
r.BUFFER_KEY="AI_buffer",r.SENT_BUFFER_KEY="AI_sentBuffer"

As a result, they can fight over the queue and duplicate each others events.

**Resolution**
It looks like namePrefix would solve this, but when I provide a value for namePrefix it appears to 1) be ignored and 2) does not get applied to the buffer names anyway.

Is this wrong, are there any other workarounds I am missing?

**Comment by markwolff** [comment]
@jasmcc Thanks for pointing this out. Looks like it is ignoring the setting for the session storage stuff. I'll add it in and release it with rc2

**Comment by markwolff** [comment]
Marking this as resolved. Will be released as part of `rc2`

**Comment by 3xj** [comment]
Hi,

I don't think this issue is resolved. I'm using `ai.2.min.js` with `namePrefix` and still seeing duplicate events between a parent and child frame. I've set up a simple test that repros consistently. Should I add details here or open a new issue?

**Comment by markwolff** [comment]
Yes you can just post the repro here

**Comment by 3xj** [comment]
```
parent.html
-------------
<script type="text/javascript">
        var sdkInstance="appInsightsSDK";window[sdkInstance]="appInsights";var aiName=window[sdkInstance],aisdk=window[aiName]||function(e){function n(e){i[e]=function(){var n=arguments;i.queue.push(function(){i[e].apply(i,n)})}}var i={config:e};i.initialize=!0;var a=document,t=window;setTimeout(function(){var n=a.createElement("script");n.src=e.url||"https://az416426.vo.msecnd.net/next/ai.2.min.js",a.getElementsByTagName("script")[0].parentNode.appendChild(n)});try{i.cookie=a.cookie}catch(e){}i.queue=[],i.version=2;for(var r=["Event","PageView","Exception","Trace","DependencyData","Metric","PageViewPerformance"];r.length;)n("track"+r.pop());n("startTrackPage"),n("stopTrackPage");var o="Track"+r[0];if(n("start"+o),n("stop"+o),!(!0===e.disableExceptionTracking||e.extensionConfig&&e.extensionConfig.ApplicationInsightsAnalytics&&!0===e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)){n("_"+(r="onerror"));var s=t[r];t[r]=function(e,n,a,t,o){var c=s&&s(e,n,a,t,o);return!0!==c&&i["_"+r]({message:e,url:n,lineNumber:a,columnNumber:t,error:o}),c},e.autoExceptionInstrumented=!0}return i}
        (
            {
                instrumentationKey: "5b4cda77-fb98-4b2e-bfdb-39be28aa6bf9",
            }
        );
        window[aiName]=aisdk,aisdk.queue&&0===aisdk.queue.length&&aisdk.trackPageView({});
        let counter = 0;
        while (counter < 120) {
                appInsights.trackEvent({ name: "JGS2 Parent Test Event" }, { embedURL: window.location.href, parent: counter });
                counter++;
        }
        console.log('parent: ' + counter);
        </script>
    ...
    <iframe src="/frame.html"></iframe>```

```
frame.html
------------
<script type="text/javascript">
        var sdkInstance="appInsightsSDK";window[sdkInstance]="appInsights";var aiName=window[sdkInstance],aisdk=window[aiName]||function(e){function n(e){i[e]=function(){var n=arguments;i.queue.push(function(){i[e].apply(i,n)})}}var i={config:e};i.initialize=!0;var a=document,t=window;setTimeout(function(){var n=a.createElement("script");n.src=e.url||"https://az416426.vo.msecnd.net/next/ai.2.min.js",a.getElementsByTagName("script")[0].parentNode.appendChild(n)});try{i.cookie=a.cookie}catch(e){}i.queue=[],i.version=2;for(var r=["Event","PageView","Exception","Trace","DependencyData","Metric","PageViewPerformance"];r.length;)n("track"+r.pop());n("startTrackPage"),n("stopTrackPage");var o="Track"+r[0];if(n("start"+o),n("stop"+o),!(!0===e.disableExceptionTracking||e.extensionConfig&&e.extensionConfig.ApplicationInsightsAnalytics&&!0===e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)){n("_"+(r="onerror"));var s=t[r];t[r]=function(e,n,a,t,o){var c=s&&s(e,n,a,t,o);return!0!==c&&i["_"+r]({message:e,url:n,lineNumber:a,columnNumber:t,error:o}),c},e.autoExceptionInstrumented=!0}return i}
        (
            {
                instrumentationKey: "fead7a4a-f937-43f4-988b-6f9ff9c456f3",
                namePrefix: "microsoft.casualgames.jgs-dev.child.appInsights",
            }
        );
        window[aiName]=aisdk,aisdk.queue&&0===aisdk.queue.length&&aisdk.trackPageView({});
        let counter = 120;
        while (counter < 240) {
                appInsights.trackEvent({ name: "JGS Child Test Event" }, { embedURL: window.location.href, child: counter });
                counter++;
        }
        console.log('child: ' + counter);
    </script>```

When I query the logs for `parent.html` in Azure, I get dupes for every parent event. If I remove the child iFrame, I see the expected # of events (no dupes).
```
customEvents
| where name contains "JGS"
| extend realTime = tostring(timestamp)
| summarize count() by name, user_Id, session_Id, tostring(customMeasurements), realTime | where count_ > 1 ```

Let me know if you need additional details. Thanks.

**Comment by 3xj** [comment]
Here are the results of the above log query, fyi.

[ai_query_data.xlsx](https://github.com/microsoft/ApplicationInsights-JS/files/3263038/ai_query_data.xlsx)

**Comment by markwolff** [comment]
Thanks for the repro and all of the details! I've addressed this in #919 which will land in 2.0.1. The npm package has been published already and the CDN will be updated this coming Monday.

**Comment by 3xj** [comment]
Great! Thanks for the quick response.

**Comment by 3xj** [comment]
Are there any updates I need to make on my end to pull down the 2.0.1 release? Pointing at `https://az416426.vo.msecnd.net/next/ai.2.min.js` doesn't appear to include the namePrefix fix.

**Comment by markwolff** [comment]
Hey @3xj, try this one:
`https://az416426.vo.msecnd.net/beta/ai.2.min.js`

**Comment by 3xj** [comment]
Ah, cool, that's got it, thanks! I'm no longer seeing the dupes using the `/beta` path.

`scripts/b/` is considered the stable release?
