### ISSUE TITLE
isOffline causes multiple duplicate events in React Native

### ISSUE THREAD

**Issue by mraware** [Microsoft/ApplicationInsights-JS#832]
I am using Application Insights in my React Native project and am having issues with sending duplicate events.

**Bug**
isOffline is always true with React Native, resends events

**Repro**
1. React Native v0.57.0
2. use npm to install applicationinsights-web
3. Make sure you are not using chrome debugging
4. Send an event

**Cause**
[React Native's JS environment](https://facebook.github.io/react-native/docs/javascript-environment) has a navigator object but does not have the onLine property. isOnline is returning undefined. This causes isOffline to return true.

https://github.com/Microsoft/ApplicationInsights-JS/blob/9d424a82ac6f47205fe971e559f61314d59b7531/vNext/channels/applicationinsights-channel-js/src/Offline.ts#L48-L53

Even if the request returns 200 success since isOffline is true it calls resendPayload

https://github.com/Microsoft/ApplicationInsights-JS/blob/e6e6f7ac58eb9ac74f984f637dadf52fd9edc67e/vNext/channels/applicationinsights-channel-js/src/Sender.ts#L268-L277

**Comment by markwolff** [comment]
Thanks for pointing this out @mraware. I'll update the navigator check we use to require `onLine` being defined as well.
