### ISSUE TITLE
[Feature request] Add option to collect ajax logs with status code in expected range

### ISSUE THREAD

**Issue by blrchen** [microsoft/ApplicationInsights-JS#838]
Currently, all ajax requests will be logged. Could you please add an option to let developer customize the range of status codes that is needed to be tracked? For example, only tracking ajax logs with status code !== 200

**Comment by markwolff** [comment]
Hi @blrchen, to customizise which status codes to track, you can add a [telemetry initializer](https://github.com/Microsoft/ApplicationInsights-JS#telemetry-initializers). These let you perform some last step filtering/modifications on your telemetry before it gets sent out. To only track ajax logs with status code !== 200, you can use the following.

```js
let appInsights = new ApplicationInsights({config: {
  instrumentationKey: INSTRUMENTATION_KEY,
  disableFetchTracking: false,
}});
appInsights.loadAppInsights();

// Add status code telemetry initializer
appInsights.addTelemetryInitializer((envelope) => {
  if (envelope.baseType === "RemoteDependencyData") {
    if (envelope.baseData.statusCode !== 200) {
      // Send telemetry without statusCode === 200
      return true;
    } else {
      // status code is 200, drop this telemetry
      return false;
    }
  }

  // Accept all other telemetry that is not RemoteDependencyData
  return true;
});
```
