### ISSUE TITLE
[Enhancement] Support live metrics stream

### ISSUE THREAD

**Issue by KrishnaPravin** [microsoft/ApplicationInsights-JS#841]
https://azure.microsoft.com/en-us/blog/live-metrics-stream/

Currently Live metrics is supported for .NET web app and node.js SDKs.
Are you looking into enabling it in javascript(web apps) SDK? Is there a timeline for it?

**Comment by markwolff** [comment]
Sorry for the late reply, there are currently no plans for supporting live metrics with the web SDK.

**Comment by KrishnaPravin** [comment]
> Sorry for the late reply, there are currently no plans for supporting live metrics with the web SDK.

Anyways thank you @markwolff for letting know.

**Comment by JohnGalt1717** [comment]
Please re-evaluate this decision. It would be really nice to be able to see this in real-time.
