### ISSUE TITLE
all data (browser and server) going to server view in Azure UI

### ISSUE THREAD

**Issue by artparks** [microsoft/ApplicationInsights-JS#843]
We have a web app (Angular 7.2.12) being served by a NodeJS backend, with both sides configured to send telemetry to App Insights. The server side part works as expected, using the [applicationinsights](https://github.com/Microsoft/ApplicationInsights-node.js) package, but the browser app is not behaving. That is set up using 2.0.0-rc3 of this library, but it also has the same issue with 2.0.0-rc1 - I have not tried any other versions as I don't think the issue is necessarily with the library.

The problem is that all data, both that sent from the server with the Node SDK, and that sent from the browser with the web SDK, shows up in the "server" section of the "failures" panel in the UI. I see web data in the "users" and "events" panels, so this data is going to the right location, but exceptions (both those auto sent and those manually submitted) go to the wrong location. Here is a list of exceptions from the UI - the ones that have no users are those sent by server code, those with users come from client code:

<img width="467" alt="Screen Shot 2019-04-17 at 19 25 26" src="https://user-images.githubusercontent.com/2233174/56311788-b5f75100-6146-11e9-9ff7-c56d8c9ca7cd.png">

When I look at the data sent, it looks like its tagged as being from a browser, but I have no idea how this is handled on the server so this may not be correct still. This is an example of what is sent as an exception:

<img width="670" alt="Screen Shot 2019-04-17 at 19 14 14 copy" src="https://user-images.githubusercontent.com/2233174/56311542-2e114700-6146-11e9-84d8-21a7c7b70e27.png">

One other point is that the documentation for the UI is hugely out of date - it appears not to have beed amended since 2017 while the UI has clearly changed massively since then.

**Comment by markwolff** [comment]
I believe it separates it based on `tags["ai.device.type"] === "Browser"`. It seems this field is no longer being set. I will add it and it will land in rc4 later this week.

**Comment by artparks** [comment]
awesome, will try it out and let you know.

**Comment by artparks** [comment]
just tested rc4 and it appears fixed, exceptions are now heading in the right direction. thanks for the quick fix.
