### ISSUE TITLE
How to remove server headers from the response of application insights request.  

### ISSUE THREAD

**Issue by swodeshm** [microsoft/ApplicationInsights-JS#850]
How to remove server headers from the response of application insights request 

my client app is angular 5
i want to remove following headers from the response.

X-Powered-By :ASP.NET    
Server: Microsoft-IIS/10.0

**Comment by hectorhdzg** [comment]
@swodeshm  you can open the issue in ASP.NET ApplicationInsights repo to get more accurate responses

https://github.com/Microsoft/ApplicationInsights-aspnetcore
