### ISSUE TITLE
Uncaught TypeError: Cannot read property 'queue' of undefined @Initialization.ts:106 

### ISSUE THREAD

**Issue by eyang414** [microsoft/ApplicationInsights-JS#855]
This TypeError shows for a website that has two App Insights instances both using the JavaScript snippet set-up.  The website uses both version 1.0 and 2.0 for different uses.

![image](https://user-images.githubusercontent.com/22535690/56996759-98c57800-6b73-11e9-9ab7-ffc3dbcf0f15.png)

![image](https://user-images.githubusercontent.com/22535690/56996814-be528180-6b73-11e9-934c-b4a97e5c7023.png)

If I am not able to upgrade the version 1.0 App Insights instance, is there a way to solve this?

Thanks,
Eric

**Comment by markwolff** [comment]
I believe this is because the 1.0 & 2.0 snippet setup scripts are writing to the same window variable (both use `window.appInsights`). You can now modify this in the 2.0 snippet at the very beginning of it
```js
var sdkInstance="appInsightsSDK";window[sdkInstance]="appInsights"
```
change this to something like
```js
var sdkInstance="someInstanceName";window[sdkInstance]="someWindowName"
```

**Comment by eyang414** [comment]
Hi Mark,

Thanks for helping me with this issue.  I tried your solution, but there seems to be another issue where changing the sdkInstance name causes the window[sdkInstance] to not have all functionality attached. 

![image](https://user-images.githubusercontent.com/22535690/57706886-9d3e6600-7634-11e9-97e9-8c2ea4673a7c.png)

![image](https://user-images.githubusercontent.com/22535690/57706962-c828ba00-7634-11e9-898a-e1c18062f143.png)

I remember v1.0's appInsights loading script attached properties specifically to window.appInsights.  Is v2.0 doing a similar thing?

**Comment by markwolff** [comment]
@eyang414 My mistake. You only need to change the 2nd string var. You should not change the 1st

```js
var sdkInstance="appInsightsSDK";window[sdkInstance]="someWindowName"
```

**Comment by eyang414** [comment]
@markwolff  This error has been happening with the 2nd string var being set to something custom.

**Comment by eyang414** [comment]
@markwolff  Hi Mark, any updates on this issue?

**Comment by markwolff** [comment]
It seems like it is a bug. I will likely look into it by next week

**Comment by markwolff** [comment]
The cause of this is the rollup config has an output name of "Microsoft.ApplicationInsights" which conflicts with the legacy version's name. A fix will go out for the next patch release
https://github.com/microsoft/ApplicationInsights-JS/blob/master/vNext/AISKU/rollup.config.js#L20

**Comment by syltaxue** [comment]
I got the same error when trying to setup my AppInsights scripts on Dynamics365.

I tried to update the 2nd string in the window[sdkInstance] but no luck.

Any workaround?

The code I used:
`var sdkInstance = "appInsightsSDK"; window[sdkInstance] = "someWindowName"; var aiName = window[sdkInstance], aisdk = window[aiName] || function (e) {
    function n(e) { t[e] = function () { var n = arguments; t.queue.push(function () { t[e].apply(t, n) }) } } var t = { config: e }; t.initialize = !0; var i = document, a = window; setTimeout(function () { var n = i.createElement("script"); n.src = e.url || "https://az416426.vo.msecnd.net/next/ai.2.min.js", i.getElementsByTagName("script")[0].parentNode.appendChild(n) }); try { t.cookie = i.cookie } catch (e) { } t.queue = [], t.version = 2; for (var r = ["Event", "PageView", "Exception", "Trace", "DependencyData", "Metric", "PageViewPerformance"]; r.length;)n("track" + r.pop()); n("startTrackPage"), n("stopTrackPage"); var s = "Track" + r[0]; if (n("start" + s), n("stop" + s), n("setAuthenticatedUserContext"), n("clearAuthenticatedUserContext"), n("flush"), !(!0 === e.disableExceptionTracking || e.extensionConfig && e.extensionConfig.ApplicationInsightsAnalytics && !0 === e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)) { n("_" + (r = "onerror")); var o = a[r]; a[r] = function (e, n, i, a, s) { var c = o && o(e, n, i, a, s); return !0 !== c && t["_" + r]({ message: e, url: n, lineNumber: i, columnNumber: a, error: s }), c }, e.autoExceptionInstrumented = !0 } return t
}({
    instrumentationKey: ""
});

window[aiName] = aisdk, aisdk.queue && 0 === aisdk.queue.length && aisdk.trackPageView({});`

**Comment by MSNev** [comment]
We have updated the snippet version to be able to handle multiple "named" instances as well as configuration that allow you to set the sdkInstance name -- see the readme for the updated details or the snippet code (full and minifed here)
https://github.com/microsoft/ApplicationInsights-JS/tree/master/AISKU/snippet
