### ISSUE TITLE
LoggingSeverity isn't exposed in @microsoft/applicationinsights-core-js

### ISSUE THREAD

**Issue by studioab** [microsoft/ApplicationInsights-JS#856]
[!] Error: 'LoggingSeverity' is not exported by node_modules\@microsoft\applicationinsights-core-js\browser\applicationinsights-core-js.min.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
node_modules\@microsoft\applicationinsights-common\dist-esm\Telemetry\Common\DataSanitizer.js (3:9)
1: // Copyright (c) Microsoft Corporation. All rights reserved.
2: // Licensed under the MIT License.
3: import { LoggingSeverity, _InternalMessageId } from '@microsoft/applicationinsights-core-js';
            ^

**Comment by markwolff** [comment]
@studioab Which version are you using? How are you initializing the SDK? AFAIK is it exposed, but may be missing for some specific uncommon scenarios.
https://github.com/microsoft/ApplicationInsights-JS/blob/558ae6ec913e4f13e209400be80b0c6e6f6c78df/vNext/shared/AppInsightsCore/src/applicationinsights-core-js.ts#L15

**Comment by markwolff** [comment]
Closing this as I'm unsure if this is still an issue. Please reopen if this hasn't been resolved

**Comment by sawyerh** [comment]
I also ran into this as well. **Here's a minimal recreation of the issue:https://github.com/sawyerh/applicationinsights-web-issue-856**

I was able to resolve it by manually specifying the named exports in my rollup configuration. Not ideal, but it got past the error:

```js
...
plugins: [
    resolve({
      browser: true
    }),
    commonjs({
      namedExports: {
        "@microsoft/applicationinsights-core-js/browser/applicationinsights-core-js.min": [
          "_InternalMessageId",
          "AppInsightsCore",
          "CoreUtils",
          "DiagnosticLogger",
          "LoggingSeverity"
        ]
      }
    }) 
  ]
```

**Comment by markwolff** [comment]
@sawyerh Thanks for the repro. Out of curiosity, do you have a requirement to use `browser: true`?

**Comment by sawyerh** [comment]
@markwolff No, but my understanding was that using the `browser` bundle would be best for file size? FWIW, I ended up moving away from RollUp and back to Webpack, so this isn't necessarily an issue for me anymore.
