### ISSUE TITLE
appId not auto generating

### ISSUE THREAD

**Issue by lworkman** [microsoft/ApplicationInsights-JS#857]
I'm using `applicationinsights-js` in an Angular 5 app with a node.js backend (running `applicationinsights`). I've been struggling for the past day to get correlation working correctly between the two services, and it seems like the issue has come down to a missing correlation header (`Request-Context`). My analytics class constructor looks like this:
```
    this.appInsightsClient = new ApplicationInsights({
      config: {
        instrumentationKey: "MY KEY HERE",
        enableCorsCorrelation: true,
        disableFetchTracking: false,
        disableCorrelationHeaders: false
      }
    });
    this.appInsightsClient.loadAppInsights();
```
And it appears to track all requests properly _without proper correlation since `Request-Context` is missing_. I could only get `Request-Context` included in the headers by adding a manual `appId`:
```
    this.appInsightsClient = new ApplicationInsights({
      config: {
        instrumentationKey: "MY KEY HERE",
        enableCorsCorrelation: true,
        disableFetchTracking: false,
        disableCorrelationHeaders: false,
        appId: "Editor"
      }
    });
    this.appInsightsClient.loadAppInsights();
```

**Is it necessary to manually set the `appId`**? The typescript definition makes it sound the appId should be automatically set _unless_ you're using the Beacon API.  Although the correlation appears to be working now, I'd like to know if having to set `appId` manually is a bug, intended, or a result of me messing up my setup.

**Comment by jpiyali** [comment]
Manual setup is not required for appId. The setting enableCorsCorrelation and disableCorrelationHeaders should be enough. Are you not seeing these headers setup in your outgoing dependencies from your client?

**Comment by jpiyali** [comment]
Please note only dependency requests sent through with XmlHttpRequest are instrumented.

**Comment by jpiyali** [comment]
Forgot to mention, if you use Fetch, you have to enable tracking explicitly 

disableFetchTracking | true | If true, Fetch requests are not autocollected. Default is true
-- | -- | --

**Comment by lworkman** [comment]
@jpiyali with the below settings:
```
new ApplicationInsights({
  config: {
    instrumentationKey: "MY KEY HERE",
    enableCorsCorrelation: true,
    disableFetchTracking: false,
    disableCorrelationHeaders: false
  }
});
this.appInsightsClient.loadAppInsights();
```

The follow headers are sent:
![image](https://user-images.githubusercontent.com/12467662/57157575-ee796a80-6d95-11e9-93e5-0194cd3b1622.png)

However, if I manually generate the app id I get these headers:

![image](https://user-images.githubusercontent.com/12467662/57157599-0a7d0c00-6d96-11e9-87ea-cae171ce0472.png)

**Comment by jpiyali** [comment]
Does not look correct. Please post version of applicationinsights-js you are using.
Request-Context: appId=cid-v1:{appId} (outgoing dependency) This I believe should be the format in the outgoing request.

@markwolff , @xiao-lix  - please investigate.

**Comment by lworkman** [comment]
I'm using `2.0.0-rc4`.

To be clear, in my example above I set `appId` to manually be `Editor`.

**Comment by jpiyali** [comment]
well, appId is supposed to your applicationId (you can find this under API Key under Table of contents in the azure portal). 

If you dont set up the appId field, the request-context header is missing (is that correct? - this should not be so).

**Comment by lworkman** [comment]
Yes, that's what's happening

**Comment by markwolff** [comment]
Closing as this was added in #866 and dropped in `2.0.0-rc5`

**Comment by lworkman** [comment]
Thanks for the fix!
