### ISSUE TITLE
StopCalledWithoutStart message:"stop was called without a corresponding start."

### ISSUE THREAD

**Issue by aherrick** [microsoft/ApplicationInsights-JS#858]
Am seeing this warning in the Console when trying to Track a Page View? What exactly does it mean and is something not configured correct?

![image](https://user-images.githubusercontent.com/586671/48289946-32bb2c00-e43f-11e8-8c03-f8f2e242f251.png)

**Comment by SergeyKanzhelev** [comment]
@ramthi can you please help with this?

**Comment by markwolff** [comment]
@jwuliger Is it happening on each call or just some to `trackPageView`? Are you using `startTrackPage` or `stopTrackPage` anywhere or do you have a repro for your use case?

**Comment by jwuliger** [comment]
@markwolff I think that this has something to do with change detection in our repo. Unfortunately it is a private organization repro so I can't share it. After diving deeper, it looks like our devs are calling these events in the wrong life-cycle. The warning message that shows; is it something that our team should be concerned about? Or should they fix the life-cycle events? I am just trying to track down performance issues in the app I am working on. Thanks!

**Comment by markwolff** [comment]
@jwuliger Basically it means that the `stopTrackPage` that was called is showing that warning instead of sending your page view duration because it does not have a corresponding `startTrackPage`. It will not affect any other telemetry.

**Comment by ImDmj** [comment]
@markwolff  Any updates on this one? 
I do have a startTrackEvent and i still see this error.

I think the stopTrackEvent is not getting registered or pushed into "_events[names]" while initializing, This  is the one that's being checked and an error is thrown.

For reference - ApplicaitonInsights.js Line 634
