### ISSUE TITLE
Tags from custom telemetry initializer not applied to sent telemetry

### ISSUE THREAD

**Issue by skaempfer** [microsoft/ApplicationInsights-JS#861]
# Environment:
- Package: @microsoft/applicationinsights-web
- Version: 2.0.0-rc4
- Host application: TypeScript based SPA (TS version: 3.0.1 , TS target: ES5)

# Problem
The following code is executed
```typescript
import { ApplicationInsights, ITelemetryItem } from "@microsoft/applicationinsights-web";

const appInsights = new ApplicationInsights({
    config: {
        instrumentationKey: instrumentationKey,
        maxBatchInterval: 1000,
    },
});
appInsights.loadAppInsights();
const tagKeys = new ContextTagKeys();
appInsights.addTelemetryInitializer((item: ITelemetryItem) => {
    item.tags[tagKeys.cloudRole] = "my-cloudrolename";
});

appInsights.trackTrace({ message: "Test message" });
appInsights.flush();
```

The following telemetry data is sent
![ai-telemetry](https://user-images.githubusercontent.com/5021242/57435044-a9918000-723c-11e9-8526-70821690faf4.PNG)

As you can see the tag set in the custom telemetry initializer is not included in the telemetry data (may overwritten in subsequent steps). Adding e.g. custom properties to the telemetry inside the custom initializer works just fine.

Am I missing something here during the configuration or is this a bug?

**Comment by markwolff** [comment]
I will be changing the custom tag interface in the next update so that it matches how you are trying to do it. For now, you can get this working by following the example [here](https://github.com/Azure/react-appinsights/issues/84#issuecomment-486901261).

**Comment by skaempfer** [comment]
Thanks for the hint @markwolff ! Changed the statement accordingly and it works!
