### ISSUE TITLE
beacon API not working in chrome

### ISSUE THREAD

**Issue by valerionatangelo** [microsoft/ApplicationInsights-JS#862]
We tried to enable beacon API but it's not working in Chrome (not desktop nor mobile). Is it a known issue?

**Comment by markwolff** [comment]
This functionality should work with the config option `isBeaconApiDisabled: false`. Is it not sending telemetry with this option set?

**Comment by valerionatangelo** [comment]
We tried this in our application and didn't work in both Chrome desktop and mobile 74, but we didn't have time to isolate this in a minimal environment. We will try to make this test.

Anyone else expirienced this issue?

**Comment by markwolff** [comment]
Please reopen if you have a snippet sample where the beacon api is not working
