### ISSUE TITLE
add support for whitelisting of correlation header domains

### ISSUE THREAD

**Issue by goenning** [microsoft/ApplicationInsights-JS#864]
## Scenarios:

Some times it's easier to whitelist the domains we want to send Correlation Header rather than exclude third party domains. If a third party script changes in a way that a a new XHR request is sent to a non-excluded domain, the request will fail. 

## Proposal:

Add a new configuration (correlationHeaderDomains ?) that supersedes correlationHeaderExcludedDomains.

Correlation headers would only be included if domain is in the correlationHeaderDomains array. If it's empty, then continue with current logic.

**Comment by LeopoldLerch** [comment]
same here. I would like to be able to send the Correlation-Headers only to my service, not to others. Not just because some of them are failing because of the requestHeader (eg the options-Preflight to them), but also it is not necessary as they are not logging to azure anyway.

**Comment by markwolff** [comment]
Thanks for the proposal. I believe this can be done by adding a whitelist check to our existing `Util.canIncludeCorrelationHeader(...)`. I will add this to our planning, but would review a PR you submit as well 👍 

https://github.com/microsoft/ApplicationInsights-JS/blob/5249c7a42977dd52f685814d7a7084d4ae031703/vNext/shared/AppInsightsCommon/src/Util.ts#L609-L612

**Comment by LeopoldLerch** [comment]
Hi,
I tried to do a fork, and made the changes. However, altough i ran the tests successfully, I had some troubles.
There is no build-script (as mentioned in readme), npm run build fails, only test works. How can I build only?
How can I test it with my other solution? I removed applicationinsights-web from the packages and added the one from my fork (leopoldlerch/applicationinsights-js), but that didn´t work out. I got only an old dist-folder with an old version.
Can you help me out with some advice? I am quite new to contributing.
Thx

**Comment by markwolff** [comment]
Sure. First run `npm install` in the root directory. You will also need `npm install -g grunt-cli @microsoft/rush`. We use rush to manage this as a monorepo, so after you've made your changes, `cd` to the `vNext` folder and run
```zsh
rush update
rush build --verbose
```
This will link and build all of the repos. You only need to run `rush update` once. You can run `rush test --verbose`, but this runs all of the tests and takes a quite a bit of time.

Instead, your changes will be in the `vNext/shared/AppInsightsCommon` folder, so you can just run `npm run test` in that directory, once you've built everything. Then you can install this package to your app via modifying your package.json and reinstalling everything.
```
"dependencies": {
  "@microsoft/applicationinsights-web": "file:../some/path/to/applicationinsights-js/vNext/AISKU"
}
```

**Comment by LeopoldLerch** [comment]
Should be supported with PR #869
