### ISSUE TITLE
add support for selecting Requests to add CorrelationHeaders to

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/ApplicationInsights-JS#867]
I want to track all Ajax- and Fetch-Requests.

However, the CORS-Preflights sometimes do not allow that header, and therefore it fails. 

It would be cool to have the possibility, to exclude eg OPTIONS-Requests from adding the correlation Headers

**Comment by markwolff** [comment]
I believe this is a duplicate of #864. Reopen if this is not the case
