### ISSUE TITLE
How to configure Insights in Angular 7 application

### ISSUE THREAD

**Issue by vindemi** [microsoft/ApplicationInsights-JS#871]
I am struggling with initialization of ApplicationInsights class. 
I used:
`npm i --save @microsoft/applicationinsights-web`

and then I tried to put:
```
import { ApplicationInsights } from '@microsoft/applicationinsights-web'

const appInsights = new ApplicationInsights({ config: {
  instrumentationKey: 'YOUR_INSTRUMENTATION_KEY_GOES_HERE'
  /* ...Other Configuration Options... */
} });
appInsights.loadAppInsights();
```

in the **main.ts** or **app.component.ts** file. But still I doesn't receive any global logs from it.

What am I doing wrong?

**Comment by markwolff** [comment]
@vindemi are you seeing anything in the Search blade on your Application Insights resource?
![image](https://user-images.githubusercontent.com/5515583/57640809-3f444c80-7568-11e9-9ea7-79b7378142e5.png)

**Comment by vindemi** [comment]
@markwolff My Insights App is associated with 3 apps (angular, api .net core and function) so search tab is not empty.
Where can I enable this Debug mode?
At this point shall I use instructions from [this](https://www.npmjs.com/package/applicationinsights-js) (applicationinsights-js 1.0.20)? Or try with mentioned above  2.0.0-rc5? But if second I still don't know how to make it works.

**Comment by markwolff** [comment]
enableDebug exists in both versions. Which version are you using? enableDebug goes in config, next to where you put your instrumentation key

**Comment by vindemi** [comment]
@markwolff But where shall I put it on in Angular project to collect data (tracks, errors etc) globally? Or do I need to create some kind of service and put this in particular components?

**Comment by markwolff** [comment]
You can paste the [snippet](https://github.com/microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup) in your index.html or you can use the [npm package setup](https://github.com/microsoft/ApplicationInsights-JS#npm-setup-ignore-if-using-snippet-setup) in a High Order Component you create for your app

**Comment by vindemi** [comment]
@markwolff But still I do not know if it works globally if I put this on app.component.ts or shall I initialize it on each component? In the wiki there is lack of sample angular project.

**Comment by markwolff** [comment]
It will work globally if you put it in app.components.ts

**Comment by markwolff** [comment]
Also consider using [angular-application-insights](https://github.com/TrilonIO/angular-application-insights) which is an angular wrapper written on top of this SDK
