### ISSUE TITLE
ip address is not masked

### ISSUE THREAD

**Issue by mderazon** [microsoft/ApplicationInsights-JS#876]
According to this:
https://feedback.azure.com/forums/357324-application-insights/suggestions/13088763-allow-full-ip-to-be-collected

I understand that app Insights should drop the last octet of an IP (for privacy reasons)

I don't see anything in the code that supports this claim and I couldn't find any document for the correct behavior.

Anybody know what should be the correct behaviour and how we can opt out on sending ip addresses or at least mask it ?

**Comment by markwolff** [comment]
IP address calculations are done on the ingestion side, outside of this SDK. Masking and other behavior of this is not currently configurable. You can collect your own IP addresses and send as a custom property if you'd like them to be "less secure", but I do not believe there is currently solution for masking the entire address.
