### ISSUE TITLE
Do not send navigator.sendBeacon requests if payload > 64KB

### ISSUE THREAD

**Issue by vishwam** [microsoft/ApplicationInsights-JS#880]
Version: 2.0.0-rc.5
Browser: Chrome 74

Repro:
1. Initialize AppInsights with `isBeaconApiDisabled: false` (I want to use this because it ensures pending events are uploaded when the page is closed - useful for debugging automated tests - and it does not block higher priority tasks).
2. Load page and set network to offline (in F12 dev tools) to block telemetry requests.
3. Trigger a bunch of events so the session storage buffer is populated (I tested with ~200 events).
4. Reset network to online and refresh page (to trigger the track request)

Actual: because the payload size now exceeds the browser's limit for beacon requests ([64KB according to SO](https://stackoverflow.com/questions/28989640/navigator-sendbeacon-data-size-limits)), the request is never sent and the buffer queues up indefinitely. The only way to recover is to close the tab and clear the site's data manually.

Expected: AppInsights should either split the payloads so they're below the browser's limit, or fallback to XHR if the payload size > 64KB.

**Comment by xiao-lix** [comment]
I added in this PR: [https://github.com/microsoft/ApplicationInsights-JS/pull/936](url) Should be released, please update to latest version.
