### ISSUE TITLE
Question: which API doc is the source of truth?

### ISSUE THREAD

**Issue by sawyerh** [microsoft/ApplicationInsights-JS#885]
As a new user of this SDK, I'm confused about which API doc I should be referencing in order to learn what arguments I should be passing to methods like `trackPageView`. 

I notice that there are two different `.md` docs in the repo, both with different variations of documentation:

1. [`API.md`](https://github.com/microsoft/ApplicationInsights-JS/blob/c77f231b3e413b205d6986e51c40e360522f0881/API.md)
1. [`API-reference.md`](https://github.com/microsoft/ApplicationInsights-JS/blob/c77f231b3e413b205d6986e51c40e360522f0881/API-reference.md)

Which one should developers reference?

**Comment by markwolff** [comment]
Hi, we are currently in the process of moving around documentation for the v2 release to remove ambiguity on which docs belong to v1 vs v2. They are different npm packages, so choose based on which you are using. The current default README.md for this repo is for v2.
v2 [`@microsoft/applicationinsights-web`](https://www.npmjs.com/package/@microsoft/applicationinsights-web) - [`API.md`](https://github.com/microsoft/ApplicationInsights-JS/blob/master/API.md)
v1 [`applicationinsights-js`](https://www.npmjs.com/package/applicationinsights-js) - [`API-reference.md`](https://github.com/microsoft/ApplicationInsights-JS/blob/c77f231b3e413b205d6986e51c40e360522f0881/API-reference.md)

**Comment by sawyerh** [comment]
@markwolff Thank you, that clarifies it (I'm working with v2) 👍
