### ISSUE TITLE
AuthenticatedUserId not being sent

### ISSUE THREAD

**Issue by vivek201** [microsoft/ApplicationInsights-JS#887]
As per the documentation [here](https://github.com/microsoft/ApplicationInsights-JS/blob/master/API-reference.md#setauthenticatedusercontext), it says that

> The authenticated user id will be available as part of the context of the telemetry sent to the portal, so that you can filter and search on it. It will also be saved as a cookie and sent to the server, where the server SDK (if installed) will attach it to server telemetry.

But the authenticated user Id that I set using the `setAuthenticatedUserContext` method is not being used by the server SDK. Am I missing something?

**Comment by vivek201** [comment]
I've tried that as well but it still isn't working. The server-side is using .NET web api and the ApplicationInsights.Web package. I'm using the same instrumentation key in both client and server side code.

**Comment by vivek201** [comment]
I created a sample project to demonstrate this. Can you please check [this](https://github.com/vivek201/AppInsightsDemo)?

**Comment by markwolff** [comment]
Thanks for the repro. Can you verify if your client is adding a cookie header to its requests to your backend? If so, it seems the server SDK is not correctly parsing session cookies (at least this is the case for my node.js backend demo).
