### ISSUE TITLE
Adding custom properties to request in Azure Functions (Javascript/Typescript)

### ISSUE THREAD

**Issue by andrejpk** [microsoft/ApplicationInsights-JS#888]
I'm building an Azure Function in Typescript and I'm trying to add some custom properties to the request object so I can query the requests to find specific entities.

Here's a mockup of the scenario:

```typescript
import {AzureFunction, Context, HttpRequest} from '@azure/functions';
import appInsights from 'applicationinsights';

appInsights.setup();
const telemetry = appInsights.defaultClient;

const httpTrigger: AzureFunction = async function(
  context: Context,
  req: HttpRequest
): Promise<void> {
  if (!context.res || !context.req)
    throw new Error('context.res or context.req not supplied');

    const {order_id} = req.body;

    // How do I add order_id to the request context that AI already created?

    // do work here
}

export default httpTrigger;

```

looking at the telemetry/client object, I see context that has a key and tag value but I don't see docs on how to add anything here. I don't want to track another event and I'd like to avoid a global telemetry processor if I have to do my parameter parsing in there as well (it's already done inline). Ideally I'd love some simple syntax like ```telemetry.context.customProperties.add('order_id',order_id)```.

**Comment by markwolff** [comment]
Are you relying on the autocollected requests? For Azure Functions, request telemetry is created by the azure function app insights SDK. If you want to modify your telemetry context directly, I'd recommend calling `trackRequest` manually instead, as modifying context is more directly available.

Also the github/docs for SDK you are using is located here https://github.com/microsoft/applicationinsights-node.js

**Comment by andrejpk** [comment]
Thanks, Mark... so since the out-of-box request AI plumbing is sealed, I'll manually track my requests. I'll have to see how to disable the automatic ones so I don't get duplicate request events in AI. I guess that means I'll have to wire in the traces as well. It seems like a lot of extra work but seems like the only way for now.

**Comment by markwolff** [comment]
You can add a telemetry initializer so that IP is added as a property to all telemetry. This lets you modify the envelope before it gets sent out to the ingestion server.
https://github.com/microsoft/ApplicationInsights-JS#telemetry-initializers

Language agnostic overview: https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling

**Comment by andrejpk** [comment]
Hi Mark, by traces I mean the context.log calls that automatically go to the trace object now in AI. I assume I"ll have to wire that in. 

Is the Functions -> AI integration SDK open-source or MSFT-internal? It would be really nice to get some access to that telemetry context to add just a little bit of data. Either that or expose something under Functions' context object beyond log where you can add custom request properties that way.
