### ISSUE TITLE
App Insights for Angular Single Page App showing multiple components all in root (code attached)

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-JS#889]
Hi All,
I have created a very simple sample Angular SPA App and have 2 links Task and PageNotFound which should report under the Application Insights on being clicked but currently all I see in Application Insights is just "/" i.e. Root not sure what is that I have missed in the code. I have attached my sample App whcih has Application Insights code under Service folder. Any help please in sorting this one out so I can see each component/page as a separate entry rather than everything under one single "/" root .
[MySampleWebApp.zip](https://github.com/microsoft/ApplicationInsights-JS/files/3208615/MySampleWebApp.zip)

If you see in the image below, MainPage, TaskPage and coming in sample but not in main view any help?
<img width="858" alt="snipd" src="https://user-images.githubusercontent.com/12475114/58196083-78cb3500-7c97-11e9-902f-c7e99849d73d.PNG">

**Comment by markwolff** [comment]
By default, this SDK does not currently track state based route changes, but it is in the pipeline of improvements to be added. For now you must manually instrument your angular route listener to do this
https://github.com/microsoft/ApplicationInsights-JS#single-page-applications
