### ISSUE TITLE
Please keep the releases on track

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/ApplicationInsights-JS#890]

**Comment by LeopoldLerch** [comment]
In NPM there is version 2 out now. But on github in the releases is still rc5 the last entry. I also missed the changelogs when rc6 was out. 
Please keep that on track so that we can revisit changes before updating code to new versions.

**Comment by markwolff** [comment]
Hi, I have typically been updating the changelog upon releasing to CDN, as this is more broadly used consumption path and users are automatically updated. Lately, I have been updating the CDN the day after the npm package is published.

RC6 is identical to version 2, and as such I decided to combine the two changelogs. Moving forward, I will start posting changelogs after npm publication
