### ISSUE TITLE
Logging in console is not working

### ISSUE THREAD

**Issue by abhi2kollam** [microsoft/ApplicationInsights-JS#892]
I tried with the way which is specified in the documentation. I want to log information in console instead of sending to azure.

consoleLoggingLevel is not working as expected

**Comment by markwolff** [comment]
Hi, consoleLoggingLevel only displays internal errors. If you wish to log telemetry to console you can use a [telemetry initializer](https://github.com/microsoft/ApplicationInsights-JS#telemetry-initializers). 

Here is a function that will log out all telemetry. If the function returns false, the item will not be sent to Azure.
```js
var telemetryInitializer = (envelope) => {
  console.log(envelope);
  return true; // return false instead if you would like to not send this envelope to Azure
};
appInsights.addTelemetryInitializer(telemetryInitializer);
```
