### ISSUE TITLE
Linking together client ajax request target and API nodes on Application Insights map

### ISSUE THREAD

**Issue by jdudleyie** [microsoft/ApplicationInsights-JS#894]
Hi,

I have started using the new v2 version of applicationinsights-js but I still see on my application map that the target node of my angular app's ajax calls is not linked together with my dotnet core API node to which the requests are being made. Is there something else I need to do?

In the picture, I expected the two nodes highlighted with a red square to be the same node on the map, as they are the same node in reality (my dotnet core API running in Kubernetes AKS on Azure).

![image](https://user-images.githubusercontent.com/3493601/58387129-08f3dc00-8002-11e9-9e24-5bcf3a552e30.png)

**Comment by LeopoldLerch** [comment]
Have you enabled the CorrelationHeaders? And do you evaluete them on server side?

**Comment by jdudleyie** [comment]
I don't know what those are, I will do a search later on it. If you have
any link to documentation on that it would be great, if it's not easy to
find.

Thanks.

**Comment by markwolff** [comment]
Can you check to see what the headers are in your outgoing requests to the service? Specifically the request-id header?
https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#correlation-headers

Also, could you view some telemetry in the Search blade between these 2 services and check if they share an Operation Id?

**Comment by jdudleyie** [comment]
I will check and let you know - thanks

**Comment by jdudleyie** [comment]
Hi,

I have attached a csv file which hopefully contains the relevant information. It's a snippet from Azure Log Analytics showing an Ajax request from my angular client, and then the resulting server call to Google API and to my DB. Can you please let me know if this contains the information you were looking for? Thanks.

It's a csv renamed to txt.

[query_data.txt](https://github.com/microsoft/ApplicationInsights-JS/files/3247710/query_data.txt)

**Comment by jdudleyie** [comment]
Hi @markwolff - I was just wondering if you had a chance to look at this? Thanks.

**Comment by markwolff** [comment]
I'm unable to see multiple telemetry items in your query data. Can you click on a sample Dependency or Request telemetry item which you expect to be correlated properly in the Search panel and paste a screenshot? When you click it to view the End-to-end transaction details, do you see both the dependency and request in the Gantt chart?

> *Click the highlighted stuff to get to end-to-end transaction details*
![image](https://user-images.githubusercontent.com/5515583/60552059-35c29f80-9ce2-11e9-9013-62b39286e810.png)

**Comment by jdudleyie** [comment]
Thanks for your help, I was able to get this working by enabling the cors correlation option to send the Request-Id from my client.
