### ISSUE TITLE
How to set cloud role to see the frontend as a component in application Map in azure portal 

### ISSUE THREAD

**Issue by RamYadlapalli** [microsoft/ApplicationInsights-JS#895]
I am using V2.0.0 of @microsoft/applicationinsights-react-js, @microsoft/applicationinsights-web  in my react application and trying to set the cloud role for the web app, so that i can visualize the connections in Application map in Azure portal. 

I'm trying to set cloud role in below manner
`   

            appInsights.addTelemetryInitializer(envelope => {
                envelope.tags["ai.cloud.role"] = "UI";
            });

          `

As per documentation (https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-map#clientbrowser-side-javascript) we need to call addTelemetryInitializer function on appInsights.Context, but in the new version it is available under appInsights not under Context. 

Please let us know how to set cloud role to see the value in Azure Application Map, documentation is so confusing and outdated.

**Comment by LeopoldLerch** [comment]
It is wrong in documentation. It is really an Array that is evaluated. It works for me like this:

`    appInsights.addTelemetryInitializer((envelope) => {
        if (!envelope.tags) {
            envelope.tags = [];
        }
        envelope.tags.push({ "ai.cloud.role": appInsights.config.appId });
    });
`

**Comment by lamuertepeluda** [comment]
@LeopoldLerch this actually worked! Thank you

**Comment by LeopoldLerch** [comment]
U´re welcome. Glad that I could help

**Comment by RamYadlapalli** [comment]
Thanks @LeopoldLerch , created a PR to update documentation https://github.com/MicrosoftDocs/azure-docs/pull/32320
