### ISSUE TITLE
i want to know from azure portal when my application went offline.

### ISSUE THREAD

**Issue by mostafa-raafat** [microsoft/ApplicationInsights-JS#897]
i'm working on an electron-angular app and i'm using ApplicationInsights-JS ,
i want to know from azure portal when my went offline.
i used to do a heartbeat is there any feature i can use to get the same result ?

**Comment by LeopoldLerch** [comment]
I cannot imagine something else. Howe else should it notify Azure when it is offline? The only way is a heartbeat from clientside or (if it makes any sense in your case) polling from server side.

**Comment by morgangrobin** [comment]
In Application Insights, there is a feature called [Availability Testing](https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-web-app-availability). You can configure synthetic tests to make an http request to your application at regular intervals, and create alerts on site availability.
