### ISSUE TITLE
README.md snippet missing setAuthenticatedUserContext

### ISSUE THREAD

**Issue by madaz** [microsoft/ApplicationInsights-JS#900]
The README.md snippet does not include the full API implementation.

e.g. You cant call `window.appInsights.setAuthenticatedUserContext('xxx')`

**Work around**: 
To get it working i changed 

`n("startTrackPage"),n("stopTrackPage")`

to 
`n("startTrackPage"),n("stopTrackPage"),n("setAuthenticatedUserContext")`

**Comment by markwolff** [comment]
Thanks for pointing this out. #902 will fix this. It is the same as your workaround, so you don't need to redo your snippet
