### ISSUE TITLE
v2 window.appInsights.context is undefined and no context.operation 

### ISSUE THREAD

**Issue by madaz** [microsoft/ApplicationInsights-JS#906]
Using the snippet implementation of version 2, I can no longer access `window.appInsights.context`

I have to use `window.appInsights.properties.context`  (This is not documented in the upgrade docs)  Im not sure if this is the correct way?

Also the new `window.appInsights.properties.context` object does not contain the  `operation` object like it does in v1.

I display the `appInsights.context.operation.id`  during debugging support calls for tracking the traces through appinsights queries.

**Comment by markwolff** [comment]
Hi, this was moved to `appInsights.properties.context.telemetryTrace.traceID`. I will update the Upgrade Guide to clarify this!
