### ISSUE TITLE
Dependency tracking with resultCode = 0

### ISSUE THREAD

**Issue by sdurandeu** [microsoft/ApplicationInsights-JS#911]
Hi! This is probably more of a question than an issue. Any ideas of what does it mean that we are seeing client-side dependencies requests with `duration > 0` but `resultCode = 0`? Does this mean that the user closed the browser window? That the request was attempted but never executed due to lack of connectivity?

![image](https://user-images.githubusercontent.com/821193/58801363-3cd29100-8602-11e9-9a56-cb4b8df2c44d.png)

Any guidance will be appreciated,
Thanks!!

**Comment by markwolff** [comment]
Usually this means that no response was received (basically an undefined status code). This could be due to the user going offline, some sort of domain blocking (e.g adblock), or the server responded with nothing.
