### ISSUE TITLE
Confused on using trackEvent or trackPageView or startTrackPage  startTrackPage 

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-JS#914]
Hi All,
We have SPA Angular app and we want it to send telemetry to Azure Application Insights. I understand we have to include the instrumentation class within the SPA Angular App so that telemetry can be sent to Azure App Insights. I read about using trackEvent() and trackPageView() but not sure which one would be the best to use to make sure every PageView is tracked and every Event that happens within the app is also recorded in Application Insights. I read about using Interceptors so that I don't have to make individual calls in each method, this blog mentions about it:- https://ppolyzos.com/2017/10/14/monitor-your-angular-application-using-azure-application-insights/

Can someone please help me in understanding what should I use in my SPA Angular App? trackEvent or trackPageView or the startTrackPage and startTrackPage as the requirement is to capture maximum possible telemetry about the SPA app. Any help?

**Comment by markwolff** [comment]
Please see https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#trackevent
trackEvent is for some notable event occurring in your app. For example, adding an item to your cart.

Page views are an impression on a particular webpage, but not necessarily a notable event. start/stopTrackPage just lets you provide custom timing to the duration of the pageview. By default, trackPageview sends the duration as the loadtime of your page.

**Comment by ketaanhshah** [comment]
thank you @markwolff
