### ISSUE TITLE
NPM Package @microsoft/applicationinsights-react-native is not compiled

### ISSUE THREAD

**Issue by Vstoy001** [microsoft/ApplicationInsights-JS#915]
I am setting up Application Insights on a mobile app to do some frontend related logging.

When creating the React Native bundle, I am encountering the following error:
> error: bundling failed: Error: While trying to resolve module `@microsoft/applicationinsights-react-native` from file `C:\Projects\MobileApp\universalapp\src\services\AIService.js`, the package `C:\Projects\MobileApp\universalapp\node_modules\@microsoft\applicationinsights-react-native\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Projects\MobileApp\universalapp\node_modules\@microsoft\applicationinsights-react-native\dist-esm\index.js`. Indeed, none of these files exist:
  * `C:\Projects\MobileApp\universalapp\node_modules\@microsoft\applicationinsights-react-native\dist-esm\index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\Projects\MobileApp\universalapp\node_modules\@microsoft\applicationinsights-react-native\dist-esm\index.js\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (C:\Projects\MobileApp\universalapp\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (C:\Projects\MobileApp\universalapp\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (C:\Projects\MobileApp\universalapp\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at dependencies.map.result (C:\Projects\MobileApp\universalapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Projects\MobileApp\universalapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
    at C:\Projects\MobileApp\universalapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Projects\MobileApp\universalapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
    at _next (C:\Projects\MobileApp\universalapp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)
 DELTA  [android, dev] ..\..\../index.js ▓▓░░░░░░░░░░░░░░ 14.7% (447/1167), failed.

My dependencies in package.json are

```
"dependencies": {
    "@microsoft/applicationinsights-react-native": "^1.0.0",
    "@microsoft/applicationinsights-web": "^2.0.0",
    "react-native-device-info": "^2.0.2"
}
```

When I check the folders in `C:\Projects\MobileApp\universalapp\node_modules\@microsoft`, I can see that all of the folders, ie `applicationinsights-web` contain `dist` and `dist-esm` folders with compiled code within them. (also the other regular folders such as `src` and `node_modules`)

However, the `applicationinsights-react-native` folder only has `src` and `node_modules` folders.

To resolve this, I have to navigate to the `C:\Projects\MobileApp\universalapp\node_modules\@microsoft\applicationinsights-react-native` directory and run the `tsc` command to have the typescript compile.

With this, I can at least get the `dist-esm` folder which contains the missing files the bundler was missing. With this my app compiles and runs without any further issue.

However, I am maintaining and distributing this app though the Appcenter, which will run into the same bundler issue since I can not perform additional file operations on there.

I'd like to request for the NPM Package to be updated with the properly compiled typescript.

Thanks for any assistance!

**Comment by markwolff** [comment]
It's been republished as 1.0.1 with latest RN versions. you can also rollback to 1.0.0-rc1
