### ISSUE TITLE
AngularJS states as operation names - telemetry not getting captured

### ISSUE THREAD

**Issue by koosala** [microsoft/ApplicationInsights-JS#923]
When using the ai.2.js, I had the issue decsribed in this stackoverflow post: https://stackoverflow.com/questions/56481298/application-insights-in-javascript-angularjs

Dmitry thankfully suggested that this correction was merged a day ago and taking the latest codebase fixed it. 

I then added in a telemetry initializer, which can update the operation name (and also operation id since it looked like just the operation name was not categorizing a telemetry record as a separate operation) as suggested in this post
https://stackoverflow.com/questions/48508883/how-to-set-application-insights-operation-name-from-javascript
```

var sdkInstance = "appInsightsSDK"; window[sdkInstance] = "appInsights"; var aiName = window[sdkInstance], aisdk = window[aiName] || function (e) { function n(e) { t[e] = function () { var n = arguments; t.queue.push(function () { t[e].apply(t, n) }) } } var t = { config: e }; t.initialize = !0; var i = document, a = window; setTimeout(function () { var n = i.createElement("script"); n.src = e.url || "/scripts/plugins/ai/ai.js", i.getElementsByTagName("script")[0].parentNode.appendChild(n) }); try { t.cookie = i.cookie } catch (e) { } t.queue = [], t.version = 2; for (var r = ["Event", "PageView", "Exception", "Trace", "DependencyData", "Metric", "PageViewPerformance"]; r.length;)n("track" + r.pop()); n("startTrackPage"), n("stopTrackPage"); var s = "Track" + r[0]; if (n("start" + s), n("stop" + s), n("setAuthenticatedUserContext"), n("clearAuthenticatedUserContext"), n("flush"), !(!0 === e.disableExceptionTracking || e.extensionConfig && e.extensionConfig.ApplicationInsightsAnalytics && !0 === e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)) { n("_" + (r = "onerror")); var o = a[r]; a[r] = function (e, n, i, a, s) { var c = o && o(e, n, i, a, s); return !0 !== c && t["_" + r]({ message: e, url: n, lineNumber: i, columnNumber: a, error: s }), c }, e.autoExceptionInstrumented = !0 } return t }(
    {
        instrumentationKey: "<<key>>"
    }
); window[aiName] = aisdk, aisdk.queue && 0 === aisdk.queue.length && aisdk.trackPageView({});
appInsights.queue.push(() => {
    appInsights.context.addTelemetryInitializer(envelope => {
        if (window.myVirtualPage !== undefined) {
            envelope.tags['ai.operation.name'] = window.myVirtualPage;
            envelope.tags['ai.operation.id'] = window.myVirtualPage;
        }
    });
});

```

The myVirtulPage is updated every time AngularJS state based routing takes place.

From the browser, the telemetry calls seem to be getting sent ok to the "track" api, with the operation ID and Name set correctly. 

The issue now is that on supplying different opreration name and operation id, though the telemetry is sent to Azure AppInsights, they are not registering as operations. two odd requests - lamsadministrator.userAccessRequest and account.maintenance operations got registered, but the tens of other operation name / id combination does not show up under operations, or even accidentally under already registered operation.

I have attached a text file with two telemetry requests for your reference, with the key guid masked.  Neither of these show up in browser performance. 
[browserTelemetry.txt](https://github.com/microsoft/ApplicationInsights-JS/files/3269184/browserTelemetry.txt)
Can you please advise why this is the behavior, how to correct it or any directions to troubleshoot this issue?

**Comment by markwolff** [comment]
How are you initializing the sdk?

**Comment by koosala** [comment]
Updated the original post to include the complete initialization script (ai.js is JS built from the latest code.

**Comment by markwolff** [comment]
Hey I believe the issue is that `addTelemetryInitializer` is a member of `appInsights`

**Comment by koosala** [comment]
Hi Mark, sorry about the delay in response, I was out for a while. appInsight.addTelemetryInitializer is underfined, and I could find the API only on the context property, similar to the stackoverflow answer. Also, if you see the browserTelemetry.txt file I have attached above, the telemetry seems to be carrying the operation name correctly, just not showing up in azure portal.
