### ISSUE TITLE
Difference between telemetry initializer & plugin?

### ISSUE THREAD

**Issue by andrewconnell** [microsoft/ApplicationInsights-JS#924]
I’ve [read the docs](https://github.com/microsoft/ApplicationInsights-JS/blob/master/API.md#addtelemetryinitializer) on both telemetry initializers and plugins, and I see the difference in the docs, but it’s not clear why I would pick one over the other. It appears I can do the same thing with both of them so I’m not sure if one would make more sense for my situation or not. Can you elaborate with a bit more info on the difference?

**Comment by markwolff** [comment]
Hey @andrewconnell, plugins are a new concept for v2 of the SDK. They are similar in that they both are able to modify telemetry items before being sent out to Application Insights. Telemetry initializers are run after all plugins have finished, whereas plugins can be configured to be run in any order. All plugins also implement an `initialize` method which is run when the SDK installs. This is where this SDK sets up all of its exception, ajax, user/session tracking. For custom plugins, e.g. the React plugin, hooking onto Route and Component changes is also done here. Overall, plugins can be seen as more complex telemetry intializers  that could potentially be published/shared across applications.
