### ISSUE TITLE
Q: Possible with v2 to have “sub instances” of AI?

### ISSUE THREAD

**Issue by andrewconnell** [microsoft/ApplicationInsights-JS#925]
This wasn’t possible in v1 and I’ve been picking through the source of v2 but can’t tell if this is / isn’t possible. Today we are achieving this using a custom proxy, but we’re missing out on a lot of the OOTB AI functionality that we don’t want to dupe...

### Scenario
A hosting web app (SharePoint) that can host multiple sub components (web parts). These sub components may be built by different people and collect their own telemetry. 

Ideal situation is to have AI setup globally in SharePoint, then have the ability for a specific web part to have their telemetry sent to a different AI instance.

Looking at the plugin & initializer APIs, I see the `instrumentationKey?` property... not clear if I can set a plugin that’s conditional checking for specific data in a telemetry post (event/trace/page view/exception/etc) to see if a different AI intrumentation key can be set conditionally for specific submissions to AI... 

Doesn’t appear so... I recall this being a request in the past with v1 and can’t tell if it was implemented in v2 or if the scenario is possible with the new plugin arch.

**Comment by markwolff** [comment]
Yes, you can use a telemetry initializer and modify the `ikey` field of the incoming item, `ITelemetryItem`.
https://github.com/microsoft/ApplicationInsights-JS/blob/96a5125a40229fb5c496a9a799d7deb26aa88b56/vNext/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/ITelemetryItem.ts#L24-L27

**Comment by andrewconnell** [comment]
Interesting... so would the flow be then that wherever this component was added to the page, within it's constructor or equiv `onInit()` event, you'd add the telemetry initializer. Then, within the implementation of the telemetry initializer, you would check "is this from this app" and if so, override the key? Otherwise, it will use the global setup config & key?

My understanding is adding a telemetry initializer is a global thing to the page. So, if you're adding one, you need to add a check to if you want to apply changes such as adding tags, properties or changing the AI key as everything else on the page leveraging AI will be running through your initializer as well... correct?

**Comment by markwolff** [comment]
Yes telemetry initializers are global, so adding one to each will have it run for every telemetry item. Ideally you have just one and it looks for some flag that is unique to telemetry generated by each particular subinstance.

**Comment by andrewconnell** [comment]
Nice... nice addition to the v2 SDK! This will help quite a bit. Thanks for the additional detail!

**Comment by markwolff** [comment]
@andrewconnell Also want to add that you can try creating multiple instances of the SDK. In v1, the SDK was just a singleton static instance, whereas in v2 you can construct multiple independent instances with different instrumentation keys.

**Comment by andrewconnell** [comment]
Oh... that wasn't obvious from the release notes I was picking through. Nice to know as I was going with the above approach to get around this.

Submitted in another issue (#916), but is there an ETA on updated docs for the v2 AI JS SDK?
