### ISSUE TITLE
Allow JS script tag to be inserted with SRI attributes

### ISSUE THREAD

**Issue by piaseckim** [microsoft/ApplicationInsights-JS#926]
Currently the default behavior when instantiating AI client is to inject JS script tag in the head of the page. Modern browsers allows to verify contents of dynamically loaded scripts with subresource integrity checks making such inclusion much safer in terms of XSS attacks.

I'd like to be able to control if script element is created on the page with `integrity` and `crossOrigin` attributes so browser can verify if it's contents has not been changed.
Ideally if this could be the default behavior when AI gets loaded from CDN's url: `https://az416426.vo.msecnd.net/scripts/a/ai.0.js`.

**Comment by markwolff** [comment]
You can generate the hash via https://www.srihash.org/ and modify the snippet to set the specified fields
```html
<script type="text/javascript">
  var appInsights=window.appInsights||function(a){
      function b(a){c[a]=function(){var b=arguments;c.queue.push(function(){c[a].apply(c,b)})}}var c={config:a},d=document,e=window;setTimeout(function(){var b=d.createElement("script");
      b.src=a.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js";
      b.integrity="sha384-SeVeDUKmrHkrSoenouOyjFMT4alVcWrEz3W0lTnlI4nU9qHJ/eAkxqI32j8uq/HB";
      b.crossOrigin="anonymous",
      d.getElementsByTagName("script")[0].parentNode.appendChild(b)});try{c.cookie=d.cookie}catch(a){}c.queue=[];for(var f=["Event","Exception","Metric","PageView","Trace","Dependency"];f.length;)b("track"+f.pop());if(b("setAuthenticatedUserContext"),b("clearAuthenticatedUserContext"),b("startTrackEvent"),b("stopTrackEvent"),b("startTrackPage"),b("stopTrackPage"),b("flush"),!a.disableExceptionTracking){f="onerror",b("_"+f);var g=e[f];e[f]=function(a,b,d,e,h){var i=g&&g(a,b,d,e,h);return!0!==i&&c["_"+f](a,b,d,e,h),i}}return c
  }({
      instrumentationKey: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
  });

  window.appInsights=appInsights,appInsights.queue&&0===appInsights.queue.length&&appInsights.trackPageView();
</script>
```

**Comment by piaseckim** [comment]
Hi @markwolff, thanks for quick response.

The given code example brings to me some more doubts. Calculating SHAs on user/client side seems even more problematic. 
Here're two examples for the given approach where it fails or becomes hard to maintain:
- there's a new release of `ai.0.js` - hash changes - script doesn't load - can't collect logs
- how to deal with sha change in every app in case this code is going to be used very commonly?

My main motivation and intention was to encourage for secure script referencing. `ai.0.js` code is already responsive for creation of the dom element, it potentially could take care of making it more secure way. 

I'm totally aware it makes a huge difference in the matter of the making new releases but I'm hoping it would make also a huge impact on the security for sites using Application Insights (including projects I contribute too :)

Still hoping for `enhancement` tag

Thanks!
