### ISSUE TITLE
v2 trackPageView() crossing multiple instances

### ISSUE THREAD

**Issue by andrewconnell** [microsoft/ApplicationInsights-JS#931]
I have two instances of v2 SDK implemented on my site. I'm seeing what appears to be an undesireable behavior, but might be by design...

### Instance 1: global
One is deployed globally on every page on the site & tied to a specific AppInsights instrumentation key. This one does the following:
- setup instance
- setup authenticated user context
- track page view
- track event with custom data

```ts
const appInsights = new ApplicationInsights({
  config: {
    instrumentationKey: this.properties.aikey,
    maxBatchInterval: 0,
    disableFetchTracking: false
  }
});

// load app insights
appInsights.loadAppInsights();

// set to currently logged in user
appInsights.setAuthenticatedUserContext(this.context.pageContext.user.email);

// track page view
appInsights.trackPageView();

// track event
appInsights.trackEvent(
  { 
    name: 'spfx_appcustomizer_loaded', 
    properties: {
      site_id: this.context.pageContext.site.id,
      web_id: this.context.pageContext.web.id,
      web_title: this.context.pageContext.web.title,
      web_desc: this.context.pageContext.web.description
    }
  }
);
```

### Instance 2: local
The other is deployed on one specific page & tied to a different AppInsights instrumentation key. This one does the following:
- setup instance
- setup react plugin
- setup telemetry init
- track trace with custom data

```ts
const history = createBrowserHistory({ basename: '' });

const appInsights = new ApplicationInsights({
  config: {
    instrumentationKey: AZURE_APPINSIGHTS_INSTRUMENTATIONKEY,
    maxBatchInterval: 0,
    disableFetchTracking: false,
    extensions: [TelemetryService.getReactPluginInstance()],
    extensionConfig: {
      [TelemetryService.getReactPluginInstance().identifier]: { history: history }
    }
  }
});

// load app insights
appInsights.loadAppInsights();

// add component name & version to every telemetry call
appInsights.addTelemetryInitializer((envelope: ITelemetryItem) => {
  envelope.data['app_name'] = AZURE_APPINSIGHTS_APPLICATIONNAME;
  envelope.data['app_version'] = '[AIV]{version}[/AIV]';
});

appInsights.trackTrace( {message: 'Initialized AI in web part', severityLevel: SeverityLevel.Information } );
```

When I hit the page & inspect, I see traces, authenticated user context data, the initializer etc in the correct App Insights instances... except for the page view. The page views are showing in both... the same page view has different operation IDs, but the user ID & session ID are the same... the two pictures show the different instances & I've highlighted the specific parts

### Instance 1 (global)
Notice the instance named **masteringspfx** (top right), **Auth ID** is set because I've set the user context, and the custom properties are limited to just one (nothing added by the telemetry initializer as that's in the other instance):

![image](https://user-images.githubusercontent.com/2068657/59285031-4c259000-8c3b-11e9-889e-54090192b723.png)

### Instance 2 (local)
Notice the instance named **masteringspfx-subinstance** (top right), **Auth ID** is not specified  & custom properties are missing from the telemetry initializer in this instance:

![image](https://user-images.githubusercontent.com/2068657/59285248-afafbd80-8c3b-11e9-85b8-7c0e1a437324.png)

The following shows when I select the trace event from the second instance and how values are added from the telemetry init:

![image](https://user-images.githubusercontent.com/2068657/59285710-67dd6600-8c3c-11e9-8cbd-3bd0867cb7ab.png)

What does this show? It shows a call from the `trackPageView({})` in one instance is showing up across all instances. Is this **by design**? If so... why when other things don't appear to be doing that?

**Comment by markwolff** [comment]
@andrewconnell Hi, can you try setting a unique `namePrefix` config option for each instance?

**Comment by andrewconnell** [comment]
That fixed it... wasn't aware of this property. I see it was listed in the docs on the repo's root README, but not in the `IConfig` interface. Submitted PR #938 to fix this. Thanks @markwolff
