### ISSUE TITLE
xhr request issue in chrome

### ISSUE THREAD

**Issue by kieranjohn** [microsoft/ApplicationInsights-JS#934]
I am getting an error in chrome(74) when sending a tracking request. 

- It is a client-side application (angular 8)
- using package "@microsoft/applicationinsights-web": "^2.0.1",
- could be related to #862 

My config looks like this.
```
const appInsights = new ApplicationInsights({
config: {
    instrumentationKey: environment.appInsights.instrumentationKey,
    correlationHeaderExcludedDomains: ["xxxxx.b2clogin.com"],
    enableDebug: true,
    consoleLoggingLevel: 2,

    enableCorsCorrelation: true,
    disableFetchTracking: false,
    disableCorrelationHeaders: false,
},
});
this._appInsights = appInsights.loadAppInsights();
```

When in Chrome I get the following for an options request
![chrome-74](https://user-images.githubusercontent.com/1954155/59313182-3ffd0980-8cf3-11e9-8956-b4feb60a7271.png)

When in edge the CORS error is not present
![ie-edge2](https://user-images.githubusercontent.com/1954155/59313524-c36b2a80-8cf4-11e9-9599-b7ac30ddd6e2.png)

As you can see no other logs are output despite the debug option and console log level. Would appreciate your help on this one.

**Comment by markwolff** [comment]
Can you add `"*.visualstudio.com"` to your list of `correlationHeaderExcludedDomains` and report back on the results?

**Comment by kieranjohn** [comment]
Thanks for your quick response. 

I have added the following 
`"*.visualstudio.com"` and then on after tried explicitly adding `"dc.services.visualstudio.com"` to the `correlationHeaderExcludedDomains` and have the same result.

I have cache disabled in the chrome XHR options but it is still reporting 
I cleared cache (empty cache and hard reload) but still get
`Status Code: 200 OK (from disk cache)`

I am not sure why it is so difficult to remove it from the cache. 
The cached response has no headers like `ETag`, `Cache-Control`, `Expires`, `Last-Modified`

**Comment by kieranjohn** [comment]
Closing this issue. not sure why it started working but:

- clearing the cache did not help even removing the cached from AppData (windows)
- Chrome has stopped making the OPTIONS request to this resource.

**Comment by elvirdolic** [comment]
We are facing the same issue.

Access to XMLHttpRequest at 'https://dc.services.visualstudio.com/v2/track' from origin 'https://paldesk.palfinger.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.

Version 76.0.3809.100
