### ISSUE TITLE
Application Insights fails with Angular 5 giving 404

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-JS#941]
Hi All,
One of my team is working on implmenting  Azure App Insights with there Angular 5 developed SPA app and whenever they include the required App Insights library they receive following error:-

Failed to load resource: the server responded with a status of 404 (Not Found)
details:194 Error
(anonymous) @ details:194
node_modules/@angular/core/bundles/core.umd.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
node_modules/@angular/forms/bundles/forms.umd.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
node_modules/@angular/common/bundles/common-http.umd.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
node_modules/@angular/common/bundles/common.umd.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
node_modules/@angular/router/bundles/router.umd.js:1 Failed to load resource: the server responded with a status of 404 (Not Found) 

Not sure what is going wrong here and why get a 404, This is Angular 5 app.
Any insights on how we can fix it?

**Comment by markwolff** [comment]
can you post a code snippet

**Comment by ketaanhshah** [comment]
hi @markwolff sorry for the delay in responding, I have asked my dev team to let me know where exactly and when we get this issue, is it just when we add the required nugget packages and call some method. I will get back to you on this one.

**Comment by markwolff** [comment]
Closing this for now. Please comment again if you'd like it to be re-opened
