### ISSUE TITLE
How to read or get appInsights's  SessionID

### ISSUE THREAD

**Issue by satyarapelly** [microsoft/ApplicationInsights-JS#943]
Hi, 

We are trying to session Id i.e. ai.session.id value after we load the appInsights using appInsights.loadAppInsights().

Please help us in getting the ai.session.id value using appInsights objects in Javascript.

Thanks
satya R

**Comment by markwolff** [comment]
Hi you can use 
`appInsights.context.sessionManager.automaticSession`
