### ISSUE TITLE
How do I initialize 2 separate instances in the same window

### ISSUE THREAD

**Issue by Itazulay** [microsoft/ApplicationInsights-JS#944]
Today, If I want my site to have 2 different instances (with 2 different instrumentation keys) I cannot initialize them on the same window as the appInsights JS code is pinned to be initialized through the single variable "window.appInsights".

This causes an override of the second initialization and basically disables the option of having more than 1 instances on the same window.

This is not a theoretical concern, unfortunately I have to retrieve a custom application insights code from my server with the specific change of getting the initialization for a second variable name.

**Comment by markwolff** [comment]
Can you use npm? You can use the npm package of the v2 SDK and just construct 2 separate instances of ApplicationInsights. Be sure to set a unique `namePrefix` for each in the config.

https://npmjs.com/package/@microsoft/applicationinsights-web

**Comment by Itazulay** [comment]
@markwolff - That's the part I wanted to avoid.
I wanted to to use appInsights.js and and initialize 2 instances out of the box.
