### ISSUE TITLE
× Error: Core should not be initialized more than once

### ISSUE THREAD

**Issue by musema** [microsoft/ApplicationInsights-JS#953]
I have a react component which uses AppInsights for telemetry, and the consumers of my component has also their own instance of AppInsights , looks like we can't have two different instances of AppInsight on the same window, I think the root cause is,  core.js dependency.

**Comment by markwolff** [comment]
Are you using the snippet or the npm package to initialize the SDK?

**Comment by musema** [comment]
I am using [npm ](https://www.npmjs.com/package/@microsoft/applicationinsights-web) package

**Comment by diegomichell** [comment]
I'm still getting this error on iOS
