### ISSUE TITLE
Application Insights Logs Exception at trackException Method repeatedly

### ISSUE THREAD

**Issue by sudarshan1933** [microsoft/ApplicationInsights-JS#955]
I have Angular 5 Web App in which I have configured the Application Insights js of version 1.0.20 (applicationinsights-js). [https://www.npmjs.com/package/applicationinsights-js]

Following Exception was getting logged continuously in our Production Application Insights because of which lot of users are getting impacted.

Application Insights Logs Exception at trackException Method repeatedly in its own assembly "https://az416426.vo.msecnd.net/scripts/a/ai.0.js"

Please do the needful. Thanks in advance!!!
[Please find this Logs for Reference](https://i.stack.imgur.com/8Qp28.jpg)

**Comment by markwolff** [comment]
Can you please post a repro

**Comment by sudarshan1933** [comment]
> Can you please post a repro

Can you please elaborate what do you mean "repro" ? Sorry, I didn't get you...

**Comment by markwolff** [comment]
Can you provide more details on your scenario or a code snippet that I can use to reproduce this issue?

**Comment by sudarshan1933** [comment]
`@Injectable()
export class ApplicationInsightsService {
ikey: string;

  constructor(private http: HttpClient) {
this.initializeApplicationInsights();
}

 public initializeApplicationInsights() {
    if (sessionStorage.getItem('ikey')) {
      AppInsights.downloadAndSetup({ instrumentationKey: sessionStorage.getItem('ikey') });
    }
  }

 //Track an exception in Appinsights
  public logException(e: Error, handledAt?: string, properties?: any, measurements?: any) {
    AppInsights.trackException(e, handledAt, properties, measurements);
  }

}
`

And In Angular, I have Global Error Handler, 
where we logged the Exceptions. 
const applicationInsightsService = this.injector.get(ApplicationInsightsService);
applicationInsightsService.logException(error);

**Comment by markwolff** [comment]
Are there multiple instances of application insights running in your app? Also are you able to try v2 of the SDK? It better handles these types of scenarios
https://github.com/microsoft/applicationinsights-js#npm-setup-ignore-if-using-snippet-setup

**Comment by sudarshan1933** [comment]
> Are there multiple instances of application insights running in your app? Also are you able to try v2 of the SDK? It better handles these types of scenarios
> https://github.com/microsoft/applicationinsights-js#npm-setup-ignore-if-using-snippet-setup

Hi Mark, 
As posted previously, I have following Method which initialize ApplicationInsights. 
`public initializeApplicationInsights() {
    if (sessionStorage.getItem('ikey')) {
      AppInsights.downloadAndSetup({ instrumentationKey: sessionStorage.getItem('ikey') });
    }
  }`
and Just now I checked this initializeApplicationInsights() method called multiple time during the Page loads. I have 2 questions. 

1. As initializeApplicationInsights() method called multiple times, Does it cause the Problem?  
2. Do we need to initialize ApplicationInsights when user opens the application in another TAB in the same browser?

**Comment by markwolff** [comment]
It is not ideal to call it multiple times, I'm not aware of it causing any issues though. App insights is added to the window object, and so each tab can its own app insights instance.
