### ISSUE TITLE
applicationinsights-react-native - jest failing

### ISSUE THREAD

**Issue by MakhouT** [microsoft/ApplicationInsights-JS#959]
I am using `@microsoft/applicationinsights-react-native` and when running my tests I am getting this:

> Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     /Users/makhout/Documents/Projects/DLWR.xAnywhere/clients/core/node_modules/@microsoft/applicationinsights-react-native/dist-esm/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { ReactNativePlugin } from './ReactNativePlugin';
>                                                                                                     ^
> 
>     SyntaxError: Unexpected token {
> 
>       3 |   SeverityLevel,
>       4 | } from '@microsoft/applicationinsights-web';
>     > 5 | import { ReactNativePlugin } from '@microsoft/applicationinsights-react-native';
>         | ^
>       6 | 
>       7 | const RNPlugin = new ReactNativePlugin();
>       8 | 
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
>       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
>       at Object.<anonymous> (src/utils/appInsights.utils.js:5:1)
> 

I've done as the docs said and added in my jest config `"node_modules/(?!(@microsoft/applicationinsights-react-native)/)"`
But that still doesn't do the trick. What is wrong with this plugin?

**Comment by MakhouT** [comment]
Found the solution.
In your jest config the following snippet was needed:

`    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|jestError|@microsoft|@react-native-community|react-native-navigation)/)"
    ],
`

**Comment by markwolff** [comment]
Thanks for posting your solution. Seems related to #891, which required some rollup config changes to resolve. Will look into a proper RCA for this
