### ISSUE TITLE
support for vs2015?

### ISSUE THREAD

**Issue by bengreenier** [Microsoft/ApplicationInsights-JS#96]
I realize the instructions say use vs2013, but is there support for vs2015? Or plans to support it?

**Comment by MaxShehovtsov** [comment]
It shouldn't be much different, it's a matter of trying it and perhaps solving couple of typescript issues. Some people compile it with Visual Studio code.
Try and let us know what issues you hit.

**Comment by bengreenier** [comment]
i get a failure [here](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK/JavaScriptSDK.csproj#L33) due to the following missing on my machine - commenting it out let's me load the project fine, though i'm not sure what functionality i may be missing.

```
<Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
```

a quick search leads me to believe that swapping that for a reference derived from [this nuget package](https://www.nuget.org/packages/MSBuild.Microsoft.VisualStudio.Web.targets/) would work. [source](http://stackoverflow.com/questions/25047714/microsoft-webapplication-targets).

Perhaps i'll submit a PR with this change when i have a spare moment.

**Comment by MaxShehovtsov** [comment]
Thanks for looking into this!

**Comment by bengreenier** [comment]
see #97

**Comment by kamilszostak** [comment]
Do you still see this issue in VS 2015? For me it worked without any changes. 
I see that the `Microsoft.WebApplication.targets` file is present in both version of Visual Studio: 2013 and 2015 and VSToolsPath always points to the right directory. 
![image](https://cloud.githubusercontent.com/assets/12164228/13301404/9063dac0-daf9-11e5-8a69-231e5420420f.png)

The only scenario when it didn't work for me was when I tried opening the solution in VS 2015, but I used Developer Command prompt for VS 2013. It looks like the older command prompt is overriding the VSToolsPath variable. 

If you don't mind, I'll close this issue. Please re-open if you want to discuss.
