### ISSUE TITLE
React plugin version 2.1.0 | TypeError: Cannot read property 'throwInternal' of undefined

### ISSUE THREAD

**Issue by xZliman** [microsoft/ApplicationInsights-JS#960]
### When trying to update 
> @microsoft/applicationinsights-react-js from 2.0.1 to 2.1.0

###  Error log messages
> TypeError: Cannot read property 'throwInternal' of undefined

### Desired behavior
> To run as expected before updating to version 2.1.0

Currently trying to use 2.0.1, because 2.1.0 is broken

**Comment by markwolff** [comment]
Should be fixed in 2.1.1
Thanks for the report!
