### ISSUE TITLE
Unable to pass customProperties to TrackException 

### ISSUE THREAD

**Issue by pchevilley** [microsoft/ApplicationInsights-JS#963]
Hi,

In the [doc](https://github.com/microsoft/ApplicationInsights-JS/blob/master/API.md), it says we can pass custom properties to the trackException method, but it looks like it only accepts one parameter ( IExceptionTelemtry ).
Is it a bug or is the documentation out of date?
How can I pass additional data to my exceptions in order to filter my reports without it?

thanks!

**Comment by markwolff** [comment]
Thanks for pointing this out. Looks like the docs need to be updated, but the `IExceptionTelemetry` interface is correct.
```js
appInsights.trackException({ exception: new Error(), properties: { foo: 'bar' } })
```
