### ISSUE TITLE
after 3 min of being offline the insights not sending any request  

### ISSUE THREAD

**Issue by mostafa-raafat** [microsoft/ApplicationInsights-JS#966]
after 3 min of being offline analytics not being saved to sessionStorage 
and i keeping get this error on option requests 

![Screen Shot 2019-07-10 at 5 35 56 PM](https://user-images.githubusercontent.com/43439787/60982898-4950b480-a339-11e9-817e-894582ffa017.png)

**Comment by markwolff** [comment]
What is the error?

Also as a note, this SDK uses exponential fallback timing. This means that the longer the user is offline, the longer we will wait to retry again the next time.

https://github.com/microsoft/ApplicationInsights-JS/blob/c9397161cd1ac9fb2b8faa80e4b4b3d561bd51e0/vNext/channels/applicationinsights-channel-js/src/Sender.ts#L591-L594
