### ISSUE TITLE
enableAutoRouteTracking has wrong page name

### ISSUE THREAD

**Issue by vishwam** [microsoft/ApplicationInsights-JS#967]
Version: 2.1.0

PageView events emitted via enableAutoRouteTracking are logged before the SPA code has the chance to change the title, so they currently end up with name=old title, url=new url.

Can you please add a timeout before the event is logged, similar to [the react plugin ](https://github.com/microsoft/ApplicationInsights-JS/blob/master/vNext/extensions/applicationinsights-react-js/src/ReactPlugin.ts#L87)?

(This should ideally also be changed to use window.requestIdleCallback if available so we don't block the SPA rendering)

**Comment by markwolff** [comment]
Thanks for the report. Fixed in `2.1.1`
