### ISSUE TITLE
enableAutoRouteTracking should update refUri

### ISSUE THREAD

**Issue by vishwam** [microsoft/ApplicationInsights-JS#969]
Version: 2.1.0

Expected: The refUri in PageView events emitted by enableAutoRouteTracking should be set to document.referer only on the initial SPA load. All subsequent location changes should have uri=new href, refUri=current href.

Actual: the refUri is always set to the original document.referer

**Comment by markwolff** [comment]
Fixed in `2.1.1`

**Comment by markwolff** [comment]
Thanks for the report! Fixed in `2.1.1`

**Comment by vishwam** [comment]
@markwolff It looks like with this update, the refUri is not populated anymore for browser history changes. Is there any reason for this behavior? This prevents us from doing queries like "count of users who went from Page A to Page B".

If we're not in a single page app, the refUri would be populated correctly with the user's previous URL. I'd expect the same behavior in a SPA.
