### ISSUE TITLE
Configuration documentation for JS SDK snippet

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/ApplicationInsights-JS#971]
I’m having trouble consuming the JS SDK. I’m not able to use the NPM setup for my purposes, and the provided snippet is also not what I want. For my application, initializing telemetry should be done at a later point in time than page load, since we need to read a settings file to determine if telemetry is on and grab the aiKey from another file.

I’m trying to simply include a script tag to https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js and initialize it from something like`globalThis.Microsoft.ApplicationInsights()`. This results in the same error as https://github.com/microsoft/ApplicationInsights-JS/issues/855. I’ve tried various other methods on ApplicationInsights and haven’t been able to get into an initialized state.

1. Is it possible to provide a more human readable snippet for loading the JS SDK?
2. What is the correct way to initialize the library, and how should a config be passed or updated?

**Comment by markwolff** [comment]
> 1. Is it possible to provide a more human readable snippet for loading the JS SDK?

Unminified snippet is located [here](https://github.com/microsoft/ApplicationInsights-JS/tree/master/vNext/AISKU/snippet)

> 2. What is the correct way to initialize the library, and how should a config be passed or updated?

Here is a blog post explaining what is going on in the snippet http://apmtips.com/blog/2015/03/18/javascript-snippet-explained/
Configuration options are placed after your instrumentation key in JSON format.

>  For my application, initializing telemetry should be done at a later point in time than page load, 

You can attach the JS part of the "snippet" at runtime in your app via below link, which can be done at any time. https://stackoverflow.com/questions/18784920/how-to-add-dom-element-script-to-head-section

**Comment by RMacfarlane** [comment]
Thanks @markwolff, much appreciated!

**Comment by nareshbonagiri** [comment]
@markwolff : I am using the below script in dynamics 365  online to write telemetry, but hitting #855 

 var sdkInstance="appInsightsSDK";window[sdkInstance]="newappInsights";var aiName=window[sdkInstance],aisdk=window[aiName]||function(e){
        function n(e){t[e]=function(){var n=arguments;t.queue.push(function(){t[e].apply(t,n)})}}var t={config:e};t.initialize=!0;var i=document,a=window;setTimeout(function(){var n=i.createElement("script");n.src=e.url||"https://az416426.vo.msecnd.net/next/ai.2.min.js",i.getElementsByTagName("script")[0].parentNode.appendChild(n)});try{t.cookie=i.cookie}catch(e){}t.queue=[],t.version=2;for(var r=["Event","PageView","Exception","Trace","DependencyData","Metric","PageViewPerformance"];r.length;)n("track"+r.pop());n("startTrackPage"),n("stopTrackPage");var s="Track"+r[0];if(n("start"+s),n("stop"+s),n("setAuthenticatedUserContext"),n("clearAuthenticatedUserContext"),n("flush"),!(!0===e.disableExceptionTracking||e.extensionConfig&&e.extensionConfig.ApplicationInsightsAnalytics&&!0===e.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)){n("_"+(r="onerror"));var o=a[r];a[r]=function(e,n,i,a,s){var c=o&&o(e,n,i,a,s);return!0!==c&&t["_"+r]({message:e,url:n,lineNumber:i,columnNumber:a,error:s}),c},e.autoExceptionInstrumented=!0}return t
        }({
            instrumentationKey:""
        });
      
      window[aiName]=aisdk,aisdk.queue&&0===aisdk.queue.length&&aisdk.trackPageView({});


![image](https://user-images.githubusercontent.com/15263773/61297844-b90fe500-a7fa-11e9-9a79-1cc140e0517e.png)
