### ISSUE TITLE
Issue with CorrelationId header 'Request-Id' Duplicate operatoinId in AppInsights portal

### ISSUE THREAD

**Issue by srbalakr** [microsoft/ApplicationInsights-JS#976]
Environment: 
@microsoft/applicationinsights-react-js@2.1.1
@microsoft/applicationinsights-web@2.1.0
Microsoft_ApplicationInsights_AspNetCore: 2.7.0
Microsoft_ApplicatoinInsights: 2.10.0

We are seeing duplicate operationId in AppInsightsPortal. 

RequestId format by js sdk: | < rootid >  .< parentid >
On debugging, it looks like the correlation header 'request-id' added by appInsights-js sdk c
does not change rootid of the request but parentId

Two apis with different requestId but has same rootId
[Issue Doc.docx](https://github.com/microsoft/ApplicationInsights-JS/files/3412799/Issue.Doc.docx)

has the same rootid part due to which, server parses same rootid per user per session as operationId and we see it in portal. Is this a bug or configuration issues ?

**Comment by markwolff** [comment]
For client-side SDKs, an operation id is only updated on a new pageview. If you refresh the page or view another page in your app, the rootid should update
https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#example

**Comment by srbalakr** [comment]
Oh ok in that case, for a single page application, if we fire multiple request from same page , it will cause duplicate operationId in AppInsightsportal causing hard to view each individual request. Is there any other way to overcome ?

**Comment by markwolff** [comment]
It seems like the Dependencies tab is showing the data you are looking for
![image](https://user-images.githubusercontent.com/5515583/61568089-b7cafc00-aa36-11e9-853a-9d0ae3c62f76.png)

**Comment by srbalakr** [comment]
Thanks @markwolff . For SPA how does correlation. From my understanding operationId do not change? How else can we ident
case 1: SPA ->(req1) svc1 ; SPA ->(req2) svc1
case 2: SPA ->(req3) svc1 calls svc2 and svc3; SPA ->(req4) svc1 calls svc3 and svc4 ?

**Comment by markwolff** [comment]
You can configure your app to change operationId on each route change via `enableAutoRouteTracking: true`

https://github.com/microsoft/ApplicationInsights-JS#single-page-applications

**Comment by srbalakr** [comment]
Cool. thanks.
