### ISSUE TITLE
Usage with NextJS ?

### ISSUE THREAD

**Issue by Djiit** [microsoft/ApplicationInsights-JS#977]
I'm looking for example implementation in a https://github.com/zeit/next.js/ project ?
I'm interested in how do you wire up the router ? Do you use the separate node-js lib for SSR ?

Thanks !

**Comment by goenning** [comment]
Hey @Djiit 

I have recently created this package ( https://npmjs.com/package/next-applicationinsights )

But it's currently only tracking CSR events, pageView and exceptions.

I do want to add SSR, but haven't got a chance to implement that yet.

**Comment by HanliTheron** [comment]
Hey @goenning ,

First off, thanks for this package, I'm new to both Next and App Insights so this is helping me understand how both work. 

I added google analytics to the Next app first to see if I could get it to work and it works perfectly, but when I try app insights I struggle. It seems to work for some stuff, but not everything. 

For example I can't see any page views being logged. Also in the application map I can see one of the external APIs I call, but not the other even though I can verify that it indeed being consumed and returning a response. Can this be something to do with my Next app not being configured correctly? 

Also, do you possibly plan on letting the package expose a method to do custom event logging? 

P.S. I'm aware I don't need both google analytics and app insights. I just wanted to try and see if I could get the packages working with Next.

Thanks!

**Comment by HanliTheron** [comment]
Hey @Djiit,

Did you ever get app insights working correctly with Next?

**Comment by HanliTheron** [comment]
I've solved my issue. My app wasn't correctly configured on production. Logging custom events myself and using the package to use the ai to track page views etc.

**Comment by Djiit** [comment]
HEy @HanliTheron , yup, we are still using it on a quite big production website without any issue. We don't track deep events and all the page transitions/views, but it's doing a great job so far on client side.

**Comment by HanliTheron** [comment]
Hey @Djiit,
Thanks appreciate the reply. That's great news, I'll definitely play around with it some more, so far everything just works.
