### ISSUE TITLE
enableAutoRouteTracking should populate refUris on browser history changes

### ISSUE THREAD

**Issue by vishwam** [microsoft/ApplicationInsights-JS#979]
[Related to #969, but the issue was marked as closed]

Version: 2.1.1

It looks like with #970, the refUri is not populated anymore for client-side browser history changes. Is there any reason for this behavior? This prevents us from doing queries like "list of users who went from Page A to Page B".

If we're not in a single page app, the refUri would be populated correctly with the user's previous URL for all page navigates. I'd expect the same behavior in a SPA.

**Comment by xiao-lix** [comment]
This is solved in this pr: https://github.com/microsoft/ApplicationInsights-JS/pull/983
