### ISSUE TITLE
TrackException not sending to AI in Angular 6

### ISSUE THREAD

**Issue by davec643** [microsoft/ApplicationInsights-JS#981]
I'm currently having an issue with my custom exception tracking code sending to App Insights from Angular. Nothing is appearing on the other end. 

The only issue I can see in the console potentially causing this is a failed _POST request to https://dc.services.visualstudio.com/v2/track responding with a 400 Bad Request - 106: Field 'exceptions' on type 'ExceptionData' is of incorrect type. Expected: array, Actual: undefined_

From what I can see, the ExceptionData being sent up is lower level than what I have control over. Is this an issue with the library?

```
import { Injectable } from '@angular/core';
import { ApplicationInsights, IExceptionTelemetry } from '@microsoft/applicationinsights-web';
import {environment} from '../../environments/environment';

@Injectable({
    providedIn: 'root'
})
export class ApplicationInsightsService {

    private appInsights: ApplicationInsights;

    constructor() {
                
        this.appInsights = new ApplicationInsights({
            config: {
                instrumentationKey: environment.appInsightsKey,
                disableExceptionTracking: true
            }
        });
        this.appInsights.loadAppInsights();
    }

    setUserId(userId: string) {
        this.appInsights.setAuthenticatedUserContext(userId);
    }

    clearUserId() {
        this.appInsights.clearAuthenticatedUserContext();
    }

    logPageView(name?: string, uri?: string) {
        this.appInsights.trackPageView({ name, uri });
    }
    
    logException(errorId: string, errorMessage: string) {
        let exception: IExceptionTelemetry = {
            id: errorId,
            exception: {
                name: errorMessage,
                message: errorMessage
            }
        };
        
        this.appInsights.trackException(exception);
    }
}
```

EDIT: After setting disableTelemetry to true, it doesn't seem to send anything at all now... the plot thickens.

**Comment by markwolff** [comment]
When you are creating your `IExceptionTelemetry`, the `exception` field expects type `Error | string` because we try to extract some callstack stuff out for you if it is a nonstring Error, else we just create a  `new Error(string)` from the provided `string` and go from there.

Are you able to do `exception: new Error(errorMessage)`

**Comment by davec643** [comment]
I actually did manage to get an exception logging when instantiating a new Error(string), but I had also re-enabled the sending of telemetry and assumed that it was that which cured it. I'll try again tomorrow when in work! Thanks.
