### ISSUE TITLE
logging protractor e2e logs to application insights

### ISSUE THREAD

**Issue by krishnasingh1818** [microsoft/ApplicationInsights-JS#982]
hi,

i have protractor e2e tests which run to test different workflows from user perspective.  As part of e2e test we have written some console.logs for debugging and trouble shooting purposes. Is there a way i could send this logs to application insights . This will help to write queries to answer questions like most failing paths etc.
I tried using application insight js lib but it was erroring out with some window underfined error. 
please share if any links or pointers.  thanks you.

**Comment by markwolff** [comment]
You can use `trackTrace` instead of `console.log` to send your telemetry as "log telemetry"
