### ISSUE TITLE
[v2] Function does not exists for addTelemetryInitializer()

### ISSUE THREAD

**Issue by tbolon** [microsoft/ApplicationInsights-JS#985]
The current readme suggest adding telemetryInitializers using the `appInsights.addTelemetryInitializer(telemetryInitializer);`.

This method is not defined in the snippet when building lazy methods. As of now, we have to manually queue the method call.

You should create the lazy method proxy in the snippet.

**Comment by xiao-lix** [comment]
Updated in this pr: https://github.com/microsoft/ApplicationInsights-JS/pull/996 
With the update, you don't need to manually queue the method.
