### ISSUE TITLE
Exclude a specific route from automatic AJAX tracking?

### ISSUE THREAD

**Issue by sawyerh** [microsoft/ApplicationInsights-JS#987]
I think the answer to this is "No," but is there a way to exclude a specific route from the automatic AJAX call tracking? If not, I'd like to request this as a feature enhancement.

My use case is that I have a "status endpoint," that is frequently pinged in order to check a user's upload status. This endpoint gets a lot of requests, and I'd rather not include it in the AJAX tracking. 

I enjoy the automatic tracking that comes out of the box, and it's not super clear from the documentation how I'd get the necessary data that `trackDependency` needs, so I'd prefer to have the option to exclude or temporarily disable a dependency from being tracked.

**Comment by xiao-lix** [comment]
Hi, we have a way to exclude specific route from automatic tracking: 

For XMLHttpRequest, you can add this to your request before open and send: 
`
xhr["Microsoft_ApplicationInsights_BypassAjaxInstrumentation"]=true
`

For Fetch request, you can add this to the fetch input: 
`
{
    Microsoft_ApplicationInsights_BypassAjaxInstrumentation: true
}
`

**Comment by sawyerh** [comment]
@xiao-lix Is this documented somewhere?

**Comment by xiao-lix** [comment]
Hi @sawyerh it's an internal flag and no one has asked about it before, thanks.

**Comment by sawyerh** [comment]
@xiao-lix They may not have asked because it's not documented. Can it be documented, or is there a risk that since it's an internal flag, it will be removed or changed without notice?
