### ISSUE TITLE
securing telemetry requests to accept for specific domain

### ISSUE THREAD

**Issue by tkumark** [microsoft/ApplicationInsights-JS#989]
Since there is a limitation that instrumentation key is available on web source and no secure way to handle it. looking at the request being sent for  Access-Control-Allow-Origin it is to wild card. Is there a way to set that it only accepts from a specific domain?
 Host: dc.services.visualstudio.com   
Access-Control-Allow-Origin: *

**Comment by markwolff** [comment]
There is currently no way to allow telemetry from only certain domains. However, you can rotate your ikey via a support ticket.
