### ISSUE TITLE
Internal trace: AI (Internal): client performance math error:1 < 0 + 0 + 2579 + 0

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-JS#99]
Seeing high occurrence of this message

**Comment by AlexBulankou** [comment]
Issue started appearing on 12/3
![image](https://cloud.githubusercontent.com/assets/11968377/11860006/44e0a05c-a425-11e5-9ef7-e29fe3c3768c.png)

**Comment by AlexBulankou** [comment]
For the record these are the percentage of page views affected by each of the warnings that I'm making non-reporting with this change:

![image](https://cloud.githubusercontent.com/assets/11968377/11878722/57ba2108-a4ac-11e5-9bf7-f75409937599.png)

**Comment by Ruud-cb** [comment]
Hi
Is there anything to do to fix this issue other then that it is a warning? Or can it be safely ignored?
I am currently not sure if, when this exception occurs on a logging event, it prevents futher execution of the process. Should every AI logging call be try-catched for this? Kind of an annoying one..
