### ISSUE TITLE
custom role name is not respected in "Roles" pane?

### ISSUE THREAD

**Issue by avs099** [microsoft/ApplicationInsights-JS#990]
I'm trying to setup filtering in AI to be able to easy switch between different (but related) projects. I want to use Roles pane for that. It works fine for server events - if I defined a custom role name, I will see it in the "Roles" pane, but it does not work for frontend (JS SDK). Here is how I initialize JS snippet based on [official FAQ ](https://github.com/Microsoft/ApplicationInsights-JS/wiki/FAQ#how-to-set-a-custom-cloud_rolename)and some googling:
```
window.appInsights = appInsights;

appInsights.queue.push(() => {
    appInsights.context.addTelemetryInitializer((envelope) => {
        envelope.tags["ai.device.roleName"] = "today.ya";
        envelope.tags["ai.cloud.role"] = "today.ya";
        envelope.tags["ai.cloud.roleInstance"] ="YAWEB02";
    });
});
appInsights.trackPageView();
```
but that does not help. Even though "role" **is passed through** (so I can manually filter by it, as shown on screenshot), **it does not appear in the Roles pane**. Any ideas how to get it to work?

![](https://i.stack.imgur.com/zuypj.png)

I'm still using older version of the SDK - ai.0.js - if that matters.

And needless to say, i play with different combinations of `ai.device.roleName`, `ai.cloud.role` before just dumping all of them - but neither worked.

**Comment by xiao-lix** [comment]
I tried the old version SDK with snippet and it seems working fine to me, is this what you are expecting?  Can you please retry?

Here's the snippet I used: https://github.com/microsoft/ApplicationInsights-JS/blob/master/snippet/snippet.html

![image](https://user-images.githubusercontent.com/20292261/62327880-8276d300-b466-11e9-896f-09f3f98cf09c.png)

**Comment by avs099** [comment]
yes - snippet EXACTLY is the same, the only difference is the bottom part. Instead of
` window.appInsights=appInsights,appInsights.queue&&0===appInsights.queue.length&&appInsights.trackPageView();`
I have this:
```
window.appInsights = appInsights;

appInsights.queue.push(() => {
    appInsights.context.addTelemetryInitializer((envelope) => {
        envelope.tags["ai.device.roleName"] = "today.ya";
        envelope.tags["ai.cloud.role"] = "today.ya";
        envelope.tags["ai.cloud.roleInstance"] ="YAWEB02";
    });
});
appInsights.trackPageView();
```
not sure if that's the same thing? How did you add role name into that snippet?

And yes - your screenshot is exactly what I'm looking for to get.

Thank you!

**Comment by xiao-lix** [comment]
Hi I tried both put your code right after the snippet, and remove the line and have your code there and both worked fine on my machine.

**Comment by xiao-lix** [comment]
@avs099 And do you see Network traffic like this in your browser? The traffic is called "track"
![image](https://user-images.githubusercontent.com/20292261/62391770-91b75880-b51a-11e9-853c-4a457980c2c8.png)

**Comment by avs099** [comment]
i do:
![image](https://user-images.githubusercontent.com/11927312/62401685-3608c180-b552-11e9-9f86-441256cb669b.png)

the weird part is this code works for another AI instance (brand new) for another project. Here I was trying to add new app to existing AI instance. Not sure if that matters but still. Do you have any connections in MS support team where I can file all details? It looks like AI issue to me. Data IS THERE - i can see it - with cloud_RoleName setting - but it's not showing up on "Roles" pane.

**Comment by xiao-lix** [comment]
let me ask around and get back to you later. :)

**Comment by xiao-lix** [comment]
Hi @avs099 , the reason role is not appearing is because the current query to get the list of roles only consider "requests, dependencies, exceptions, and performanceCounters tables". If you have only pageViews and no dependencies, the role won't appear. The support team is working on this to get it fixed and the work around for now is to send dependencies.

**Comment by avs099** [comment]
Thank you.

**Comment by xiao-lix** [comment]
I don't have an open issue with this, I'll follow it up and get back to you when there's an update.
