### ISSUE TITLE
W3C Traceparent header name is wrong

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-JS#993]
`traceparentHeader` is not the correct name: 
 https://github.com/microsoft/ApplicationInsights-JS/blob/bc4027c39b33b6163b5b325ba65f324a83ff4c32/vNext/shared/AppInsightsCommon/src/RequestResponseHeaders.ts#L29

The correct one is  `traceparent` 
https://www.w3.org/TR/trace-context/#header-name

**Comment by xiao-lix** [comment]
Thanks, updated in next pr.
