### ISSUE TITLE
Can't execute code from a freed script while using AI telemetry in dynamics crm

### ISSUE THREAD

**Issue by rupakraj6** [microsoft/ApplicationInsights-JS#997]
*** Scenario: Integrating AI JS SDK with dynamics CRM online  Forms/web resources ***

We are using AI SDK to log telemetry events from custom javascript code in a web resource in CRM online.
I am hitting (**Can't execute code from a freed script**) exception only  after creating the dependent entity record (which opens up the quick create form) . Immediately after closing quick create form I am hitting the exception on any telemetry call.

- Stack trace :

Error: Can't execute code from a freed script
   at XMLHttpRequest.prototype.open (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:42298)

**Comment by hectorhdzg** [comment]
The JS error you are getting is usually caused by trying to access an object created in a window object that is not available anymore, following stackoverflow link may help you solve issue

https://stackoverflow.com/questions/83132/what-causes-the-error-cant-execute-code-from-a-freed-script
