### ISSUE TITLE
enableAutoRouteTracking breaks angular router in IE11

### ISSUE THREAD

**Issue by wdrobinson** [microsoft/ApplicationInsights-JS#998]
To reproduce create a new angular app (ng new my-app), create any component and route to it, and then add application insights. Routing works fine without enableAutoRouteTracking but fails with enableAutoRouteTracking: true with the error "Unhandled Navigation Error:"

Routing works fine with route tracking in Edge, Firefox, and Chrome. This is only an issue in IE11.

Versions:
angular 8.2.2
applicationinsights 2.1.1

**Comment by markwolff** [comment]
Thanks for the report. I have a fix out for this that will be included in the next release (most likely tomorrow)

**Comment by markwolff** [comment]
Fix is out now. Here is repro to verify fix.
https://stackblitz.com/edit/angular-router-basic-example-nkma6a?file=main.ts

Let me know if it doesn't fix it on your end

**Comment by wdrobinson** [comment]
Confirmed that v2.2.0 fixed our issue. Thank you for the quick fix!
